const Joi = require('joi');

const hitterSchema = Joi.object({
    Year: '2014',
    TM: 'SEA',
    real_team_id: '',
    HITTERS: 'Zunino,M',
    INJ: '',
    AB: '438',
    SO_v_lhp: '43',
    BB_v_lhp: '0',
    HIT_v_lhp: '18.1',
    OB_v_lhp: '26.1',
    TB_v_lhp: '35.2',
    HR_v_lhp: '2.7',
    BP_v_lhp: '5',
    CL_v_lhp: '-1',
    DP_v_lhp: '23',
    SO_v_rhp: '51',
    BB_v_rhp: '0',
    HIT_v_rhp: '7',
    OB_v_rhp: '15',
    TB_v_rhp: '24.6',
    HR_v_rhp: '4.8',
    BP_v_rhp: '8*',
    CL_v_rhp: '0',
    DP_v_rhp: '18',
    STEALING: '2-8,12/- (3-1)',
    STL: 'E',
    SPD: '10',
    B: 'D',
    H: 'D',
    d_CA: '201',
    d_1B: '',
    d_2B: '',
    d_3B: '',
    d_SS: '',
    d_LF: '',
    d_CF: '',
    d_RF: '',
    FIELDING: 'c-2(0)e1,T-6(pb-2)',
    rml_team_id: '',
});

module.exports = hitterSchema;
