const Joi = require('joi');

const pitchersSchema = Joi.array().items({
    Year: Joi.number().integer().min(1900).max(2050).required(),
    TM: Joi.string().length(3).required(),
    real_team_id: Joi.optional(),
    PITCHERS: Joi.string().min(3).required(),
    IP: Joi.number().integer().min(1).required(),
    SO_v_l: Joi.number().integer().min(0).required(),
    BB_v_l: Joi.number().integer().min(0).required(),
    HIT_v_l: Joi.number().min(0).required(),
    OB_v_l: Joi.number().min(0).required(),
    TB_v_l: Joi.number().min(0).required(),
    HR_v_l: Joi.number().min(0).required(),
    BP_v_l: Joi.string().min(1).max(2).required(),
    DP_v_l: Joi.number().integer().min(0).required(),
    SO_v_r: Joi.number().integer().min(0).required(),
    BB_v_r: Joi.number().integer().min(0).required(),
    HIT_v_r: Joi.number().min(0).required(),
    OB_v_r: Joi.number().min(0).required(),
    TB_v_r: Joi.number().min(0).required(),
    HR_v_r: Joi.number().min(0).required(),
    BP_v_r: Joi.string().min(1).max(2).required(),
    DP_v_r: Joi.number().integer().min(0).required(),
    HO: Joi.number().integer().min(-6).max(9).required(),
    ENDURANCE: Joi.string().required(),
    FIELD: Joi.string().required(),
    BK: Joi.number().integer().min(0).max(20).required(),
    WP: Joi.number().integer().min(0).max(20).required(),
    BAT_B: Joi.string().length(5).required(),
    STL: Joi.string().valid('AAA', 'AA', 'A', 'B', 'C', 'D', 'E').required(),
    SPD: Joi.number().integer().min(0).required(),
    rml_team_id: Joi.optional(),
});

module.exports = pitchersSchema;
