const cardedPlayers = [
    { year: 2022, name: 'Abrams,C', team: 'RockHounds' },
    { year: 2022, name: 'Abreu,A', team: 'River Dogs' },
    { year: 2022, name: 'Abreu,B', team: 'TinCaps' },
    { year: 2022, name: 'Abreu,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Acevedo,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Acuna,R', team: 'Bandits' },
    { year: 2022, name: 'Adam,J', team: 'Gypsies' },
    { year: 2022, name: 'Adames,W', team: 'Knights' },
    { year: 2022, name: 'Adams,R', team: 'Pilots' },
    { year: 2022, name: 'Adell,J', team: 'Captains' },
    { year: 2022, name: 'Adon,J', team: 'Hornets' },
    { year: 2022, name: 'Aguilar,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Akin,K', team: 'RockHounds' },
    { year: 2022, name: 'Alberto,H', team: 'Whales' },
    { year: 2022, name: 'Albies,O', team: 'Titans' },
    { year: 2022, name: 'Alcantara,S', team: 'Bandits' },
    { year: 2022, name: 'Alcantara,S', team: 'Z-Unowned' },
    { year: 2022, name: 'Alexander,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Alexander,T', team: 'Yellow Jackets' },
    { year: 2022, name: 'Alfaro,J', team: 'RockHounds' },
    { year: 2022, name: 'Allen,G', team: 'Z-Unowned' },
    { year: 2022, name: 'Allen,N', team: 'Blaze' },
    { year: 2022, name: 'Almonte,Y', team: 'Browns' },
    { year: 2022, name: 'Almora,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Alonso,P', team: 'Blaze' },
    { year: 2022, name: 'Altuve,J', team: 'Grays' },
    { year: 2022, name: 'Alvarado,J', team: 'Stars' },
    { year: 2022, name: 'Alvarez,Y', team: 'Browns' },
    { year: 2022, name: 'Anderson,B', team: 'Expos' },
    { year: 2022, name: 'Anderson,I', team: 'Knights' },
    { year: 2022, name: 'Anderson,T', team: 'Bandits' },
    { year: 2022, name: 'Anderson,T', team: 'Captains' },
    { year: 2022, name: 'Andrus,E', team: 'Z-Unowned' },
    { year: 2022, name: 'Andujar,M', team: 'Colt .45s' },
    { year: 2022, name: 'Aquino,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Arano,V', team: 'Z-Unowned' },
    { year: 2022, name: 'Archer,C', team: 'Stars' },
    { year: 2022, name: 'Arcia,O', team: 'Bandits' },
    { year: 2022, name: 'Arenado,N', team: 'Dodgers' },
    { year: 2022, name: 'Armstrong,S', team: 'Z-Unowned' },
    { year: 2022, name: 'Arozarena,R', team: 'Monarchs' },
    { year: 2022, name: 'Arraez,L', team: 'Captains' },
    { year: 2022, name: 'Arroyo,C', team: 'Bandits' },
    { year: 2022, name: 'Ashby,A', team: 'Expos' },
    { year: 2022, name: 'Ashcraft,G', team: 'Z-Unowned' },
    { year: 2022, name: 'Azocar,J', team: 'Gypsies' },
    { year: 2022, name: 'Baddoo,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Bader,H', team: 'Titans' },
    { year: 2022, name: 'Baez,J', team: 'Titans' },
    { year: 2022, name: 'Baker,B', team: 'Z-Unowned' },
    { year: 2022, name: 'Banda,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Banks,T', team: 'Z-Unowned' },
    { year: 2022, name: 'Banuelos,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Bard,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Barlow,J', team: 'Colt .45s' },
    { year: 2022, name: 'Barlow,S', team: 'Reds' },
    { year: 2022, name: 'Barnes,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Barnes,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Barnhart,T', team: 'Z-Unowned' },
    { year: 2022, name: 'Barrero,J', team: 'Monarchs' },
    { year: 2022, name: 'Barria,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Bart,J', team: 'RockHounds' },
    { year: 2022, name: 'Bass,A', team: 'Reds' },
    { year: 2022, name: 'Bassitt,C', team: 'Browns' },
    { year: 2022, name: 'Bautista,F', team: 'Z-Unowned' },
    { year: 2022, name: 'Bednar,D', team: 'Captains' },
    { year: 2022, name: 'Beede,T', team: 'Captains' },
    { year: 2022, name: 'Beeks,J', team: 'Hornets' },
    { year: 2022, name: 'Beer,S', team: 'Knights' },
    { year: 2022, name: 'Bell,J', team: 'Browns' },
    { year: 2022, name: 'Bellatti,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Bellinger,C', team: 'Pilots' },
    { year: 2022, name: 'Bello,B', team: 'RockHounds' },
    { year: 2022, name: 'Belt,B', team: 'Yellow Jackets' },
    { year: 2022, name: 'Benintendi,A', team: 'Yellow Jackets' },
    { year: 2022, name: 'Berrios,J', team: 'Yellow Jackets' },
    { year: 2022, name: 'Berti,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Bethancourt,C', team: 'Z-Unowned' },
    { year: 2022, name: 'Betts,M', team: 'Grays' },
    { year: 2022, name: 'Bichette,B', team: 'Twins' },
    { year: 2022, name: 'Bickford,P', team: 'Titans' },
    { year: 2022, name: 'Bieber,S', team: 'Captains' },
    { year: 2022, name: 'Biggio,C', team: 'Browns' },
    { year: 2022, name: 'Bird,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Blackburn,P', team: 'Grays' },
    { year: 2022, name: 'Blackmon,C', team: 'Z-Unowned' },
    { year: 2022, name: 'Bleday,J', team: 'Dodgers' },
    { year: 2022, name: 'Bleier,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Bogaerts,X', team: 'Bandits' },
    { year: 2022, name: 'Bohm,A', team: 'Blaze' },
    { year: 2022, name: 'Bolt,S', team: 'Z-Unowned' },
    { year: 2022, name: 'Borucki,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Bote,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Boxberger,B', team: 'Z-Unowned' },
    { year: 2022, name: 'Bradish,K', team: 'Hornets' },
    { year: 2022, name: 'Bradley,J', team: 'Bandits' },
    { year: 2022, name: 'Brantley,M', team: 'Monarchs' },
    { year: 2022, name: 'Brash,M', team: 'Hornets' },
    { year: 2022, name: 'Brasier,R', team: 'Pelicans' },
    { year: 2022, name: 'Brebbia,J', team: 'Yellow Jackets' },
    { year: 2022, name: 'Bregman,A', team: 'Colt .45s' },
    { year: 2022, name: 'Bride,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Brieske,B', team: 'Expos' },
    { year: 2022, name: 'Brogdon,C', team: 'Browns' },
    { year: 2022, name: 'Brosseau,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Brown,S', team: 'Browns' },
    { year: 2022, name: 'Brubaker,J', team: 'Twins' },
    { year: 2022, name: 'Brujan,V', team: 'River Dogs' },
    { year: 2022, name: 'Bryant,K', team: 'Stars' },
    { year: 2022, name: 'Bubic,K', team: 'Pilots' },
    { year: 2022, name: 'Buehler,W', team: 'Titans' },
    { year: 2022, name: 'Bumgarner,M', team: 'Yellow Jackets' },
    { year: 2022, name: 'Bummer,A', team: 'Bandits' },
    { year: 2022, name: 'Bundy,D', team: 'Monarchs' },
    { year: 2022, name: 'Burger,J', team: 'Yellow Jackets' },
    { year: 2022, name: 'Burke,B', team: 'TinCaps' },
    { year: 2022, name: 'Burnes,C', team: 'Dodgers' },
    { year: 2022, name: 'Bush,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Buxton,B', team: 'Bandits' },
    { year: 2022, name: 'Cabrera,E', team: 'RockHounds' },
    { year: 2022, name: 'Cabrera,G', team: 'River Dogs' },
    { year: 2022, name: 'Cabrera,M', team: 'Expos' },
    { year: 2022, name: 'Cabrera,O', team: 'Z-Unowned' },
    { year: 2022, name: 'Cain,L', team: 'Z-Unowned' },
    { year: 2022, name: 'Calhoun,K', team: 'Z-Unowned' },
    { year: 2022, name: 'Call,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Camargo,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Candelario,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Canha,M', team: 'Captains' },
    { year: 2022, name: 'Cano,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Caratini,V', team: 'Reds' },
    { year: 2022, name: 'Carlson,D', team: 'TinCaps' },
    { year: 2022, name: 'Carpenter,K', team: 'Z-Unowned' },
    { year: 2022, name: 'Carpenter,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Carrasco,C', team: 'River Dogs' },
    { year: 2022, name: 'Carroll,C', team: 'Colt .45s' },
    { year: 2022, name: 'Casali,C', team: 'Z-Unowned' },
    { year: 2022, name: 'Castellanos,N', team: 'Pilgrims' },
    { year: 2022, name: 'Castillo,D', team: 'Colt .45s' },
    { year: 2022, name: 'Castillo,D', team: 'River Dogs' },
    { year: 2022, name: 'Castillo,L', team: 'Captains' },
    { year: 2022, name: 'Castro,H', team: 'Gypsies' },
    { year: 2022, name: 'Castro,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Castro,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Castro,W', team: 'TinCaps' },
    { year: 2022, name: 'Cave,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Cease,D', team: 'Browns' },
    { year: 2022, name: 'Celestino,G', team: 'Expos' },
    { year: 2022, name: 'Cessa,L', team: 'Whales' },
    { year: 2022, name: 'Chacin,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Chafin,A', team: 'Reds' },
    { year: 2022, name: 'Chang,Y', team: 'Z-Unowned' },
    { year: 2022, name: 'Chapman,A', team: 'Whales' },
    { year: 2022, name: 'Chapman,M', team: 'Blaze' },
    { year: 2022, name: 'Chavez,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Chavis,M', team: 'Browns' },
    { year: 2022, name: 'Chirinos,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Chisholm,J', team: 'Pelicans' },
    { year: 2022, name: 'Choi,J', team: 'Monarchs' },
    { year: 2022, name: 'Cimber,A', team: 'Hornets' },
    { year: 2022, name: 'Cishek,S', team: 'Pelicans' },
    { year: 2022, name: 'Civale,A', team: 'River Dogs' },
    { year: 2022, name: 'Clarke,T', team: 'Z-Unowned' },
    { year: 2022, name: 'Clase,E', team: 'RockHounds' },
    { year: 2022, name: 'Clemens,K', team: 'Z-Unowned' },
    { year: 2022, name: 'Clement,E', team: 'River Dogs' },
    { year: 2022, name: 'Clevinger,M', team: 'Gypsies' },
    { year: 2022, name: 'Cobb,A', team: 'Monarchs' },
    { year: 2022, name: 'Cole,G', team: 'Whales' },
    { year: 2022, name: 'Coleman,D', team: 'Blaze' },
    { year: 2022, name: 'Colome,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Contreras,R', team: 'Reds' },
    { year: 2022, name: 'Contreras,W', team: 'Browns' },
    { year: 2022, name: 'Contreras,W', team: 'Colt .45s' },
    { year: 2022, name: 'Cooper,G', team: 'RockHounds' },
    { year: 2022, name: 'Corbin,P', team: 'Stars' },
    { year: 2022, name: 'Cordero,F', team: 'Z-Unowned' },
    { year: 2022, name: 'Correa,C', team: 'Whales' },
    { year: 2022, name: 'Cortes Jr,N', team: 'Whales' },
    { year: 2022, name: 'Cotton,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Crawford,B', team: 'Pelicans' },
    { year: 2022, name: 'Crawford,J', team: 'Pilgrims' },
    { year: 2022, name: 'Crawford,K', team: 'Browns' },
    { year: 2022, name: 'Crismatt,N', team: 'Z-Unowned' },
    { year: 2022, name: 'Cron,C', team: 'Z-Unowned' },
    { year: 2022, name: 'Cronenworth,J', team: 'Hornets' },
    { year: 2022, name: 'Crowe,W', team: 'Stars' },
    { year: 2022, name: 'Cruz,N', team: 'Z-Unowned' },
    { year: 2022, name: 'Cruz,O', team: 'RockHounds' },
    { year: 2022, name: 'Cuas,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Cueto,J', team: 'Gypsies' },
    { year: 2022, name: 'Culberson,C', team: 'Z-Unowned' },
    { year: 2022, name: 'd\'Arnaud,T', team: 'Captains' },
    { year: 2022, name: 'Dalbec,B', team: 'Colt .45s' },
    { year: 2022, name: 'Danish,T', team: 'Z-Unowned' },
    { year: 2022, name: 'Darvish,Y', team: 'Grays' },
    { year: 2022, name: 'Davidson,T', team: 'Pilots' },
    { year: 2022, name: 'Davies,Z', team: 'Browns' },
    { year: 2022, name: 'Davis,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Davis,J', team: 'Colt .45s' },
    { year: 2022, name: 'Daza,Y', team: 'Hornets' },
    { year: 2022, name: 'De Jong,C', team: 'Z-Unowned' },
    { year: 2022, name: 'De La Cruz,B', team: 'Pilgrims' },
    { year: 2022, name: 'De Los Santos,E', team: 'Z-Unowned' },
    { year: 2022, name: 'deGrom,J', team: 'Grays' },
    { year: 2022, name: 'DeJong,P', team: 'Yellow Jackets' },
    { year: 2022, name: 'Delay,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Detmers,R', team: 'Knights' },
    { year: 2022, name: 'Detwiler,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Devers,R', team: 'Knights' },
    { year: 2022, name: 'Diaz,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Diaz,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Diaz,E', team: 'Bandits' },
    { year: 2022, name: 'Diaz,E', team: 'Z-Unowned' },
    { year: 2022, name: 'Diaz,L', team: 'Knights' },
    { year: 2022, name: 'Diaz,Y', team: 'River Dogs' },
    { year: 2022, name: 'Dickerson,C', team: 'Z-Unowned' },
    { year: 2022, name: 'Diekman,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Dominguez,S', team: 'Z-Unowned' },
    { year: 2022, name: 'Donaldson,J', team: 'Captains' },
    { year: 2022, name: 'Donovan,B', team: 'Z-Unowned' },
    { year: 2022, name: 'Doval,C', team: 'Z-Unowned' },
    { year: 2022, name: 'Dozier,H', team: 'RockHounds' },
    { year: 2022, name: 'Drury,B', team: 'Z-Unowned' },
    { year: 2022, name: 'Dubon,M', team: 'Twins' },
    { year: 2022, name: 'Duffey,T', team: 'Z-Unowned' },
    { year: 2022, name: 'Duffy,M', team: 'Reds' },
    { year: 2022, name: 'Dunning,D', team: 'Captains' },
    { year: 2022, name: 'Duran,E', team: 'Monarchs' },
    { year: 2022, name: 'Duran,J', team: 'Pilots' },
    { year: 2022, name: 'Duran,J', team: 'River Dogs' },
    { year: 2022, name: 'Duvall,A', team: 'Gypsies' },
    { year: 2022, name: 'Eaton,N', team: 'Z-Unowned' },
    { year: 2022, name: 'Edman,T', team: 'Yellow Jackets' },
    { year: 2022, name: 'Edwards,C', team: 'Reds' },
    { year: 2022, name: 'Effross,S', team: 'Z-Unowned' },
    { year: 2022, name: 'Eflin,Z', team: 'Expos' },
    { year: 2022, name: 'Engel,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Eovaldi,N', team: 'Colt .45s' },
    { year: 2022, name: 'Escobar,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Escobar,E', team: 'Z-Unowned' },
    { year: 2022, name: 'Espinal,S', team: 'Browns' },
    { year: 2022, name: 'Espino,P', team: 'Expos' },
    { year: 2022, name: 'Estevez,C', team: 'Knights' },
    { year: 2022, name: 'Estrada,T', team: 'Pilgrims' },
    { year: 2022, name: 'Faedo,A', team: 'Pelicans' },
    { year: 2022, name: 'Falter,B', team: 'Z-Unowned' },
    { year: 2022, name: 'Familia,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Farmer,B', team: 'Z-Unowned' },
    { year: 2022, name: 'Farmer,K', team: 'Colt .45s' },
    { year: 2022, name: 'Fedde,E', team: 'Z-Unowned' },
    { year: 2022, name: 'Feltner,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Ferguson,C', team: 'Blaze' },
    { year: 2022, name: 'Festa,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Finnegan,K', team: 'Whales' },
    { year: 2022, name: 'Fletcher,D', team: 'Knights' },
    { year: 2022, name: 'Flexen,C', team: 'Reds' },
    { year: 2022, name: 'Flores,W', team: 'Colt .45s' },
    { year: 2022, name: 'Floro,D', team: 'Titans' },
    { year: 2022, name: 'Foley,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Ford,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Fortes,N', team: 'Z-Unowned' },
    { year: 2022, name: 'Foster,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Fraley,J', team: 'Pilots' },
    { year: 2022, name: 'France,T', team: 'Blaze' },
    { year: 2022, name: 'Franco,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Franco,W', team: 'Pilgrims' },
    { year: 2022, name: 'Frazier,A', team: 'RockHounds' },
    { year: 2022, name: 'Freeland,K', team: 'Z-Unowned' },
    { year: 2022, name: 'Freeman,F', team: 'Dodgers' },
    { year: 2022, name: 'Fried,M', team: 'Dodgers' },
    { year: 2022, name: 'Friedl,T', team: 'Gypsies' },
    { year: 2022, name: 'Fulmer,M', team: 'Twins' },
    { year: 2022, name: 'Gallegos,G', team: 'Expos' },
    { year: 2022, name: 'Gallen,Z', team: 'Yellow Jackets' },
    { year: 2022, name: 'Gallo,J', team: 'Grays' },
    { year: 2022, name: 'Gamel,B', team: 'Reds' },
    { year: 2022, name: 'Garcia,A', team: 'Expos' },
    { year: 2022, name: 'Garcia,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Garcia,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Garcia,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Garcia,J', team: 'Yellow Jackets' },
    { year: 2022, name: 'Garcia,L', team: 'Blaze' },
    { year: 2022, name: 'Garcia,L', team: 'Knights' },
    { year: 2022, name: 'Garcia,L', team: 'Monarchs' },
    { year: 2022, name: 'Garcia,L', team: 'TinCaps' },
    { year: 2022, name: 'Garcia,Y', team: 'Browns' },
    { year: 2022, name: 'Garlick,K', team: 'Z-Unowned' },
    { year: 2022, name: 'Garrett,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Garrett,B', team: 'Blaze' },
    { year: 2022, name: 'Garver,M', team: 'Grays' },
    { year: 2022, name: 'Gausman,K', team: 'Titans' },
    { year: 2022, name: 'German,D', team: 'Knights' },
    { year: 2022, name: 'Gibaut,I', team: 'Z-Unowned' },
    { year: 2022, name: 'Gibson,K', team: 'Monarchs' },
    { year: 2022, name: 'Gilbert,L', team: 'RockHounds' },
    { year: 2022, name: 'Gilbreath,L', team: 'TinCaps' },
    { year: 2022, name: 'Gimenez,A', team: 'Blaze' },
    { year: 2022, name: 'Ginkel,K', team: 'Z-Unowned' },
    { year: 2022, name: 'Giolito,L', team: 'Z-Unowned' },
    { year: 2022, name: 'Givens,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Goldschmidt,P', team: 'Bandits' },
    { year: 2022, name: 'Gomber,A', team: 'Stars' },
    { year: 2022, name: 'Gomes,Y', team: 'Titans' },
    { year: 2022, name: 'Gonsolin,T', team: 'RockHounds' },
    { year: 2022, name: 'Gonzales,M', team: 'Pilots' },
    { year: 2022, name: 'Gonzalez,L', team: 'Z-Unowned' },
    { year: 2022, name: 'Gonzalez,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Gonzalez,O', team: 'Z-Unowned' },
    { year: 2022, name: 'Gonzalez,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Gordon,N', team: 'Pilots' },
    { year: 2022, name: 'Gore,M', team: 'Hornets' },
    { year: 2022, name: 'Gorman,N', team: 'Rockhounds' },
    { year: 2022, name: 'Gott,T', team: 'Z-Unowned' },
    { year: 2022, name: 'Grandal,Y', team: 'Z-Unowned' },
    { year: 2022, name: 'Graterol,B', team: 'River Dogs' },
    { year: 2022, name: 'Graveman,K', team: 'Hornets' },
    { year: 2022, name: 'Gray,J', team: 'Pelicans' },
    { year: 2022, name: 'Gray,J', team: 'RockHounds' },
    { year: 2022, name: 'Gray,S', team: 'Browns' },
    { year: 2022, name: 'Greene,H', team: 'Pilgrims' },
    { year: 2022, name: 'Greene,R', team: 'Twins' },
    { year: 2022, name: 'Gregorius,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Greinke,Z', team: 'Hornets' },
    { year: 2022, name: 'Grichuk,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Grisham,T', team: 'TinCaps' },
    { year: 2022, name: 'Grissom,V', team: 'Twins' },
    { year: 2022, name: 'Grossman,R', team: 'Whales' },
    { year: 2022, name: 'Guerrero,V', team: 'Whales' },
    { year: 2022, name: 'Guillorme,L', team: 'RockHounds' },
    { year: 2022, name: 'Gurriel,L', team: 'Captains' },
    { year: 2022, name: 'Gurriel,Y', team: 'Z-Unowned' },
    { year: 2022, name: 'Haase,E', team: 'Gypsies' },
    { year: 2022, name: 'Hader,J', team: 'Colt .45s' },
    { year: 2022, name: 'Haggerty,S', team: 'Z-Unowned' },
    { year: 2022, name: 'Hall,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Hampson,G', team: 'Reds' },
    { year: 2022, name: 'Hand,B', team: 'Yellow Jackets' },
    { year: 2022, name: 'Haniger,M', team: 'Titans' },
    { year: 2022, name: 'Happ,I', team: 'Reds' },
    { year: 2022, name: 'Harper,B', team: 'Bandits' },
    { year: 2022, name: 'Harris,M', team: 'Pelicans' },
    { year: 2022, name: 'Harrison,J', team: 'Whales' },
    { year: 2022, name: 'Harvey,H', team: 'Z-Unowned' },
    { year: 2022, name: 'Hayes,K', team: 'Monarchs' },
    { year: 2022, name: 'Hays,A', team: 'Stars' },
    { year: 2022, name: 'Heaney,A', team: 'Browns' },
    { year: 2022, name: 'Hearn,T', team: 'Pelicans' },
    { year: 2022, name: 'Heasley,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Hedges,A', team: 'Knights' },
    { year: 2022, name: 'Heim,J', team: 'Blaze' },
    { year: 2022, name: 'Heineman,T', team: 'Z-Unowned' },
    { year: 2022, name: 'Helsley,R', team: 'Knights' },
    { year: 2022, name: 'Henderson,G', team: 'Monarchs' },
    { year: 2022, name: 'Hendricks,K', team: 'Titans' },
    { year: 2022, name: 'Hendriks,L', team: 'Dodgers' },
    { year: 2022, name: 'Hentges,S', team: 'River Dogs' },
    { year: 2022, name: 'Herget,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Hernandez,C', team: 'Pelicans' },
    { year: 2022, name: 'Hernandez,E', team: 'Z-Unowned' },
    { year: 2022, name: 'Hernandez,E', team: 'Z-Unowned' },
    { year: 2022, name: 'Hernandez,T', team: 'Bandits' },
    { year: 2022, name: 'Hernandez,Y', team: 'Reds' },
    { year: 2022, name: 'Herrera,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Herrera,O', team: 'Yellow Jackets' },
    { year: 2022, name: 'Heyward,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Hicks,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Hicks,J', team: 'Grays' },
    { year: 2022, name: 'Higashioka,K', team: 'Monarchs' },
    { year: 2022, name: 'Higgins,P', team: 'Z-Unowned' },
    { year: 2022, name: 'Hill,G', team: 'Z-Unowned' },
    { year: 2022, name: 'Hill,R', team: 'Twins' },
    { year: 2022, name: 'Hill,T', team: 'Captains' },
    { year: 2022, name: 'Hilliard,S', team: 'River Dogs' },
    { year: 2022, name: 'Hiura,K', team: 'RockHounds' },
    { year: 2022, name: 'Hoerner,N', team: 'Browns' },
    { year: 2022, name: 'Hoffman,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Holmes,C', team: 'TinCaps' },
    { year: 2022, name: 'Hoskins,R', team: 'Monarchs' },
    { year: 2022, name: 'Hosmer,E', team: 'Gypsies' },
    { year: 2022, name: 'Houck,T', team: 'Blaze' },
    { year: 2022, name: 'Houser,A', team: 'Knights' },
    { year: 2022, name: 'Hudson,D', team: 'Captains' },
    { year: 2022, name: 'Huff,S', team: 'Captains' },
    { year: 2022, name: 'Hughes,B', team: 'Z-Unowned' },
    { year: 2022, name: 'Hummel,C', team: 'Z-Unowned' },
    { year: 2022, name: 'Hutchison,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Ibanez,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Iglesias,J', team: 'Bandits' },
    { year: 2022, name: 'Iglesias,R', team: 'Twins' },
    { year: 2022, name: 'India,J', team: 'Pilgrims' },
    { year: 2022, name: 'Irvin,C', team: 'Hornets' },
    { year: 2022, name: 'Isbel,K', team: 'Z-Unowned' },
    { year: 2022, name: 'Jackson,Z', team: 'Pelicans' },
    { year: 2022, name: 'Jansen,D', team: 'Pilgrims' },
    { year: 2022, name: 'Jansen,K', team: 'Bandits' },
    { year: 2022, name: 'Javier,C', team: 'River Dogs' },
    { year: 2022, name: 'Jax,G', team: 'Z-Unowned' },
    { year: 2022, name: 'Jeffers,R', team: 'Colt .45s' },
    { year: 2022, name: 'Jimenez,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Jimenez,E', team: 'Monarchs' },
    { year: 2022, name: 'Jimenez,J', team: 'Pelicans' },
    { year: 2022, name: 'Joe,C', team: 'Gypsies' },
    { year: 2022, name: 'Judge,A', team: 'Colt .45s' },
    { year: 2022, name: 'Junis,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Kaprielian,J', team: 'Browns' },
    { year: 2022, name: 'Karinchak,J', team: 'Gypsies' },
    { year: 2022, name: 'Kelenic,J', team: 'Twins' },
    { year: 2022, name: 'Keller,B', team: 'Browns' },
    { year: 2022, name: 'Keller,M', team: 'Captains' },
    { year: 2022, name: 'Kelly,C', team: 'Reds' },
    { year: 2022, name: 'Kelly,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Kelly,M', team: 'Gypsies' },
    { year: 2022, name: 'Kemp,T', team: 'Browns' },
    { year: 2022, name: 'Kennedy,I', team: 'Z-Unowned' },
    { year: 2022, name: 'Kepler,M', team: 'Yellow Jackets' },
    { year: 2022, name: 'Kershaw,C', team: 'Gypsies' },
    { year: 2022, name: 'Keuchel,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Kiermaier,K', team: 'Z-Unowned' },
    { year: 2022, name: 'Kikuchi,Y', team: 'Z-Unowned' },
    { year: 2022, name: 'Kim,H', team: 'Grays' },
    { year: 2022, name: 'Kimbrel,C', team: 'Titans' },
    { year: 2022, name: 'Kiner-Falefa,I', team: 'Hornets' },
    { year: 2022, name: 'King,J', team: 'Pilots' },
    { year: 2022, name: 'King,M', team: 'Whales' },
    { year: 2022, name: 'Kirby,G', team: 'Colt .45s' },
    { year: 2022, name: 'Kirilloff,A', team: 'Pilots' },
    { year: 2022, name: 'Kirk,A', team: 'Hornets' },
    { year: 2022, name: 'Kluber,C', team: 'Reds' },
    { year: 2022, name: 'Knebel,C', team: 'Hornets' },
    { year: 2022, name: 'Knizner,A', team: 'Pilots' },
    { year: 2022, name: 'Kopech,M', team: 'RockHounds' },
    { year: 2022, name: 'Krehbiel,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Kremer,D', team: 'Pilots' },
    { year: 2022, name: 'Kuhl,C', team: 'Z-Unowned' },
    { year: 2022, name: 'Kuhnel,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Kwan,S', team: 'River Dogs' },
    { year: 2022, name: 'La Stella,T', team: 'Z-Unowned' },
    { year: 2022, name: 'Lambert,J', team: 'Twins' },
    { year: 2022, name: 'Lamet,D', team: 'RockHounds' },
    { year: 2022, name: 'Lange,A', team: 'Pilots' },
    { year: 2022, name: 'Langeliers,S', team: 'Knights' },
    { year: 2022, name: 'Larnach,T', team: 'Dodgers' },
    { year: 2022, name: 'Lauer,E', team: 'Dodgers' },
    { year: 2022, name: 'Laureano,R', team: 'Captains' },
    { year: 2022, name: 'Lawrence,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Leblanc,C', team: 'Z-Unowned' },
    { year: 2022, name: 'LeClerc,J', team: 'Titans' },
    { year: 2022, name: 'Lee,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Leiter,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Lemahieu,D', team: 'Reds' },
    { year: 2022, name: 'Leone,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Lindor,F', team: 'Dodgers' },
    { year: 2022, name: 'Littell,Z', team: 'Z-Unowned' },
    { year: 2022, name: 'Loaisiga,J', team: 'River Dogs' },
    { year: 2022, name: 'Lodolo,N', team: 'Blaze' },
    { year: 2022, name: 'Logue,Z', team: 'Z-Unowned' },
    { year: 2022, name: 'Longoria,E', team: 'Z-Unowned' },
    { year: 2022, name: 'Lopez,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Lopez,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Lopez,N', team: 'TinCaps' },
    { year: 2022, name: 'Lopez,P', team: 'Captains' },
    { year: 2022, name: 'Lopez,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Lorenzen,M', team: 'Pelicans' },
    { year: 2022, name: 'Loup,A', team: 'Yellow Jackets' },
    { year: 2022, name: 'Lowe,B', team: 'Stars' },
    { year: 2022, name: 'Lowe,J', team: 'Knights' },
    { year: 2022, name: 'Lowe,N', team: 'Stars' },
    { year: 2022, name: 'Lowrie,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Luetge,L', team: 'Stars' },
    { year: 2022, name: 'Lugo,S', team: 'Stars' },
    { year: 2022, name: 'Luplow,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Lux,G', team: 'Dodgers' },
    { year: 2022, name: 'Luzardo,J', team: 'Monarchs' },
    { year: 2022, name: 'Lyles,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Lynch,D', team: 'Pilgrims' },
    { year: 2022, name: 'Lynn,L', team: 'Reds' },
    { year: 2022, name: 'Machado,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Machado,M', team: 'Gypsies' },
    { year: 2022, name: 'Machin,V', team: 'Z-Unowned' },
    { year: 2022, name: 'Madrigal,N', team: 'Grays' },
    { year: 2022, name: 'Madris,B', team: 'Z-Unowned' },
    { year: 2022, name: 'Mahle,T', team: 'Twins' },
    { year: 2022, name: 'Maile,L', team: 'Z-Unowned' },
    { year: 2022, name: 'Maldonado,M', team: 'RockHounds' },
    { year: 2022, name: 'Manaea,S', team: 'Bandits' },
    { year: 2022, name: 'Mancini,T', team: 'River Dogs' },
    { year: 2022, name: 'Manning,M', team: 'Knights' },
    { year: 2022, name: 'Manoah,A', team: 'Blaze' },
    { year: 2022, name: 'Mantiply,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Marcano,T', team: 'Colt .45s' },
    { year: 2022, name: 'Margot,M', team: 'Expos' },
    { year: 2022, name: 'Marinaccio,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Marquez,G', team: 'Z-Unowned' },
    { year: 2022, name: 'Marsh,B', team: 'Monarchs' },
    { year: 2022, name: 'Marte,K', team: 'Dodgers' },
    { year: 2022, name: 'Marte,S', team: 'Gypsies' },
    { year: 2022, name: 'Marte,Y', team: 'Z-Unowned' },
    { year: 2022, name: 'Martin,B', team: 'Expos' },
    { year: 2022, name: 'Martin,C', team: 'Z-Unowned' },
    { year: 2022, name: 'Martin,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Martinez,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Martinez,J', team: 'Captains' },
    { year: 2022, name: 'Martinez,N', team: 'Twins' },
    { year: 2022, name: 'Massey,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Mateo,J', team: 'Monarchs' },
    { year: 2022, name: 'Maton,P', team: 'Z-Unowned' },
    { year: 2022, name: 'Matz,S', team: 'Hornets' },
    { year: 2022, name: 'Matzek,T', team: 'Z-Unowned' },
    { year: 2022, name: 'Mayza,T', team: 'Pilgrims' },
    { year: 2022, name: 'Mazara,N', team: 'Z-Unowned' },
    { year: 2022, name: 'McCann,J', team: 'Yellow Jackets' },
    { year: 2022, name: 'McCarthy,J', team: 'Monarchs' },
    { year: 2022, name: 'McClanahan,S', team: 'Captains' },
    { year: 2022, name: 'McCormick,C', team: 'Browns' },
    { year: 2022, name: 'McCutchen,A', team: 'Z-Unowned' },
    { year: 2022, name: 'McGee,J', team: 'Z-Unowned' },
    { year: 2022, name: 'McGuire,R', team: 'Blaze' },
    { year: 2022, name: 'McHugh,C', team: 'Grays' },
    { year: 2022, name: 'McKenna,R', team: 'Z-Unowned' },
    { year: 2022, name: 'McKenzie,T', team: 'Colt .45s' },
    { year: 2022, name: 'McKinstry,Z', team: 'Dodgers' },
    { year: 2022, name: 'McMahon,R', team: 'Whales' },
    { year: 2022, name: 'McNeil,J', team: 'Twins' },
    { year: 2022, name: 'Meadows,A', team: 'Blaze' },
    { year: 2022, name: 'Megill,T', team: 'Z-Unowned' },
    { year: 2022, name: 'Mejia,F', team: 'Knights' },
    { year: 2022, name: 'Melancon,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Melendez,M', team: 'Knights' },
    { year: 2022, name: 'Meneses,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Mercado,O', team: 'Z-Unowned' },
    { year: 2022, name: 'Merrifield,W', team: 'Expos' },
    { year: 2022, name: 'Meyers,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Mikolas,M', team: 'Colt .45s' },
    { year: 2022, name: 'Miller,B', team: 'Z-Unowned' },
    { year: 2022, name: 'Miller,O', team: 'Twins' },
    { year: 2022, name: 'Milner,H', team: 'Z-Unowned' },
    { year: 2022, name: 'Minor,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Minter,A', team: 'Stars' },
    { year: 2022, name: 'Miranda,J', team: 'Pilots' },
    { year: 2022, name: 'Misiewicz,A', team: 'Knights' },
    { year: 2022, name: 'Mitchell,C', team: 'Captains' },
    { year: 2022, name: 'Molina,Y', team: 'Twins' },
    { year: 2022, name: 'Moll,S', team: 'Z-Unowned' },
    { year: 2022, name: 'Moncada,Y', team: 'Stars' },
    { year: 2022, name: 'Moniak,M', team: 'Reds' },
    { year: 2022, name: 'Montas,F', team: 'Twins' },
    { year: 2022, name: 'Montero,E', team: 'Whales' },
    { year: 2022, name: 'Montero,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Montgomery,J', team: 'Monarchs' },
    { year: 2022, name: 'Moore,D', team: 'Knights' },
    { year: 2022, name: 'Moore,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Moran,C', team: 'Z-Unowned' },
    { year: 2022, name: 'Moran,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Morel,C', team: 'Yellow Jackets' },
    { year: 2022, name: 'Moreta,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Morgan,E', team: 'Pilots' },
    { year: 2022, name: 'Moronta,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Morton,C', team: 'Expos' },
    { year: 2022, name: 'Mountcastle,R', team: 'RockHounds' },
    { year: 2022, name: 'Moustakas,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Mullins,C', team: 'Dodgers' },
    { year: 2022, name: 'Muncy,M', team: 'Grays' },
    { year: 2022, name: 'Munoz,A', team: 'Knights' },
    { year: 2022, name: 'Murfee,P', team: 'Z-Unowned' },
    { year: 2022, name: 'Murphy,S', team: 'Yellow Jackets' },
    { year: 2022, name: 'Musgrove,J', team: 'Pelicans' },
    { year: 2022, name: 'Myers,W', team: 'Browns' },
    { year: 2022, name: 'Nance,T', team: 'Z-Unowned' },
    { year: 2022, name: 'Naquin,T', team: 'Gypsies' },
    { year: 2022, name: 'Narvaez,O', team: 'Z-Unowned' },
    { year: 2022, name: 'Naylor,J', team: 'Captains' },
    { year: 2022, name: 'Nelson,K', team: 'Z-Unowned' },
    { year: 2022, name: 'Nelson,N', team: 'Z-Unowned' },
    { year: 2022, name: 'Neris,H', team: 'Pelicans' },
    { year: 2022, name: 'Neuse,S', team: 'Z-Unowned' },
    { year: 2022, name: 'Nevin,T', team: 'Expos' },
    { year: 2022, name: 'Newman,K', team: 'Rockhounds' },
    { year: 2022, name: 'Nido,T', team: 'River Dogs' },
    { year: 2022, name: 'Nimmo,B', team: 'Pilgrims' },
    { year: 2022, name: 'Nola,A', team: 'Pilgrims' },
    { year: 2022, name: 'Nola,A', team: 'Yellow Jackets' },
    { year: 2022, name: 'Nootbaar,L', team: 'Blaze' },
    { year: 2022, name: 'Norris,D', team: 'Z-Unowned' },
    { year: 2022, name: 'O\'Hearn,R', team: 'Z-Unowned' },
    { year: 2022, name: 'O\'Neill,T', team: 'Titans' },
    { year: 2022, name: 'Ober,B', team: 'Whales' },
    { year: 2022, name: 'Odor,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Odorizzi,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Ohtani,S', team: 'Titans' },
    { year: 2022, name: 'Okert,S', team: 'Dodgers' },
    { year: 2022, name: 'Olivares,E', team: 'Reds' },
    { year: 2022, name: 'Oller,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Olson,M', team: 'Reds' },
    { year: 2022, name: 'Ortega,R', team: 'Expos' },
    { year: 2022, name: 'Ottavino,A', team: 'Expos' },
    { year: 2022, name: 'Otto,G', team: 'Z-Unowned' },
    { year: 2022, name: 'Ozuna,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Pache,C', team: 'Yellow Jackets' },
    { year: 2022, name: 'Pagan,E', team: 'Z-Unowned' },
    { year: 2022, name: 'Palacios,R', team: 'Pilots' },
    { year: 2022, name: 'Pallante,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Paredes,I', team: 'Pelicans' },
    { year: 2022, name: 'Pasquantino,V', team: 'TinCaps' },
    { year: 2022, name: 'Payamps,J', team: 'Expos' },
    { year: 2022, name: 'Pederson,J', team: 'Yellow Jackets' },
    { year: 2022, name: 'Pena,J', team: 'Pilots' },
    { year: 2022, name: 'Peralta,D', team: 'Reds' },
    { year: 2022, name: 'Peralta,F', team: 'Stars' },
    { year: 2022, name: 'Peralta,W', team: 'Colt .45s' },
    { year: 2022, name: 'Perdomo,G', team: 'Grays' },
    { year: 2022, name: 'Perez,C', team: 'Z-Unowned' },
    { year: 2022, name: 'Perez,M', team: 'Pelicans' },
    { year: 2022, name: 'Perez,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Perez,S', team: 'Browns' },
    { year: 2022, name: 'Peterson,D', team: 'RockHounds' },
    { year: 2022, name: 'Peterson,J', team: 'Expos' },
    { year: 2022, name: 'Pham,T', team: 'Z-Unowned' },
    { year: 2022, name: 'Phelps,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Phillips,B', team: 'Z-Unowned' },
    { year: 2022, name: 'Phillips,E', team: 'Gypsies' },
    { year: 2022, name: 'Pilkington,K', team: 'Blaze' },
    { year: 2022, name: 'Pinder,C', team: 'Z-Unowned' },
    { year: 2022, name: 'Pineda,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Piscotty,S', team: 'Z-Unowned' },
    { year: 2022, name: 'Pivetta,N', team: 'Grays' },
    { year: 2022, name: 'Plawecki,K', team: 'Z-Unowned' },
    { year: 2022, name: 'Plesac,Z', team: 'Dodgers' },
    { year: 2022, name: 'Poche,C', team: 'Hornets' },
    { year: 2022, name: 'Polanco,J', team: 'Pilgrims' },
    { year: 2022, name: 'Pollock,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Pop,Z', team: 'Whales' },
    { year: 2022, name: 'Pratto,N', team: 'Knights' },
    { year: 2022, name: 'Pressly,R', team: 'Titans' },
    { year: 2022, name: 'Price,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Profar,J', team: 'Twins' },
    { year: 2022, name: 'Pruitt,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Pujols,A', team: 'Gypsies' },
    { year: 2022, name: 'Puk,A', team: 'RockHounds' },
    { year: 2022, name: 'Quantrill,C', team: 'TinCaps' },
    { year: 2022, name: 'Quijada,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Quintana,J', team: 'Grays' },
    { year: 2022, name: 'Raleigh,C', team: 'Stars' },
    { year: 2022, name: 'Raley,B', team: 'Blaze' },
    { year: 2022, name: 'Ramirez,E', team: 'Z-Unowned' },
    { year: 2022, name: 'Ramirez,H', team: 'River Dogs' },
    { year: 2022, name: 'Ramirez,J', team: 'Pilgrims' },
    { year: 2022, name: 'Ramirez,N', team: 'Z-Unowned' },
    { year: 2022, name: 'Ramirez,Y', team: 'Z-Unowned' },
    { year: 2022, name: 'Rasmussen,D', team: 'TinCaps' },
    { year: 2022, name: 'Ray,R', team: 'Yellow Jackets' },
    { year: 2022, name: 'Realmuto,J', team: 'Pelicans' },
    { year: 2022, name: 'Refsnyder,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Rendon,A', team: 'Captains' },
    { year: 2022, name: 'Renfroe,H', team: 'River Dogs' },
    { year: 2022, name: 'Rengifo,L', team: 'RockHounds' },
    { year: 2022, name: 'Reyes,F', team: 'RockHounds' },
    { year: 2022, name: 'Reyes,V', team: 'Knights' },
    { year: 2022, name: 'Reynolds,B', team: 'Knights' },
    { year: 2022, name: 'Reynolds,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Richards,G', team: 'Z-Unowned' },
    { year: 2022, name: 'Richards,T', team: 'Z-Unowned' },
    { year: 2022, name: 'Riley,A', team: 'Titans' },
    { year: 2022, name: 'Rivas,A', team: 'Colt .45s' },
    { year: 2022, name: 'Rivera,E', team: 'Z-Unowned' },
    { year: 2022, name: 'Rizzo,A', team: 'Yellow Jackets' },
    { year: 2022, name: 'Robert,L', team: 'RockHounds' },
    { year: 2022, name: 'Robertson,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Robles,V', team: 'Browns' },
    { year: 2022, name: 'Rodgers,B', team: 'Stars' },
    { year: 2022, name: 'Rodon,C', team: 'Blaze' },
    { year: 2022, name: 'Rodriguez,E', team: 'Hornets' },
    { year: 2022, name: 'Rodriguez,J', team: 'Grays' },
    { year: 2022, name: 'Rodriguez,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Rogers,T', team: 'Browns' },
    { year: 2022, name: 'Rogers,T', team: 'Colt .45s' },
    { year: 2022, name: 'Rogers,T', team: 'Monarchs' },
    { year: 2022, name: 'Rojas,J', team: 'Hornets' },
    { year: 2022, name: 'Rojas,M', team: 'Twins' },
    { year: 2022, name: 'Romano,J', team: 'Knights' },
    { year: 2022, name: 'Romine,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Rosario,A', team: 'Stars' },
    { year: 2022, name: 'Rosario,E', team: 'Z-Unowned' },
    { year: 2022, name: 'Rucker,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Ruf,D', team: 'Pelicans' },
    { year: 2022, name: 'Ruiz,J', team: 'Pilots' },
    { year: 2022, name: 'Ruiz,K', team: 'Stars' },
    { year: 2022, name: 'Rutschman,A', team: 'Grays' },
    { year: 2022, name: 'Ryan,J', team: 'Blaze' },
    { year: 2022, name: 'Sampson,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Sanchez,A', team: 'Titans' },
    { year: 2022, name: 'Sanchez,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Sanchez,G', team: 'Z-Unowned' },
    { year: 2022, name: 'Sanchez,J', team: 'Reds' },
    { year: 2022, name: 'Sandlin,N', team: 'Hornets' },
    { year: 2022, name: 'Sandoval,P', team: 'TinCaps' },
    { year: 2022, name: 'Sanmartin,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Santana,C', team: 'Z-Unowned' },
    { year: 2022, name: 'Santana,D', team: 'Reds' },
    { year: 2022, name: 'Santander,A', team: 'Pelicans' },
    { year: 2022, name: 'Sawamura,H', team: 'Z-Unowned' },
    { year: 2022, name: 'Scherzer,M', team: 'Yellow Jackets' },
    { year: 2022, name: 'Schoop,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Schreiber,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Schwarber,K', team: 'Dodgers' },
    { year: 2022, name: 'Schwindel,F', team: 'Z-Unowned' },
    { year: 2022, name: 'Scott,T', team: 'Twins' },
    { year: 2022, name: 'Seager,C', team: 'Reds' },
    { year: 2022, name: 'Sears,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Segura,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Semien,M', team: 'Yellow Jackets' },
    { year: 2022, name: 'Senzatela,A', team: 'RockHounds' },
    { year: 2022, name: 'Senzel,N', team: 'Z-Unowned' },
    { year: 2022, name: 'Serven,B', team: 'Z-Unowned' },
    { year: 2022, name: 'Severino,L', team: 'Reds' },
    { year: 2022, name: 'Sewald,P', team: 'Pilgrims' },
    { year: 2022, name: 'Shaw,B', team: 'Z-Unowned' },
    { year: 2022, name: 'Sheets,G', team: 'TinCaps' },
    { year: 2022, name: 'Singer,B', team: 'Whales' },
    { year: 2022, name: 'Siri,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Skubal,T', team: 'Pilots' },
    { year: 2022, name: 'Slater,A', team: 'TinCaps' },
    { year: 2022, name: 'Smeltzer,D', team: 'TinCaps' },
    { year: 2022, name: 'Smith,C', team: 'Z-Unowned' },
    { year: 2022, name: 'Smith,D', team: 'Pilots' },
    { year: 2022, name: 'Smith,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Smith,J', team: 'Hornets' },
    { year: 2022, name: 'Smith,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Smith,K', team: 'Z-Unowned' },
    { year: 2022, name: 'Smith,P', team: 'Whales' },
    { year: 2022, name: 'Smith,W', team: 'Captains' },
    { year: 2022, name: 'Smith,W', team: 'Z-Unowned' },
    { year: 2022, name: 'Smyly,D', team: 'Stars' },
    { year: 2022, name: 'Snead,K', team: 'Z-Unowned' },
    { year: 2022, name: 'Snell,B', team: 'Blaze' },
    { year: 2022, name: 'Snider,C', team: 'Z-Unowned' },
    { year: 2022, name: 'Solano,D', team: 'Whales' },
    { year: 2022, name: 'Soler,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Sosa,E', team: 'Yellow Jackets' },
    { year: 2022, name: 'Soto,G', team: 'RockHounds' },
    { year: 2022, name: 'Soto,J', team: 'Stars' },
    { year: 2022, name: 'Springer,G', team: 'Monarchs' },
    { year: 2022, name: 'Springs,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Stallings,J', team: 'Dodgers' },
    { year: 2022, name: 'Stammen,C', team: 'Z-Unowned' },
    { year: 2022, name: 'Stanek,R', team: 'Yellow Jackets' },
    { year: 2022, name: 'Stanton,G', team: 'Dodgers' },
    { year: 2022, name: 'Stassi,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Staumont,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Steele,J', team: 'Reds' },
    { year: 2022, name: 'Stephan,T', team: 'River Dogs' },
    { year: 2022, name: 'Stephens,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Stephenson,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Stephenson,T', team: 'Expos' },
    { year: 2022, name: 'Story,T', team: 'Colt .45s' },
    { year: 2022, name: 'Stott,B', team: 'Twins' },
    { year: 2022, name: 'Strahm,M', team: 'Stars' },
    { year: 2022, name: 'Stratton,C', team: 'Pelicans' },
    { year: 2022, name: 'Straw,M', team: 'TinCaps' },
    { year: 2022, name: 'Strickland,H', team: 'Colt .45s' },
    { year: 2022, name: 'Strider,S', team: 'Hornets' },
    { year: 2022, name: 'Stripling,R', team: 'Whales' },
    { year: 2022, name: 'Stroman,M', team: 'Pilgrims' },
    { year: 2022, name: 'Strzelecki,P', team: 'Z-Unowned' },
    { year: 2022, name: 'Stubbs,G', team: 'Z-Unowned' },
    { year: 2022, name: 'Suarez,E', team: 'Z-Unowned' },
    { year: 2022, name: 'Suarez,J', team: 'Twins' },
    { year: 2022, name: 'Suarez,R', team: 'Grays' },
    { year: 2022, name: 'Suarez,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Sulser,C', team: 'Z-Unowned' },
    { year: 2022, name: 'Suter,B', team: 'Hornets' },
    { year: 2022, name: 'Suwinski,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Suzuki,K', team: 'Z-Unowned' },
    { year: 2022, name: 'Suzuki,S', team: 'TinCaps' },
    { year: 2022, name: 'Swanson,D', team: 'Gypsies' },
    { year: 2022, name: 'Swanson,E', team: 'Z-Unowned' },
    { year: 2022, name: 'Syndergaard,N', team: 'Gypsies' },
    { year: 2022, name: 'Taillon,J', team: 'Pilgrims' },
    { year: 2022, name: 'Tapia,R', team: 'Browns' },
    { year: 2022, name: 'Tate,D', team: 'Bandits' },
    { year: 2022, name: 'Taveras,L', team: 'Dodgers' },
    { year: 2022, name: 'Taylor,C', team: 'Expos' },
    { year: 2022, name: 'Taylor,M', team: 'Hornets' },
    { year: 2022, name: 'Taylor,T', team: 'TinCaps' },
    { year: 2022, name: 'Tellez,R', team: 'Colt .45s' },
    { year: 2022, name: 'Tepera,R', team: 'Titans' },
    { year: 2022, name: 'Thielbar,C', team: 'Colt .45s' },
    { year: 2022, name: 'Thomas,A', team: 'Grays' },
    { year: 2022, name: 'Thomas,L', team: 'Whales' },
    { year: 2022, name: 'Thompson,B', team: 'Pelicans' },
    { year: 2022, name: 'Thompson,K', team: 'Grays' },
    { year: 2022, name: 'Thompson,R', team: 'Z-Unowned' },
    { year: 2022, name: 'Thompson,T', team: 'Z-Unowned' },
    { year: 2022, name: 'Thompson,Z', team: 'TinCaps' },
    { year: 2022, name: 'Thornton,T', team: 'Dodgers' },
    { year: 2022, name: 'Toglia,M', team: 'Reds' },
    { year: 2022, name: 'Torkelson,S', team: 'Pilots' },
    { year: 2022, name: 'Toro,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Torrens,L', team: 'Z-Unowned' },
    { year: 2022, name: 'Torres,G', team: 'Titans' },
    { year: 2022, name: 'Trammell,T', team: 'Reds' },
    { year: 2022, name: 'Trejo,A', team: 'Gypsies' },
    { year: 2022, name: 'Trevino,J', team: 'River Dogs' },
    { year: 2022, name: 'Trivino,L', team: 'Z-Unowned' },
    { year: 2022, name: 'Trout,M', team: 'Titans' },
    { year: 2022, name: 'Tsutsugo,Y', team: 'Z-Unowned' },
    { year: 2022, name: 'Tucker,K', team: 'Stars' },
    { year: 2022, name: 'Turner,J', team: 'Bandits' },
    { year: 2022, name: 'Turner,T', team: 'Blaze' },
    { year: 2022, name: 'Underwood,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Urena,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Urias,J', team: 'Bandits' },
    { year: 2022, name: 'Urias,L', team: 'Browns' },
    { year: 2022, name: 'Urias,R', team: 'Reds' },
    { year: 2022, name: 'Urquidy,J', team: 'TinCaps' },
    { year: 2022, name: 'Urshela,G', team: 'Twins' },
    { year: 2022, name: 'Valdez,F', team: 'Twins' },
    { year: 2022, name: 'VanMeter,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Vargas,I', team: 'Z-Unowned' },
    { year: 2022, name: 'Varsho,D', team: 'TinCaps' },
    { year: 2022, name: 'Vaughn,A', team: 'Hornets' },
    { year: 2022, name: 'Vazquez,C', team: 'Twins' },
    { year: 2022, name: 'Velasquez,V', team: 'Z-Unowned' },
    { year: 2022, name: 'Velazquez,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Velazquez,N', team: 'Pilots' },
    { year: 2022, name: 'Verdugo,A', team: 'Dodgers' },
    { year: 2022, name: 'Verlander,J', team: 'Bandits' },
    { year: 2022, name: 'Vesia,A', team: 'Twins' },
    { year: 2022, name: 'Vest,W', team: 'Z-Unowned' },
    { year: 2022, name: 'Vierling,M', team: 'Z-Unowned' },
    { year: 2022, name: 'Villar,D', team: 'Z-Unowned' },
    { year: 2022, name: 'Villar,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Vogelbach,D', team: 'Bandits' },
    { year: 2022, name: 'Vogt,S', team: 'Z-Unowned' },
    { year: 2022, name: 'Voit,L', team: 'Pilgrims' },
    { year: 2022, name: 'Voth,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Votto,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Wacha,M', team: 'River Dogs' },
    { year: 2022, name: 'Wade,L', team: 'Hornets' },
    { year: 2022, name: 'Wade,T', team: 'Hornets' },
    { year: 2022, name: 'Wainwright,A', team: 'Colt .45s' },
    { year: 2022, name: 'Walker,C', team: 'Pelicans' },
    { year: 2022, name: 'Walker,T', team: 'Dodgers' },
    { year: 2022, name: 'Walls,T', team: 'Pilots' },
    { year: 2022, name: 'Walsh,J', team: 'Hornets' },
    { year: 2022, name: 'Wantz,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Ward,T', team: 'Pelicans' },
    { year: 2022, name: 'Warren,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Watkins,S', team: 'Z-Unowned' },
    { year: 2022, name: 'Webb,L', team: 'Reds' },
    { year: 2022, name: 'Weems,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Wells,T', team: 'Gypsies' },
    { year: 2022, name: 'Wendle,J', team: 'Gypsies' },
    { year: 2022, name: 'Wheeler,Z', team: 'Pilgrims' },
    { year: 2022, name: 'White,E', team: 'Z-Unowned' },
    { year: 2022, name: 'White,M', team: 'Pilgrims' },
    { year: 2022, name: 'Whitlock,G', team: 'Gypsies' },
    { year: 2022, name: 'Wick,R', team: 'Monarchs' },
    { year: 2022, name: 'Williams,D', team: 'Stars' },
    { year: 2022, name: 'Williams,L', team: 'Z-Unowned' },
    { year: 2022, name: 'Williams,T', team: 'Whales' },
    { year: 2022, name: 'Wilson,B', team: 'Stars' },
    { year: 2022, name: 'Wilson,S', team: 'Z-Unowned' },
    { year: 2022, name: 'Winckowski,J', team: 'Z-Unowned' },
    { year: 2022, name: 'Winder,J', team: 'River Dogs' },
    { year: 2022, name: 'Winker,J', team: 'Pilgrims' },
    { year: 2022, name: 'Wisdom,P', team: 'Hornets' },
    { year: 2022, name: 'Wisler,M', team: 'Colt .45s' },
    { year: 2022, name: 'Witt,B', team: 'Twins' },
    { year: 2022, name: 'Wong,K', team: 'Bandits' },
    { year: 2022, name: 'Wood,A', team: 'Monarchs' },
    { year: 2022, name: 'Woodruff,B', team: 'Pilgrims' },
    { year: 2022, name: 'Wright,K', team: 'Pilots' },
    { year: 2022, name: 'Wynns,A', team: 'Z-Unowned' },
    { year: 2022, name: 'Yarbrough,R', team: 'Pelicans' },
    { year: 2022, name: 'Yastrzemski,M', team: 'Gypsies' },
    { year: 2022, name: 'Yelich,C', team: 'Titans' },
    { year: 2022, name: 'Yepez,J', team: 'Dodgers' },
    { year: 2022, name: 'Zavala,S', team: 'Bandits' },
    { year: 2022, name: 'Zimmer,B', team: 'Z-Unowned' },
    { year: 2022, name: 'Zimmermann,B', team: 'Z-Unowned' },
    { year: 2022, name: 'Zunino,M', team: 'Bandits' },
    { year: 2023, name: 'Abbott,A', team: 'Clown Princes' },
    { year: 2023, name: 'Abrams,C', team: 'RockHounds' },
    { year: 2023, name: 'Abreu,A', team: 'River Dogs' },
    { year: 2023, name: 'Abreu,B', team: 'TinCaps' },
    { year: 2023, name: 'Abreu,J', team: 'Bandits' },
    { year: 2023, name: 'Acuna Jr,R', team: 'Grays' },
    { year: 2023, name: 'Adam,J', team: 'Gypsies' },
    { year: 2023, name: 'Adames,W', team: 'Knights' },
    { year: 2023, name: 'Adams,R', team: 'Z-Unowned' },
    { year: 2023, name: 'Adon,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Aguilar,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Ahmed,N', team: 'Monarchs' },
    { year: 2023, name: 'Albies,O', team: 'Titans' },
    { year: 2023, name: 'Alcantara,S', team: 'Bandits' },
    { year: 2023, name: 'Alexander,S', team: 'Z-Unowned' },
    { year: 2023, name: 'Allen,L', team: 'Expos' },
    { year: 2023, name: 'Allen,N', team: 'Browns' },
    { year: 2023, name: 'Almonte,Y', team: 'Z-Unowned' },
    { year: 2023, name: 'Alonso,P', team: 'Blaze' },
    { year: 2023, name: 'Altuve,J', team: 'Grays' },
    { year: 2023, name: 'Alu,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Alvarado,J', team: 'Stars' },
    { year: 2023, name: 'Alvarez,F', team: 'Twins' },
    { year: 2023, name: 'Alvarez,Y', team: 'Grays' },
    { year: 2023, name: 'Alzolay,A', team: 'Blaze' },
    { year: 2023, name: 'Amaya,M', team: 'River Dogs' },
    { year: 2023, name: 'Anderson,B', team: 'Z-Unowned' },
    { year: 2023, name: 'Anderson,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Anderson,N', team: 'Z-Unowned' },
    { year: 2023, name: 'Anderson,T', team: 'Captains' },
    { year: 2023, name: 'Anderson,T', team: 'Bandits' },
    { year: 2023, name: 'Andrus,E', team: 'River Dogs' },
    { year: 2023, name: 'Arcia,O', team: 'Bandits' },
    { year: 2023, name: 'Arenado,N', team: 'Dodgers' },
    { year: 2023, name: 'Arias,G', team: 'TinCaps' },
    { year: 2023, name: 'Armstrong,S', team: 'Z-Unowned' },
    { year: 2023, name: 'Arozarena,R', team: 'Monarchs' },
    { year: 2023, name: 'Arraez,L', team: 'Captains' },
    { year: 2023, name: 'Arroyo,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Ashcraft,G', team: 'Titans' },
    { year: 2023, name: 'Assad,J', team: 'TinCaps' },
    { year: 2023, name: 'Baddoo,A', team: 'River Dogs' },
    { year: 2023, name: 'Bader,H', team: 'Titans' },
    { year: 2023, name: 'Bae,J', team: 'Stars' },
    { year: 2023, name: 'Baez,J', team: 'Pelicans' },
    { year: 2023, name: 'Bailey,P', team: 'Monarchs' },
    { year: 2023, name: 'Baker,B', team: 'Pilgrims' },
    { year: 2023, name: 'Banks,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Bard,D', team: 'Z-Unowned' },
    { year: 2023, name: 'Barlow,S', team: 'Reds' },
    { year: 2023, name: 'Barnes,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Barnhart,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Barrero,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Barria,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Bassitt,C', team: 'Browns' },
    { year: 2023, name: 'Batten,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Baty,B', team: 'RockHounds' },
    { year: 2023, name: 'Bauers,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Baumann,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Bautista,F', team: 'Grays' },
    { year: 2023, name: 'Beck,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Bednar,D', team: 'Captains' },
    { year: 2023, name: 'Beeks,J', team: 'Hornets' },
    { year: 2023, name: 'Bell,J', team: 'Browns' },
    { year: 2023, name: 'Bellinger,C', team: 'Pilgrims' },
    { year: 2023, name: 'Bello,B', team: 'RockHounds' },
    { year: 2023, name: 'Belt,B', team: 'Yellow Jackets' },
    { year: 2023, name: 'Benintendi,A', team: 'Yellow Jackets' },
    { year: 2023, name: 'Benson,W', team: 'Z-Unowned' },
    { year: 2023, name: 'Bernardino,B', team: 'Z-Unowned' },
    { year: 2023, name: 'Berrios,J', team: 'Yellow Jackets' },
    { year: 2023, name: 'Berti,J', team: 'Reds' },
    { year: 2023, name: 'Bethancourt,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Betts,M', team: 'Grays' },
    { year: 2023, name: 'Bibee,T', team: 'River Dogs' },
    { year: 2023, name: 'Bichette,B', team: 'Twins' },
    { year: 2023, name: 'Bickford,P', team: 'Titans' },
    { year: 2023, name: 'Bieber,S', team: 'Captains' },
    { year: 2023, name: 'Bielak,B', team: 'Z-Unowned' },
    { year: 2023, name: 'Biggio,C', team: 'Clown Princes' },
    { year: 2023, name: 'Bird,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Blach,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Blackburn,P', team: 'Titans' },
    { year: 2023, name: 'Blackmon,C', team: 'Pilgrims' },
    { year: 2023, name: 'Blanco,D', team: 'Z-Unowned' },
    { year: 2023, name: 'Bleday,J', team: 'Dodgers' },
    { year: 2023, name: 'Bogaerts,X', team: 'Colt .45s' },
    { year: 2023, name: 'Bohm,A', team: 'Blaze' },
    { year: 2023, name: 'Borucki,R', team: 'Z-Unowned' },
    { year: 2023, name: 'Boyd,M', team: 'Hornets' },
    { year: 2023, name: 'Bradish,K', team: 'Hornets' },
    { year: 2023, name: 'Bradley Jr,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Bradley,T', team: 'Grays' },
    { year: 2023, name: 'Brash,M', team: 'Hornets' },
    { year: 2023, name: 'Brasier,R', team: 'Pelicans' },
    { year: 2023, name: 'Brazoban,H', team: 'Z-Unowned' },
    { year: 2023, name: 'Brebbia,J', team: 'Yellow Jackets' },
    { year: 2023, name: 'Bregman,A', team: 'Colt .45s' },
    { year: 2023, name: 'Brennan,W', team: 'Pilots' },
    { year: 2023, name: 'Brigham,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Brito,J', team: 'Pilots' },
    { year: 2023, name: 'Brown,H', team: 'River Dogs' },
    { year: 2023, name: 'Brown,S', team: 'Knights' },
    { year: 2023, name: 'Bryant,K', team: 'Stars' },
    { year: 2023, name: 'Bummer,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Burger,J', team: 'Yellow Jackets' },
    { year: 2023, name: 'Burke,B', team: 'TinCaps' },
    { year: 2023, name: 'Burleson,A', team: 'Bandits' },
    { year: 2023, name: 'Burnes,C', team: 'Dodgers' },
    { year: 2023, name: 'Butler,L', team: 'Colt .45s' },
    { year: 2023, name: 'Buxton,B', team: 'Bandits' },
    { year: 2023, name: 'Caballero,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Cabrera,E', team: 'RockHounds' },
    { year: 2023, name: 'Cabrera,G', team: 'Z-Unowned' },
    { year: 2023, name: 'Cabrera,M', team: 'Expos' },
    { year: 2023, name: 'Cabrera,O', team: 'Bandits' },
    { year: 2023, name: 'Calhoun,K', team: 'Z-Unowned' },
    { year: 2023, name: 'Calhoun,W', team: 'Twins' },
    { year: 2023, name: 'Call,A', team: 'Dodgers' },
    { year: 2023, name: 'Campusano,L', team: 'RockHounds' },
    { year: 2023, name: 'Candelario,J', team: 'Pelicans' },
    { year: 2023, name: 'Canha,M', team: 'Captains' },
    { year: 2023, name: 'Canning,G', team: 'Dodgers' },
    { year: 2023, name: 'Cano,Y', team: 'Z-Unowned' },
    { year: 2023, name: 'Canzone,D', team: 'Bandits' },
    { year: 2023, name: 'Caratini,V', team: 'Z-Unowned' },
    { year: 2023, name: 'Carlson,D', team: 'TinCaps' },
    { year: 2023, name: 'Carpenter,K', team: 'Pilots' },
    { year: 2023, name: 'Carpenter,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Carrasco,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Carroll,C', team: 'Colt .45s' },
    { year: 2023, name: 'Casas,T', team: 'Reds' },
    { year: 2023, name: 'Castellanos,N', team: 'Gypsies' },
    { year: 2023, name: 'Castillo,L', team: 'Captains' },
    { year: 2023, name: 'Castro,H', team: 'Z-Unowned' },
    { year: 2023, name: 'Castro,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Castro,R', team: 'Z-Unowned' },
    { year: 2023, name: 'Castro,W', team: 'TinCaps' },
    { year: 2023, name: 'Cave,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Cease,D', team: 'Browns' },
    { year: 2023, name: 'Chafin,A', team: 'Reds' },
    { year: 2023, name: 'Chang,Y', team: 'Z-Unowned' },
    { year: 2023, name: 'Chapman,A', team: 'Clown Princes' },
    { year: 2023, name: 'Chapman,M', team: 'Blaze' },
    { year: 2023, name: 'Chargois,J', team: 'Expos' },
    { year: 2023, name: 'Chavez,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Chirinos,Y', team: 'Blaze' },
    { year: 2023, name: 'Chisholm Jr,J', team: 'Pelicans' },
    { year: 2023, name: 'Choi,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Cisnero,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Civale,A', team: 'River Dogs' },
    { year: 2023, name: 'Clarke,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Clase,E', team: 'Captains' },
    { year: 2023, name: 'Clemens,K', team: 'Z-Unowned' },
    { year: 2023, name: 'Clevinger,M', team: 'Gypsies' },
    { year: 2023, name: 'Cobb,A', team: 'Monarchs' },
    { year: 2023, name: 'Colas,O', team: 'RockHounds' },
    { year: 2023, name: 'Cole,G', team: 'Gypsies' },
    { year: 2023, name: 'Conforto,M', team: 'Pilgrims' },
    { year: 2023, name: 'Contreras,R', team: 'Reds' },
    { year: 2023, name: 'Contreras,W', team: 'Browns' },
    { year: 2023, name: 'Contreras,W', team: 'Colt .45s' },
    { year: 2023, name: 'Cooper,G', team: 'Twins' },
    { year: 2023, name: 'Corbin,P', team: 'Z-Unowned' },
    { year: 2023, name: 'Cordero,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Correa,C', team: 'Clown Princes' },
    { year: 2023, name: 'Cortes,N', team: 'Clown Princes' },
    { year: 2023, name: 'Cosgrove,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Coulombe,D', team: 'Gypsies' },
    { year: 2023, name: 'Crawford,B', team: 'Z-Unowned' },
    { year: 2023, name: 'Crawford,J', team: 'Titans' },
    { year: 2023, name: 'Crawford,K', team: 'Browns' },
    { year: 2023, name: 'Cron,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Cronenworth,J', team: 'Hornets' },
    { year: 2023, name: 'Cruz,F', team: 'Z-Unowned' },
    { year: 2023, name: 'Cruz,N', team: 'Z-Unowned' },
    { year: 2023, name: 'Cuas,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Cueto,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Curry,X', team: 'Pilots' },
    { year: 2023, name: 'd\'Arnaud,T', team: 'Titans' },
    { year: 2023, name: 'Darvish,Y', team: 'Grays' },
    { year: 2023, name: 'Davidson,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Davies,Z', team: 'Browns' },
    { year: 2023, name: 'Davis,H', team: 'RockHounds' },
    { year: 2023, name: 'Davis,J', team: 'Colt .45s' },
    { year: 2023, name: 'De La Cruz,B', team: 'Pilgrims' },
    { year: 2023, name: 'De La Cruz,E', team: 'RockHounds' },
    { year: 2023, name: 'De Los Santos,E', team: 'Stars' },
    { year: 2023, name: 'DeJong,P', team: 'Yellow Jackets' },
    { year: 2023, name: 'Delay,J', team: 'Z-Unowned' },
    { year: 2023, name: 'DeSclafani,A', team: 'Bandits' },
    { year: 2023, name: 'Detmers,R', team: 'Knights' },
    { year: 2023, name: 'Devenski,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Devers,R', team: 'Knights' },
    { year: 2023, name: 'Diaz,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Diaz,A', team: 'Bandits' },
    { year: 2023, name: 'Diaz,E', team: 'TinCaps' },
    { year: 2023, name: 'Diaz,J', team: 'Colt .45s' },
    { year: 2023, name: 'Diaz,Y', team: 'Twins' },
    { year: 2023, name: 'Diaz,Y', team: 'River Dogs' },
    { year: 2023, name: 'Dickerson,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Diekman,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Dominguez,S', team: 'River Dogs' },
    { year: 2023, name: 'Donaldson,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Donovan,B', team: 'Pilots' },
    { year: 2023, name: 'Doval,C', team: 'River Dogs' },
    { year: 2023, name: 'Doyle,B', team: 'River Dogs' },
    { year: 2023, name: 'Drury,B', team: 'Stars' },
    { year: 2023, name: 'Duarte,D', team: 'Z-Unowned' },
    { year: 2023, name: 'Dubon,M', team: 'Twins' },
    { year: 2023, name: 'Duffy,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Dunning,D', team: 'Captains' },
    { year: 2023, name: 'Duran,E', team: 'Monarchs' },
    { year: 2023, name: 'Duran,J', team: 'Grays' },
    { year: 2023, name: 'Duran,J', team: 'River Dogs' },
    { year: 2023, name: 'Duvall,A', team: 'Gypsies' },
    { year: 2023, name: 'Edman,T', team: 'Yellow Jackets' },
    { year: 2023, name: 'Edwards Jr,C', team: 'Reds' },
    { year: 2023, name: 'Eflin,Z', team: 'Expos' },
    { year: 2023, name: 'Elder,B', team: 'Twins' },
    { year: 2023, name: 'Encarnacion-Strand,C', team: 'Stars' },
    { year: 2023, name: 'Englert,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Eovaldi,N', team: 'Colt .45s' },
    { year: 2023, name: 'Erceg,L', team: 'Z-Unowned' },
    { year: 2023, name: 'Escobar,E', team: 'Z-Unowned' },
    { year: 2023, name: 'Espinal,S', team: 'Gypsies' },
    { year: 2023, name: 'Estevez,C', team: 'Knights' },
    { year: 2023, name: 'Estrada,T', team: 'Pilgrims' },
    { year: 2023, name: 'Faedo,A', team: 'Pelicans' },
    { year: 2023, name: 'Fairbanks,P', team: 'Knights' },
    { year: 2023, name: 'Fairchild,S', team: 'Bandits' },
    { year: 2023, name: 'Falter,B', team: 'Knights' },
    { year: 2023, name: 'Farmer,B', team: 'Yellow Jackets' },
    { year: 2023, name: 'Farmer,K', team: 'Colt .45s' },
    { year: 2023, name: 'Feltner,R', team: 'Z-Unowned' },
    { year: 2023, name: 'Ferguson,C', team: 'Stars' },
    { year: 2023, name: 'Fermin,F', team: 'Z-Unowned' },
    { year: 2023, name: 'Ferrer,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Finnegan,K', team: 'Clown Princes' },
    { year: 2023, name: 'Flaherty,J', team: 'Pilgrims' },
    { year: 2023, name: 'Flexen,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Flores,W', team: 'Colt .45s' },
    { year: 2023, name: 'Floro,D', team: 'Z-Unowned' },
    { year: 2023, name: 'Foley,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Ford,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Fortes,N', team: 'Hornets' },
    { year: 2023, name: 'Fraley,J', team: 'Pilots' },
    { year: 2023, name: 'France,J', team: 'Z-Unowned' },
    { year: 2023, name: 'France,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Franco,W', team: 'Pilgrims' },
    { year: 2023, name: 'Frazier,A', team: 'RockHounds' },
    { year: 2023, name: 'Freeland,K', team: 'Z-Unowned' },
    { year: 2023, name: 'Freeman,F', team: 'Dodgers' },
    { year: 2023, name: 'Freeman,T', team: 'Titans' },
    { year: 2023, name: 'Frelick,S', team: 'Twins' },
    { year: 2023, name: 'Fried,M', team: 'Dodgers' },
    { year: 2023, name: 'Friedl,T', team: 'Gypsies' },
    { year: 2023, name: 'Fry,D', team: 'Z-Unowned' },
    { year: 2023, name: 'Fujinami,S', team: 'Z-Unowned' },
    { year: 2023, name: 'Fulmer,M', team: 'Twins' },
    { year: 2023, name: 'Gallagher,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Gallegos,G', team: 'Expos' },
    { year: 2023, name: 'Gallen,Z', team: 'Yellow Jackets' },
    { year: 2023, name: 'Gallo,J', team: 'Browns' },
    { year: 2023, name: 'Garcia,A', team: 'Expos' },
    { year: 2023, name: 'Garcia,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Garcia,L', team: 'Knights' },
    { year: 2023, name: 'Garcia,L', team: 'Z-Unowned' },
    { year: 2023, name: 'Garcia,M', team: 'Pilots' },
    { year: 2023, name: 'Garcia,Y', team: 'Z-Unowned' },
    { year: 2023, name: 'Garrett,B', team: 'Blaze' },
    { year: 2023, name: 'Garrett,S', team: 'Gypsies' },
    { year: 2023, name: 'Garver,M', team: 'Grays' },
    { year: 2023, name: 'Gausman,K', team: 'Titans' },
    { year: 2023, name: 'Gelof,Z', team: 'Reds' },
    { year: 2023, name: 'German,D', team: 'Knights' },
    { year: 2023, name: 'Gibaut,I', team: 'Z-Unowned' },
    { year: 2023, name: 'Gibson,K', team: 'Z-Unowned' },
    { year: 2023, name: 'Gilbert,L', team: 'RockHounds' },
    { year: 2023, name: 'Gimenez,A', team: 'Blaze' },
    { year: 2023, name: 'Ginkel,K', team: 'Z-Unowned' },
    { year: 2023, name: 'Giolito,L', team: 'River Dogs' },
    { year: 2023, name: 'Glasnow,T', team: 'Grays' },
    { year: 2023, name: 'Goldschmidt,P', team: 'Colt .45s' },
    { year: 2023, name: 'Gomber,A', team: 'Stars' },
    { year: 2023, name: 'Gomes,Y', team: 'Titans' },
    { year: 2023, name: 'Gonsolin,T', team: 'Titans' },
    { year: 2023, name: 'Gonzales,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Gonzales,N', team: 'Pelicans' },
    { year: 2023, name: 'Gonzalez,O', team: 'River Dogs' },
    { year: 2023, name: 'Gonzalez,V', team: 'Z-Unowned' },
    { year: 2023, name: 'Gore,M', team: 'Hornets' },
    { year: 2023, name: 'Gorman,N', team: 'Rockhounds' },
    { year: 2023, name: 'Gott,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Grandal,Y', team: 'Monarchs' },
    { year: 2023, name: 'Graterol,B', team: 'River Dogs' },
    { year: 2023, name: 'Graveman,K', team: 'Hornets' },
    { year: 2023, name: 'Gray,J', team: 'Reds' },
    { year: 2023, name: 'Gray,J', team: 'RockHounds' },
    { year: 2023, name: 'Gray,S', team: 'Grays' },
    { year: 2023, name: 'Greene,H', team: 'Clown Princes' },
    { year: 2023, name: 'Greene,R', team: 'Twins' },
    { year: 2023, name: 'Greinke,Z', team: 'Z-Unowned' },
    { year: 2023, name: 'Grichuk,R', team: 'Clown Princes' },
    { year: 2023, name: 'Grisham,T', team: 'TinCaps' },
    { year: 2023, name: 'Grossman,R', team: 'Clown Princes' },
    { year: 2023, name: 'Grove,M', team: 'Expos' },
    { year: 2023, name: 'Guerrero Jr,V', team: 'Pilgrims' },
    { year: 2023, name: 'Guillorme,L', team: 'Z-Unowned' },
    { year: 2023, name: 'Gurriel Jr,L', team: 'RockHounds' },
    { year: 2023, name: 'Gurriel,Y', team: 'Expos' },
    { year: 2023, name: 'Haase,E', team: 'Z-Unowned' },
    { year: 2023, name: 'Hader,J', team: 'Colt .45s' },
    { year: 2023, name: 'Hamilton,I', team: 'Z-Unowned' },
    { year: 2023, name: 'Hampson,G', team: 'Reds' },
    { year: 2023, name: 'Hand,B', team: 'Z-Unowned' },
    { year: 2023, name: 'Haniger,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Happ,I', team: 'Reds' },
    { year: 2023, name: 'Harper,B', team: 'Grays' },
    { year: 2023, name: 'Harris II,M', team: 'Pelicans' },
    { year: 2023, name: 'Harris,H', team: 'Z-Unowned' },
    { year: 2023, name: 'Harrison,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Harvey,H', team: 'Clown Princes' },
    { year: 2023, name: 'Hayes,K', team: 'Monarchs' },
    { year: 2023, name: 'Hays,A', team: 'Stars' },
    { year: 2023, name: 'Heaney,A', team: 'Browns' },
    { year: 2023, name: 'Hedges,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Heim,J', team: 'Blaze' },
    { year: 2023, name: 'Helsley,R', team: 'Knights' },
    { year: 2023, name: 'Henderson,G', team: 'Monarchs' },
    { year: 2023, name: 'Hendricks,K', team: 'Reds' },
    { year: 2023, name: 'Henry,T', team: 'Yellow Jackets' },
    { year: 2023, name: 'Hentges,S', team: 'River Dogs' },
    { year: 2023, name: 'Hernandez,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Hernandez,E', team: 'Captains' },
    { year: 2023, name: 'Hernandez,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Hernandez,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Hernandez,T', team: 'Browns' },
    { year: 2023, name: 'Herrera,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Heyward,J', team: 'River Dogs' },
    { year: 2023, name: 'Hicks,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Hicks,J', team: 'Grays' },
    { year: 2023, name: 'Higashioka,K', team: 'Clown Princes' },
    { year: 2023, name: 'Hill,R', team: 'Z-Unowned' },
    { year: 2023, name: 'Hill,T', team: 'Captains' },
    { year: 2023, name: 'Hoeing,B', team: 'Z-Unowned' },
    { year: 2023, name: 'Hoerner,N', team: 'Browns' },
    { year: 2023, name: 'Hoffman,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Holderman,C', team: 'Bandits' },
    { year: 2023, name: 'Holmes,C', team: 'TinCaps' },
    { year: 2023, name: 'Holton,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Honeywell Jr,B', team: 'Yellow Jackets' },
    { year: 2023, name: 'Houck,T', team: 'Blaze' },
    { year: 2023, name: 'Houser,A', team: 'Knights' },
    { year: 2023, name: 'Hudson,D', team: 'Captains' },
    { year: 2023, name: 'Ibanez,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Iglesias,R', team: 'Z-Unowned' },
    { year: 2023, name: 'India,J', team: 'Pilgrims' },
    { year: 2023, name: 'Irvin,C', team: 'Hornets' },
    { year: 2023, name: 'Irvin,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Isbel,K', team: 'Z-Unowned' },
    { year: 2023, name: 'Jackson,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Jackson,L', team: 'Z-Unowned' },
    { year: 2023, name: 'Jankowski,T', team: 'Gypsies' },
    { year: 2023, name: 'Jansen,D', team: 'Pilgrims' },
    { year: 2023, name: 'Jansen,K', team: 'Z-Unowned' },
    { year: 2023, name: 'Javier,C', team: 'River Dogs' },
    { year: 2023, name: 'Jax,G', team: 'Reds' },
    { year: 2023, name: 'Jeffers,R', team: 'Colt .45s' },
    { year: 2023, name: 'Jimenez,E', team: 'Monarchs' },
    { year: 2023, name: 'Jimenez,J', team: 'Pelicans' },
    { year: 2023, name: 'Joe,C', team: 'Gypsies' },
    { year: 2023, name: 'Johnson,P', team: 'Z-Unowned' },
    { year: 2023, name: 'Jones,N', team: 'Dodgers' },
    { year: 2023, name: 'Judge,A', team: 'Colt .45s' },
    { year: 2023, name: 'Julien,E', team: 'Yellow Jackets' },
    { year: 2023, name: 'Julks,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Jung,J', team: 'Browns' },
    { year: 2023, name: 'Junis,J', team: 'Bandits' },
    { year: 2023, name: 'Kahnle,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Kaprielian,J', team: 'Browns' },
    { year: 2023, name: 'Karinchak,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Kelenic,J', team: 'Twins' },
    { year: 2023, name: 'Keller,M', team: 'RockHounds' },
    { year: 2023, name: 'Kelly,C', team: 'Browns' },
    { year: 2023, name: 'Kelly,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Kelly,K', team: 'Z-Unowned' },
    { year: 2023, name: 'Kelly,M', team: 'Gypsies' },
    { year: 2023, name: 'Kemp,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Kepler,M', team: 'Yellow Jackets' },
    { year: 2023, name: 'Kershaw,C', team: 'Gypsies' },
    { year: 2023, name: 'Kiermaier,K', team: 'Blaze' },
    { year: 2023, name: 'Kikuchi,Y', team: 'Z-Unowned' },
    { year: 2023, name: 'Kim,H', team: 'Grays' },
    { year: 2023, name: 'Kimbrel,C', team: 'Titans' },
    { year: 2023, name: 'Kiner-Falefa,I', team: 'Expos' },
    { year: 2023, name: 'King,J', team: 'Z-Unowned' },
    { year: 2023, name: 'King,M', team: 'Grays' },
    { year: 2023, name: 'Kirby,G', team: 'Colt .45s' },
    { year: 2023, name: 'Kirilloff,A', team: 'Titans' },
    { year: 2023, name: 'Kirk,A', team: 'Hornets' },
    { year: 2023, name: 'Knizner,A', team: 'Expos' },
    { year: 2023, name: 'Koch,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Kopech,M', team: 'RockHounds' },
    { year: 2023, name: 'Kremer,D', team: 'Pilots' },
    { year: 2023, name: 'Kwan,S', team: 'River Dogs' },
    { year: 2023, name: 'Lambert,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Lambert,P', team: 'Z-Unowned' },
    { year: 2023, name: 'Lange,A', team: 'Pilots' },
    { year: 2023, name: 'Langeliers,S', team: 'Knights' },
    { year: 2023, name: 'Larnach,T', team: 'Dodgers' },
    { year: 2023, name: 'Laureano,R', team: 'Captains' },
    { year: 2023, name: 'Law,D', team: 'Z-Unowned' },
    { year: 2023, name: 'Lawrence,J', team: 'Z-Unowned' },
    { year: 2023, name: 'LeClerc,J', team: 'Titans' },
    { year: 2023, name: 'Leiter Jr,M', team: 'RockHounds' },
    { year: 2023, name: 'Lemahieu,D', team: 'Z-Unowned' },
    { year: 2023, name: 'Leone,D', team: 'Z-Unowned' },
    { year: 2023, name: 'Lewis,R', team: 'RockHounds' },
    { year: 2023, name: 'Liberatore,M', team: 'Rockhounds' },
    { year: 2023, name: 'Lindor,F', team: 'Dodgers' },
    { year: 2023, name: 'Littell,Z', team: 'Z-Unowned' },
    { year: 2023, name: 'Lively,B', team: 'Z-Unowned' },
    { year: 2023, name: 'Llovera,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Long,S', team: 'Z-Unowned' },
    { year: 2023, name: 'Longoria,E', team: 'Z-Unowned' },
    { year: 2023, name: 'Lopez,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Lopez,N', team: 'TinCaps' },
    { year: 2023, name: 'Lopez,P', team: 'Captains' },
    { year: 2023, name: 'Lopez,R', team: 'Captains' },
    { year: 2023, name: 'Lorenzen,M', team: 'Gypsies' },
    { year: 2023, name: 'Loup,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Lowe,B', team: 'Stars' },
    { year: 2023, name: 'Lowe,J', team: 'Knights' },
    { year: 2023, name: 'Lowe,N', team: 'Stars' },
    { year: 2023, name: 'Lugo,S', team: 'Stars' },
    { year: 2023, name: 'Luzardo,J', team: 'Monarchs' },
    { year: 2023, name: 'Lyles,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Lynn,L', team: 'Z-Unowned' },
    { year: 2023, name: 'Machado,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Machado,M', team: 'Gypsies' },
    { year: 2023, name: 'Madrigal,N', team: 'Bandits' },
    { year: 2023, name: 'Maeda,K', team: 'Expos' },
    { year: 2023, name: 'Maile,L', team: 'Z-Unowned' },
    { year: 2023, name: 'Maldonado,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Manaea,S', team: 'Clown Princes' },
    { year: 2023, name: 'Mancini,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Manning,M', team: 'Knights' },
    { year: 2023, name: 'Manoah,A', team: 'Blaze' },
    { year: 2023, name: 'Mantiply,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Marcano,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Margot,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Marinaccio,R', team: 'Clown Princes' },
    { year: 2023, name: 'Marsh,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Marsh,B', team: 'Monarchs' },
    { year: 2023, name: 'Marte,K', team: 'Dodgers' },
    { year: 2023, name: 'Marte,N', team: 'Browns' },
    { year: 2023, name: 'Marte,S', team: 'Z-Unowned' },
    { year: 2023, name: 'Marte,Y', team: 'Z-Unowned' },
    { year: 2023, name: 'Martin,C', team: 'Grays' },
    { year: 2023, name: 'Martinez,J', team: 'Captains' },
    { year: 2023, name: 'Martinez,N', team: 'Twins' },
    { year: 2023, name: 'Martinez,S', team: 'Z-Unowned' },
    { year: 2023, name: 'Massey,M', team: 'Colt .45s' },
    { year: 2023, name: 'Mastrobuoni,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Mateo,J', team: 'Monarchs' },
    { year: 2023, name: 'Maton,N', team: 'Z-Unowned' },
    { year: 2023, name: 'Maton,P', team: 'Z-Unowned' },
    { year: 2023, name: 'Matos,L', team: 'Yellow Jackets' },
    { year: 2023, name: 'Matz,S', team: 'Hornets' },
    { year: 2023, name: 'Mauricio,R', team: 'Knights' },
    { year: 2023, name: 'May,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Mayza,T', team: 'Pilgrims' },
    { year: 2023, name: 'McCann,J', team: 'Z-Unowned' },
    { year: 2023, name: 'McCarthy,J', team: 'Monarchs' },
    { year: 2023, name: 'McClanahan,S', team: 'Captains' },
    { year: 2023, name: 'McCormick,C', team: 'Yellow Jackets' },
    { year: 2023, name: 'McCutchen,A', team: 'Expos' },
    { year: 2023, name: 'McGough,S', team: 'Z-Unowned' },
    { year: 2023, name: 'McGuire,R', team: 'Z-Unowned' },
    { year: 2023, name: 'McHugh,C', team: 'Z-Unowned' },
    { year: 2023, name: 'McKenna,R', team: 'Z-Unowned' },
    { year: 2023, name: 'McKinney,B', team: 'Z-Unowned' },
    { year: 2023, name: 'McKinstry,Z', team: 'Z-Unowned' },
    { year: 2023, name: 'McLain,M', team: 'Titans' },
    { year: 2023, name: 'McMahon,R', team: 'Clown Princes' },
    { year: 2023, name: 'McNeil,J', team: 'Twins' },
    { year: 2023, name: 'Meadows,P', team: 'Reds' },
    { year: 2023, name: 'Medina,L', team: 'River Dogs' },
    { year: 2023, name: 'Megill,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Megill,T', team: 'Titans' },
    { year: 2023, name: 'Mejia,F', team: 'Z-Unowned' },
    { year: 2023, name: 'Melendez,M', team: 'Knights' },
    { year: 2023, name: 'Meneses,J', team: 'Bandits' },
    { year: 2023, name: 'Merrifield,W', team: 'Expos' },
    { year: 2023, name: 'Merryweather,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Meyers,J', team: 'Colt .45s' },
    { year: 2023, name: 'Middleton,K', team: 'Z-Unowned' },
    { year: 2023, name: 'Mikolas,M', team: 'Colt .45s' },
    { year: 2023, name: 'Miley,W', team: 'Monarchs' },
    { year: 2023, name: 'Miller,B', team: 'Grays' },
    { year: 2023, name: 'Miller,B', team: 'Pilgrims' },
    { year: 2023, name: 'Miller,O', team: 'Z-Unowned' },
    { year: 2023, name: 'Miller,S', team: 'Z-Unowned' },
    { year: 2023, name: 'Milner,H', team: 'Captains' },
    { year: 2023, name: 'Minter,A', team: 'Pelicans' },
    { year: 2023, name: 'Miranda,J', team: 'Pilots' },
    { year: 2023, name: 'Mlodzinski,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Moll,S', team: 'Expos' },
    { year: 2023, name: 'Monasterio,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Moncada,Y', team: 'Stars' },
    { year: 2023, name: 'Moniak,M', team: 'Reds' },
    { year: 2023, name: 'Montero,E', team: 'Clown Princes' },
    { year: 2023, name: 'Montero,R', team: 'Z-Unowned' },
    { year: 2023, name: 'Montgomery,J', team: 'Monarchs' },
    { year: 2023, name: 'Moore,D', team: 'Knights' },
    { year: 2023, name: 'Moore,M', team: 'Browns' },
    { year: 2023, name: 'Moran,J', team: 'Clown Princes' },
    { year: 2023, name: 'Morel,C', team: 'Yellow Jackets' },
    { year: 2023, name: 'Moreno,G', team: 'TinCaps' },
    { year: 2023, name: 'Moreta,D', team: 'Knights' },
    { year: 2023, name: 'Morgan,E', team: 'Pilots' },
    { year: 2023, name: 'Morton,C', team: 'Expos' },
    { year: 2023, name: 'Mountcastle,R', team: 'RockHounds' },
    { year: 2023, name: 'Moustakas,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Muller,K', team: 'Z-Unowned' },
    { year: 2023, name: 'Mullins,C', team: 'Dodgers' },
    { year: 2023, name: 'Muncy,M', team: 'Grays' },
    { year: 2023, name: 'Munoz,A', team: 'Knights' },
    { year: 2023, name: 'Murphy,S', team: 'Yellow Jackets' },
    { year: 2023, name: 'Murphy,T', team: 'Colt .45s' },
    { year: 2023, name: 'Musgrove,J', team: 'Pelicans' },
    { year: 2023, name: 'Myers,W', team: 'Z-Unowned' },
    { year: 2023, name: 'Nardi,A', team: 'Gypsies' },
    { year: 2023, name: 'Narvaez,O', team: 'Z-Unowned' },
    { year: 2023, name: 'Naylor,B', team: 'Stars' },
    { year: 2023, name: 'Naylor,J', team: 'Captains' },
    { year: 2023, name: 'Nelson,K', team: 'Pilots' },
    { year: 2023, name: 'Nelson,R', team: 'Knights' },
    { year: 2023, name: 'Neris,H', team: 'Pelicans' },
    { year: 2023, name: 'Neto,Z', team: 'Grays' },
    { year: 2023, name: 'Newman,K', team: 'Gypsies' },
    { year: 2023, name: 'Nimmo,B', team: 'Pilgrims' },
    { year: 2023, name: 'Noda,R', team: 'Gypsies' },
    { year: 2023, name: 'Nola,A', team: 'Yellow Jackets' },
    { year: 2023, name: 'Nola,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Nootbaar,L', team: 'Blaze' },
    { year: 2023, name: 'O\'Hearn,R', team: 'Z-Unowned' },
    { year: 2023, name: 'O\'Hoppe,L', team: 'Pilgrims' },
    { year: 2023, name: 'O\'Neill,T', team: 'Titans' },
    { year: 2023, name: 'Ober,B', team: 'Clown Princes' },
    { year: 2023, name: 'Odor,R', team: 'Z-Unowned' },
    { year: 2023, name: 'Ohtani,S', team: 'Titans' },
    { year: 2023, name: 'Okert,S', team: 'Dodgers' },
    { year: 2023, name: 'Olivares,E', team: 'Reds' },
    { year: 2023, name: 'Olson,M', team: 'Reds' },
    { year: 2023, name: 'Olson,R', team: 'Gypsies' },
    { year: 2023, name: 'Ortega,R', team: 'Z-Unowned' },
    { year: 2023, name: 'Ortiz,L', team: 'Hornets' },
    { year: 2023, name: 'Ottavino,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Outman,J', team: 'Pilots' },
    { year: 2023, name: 'Oviedo,J', team: 'River Dogs' },
    { year: 2023, name: 'Ozuna,M', team: 'Pilgrims' },
    { year: 2023, name: 'Pagan,E', team: 'Titans' },
    { year: 2023, name: 'Palacios,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Pallante,A', team: 'Knights' },
    { year: 2023, name: 'Paredes,I', team: 'Pelicans' },
    { year: 2023, name: 'Pasquantino,V', team: 'TinCaps' },
    { year: 2023, name: 'Paxton,J', team: 'Pilgrims' },
    { year: 2023, name: 'Payamps,J', team: 'Expos' },
    { year: 2023, name: 'Pearson,N', team: 'Grays' },
    { year: 2023, name: 'Pederson,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Peguero,E', team: 'Z-Unowned' },
    { year: 2023, name: 'Peguero,L', team: 'Pilgrims' },
    { year: 2023, name: 'Pena,J', team: 'Pilots' },
    { year: 2023, name: 'Peralta,D', team: 'Z-Unowned' },
    { year: 2023, name: 'Peralta,F', team: 'Stars' },
    { year: 2023, name: 'Peralta,W', team: 'Z-Unowned' },
    { year: 2023, name: 'Peraza,O', team: 'Stars' },
    { year: 2023, name: 'Perdomo,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Perdomo,G', team: 'Bandits' },
    { year: 2023, name: 'Perez,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Perez,C', team: 'Pilots' },
    { year: 2023, name: 'Perez,E', team: 'Stars' },
    { year: 2023, name: 'Perez,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Perez,S', team: 'Gypsies' },
    { year: 2023, name: 'Perkins,B', team: 'Z-Unowned' },
    { year: 2023, name: 'Peterson,D', team: 'Z-Unowned' },
    { year: 2023, name: 'Peterson,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Pfaadt,B', team: 'Pilgrims' },
    { year: 2023, name: 'Pham,T', team: 'Expos' },
    { year: 2023, name: 'Phillips,E', team: 'Gypsies' },
    { year: 2023, name: 'Pillar,K', team: 'Pelicans' },
    { year: 2023, name: 'Pinto,R', team: 'Z-Unowned' },
    { year: 2023, name: 'Pivetta,N', team: 'Clown Princes' },
    { year: 2023, name: 'Poche,C', team: 'Hornets' },
    { year: 2023, name: 'Polanco,J', team: 'Pilgrims' },
    { year: 2023, name: 'Pollock,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Pratto,N', team: 'Knights' },
    { year: 2023, name: 'Pressly,R', team: 'Pilots' },
    { year: 2023, name: 'Profar,J', team: 'Twins' },
    { year: 2023, name: 'Pruitt,A', team: 'TinCaps' },
    { year: 2023, name: 'Puk,A', team: 'RockHounds' },
    { year: 2023, name: 'Quantrill,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Quintana,J', team: 'Grays' },
    { year: 2023, name: 'Ragans,C', team: 'Blaze' },
    { year: 2023, name: 'Raleigh,C', team: 'Stars' },
    { year: 2023, name: 'Raley,B', team: 'Expos' },
    { year: 2023, name: 'Raley,L', team: 'Gypsies' },
    { year: 2023, name: 'Ramirez,E', team: 'Z-Unowned' },
    { year: 2023, name: 'Ramirez,H', team: 'Titans' },
    { year: 2023, name: 'Ramirez,J', team: 'Pilgrims' },
    { year: 2023, name: 'Ramirez,N', team: 'Z-Unowned' },
    { year: 2023, name: 'Ramirez,Y', team: 'Z-Unowned' },
    { year: 2023, name: 'Rea,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Realmuto,J', team: 'Pelicans' },
    { year: 2023, name: 'Refsnyder,R', team: 'Reds' },
    { year: 2023, name: 'Remillard,Z', team: 'Z-Unowned' },
    { year: 2023, name: 'Rendon,A', team: 'Captains' },
    { year: 2023, name: 'Renfroe,H', team: 'Z-Unowned' },
    { year: 2023, name: 'Rengifo,L', team: 'RockHounds' },
    { year: 2023, name: 'Reyes,P', team: 'Z-Unowned' },
    { year: 2023, name: 'Reynolds,B', team: 'Captains' },
    { year: 2023, name: 'Richards,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Riley,A', team: 'Titans' },
    { year: 2023, name: 'Rivas,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Rivera,E', team: 'Browns' },
    { year: 2023, name: 'Rizzo,A', team: 'Yellow Jackets' },
    { year: 2023, name: 'Robert Jr,L', team: 'RockHounds' },
    { year: 2023, name: 'Robertson,D', team: 'Browns' },
    { year: 2023, name: 'Robles,V', team: 'Z-Unowned' },
    { year: 2023, name: 'Rodgers,B', team: 'Stars' },
    { year: 2023, name: 'Rodon,C', team: 'Blaze' },
    { year: 2023, name: 'Rodriguez,E', team: 'Hornets' },
    { year: 2023, name: 'Rodriguez,E', team: 'RockHounds' },
    { year: 2023, name: 'Rodriguez,G', team: 'RockHounds' },
    { year: 2023, name: 'Rodriguez,J', team: 'Grays' },
    { year: 2023, name: 'Rogers,J', team: 'Bandits' },
    { year: 2023, name: 'Rogers,T', team: 'Clown Princes' },
    { year: 2023, name: 'Rogers,T', team: 'Browns' },
    { year: 2023, name: 'Rojas,J', team: 'Stars' },
    { year: 2023, name: 'Rojas,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Rojas,M', team: 'Twins' },
    { year: 2023, name: 'Romano,J', team: 'Knights' },
    { year: 2023, name: 'Rooker,B', team: 'Bandits' },
    { year: 2023, name: 'Rosario,A', team: 'Stars' },
    { year: 2023, name: 'Rosario,E', team: 'Pilgrims' },
    { year: 2023, name: 'Rucker,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Ruiz,E', team: 'Knights' },
    { year: 2023, name: 'Ruiz,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Ruiz,K', team: 'Bandits' },
    { year: 2023, name: 'Rutschman,A', team: 'Grays' },
    { year: 2023, name: 'Ryan,J', team: 'Blaze' },
    { year: 2023, name: 'Ryu,H', team: 'Bandits' },
    { year: 2023, name: 'Sabol,B', team: 'Pilots' },
    { year: 2023, name: 'Sale,C', team: 'Grays' },
    { year: 2023, name: 'Sanchez,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Sanchez,G', team: 'Monarchs' },
    { year: 2023, name: 'Sanchez,J', team: 'Reds' },
    { year: 2023, name: 'Sandlin,N', team: 'Hornets' },
    { year: 2023, name: 'Sandoval,P', team: 'TinCaps' },
    { year: 2023, name: 'Santana,C', team: 'Monarchs' },
    { year: 2023, name: 'Santander,A', team: 'Pelicans' },
    { year: 2023, name: 'Santos,G', team: 'Reds' },
    { year: 2023, name: 'Saucedo,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Sborz,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Schanuel,N', team: 'Blaze' },
    { year: 2023, name: 'Scherzer,M', team: 'Yellow Jackets' },
    { year: 2023, name: 'Schmidt,C', team: 'Clown Princes' },
    { year: 2023, name: 'Schmitt,C', team: 'Knights' },
    { year: 2023, name: 'Schneider,D', team: 'Z-Unowned' },
    { year: 2023, name: 'Scholtens,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Schoop,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Schreiber,J', team: 'Bandits' },
    { year: 2023, name: 'Schwarber,K', team: 'Dodgers' },
    { year: 2023, name: 'Scott,T', team: 'Twins' },
    { year: 2023, name: 'Seabold,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Seager,C', team: 'Reds' },
    { year: 2023, name: 'Sears,J', team: 'Pilots' },
    { year: 2023, name: 'Segura,J', team: 'Reds' },
    { year: 2023, name: 'Semien,M', team: 'Yellow Jackets' },
    { year: 2023, name: 'Senga,K', team: 'TinCaps' },
    { year: 2023, name: 'Senzel,N', team: 'Browns' },
    { year: 2023, name: 'Severino,L', team: 'Reds' },
    { year: 2023, name: 'Sewald,P', team: 'Pilots' },
    { year: 2023, name: 'Shaw,B', team: 'Z-Unowned' },
    { year: 2023, name: 'Sheehan,E', team: 'Titans' },
    { year: 2023, name: 'Sheets,G', team: 'TinCaps' },
    { year: 2023, name: 'Short,Z', team: 'Z-Unowned' },
    { year: 2023, name: 'Shreve,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Shuster,J', team: 'Yellow Jackets' },
    { year: 2023, name: 'Sims,L', team: 'Z-Unowned' },
    { year: 2023, name: 'Singer,B', team: 'Z-Unowned' },
    { year: 2023, name: 'Siri,J', team: 'RockHounds' },
    { year: 2023, name: 'Skubal,T', team: 'Pilots' },
    { year: 2023, name: 'Slater,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Smith,D', team: 'RockHounds' },
    { year: 2023, name: 'Smith,D', team: 'Pilots' },
    { year: 2023, name: 'Smith,J', team: 'Hornets' },
    { year: 2023, name: 'Smith,K', team: 'Z-Unowned' },
    { year: 2023, name: 'Smith,P', team: 'Clown Princes' },
    { year: 2023, name: 'Smith,W', team: 'Captains' },
    { year: 2023, name: 'Smith,W', team: 'Grays' },
    { year: 2023, name: 'Smyly,D', team: 'Stars' },
    { year: 2023, name: 'Snell,B', team: 'Blaze' },
    { year: 2023, name: 'Soderstrom,T', team: 'River Dogs' },
    { year: 2023, name: 'Solano,D', team: 'Clown Princes' },
    { year: 2023, name: 'Soler,J', team: 'RockHounds' },
    { year: 2023, name: 'Soriano,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Sosa,E', team: 'Yellow Jackets' },
    { year: 2023, name: 'Sosa,L', team: 'Z-Unowned' },
    { year: 2023, name: 'Soto,G', team: 'RockHounds' },
    { year: 2023, name: 'Soto,J', team: 'Stars' },
    { year: 2023, name: 'Speier,G', team: 'Gypsies' },
    { year: 2023, name: 'Springer,G', team: 'Monarchs' },
    { year: 2023, name: 'Stallings,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Stanek,R', team: 'Yellow Jackets' },
    { year: 2023, name: 'Stanton,G', team: 'Dodgers' },
    { year: 2023, name: 'Steele,J', team: 'Reds' },
    { year: 2023, name: 'Steer,S', team: 'Expos' },
    { year: 2023, name: 'Stephan,T', team: 'River Dogs' },
    { year: 2023, name: 'Stephenson,R', team: 'Z-Unowned' },
    { year: 2023, name: 'Stephenson,T', team: 'Expos' },
    { year: 2023, name: 'Stewart,D', team: 'Z-Unowned' },
    { year: 2023, name: 'Story,T', team: 'Colt .45s' },
    { year: 2023, name: 'Stott,B', team: 'Twins' },
    { year: 2023, name: 'Strahm,M', team: 'Stars' },
    { year: 2023, name: 'Stratton,C', team: 'Reds' },
    { year: 2023, name: 'Straw,M', team: 'TinCaps' },
    { year: 2023, name: 'Strider,S', team: 'Hornets' },
    { year: 2023, name: 'Stripling,R', team: 'Z-Unowned' },
    { year: 2023, name: 'Stroman,M', team: 'Pilgrims' },
    { year: 2023, name: 'Strzelecki,P', team: 'Z-Unowned' },
    { year: 2023, name: 'Stubbs,G', team: 'Gypsies' },
    { year: 2023, name: 'Suarez,E', team: 'Browns' },
    { year: 2023, name: 'Suarez,R', team: 'Browns' },
    { year: 2023, name: 'Suter,B', team: 'Hornets' },
    { year: 2023, name: 'Suwinski,J', team: 'Colt .45s' },
    { year: 2023, name: 'Suzuki,S', team: 'TinCaps' },
    { year: 2023, name: 'Swanson,D', team: 'Gypsies' },
    { year: 2023, name: 'Swanson,E', team: 'TinCaps' },
    { year: 2023, name: 'Syndergaard,N', team: 'Z-Unowned' },
    { year: 2023, name: 'Taillon,J', team: 'Pilots' },
    { year: 2023, name: 'Tapia,R', team: 'Z-Unowned' },
    { year: 2023, name: 'Tatis Jr,F', team: 'Expos' },
    { year: 2023, name: 'Tauchman,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Taveras,L', team: 'Dodgers' },
    { year: 2023, name: 'Taylor,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Taylor,M', team: 'Hornets' },
    { year: 2023, name: 'Taylor,T', team: 'Browns' },
    { year: 2023, name: 'Teheran,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Tellez,R', team: 'Z-Unowned' },
    { year: 2023, name: 'Thaiss,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Thielbar,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Thomas,A', team: 'Bandits' },
    { year: 2023, name: 'Thomas,L', team: 'Clown Princes' },
    { year: 2023, name: 'Thompson,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Thompson,R', team: 'Z-Unowned' },
    { year: 2023, name: 'Thompson,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Thompson,Z', team: 'Z-Unowned' },
    { year: 2023, name: 'Toglia,M', team: 'Reds' },
    { year: 2023, name: 'Tonkin,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Topa,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Torkelson,S', team: 'Pilots' },
    { year: 2023, name: 'Torres,G', team: 'Titans' },
    { year: 2023, name: 'Toussaint,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Tovar,E', team: 'Blaze' },
    { year: 2023, name: 'Trejo,A', team: 'Clown Princes' },
    { year: 2023, name: 'Trevino,J', team: 'Gypsies' },
    { year: 2023, name: 'Triolo,J', team: 'Yellow Jackets' },
    { year: 2023, name: 'Trout,M', team: 'Captains' },
    { year: 2023, name: 'Tucker,K', team: 'Stars' },
    { year: 2023, name: 'Turang,B', team: 'Blaze' },
    { year: 2023, name: 'Turner,J', team: 'Stars' },
    { year: 2023, name: 'Turner,T', team: 'Blaze' },
    { year: 2023, name: 'Urena,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Urias,J', team: 'Stars' },
    { year: 2023, name: 'Urias,L', team: 'Z-Unowned' },
    { year: 2023, name: 'Urias,R', team: 'Reds' },
    { year: 2023, name: 'Uribe,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Urquidy,J', team: 'TinCaps' },
    { year: 2023, name: 'Urshela,G', team: 'Twins' },
    { year: 2023, name: 'Valdez,E', team: 'Z-Unowned' },
    { year: 2023, name: 'Valdez,F', team: 'Twins' },
    { year: 2023, name: 'Vargas,I', team: 'Z-Unowned' },
    { year: 2023, name: 'Vargas,M', team: 'Dodgers' },
    { year: 2023, name: 'Varland,L', team: 'Pilots' },
    { year: 2023, name: 'Varsho,D', team: 'TinCaps' },
    { year: 2023, name: 'Vasquez,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Vaughn,A', team: 'Hornets' },
    { year: 2023, name: 'Vazquez,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Velazquez,N', team: 'Grays' },
    { year: 2023, name: 'Verdugo,A', team: 'Dodgers' },
    { year: 2023, name: 'VerHagen,D', team: 'Z-Unowned' },
    { year: 2023, name: 'Verlander,J', team: 'Gypsies' },
    { year: 2023, name: 'Vesia,A', team: 'Twins' },
    { year: 2023, name: 'Vest,W', team: 'Knights' },
    { year: 2023, name: 'Vientos,M', team: 'Blaze' },
    { year: 2023, name: 'Vierling,M', team: 'Gypsies' },
    { year: 2023, name: 'Villar,D', team: 'Z-Unowned' },
    { year: 2023, name: 'Vogelbach,D', team: 'Z-Unowned' },
    { year: 2023, name: 'Volpe,A', team: 'Hornets' },
    { year: 2023, name: 'Votto,J', team: 'Monarchs' },
    { year: 2023, name: 'Wacha,M', team: 'Z-Unowned' },
    { year: 2023, name: 'Wade Jr,L', team: 'Hornets' },
    { year: 2023, name: 'Wainwright,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Waldichuk,K', team: 'Pilots' },
    { year: 2023, name: 'Walker,C', team: 'Pelicans' },
    { year: 2023, name: 'Walker,J', team: 'TinCaps' },
    { year: 2023, name: 'Walker,R', team: 'Z-Unowned' },
    { year: 2023, name: 'Walker,T', team: 'Dodgers' },
    { year: 2023, name: 'Wallach,C', team: 'Z-Unowned' },
    { year: 2023, name: 'Wallner,M', team: 'Blaze' },
    { year: 2023, name: 'Walls,T', team: 'Hornets' },
    { year: 2023, name: 'Walsh,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Ward,T', team: 'Pelicans' },
    { year: 2023, name: 'Waters,D', team: 'Pilots' },
    { year: 2023, name: 'Weathers,R', team: 'Colt .45s' },
    { year: 2023, name: 'Weaver,L', team: 'Z-Unowned' },
    { year: 2023, name: 'Webb,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Webb,L', team: 'Reds' },
    { year: 2023, name: 'Weems,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Wells,T', team: 'Pelicans' },
    { year: 2023, name: 'Wendle,J', team: 'Pelicans' },
    { year: 2023, name: 'Wentz,J', team: 'RockHounds' },
    { year: 2023, name: 'Wesneski,H', team: 'Stars' },
    { year: 2023, name: 'Westburg,J', team: 'Bandits' },
    { year: 2023, name: 'Wheeler,Z', team: 'Pilgrims' },
    { year: 2023, name: 'White,B', team: 'Z-Unowned' },
    { year: 2023, name: 'Whitlock,G', team: 'TinCaps' },
    { year: 2023, name: 'Wiemer,J', team: 'River Dogs' },
    { year: 2023, name: 'Williams,A', team: 'River Dogs' },
    { year: 2023, name: 'Williams,D', team: 'Stars' },
    { year: 2023, name: 'Williams,G', team: 'Clown Princes' },
    { year: 2023, name: 'Williams,T', team: 'Z-Unowned' },
    { year: 2023, name: 'Williamson,B', team: 'Reds' },
    { year: 2023, name: 'Wilson,B', team: 'Stars' },
    { year: 2023, name: 'Wilson,S', team: 'Blaze' },
    { year: 2023, name: 'Winckowski,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Winker,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Winn,M', team: 'Pilgrims' },
    { year: 2023, name: 'Wisdom,P', team: 'Hornets' },
    { year: 2023, name: 'Wisely,B', team: 'Z-Unowned' },
    { year: 2023, name: 'Witt,B', team: 'Twins' },
    { year: 2023, name: 'Wong,C', team: 'Pilots' },
    { year: 2023, name: 'Wong,K', team: 'Z-Unowned' },
    { year: 2023, name: 'Woo,B', team: 'Knights' },
    { year: 2023, name: 'Wood,A', team: 'Expos' },
    { year: 2023, name: 'Woodruff,B', team: 'Pilgrims' },
    { year: 2023, name: 'Wynns,A', team: 'Pelicans' },
    { year: 2023, name: 'Yarbrough,R', team: 'Pelicans' },
    { year: 2023, name: 'Yastrzemski,M', team: 'Gypsies' },
    { year: 2023, name: 'Yates,K', team: 'Z-Unowned' },
    { year: 2023, name: 'Yelich,C', team: 'Titans' },
    { year: 2023, name: 'Yoshida,M', team: 'TinCaps' },
    { year: 2023, name: 'Young,A', team: 'Z-Unowned' },
    { year: 2023, name: 'Young,J', team: 'Z-Unowned' },
    { year: 2023, name: 'Zavala,S', team: 'Reds' },
    { year: 2023, name: 'Zunino,M', team: 'Bandits' },
];

module.exports = cardedPlayers;
