const cardedPlayers = [
    { year: 2023, fullName: 'Abbott, Andrew', rmlTeam: 'Clown Princes', ip: '109.1', ab: '' },
    { year: 2023, fullName: 'Abrams, CJ', rmlTeam: 'RockHounds', ip: '', ab: '563' },
    { year: 2023, fullName: 'Abreu, Albert', rmlTeam: 'River Dogs', ip: '59', ab: '' },
    { year: 2023, fullName: 'Abreu, Bryan', rmlTeam: 'TinCaps', ip: '72', ab: '' },
    { year: 2023, fullName: 'Abreu, Jose', rmlTeam: 'Bandits', ip: '', ab: '540' },
    { year: 2023, fullName: 'Acuna Jr, Ronald', rmlTeam: 'Grays', ip: '', ab: '643' },
    { year: 2023, fullName: 'Adam, Jason', rmlTeam: 'Gypsies', ip: '54.1', ab: '' },
    { year: 2023, fullName: 'Adames, Willy', rmlTeam: 'Knights', ip: '', ab: '553' },
    { year: 2023, fullName: 'Adams, Riley', rmlTeam: 'Pilgrims', ip: '', ab: '143' },
    { year: 2023, fullName: 'Adon, Joan', rmlTeam: 'Bandits', ip: '51.2', ab: '' },
    { year: 2023, fullName: 'Aguilar, Jesus', rmlTeam: 'Z-Unowned', ip: '', ab: '104' },
    { year: 2023, fullName: 'Ahmed, Nick', rmlTeam: 'Bandits', ip: '', ab: '198' },
    { year: 2023, fullName: 'Albies, Ozzie', rmlTeam: 'Titans', ip: '', ab: '596' },
    { year: 2023, fullName: 'Alcantara, Sandy', rmlTeam: 'Bandits', ip: '184.2', ab: '' },
    { year: 2023, fullName: 'Alexander, Scott', rmlTeam: 'Bandits', ip: '48.1', ab: '' },
    { year: 2023, fullName: 'Allen, Logan', rmlTeam: 'Expos', ip: '125.1', ab: '' },
    { year: 2023, fullName: 'Allen, Nick', rmlTeam: 'Browns', ip: '', ab: '303' },
    { year: 2023, fullName: 'Almonte, Yency', rmlTeam: 'Z-Unowned', ip: '48', ab: '' },
    { year: 2023, fullName: 'Alonso, Pete', rmlTeam: 'Blaze', ip: '', ab: '568' },
    { year: 2023, fullName: 'Altuve, Jose', rmlTeam: 'Grays', ip: '', ab: '360' },
    { year: 2023, fullName: 'Alu, Jake', rmlTeam: 'Pilots', ip: '', ab: '159' },
    { year: 2023, fullName: 'Alvarado, Jose', rmlTeam: 'Stars', ip: '41.1', ab: '' },
    { year: 2023, fullName: 'Alvarez, Francisco', rmlTeam: 'Twins', ip: '', ab: '382' },
    { year: 2023, fullName: 'Alvarez, Yordan', rmlTeam: 'Grays', ip: '', ab: '410' },
    { year: 2023, fullName: 'Alzolay, Adbert', rmlTeam: 'Blaze', ip: '64', ab: '' },
    { year: 2023, fullName: 'Amaya, Miguel', rmlTeam: 'River Dogs', ip: '', ab: '131' },
    { year: 2023, fullName: 'Anderson, Brian', rmlTeam: 'Hornets', ip: '', ab: '318' },
    { year: 2023, fullName: 'Anderson, Chase', rmlTeam: 'Monarchs', ip: '86.1', ab: '' },
    { year: 2023, fullName: 'Anderson, Nick', rmlTeam: 'Z-Unowned', ip: '35.1', ab: '' },
    { year: 2023, fullName: 'Anderson, Tim', rmlTeam: 'Captains', ip: '', ab: '493' },
    { year: 2023, fullName: 'Anderson, Tyler', rmlTeam: 'Bandits', ip: '141', ab: '' },
    { year: 2023, fullName: 'Andrus, Elvis', rmlTeam: 'River Dogs', ip: '', ab: '374' },
    { year: 2023, fullName: 'Arcia, Orlando', rmlTeam: 'Bandits', ip: '', ab: '488' },
    { year: 2023, fullName: 'Arenado, Nolan', rmlTeam: 'Dodgers', ip: '', ab: '560' },
    { year: 2023, fullName: 'Arias, Gabriel', rmlTeam: 'TinCaps', ip: '', ab: '315' },
    { year: 2023, fullName: 'Armstrong, Shawn', rmlTeam: 'RockHounds', ip: '52', ab: '' },
    { year: 2023, fullName: 'Arozarena, Randy', rmlTeam: 'Monarchs', ip: '', ab: '551' },
    { year: 2023, fullName: 'Arraez, Luis', rmlTeam: 'Captains', ip: '', ab: '574' },
    { year: 2023, fullName: 'Arroyo, Christian', rmlTeam: 'Z-Unowned', ip: '', ab: '195' },
    { year: 2023, fullName: 'Ashcraft, Graham', rmlTeam: 'Titans', ip: '145.2', ab: '' },
    { year: 2023, fullName: 'Assad, Javier', rmlTeam: 'TinCaps', ip: '109.1', ab: '' },
    { year: 2023, fullName: 'Baddoo, Akil', rmlTeam: 'River Dogs', ip: '', ab: '312' },
    { year: 2023, fullName: 'Bader, Harrison', rmlTeam: 'Titans', ip: '', ab: '319' },
    { year: 2023, fullName: 'Bae, Ji Hwan', rmlTeam: 'Stars', ip: '', ab: '334' },
    { year: 2023, fullName: 'Baez, Javier', rmlTeam: 'Pelicans', ip: '', ab: '510' },
    { year: 2023, fullName: 'Bailey, Patrick', rmlTeam: 'Bandits', ip: '', ab: '326' },
    { year: 2023, fullName: 'Baker, Bryan', rmlTeam: 'Pilgrims', ip: '45', ab: '' },
    { year: 2023, fullName: 'Banks, Tanner', rmlTeam: 'Twins', ip: '61', ab: '' },
    { year: 2023, fullName: 'Bard, Daniel', rmlTeam: 'Z-Unowned', ip: '49.1', ab: '' },
    { year: 2023, fullName: 'Barlow, Scott', rmlTeam: 'Reds', ip: '68', ab: '' },
    { year: 2023, fullName: 'Barnes, Austin', rmlTeam: 'Z-Unowned', ip: '', ab: '178' },
    { year: 2023, fullName: 'Barnhart, Tucker', rmlTeam: 'Z-Unowned', ip: '', ab: '109' },
    { year: 2023, fullName: 'Barrero, Jose', rmlTeam: 'Z-Unowned', ip: '', ab: '133' },
    { year: 2023, fullName: 'Barria, Jaime', rmlTeam: 'Z-Unowned', ip: '82.1', ab: '' },
    { year: 2023, fullName: 'Bassitt, Chris', rmlTeam: 'Browns', ip: '200', ab: '' },
    { year: 2023, fullName: 'Batten, Matthew', rmlTeam: 'Z-Unowned', ip: '', ab: '120' },
    { year: 2023, fullName: 'Baty, Brett', rmlTeam: 'RockHounds', ip: '', ab: '353' },
    { year: 2023, fullName: 'Bauers, Jake', rmlTeam: 'Z-Unowned', ip: '', ab: '242' },
    { year: 2023, fullName: 'Baumann, Mike', rmlTeam: 'Pilgrims', ip: '64.2', ab: '' },
    { year: 2023, fullName: 'Bautista, Felix', rmlTeam: 'Grays', ip: '61', ab: '' },
    { year: 2023, fullName: 'Beck, Tristan', rmlTeam: 'Browns', ip: '85', ab: '' },
    { year: 2023, fullName: 'Bednar, David', rmlTeam: 'Captains', ip: '67.1', ab: '' },
    { year: 2023, fullName: 'Beeks, Jalen', rmlTeam: 'Hornets', ip: '42.1', ab: '' },
    { year: 2023, fullName: 'Bell, Josh', rmlTeam: 'Browns', ip: '', ab: '547' },
    { year: 2023, fullName: 'Bellinger, Cody', rmlTeam: 'Pilgrims', ip: '', ab: '499' },
    { year: 2023, fullName: 'Bello, Brayan', rmlTeam: 'RockHounds', ip: '157', ab: '' },
    { year: 2023, fullName: 'Belt, Brandon', rmlTeam: 'Yellow Jackets', ip: '', ab: '339' },
    { year: 2023, fullName: 'Benintendi, Andrew', rmlTeam: 'Yellow Jackets', ip: '', ab: '562' },
    { year: 2023, fullName: 'Benson, Will', rmlTeam: 'Browns', ip: '', ab: '287' },
    { year: 2023, fullName: 'Bernardino, Brennan', rmlTeam: 'Bandits', ip: '50.2', ab: '' },
    { year: 2023, fullName: 'Berrios, Jose', rmlTeam: 'Yellow Jackets', ip: '189.2', ab: '' },
    { year: 2023, fullName: 'Berti, Jon', rmlTeam: 'Reds', ip: '', ab: '388' },
    { year: 2023, fullName: 'Bethancourt, Christian', rmlTeam: 'Reds', ip: '', ab: '315' },
    { year: 2023, fullName: 'Betts, Mookie', rmlTeam: 'Grays', ip: '', ab: '584' },
    { year: 2023, fullName: 'Bibee, Tanner', rmlTeam: 'River Dogs', ip: '142', ab: '' },
    { year: 2023, fullName: 'Bichette, Bo', rmlTeam: 'Twins', ip: '', ab: '571' },
    { year: 2023, fullName: 'Bickford, Phil', rmlTeam: 'Titans', ip: '67.1', ab: '' },
    { year: 2023, fullName: 'Bieber, Shane', rmlTeam: 'Captains', ip: '128', ab: '' },
    { year: 2023, fullName: 'Bielak, Brandon', rmlTeam: 'Titans', ip: '80', ab: '' },
    { year: 2023, fullName: 'Biggio, Cavan', rmlTeam: 'Clown Princes', ip: '', ab: '289' },
    { year: 2023, fullName: 'Bird, Jake', rmlTeam: 'Colt .45s', ip: '89.1', ab: '' },
    { year: 2023, fullName: 'Blach, Ty', rmlTeam: 'Z-Unowned', ip: '78', ab: '' },
    { year: 2023, fullName: 'Blackburn, Paul', rmlTeam: 'Titans', ip: '103.2', ab: '' },
    { year: 2023, fullName: 'Blackmon, Charlie', rmlTeam: 'Pilgrims', ip: '', ab: '359' },
    { year: 2023, fullName: 'Blanco, Dairon', rmlTeam: 'Blaze', ip: '', ab: '124' },
    { year: 2023, fullName: 'Bleday, JJ', rmlTeam: 'Dodgers', ip: '', ab: '256' },
    { year: 2023, fullName: 'Bogaerts, Xander', rmlTeam: 'Colt .45s', ip: '', ab: '596' },
    { year: 2023, fullName: 'Bohm, Alec', rmlTeam: 'Blaze', ip: '', ab: '558' },
    { year: 2023, fullName: 'Borucki, Ryan', rmlTeam: 'Blaze', ip: '40.1', ab: '' },
    { year: 2023, fullName: 'Boyd, Matthew', rmlTeam: 'Hornets', ip: '71', ab: '' },
    { year: 2023, fullName: 'Bradish, Kyle', rmlTeam: 'Hornets', ip: '168.2', ab: '' },
    { year: 2023, fullName: 'Bradley Jr, Jackie', rmlTeam: 'Clown Princes', ip: '', ab: '105' },
    { year: 2023, fullName: 'Bradley, Taj', rmlTeam: 'Grays', ip: '104.2', ab: '' },
    { year: 2023, fullName: 'Brash, Matt', rmlTeam: 'Hornets', ip: '70.2', ab: '' },
    { year: 2023, fullName: 'Brasier, Ryan', rmlTeam: 'Pelicans', ip: '59.2', ab: '' },
    { year: 2023, fullName: 'Brazoban, Huascar', rmlTeam: 'Z-Unowned', ip: '58.2', ab: '' },
    { year: 2023, fullName: 'Brebbia, John', rmlTeam: 'Yellow Jackets', ip: '38.1', ab: '' },
    { year: 2023, fullName: 'Bregman, Alex', rmlTeam: 'Colt .45s', ip: '', ab: '622' },
    { year: 2023, fullName: 'Brennan, Will', rmlTeam: 'Pilots', ip: '', ab: '432' },
    { year: 2023, fullName: 'Brigham, Jeff', rmlTeam: 'Z-Unowned', ip: '37.2', ab: '' },
    { year: 2023, fullName: 'Brito, Jhony', rmlTeam: 'Pilots', ip: '90.1', ab: '' },
    { year: 2023, fullName: 'Brown, Hunter', rmlTeam: 'River Dogs', ip: '155.2', ab: '' },
    { year: 2023, fullName: 'Brown, Seth', rmlTeam: 'Knights', ip: '', ab: '343' },
    { year: 2023, fullName: 'Bryant, Kris', rmlTeam: 'Stars', ip: '', ab: '300' },
    { year: 2023, fullName: 'Bummer, Aaron', rmlTeam: 'River Dogs', ip: '58.1', ab: '' },
    { year: 2023, fullName: 'Burger, Jake', rmlTeam: 'Yellow Jackets', ip: '', ab: '492' },
    { year: 2023, fullName: 'Burke, Brock', rmlTeam: 'TinCaps', ip: '59.2', ab: '' },
    { year: 2023, fullName: 'Burleson, Alec', rmlTeam: 'Bandits', ip: '', ab: '315' },
    { year: 2023, fullName: 'Burnes, Corbin', rmlTeam: 'Dodgers', ip: '193.2', ab: '' },
    { year: 2023, fullName: 'Butler, Lawrence', rmlTeam: 'Colt .45s', ip: '', ab: '123' },
    { year: 2023, fullName: 'Buxton, Byron', rmlTeam: 'Monarchs', ip: '', ab: '304' },
    { year: 2023, fullName: 'Caballero, Jose', rmlTeam: 'Monarchs', ip: '', ab: '231' },
    { year: 2023, fullName: 'Cabrera, Edward', rmlTeam: 'RockHounds', ip: '99.2', ab: '' },
    { year: 2023, fullName: 'Cabrera, Genesis', rmlTeam: 'Colt .45s', ip: '55.2', ab: '' },
    { year: 2023, fullName: 'Cabrera, Miguel', rmlTeam: 'Expos', ip: '', ab: '334' },
    { year: 2023, fullName: 'Cabrera, Oswaldo', rmlTeam: 'Bandits', ip: '', ab: '298' },
    { year: 2023, fullName: 'Calhoun, Kole', rmlTeam: 'Z-Unowned', ip: '', ab: '157' },
    { year: 2023, fullName: 'Calhoun, Willie', rmlTeam: 'Twins', ip: '', ab: '134' },
    { year: 2023, fullName: 'Call, Alex', rmlTeam: 'Dodgers', ip: '', ab: '375' },
    { year: 2023, fullName: 'Campusano, Luis', rmlTeam: 'RockHounds', ip: '', ab: '163' },
    { year: 2023, fullName: 'Candelario, Jeimer', rmlTeam: 'Pelicans', ip: '', ab: '505' },
    { year: 2023, fullName: 'Canha, Mark', rmlTeam: 'Captains', ip: '', ab: '435' },
    { year: 2023, fullName: 'Canning, Griffin', rmlTeam: 'Dodgers', ip: '127', ab: '' },
    { year: 2023, fullName: 'Cano, Yennier', rmlTeam: 'TinCaps', ip: '72.2', ab: '' },
    { year: 2023, fullName: 'Canzone, Dominic', rmlTeam: 'Bandits', ip: '', ab: '173' },
    { year: 2023, fullName: 'Caratini, Victor', rmlTeam: 'Captains', ip: '', ab: '201' },
    { year: 2023, fullName: 'Carlson, Dylan', rmlTeam: 'TinCaps', ip: '', ab: '219' },
    { year: 2023, fullName: 'Carpenter, Kerry', rmlTeam: 'Pilots', ip: '', ab: '418' },
    { year: 2023, fullName: 'Carpenter, Matt', rmlTeam: 'Z-Unowned', ip: '', ab: '188' },
    { year: 2023, fullName: 'Carrasco, Carlos', rmlTeam: 'Z-Unowned', ip: '90', ab: '' },
    { year: 2023, fullName: 'Carroll, Corbin', rmlTeam: 'Colt .45s', ip: '', ab: '565' },
    { year: 2023, fullName: 'Casas, Triston', rmlTeam: 'Reds', ip: '', ab: '429' },
    { year: 2023, fullName: 'Castellanos, Nick', rmlTeam: 'Gypsies', ip: '', ab: '626' },
    { year: 2023, fullName: 'Castillo, Luis', rmlTeam: 'Captains', ip: '197', ab: '' },
    { year: 2023, fullName: 'Castro, Harold', rmlTeam: 'Pilots', ip: '', ab: '258' },
    { year: 2023, fullName: 'Castro, Miguel', rmlTeam: 'Pilgrims', ip: '64.2', ab: '' },
    { year: 2023, fullName: 'Castro, Rodolfo', rmlTeam: 'Z-Unowned', ip: '', ab: '227' },
    { year: 2023, fullName: 'Castro, Willi', rmlTeam: 'TinCaps', ip: '', ab: '358' },
    { year: 2023, fullName: 'Cave, Jake', rmlTeam: 'Z-Unowned', ip: '', ab: '184' },
    { year: 2023, fullName: 'Cease, Dylan', rmlTeam: 'Browns', ip: '177', ab: '' },
    { year: 2023, fullName: 'Chafin, Andrew', rmlTeam: 'Pelicans', ip: '51.1', ab: '' },
    { year: 2023, fullName: 'Chang, Yu', rmlTeam: 'Z-Unowned', ip: '', ab: '105' },
    { year: 2023, fullName: 'Chapman, Aroldis', rmlTeam: 'Grays', ip: '58.1', ab: '' },
    { year: 2023, fullName: 'Chapman, Matt', rmlTeam: 'Blaze', ip: '', ab: '509' },
    { year: 2023, fullName: 'Chargois, JT', rmlTeam: 'Expos', ip: '42.1', ab: '' },
    { year: 2023, fullName: 'Chavez, Jesse', rmlTeam: 'Z-Unowned', ip: '34.2', ab: '' },
    { year: 2023, fullName: 'Chirinos, Yonny', rmlTeam: 'Dodgers', ip: '85', ab: '' },
    { year: 2023, fullName: 'Chisholm Jr, Jazz', rmlTeam: 'Pelicans', ip: '', ab: '352' },
    { year: 2023, fullName: 'Choi, Ji Man', rmlTeam: 'Z-Unowned', ip: '', ab: '104' },
    { year: 2023, fullName: 'Cisnero, Jose', rmlTeam: 'Z-Unowned', ip: '59.1', ab: '' },
    { year: 2023, fullName: 'Civale, Aaron', rmlTeam: 'Browns', ip: '122.1', ab: '' },
    { year: 2023, fullName: 'Clarke, Taylor', rmlTeam: 'Z-Unowned', ip: '59', ab: '' },
    { year: 2023, fullName: 'Clase, Emmanuel', rmlTeam: 'Captains', ip: '72.2', ab: '' },
    { year: 2023, fullName: 'Clemens, Kody', rmlTeam: 'Z-Unowned', ip: '', ab: '139' },
    { year: 2023, fullName: 'Clevinger, Mike', rmlTeam: 'Gypsies', ip: '131.1', ab: '' },
    { year: 2023, fullName: 'Cobb, Alex', rmlTeam: 'Monarchs', ip: '151.1', ab: '' },
    { year: 2023, fullName: 'Colas, Oscar', rmlTeam: 'Clown Princes', ip: '', ab: '245' },
    { year: 2023, fullName: 'Cole, Gerrit', rmlTeam: 'Gypsies', ip: '209', ab: '' },
    { year: 2023, fullName: 'Conforto, Michael', rmlTeam: 'Pilgrims', ip: '', ab: '406' },
    { year: 2023, fullName: 'Contreras, Roansy', rmlTeam: 'Reds', ip: '68.1', ab: '' },
    { year: 2023, fullName: 'Contreras, William', rmlTeam: 'Browns', ip: '', ab: '540' },
    { year: 2023, fullName: 'Contreras, Willson', rmlTeam: 'Colt .45s', ip: '', ab: '428' },
    { year: 2023, fullName: 'Cooper, Garrett', rmlTeam: 'Twins', ip: '', ab: '422' },
    { year: 2023, fullName: 'Corbin, Patrick', rmlTeam: 'Z-Unowned', ip: '180', ab: '' },
    { year: 2023, fullName: 'Cordero, Jimmy', rmlTeam: 'Z-Unowned', ip: '32.2', ab: '' },
    { year: 2023, fullName: 'Correa, Carlos', rmlTeam: 'Clown Princes', ip: '', ab: '514' },
    { year: 2023, fullName: 'Cortes, Nestor', rmlTeam: 'Clown Princes', ip: '63.1', ab: '' },
    { year: 2023, fullName: 'Cosgrove, Tom', rmlTeam: 'Expos', ip: '51.1', ab: '' },
    { year: 2023, fullName: 'Coulombe, Danny', rmlTeam: 'Gypsies', ip: '51.1', ab: '' },
    { year: 2023, fullName: 'Crawford, Brandon', rmlTeam: 'Z-Unowned', ip: '', ab: '283' },
    { year: 2023, fullName: 'Crawford, JP', rmlTeam: 'Titans', ip: '', ab: '534' },
    { year: 2023, fullName: 'Crawford, Kutter', rmlTeam: 'Browns', ip: '129.1', ab: '' },
    { year: 2023, fullName: 'Cron, CJ', rmlTeam: 'Expos', ip: '', ab: '258' },
    { year: 2023, fullName: 'Cronenworth, Jake', rmlTeam: 'Hornets', ip: '', ab: '458' },
    { year: 2023, fullName: 'Cruz, Fernando', rmlTeam: 'Expos', ip: '66', ab: '' },
    { year: 2023, fullName: 'Cruz, Nelson', rmlTeam: 'Z-Unowned', ip: '', ab: '143' },
    { year: 2023, fullName: 'Cuas, Jose', rmlTeam: 'Z-Unowned', ip: '65.1', ab: '' },
    { year: 2023, fullName: 'Cueto, Johnny', rmlTeam: 'Z-Unowned', ip: '52.1', ab: '' },
    { year: 2023, fullName: 'Curry, Xzavion', rmlTeam: 'Pilots', ip: '95', ab: '' },
    { year: 2023, fullName: 'd\'Arnaud, Travis', rmlTeam: 'Titans', ip: '', ab: '267' },
    { year: 2023, fullName: 'Darvish, Yu', rmlTeam: 'Grays', ip: '136.1', ab: '' },
    { year: 2023, fullName: 'Davidson, Tucker', rmlTeam: 'Z-Unowned', ip: '51.1', ab: '' },
    { year: 2023, fullName: 'Davies, Zach', rmlTeam: 'Browns', ip: '82.1', ab: '' },
    { year: 2023, fullName: 'Davis, Henry', rmlTeam: 'Clown Princes', ip: '', ab: '225' },
    { year: 2023, fullName: 'Davis, JD', rmlTeam: 'Colt .45s', ip: '', ab: '480' },
    { year: 2023, fullName: 'De La Cruz, Bryan', rmlTeam: 'Pilgrims', ip: '', ab: '579' },
    { year: 2023, fullName: 'De La Cruz, Elly', rmlTeam: 'RockHounds', ip: '', ab: '388' },
    { year: 2023, fullName: 'De Los Santos, Enyel', rmlTeam: 'Stars', ip: '65.2', ab: '' },
    { year: 2023, fullName: 'DeJong, Paul', rmlTeam: 'Expos', ip: '', ab: '372' },
    { year: 2023, fullName: 'Delay, Jason', rmlTeam: 'Z-Unowned', ip: '', ab: '167' },
    { year: 2023, fullName: 'DeSclafani, Anthony', rmlTeam: 'Bandits', ip: '99.2', ab: '' },
    { year: 2023, fullName: 'Detmers, Reid', rmlTeam: 'Knights', ip: '148.2', ab: '' },
    { year: 2023, fullName: 'Devenski, Chris', rmlTeam: 'Z-Unowned', ip: '42.1', ab: '' },
    { year: 2023, fullName: 'Devers, Rafael', rmlTeam: 'Knights', ip: '', ab: '580' },
    { year: 2023, fullName: 'Diaz, Aledmys', rmlTeam: 'Z-Unowned', ip: '', ab: '315' },
    { year: 2023, fullName: 'Diaz, Alexis', rmlTeam: 'Bandits', ip: '67.1', ab: '' },
    { year: 2023, fullName: 'Diaz, Elias', rmlTeam: 'TinCaps', ip: '', ab: '486' },
    { year: 2023, fullName: 'Diaz, Jordan', rmlTeam: 'Colt .45s', ip: '', ab: '272' },
    { year: 2023, fullName: 'Diaz, Yainer', rmlTeam: 'Twins', ip: '', ab: '355' },
    { year: 2023, fullName: 'Diaz, Yandy', rmlTeam: 'River Dogs', ip: '', ab: '525' },
    { year: 2023, fullName: 'Dickerson, Corey', rmlTeam: 'Z-Unowned', ip: '', ab: '144' },
    { year: 2023, fullName: 'Diekman, Jake', rmlTeam: 'Twins', ip: '56.2', ab: '' },
    { year: 2023, fullName: 'Dominguez, Seranthony', rmlTeam: 'River Dogs', ip: '50', ab: '' },
    { year: 2023, fullName: 'Donaldson, Josh', rmlTeam: 'Z-Unowned', ip: '', ab: '165' },
    { year: 2023, fullName: 'Donovan, Brendan', rmlTeam: 'Pilots', ip: '', ab: '327' },
    { year: 2023, fullName: 'Doval, Camilo', rmlTeam: 'River Dogs', ip: '67.2', ab: '' },
    { year: 2023, fullName: 'Doyle, Brenton', rmlTeam: 'River Dogs', ip: '', ab: '399' },
    { year: 2023, fullName: 'Drury, Brandon', rmlTeam: 'Stars', ip: '', ab: '485' },
    { year: 2023, fullName: 'Duarte, Daniel', rmlTeam: 'Z-Unowned', ip: '31.2', ab: '' },
    { year: 2023, fullName: 'Dubon, Mauricio', rmlTeam: 'Twins', ip: '', ab: '467' },
    { year: 2023, fullName: 'Duffy, Matt', rmlTeam: 'Z-Unowned', ip: '', ab: '191' },
    { year: 2023, fullName: 'Dunning, Dane', rmlTeam: 'Captains', ip: '172.2', ab: '' },
    { year: 2023, fullName: 'Duran, Ezequiel', rmlTeam: 'Monarchs', ip: '', ab: '406' },
    { year: 2023, fullName: 'Duran, Jarren', rmlTeam: 'Grays', ip: '', ab: '332' },
    { year: 2023, fullName: 'Duran, Jhoan', rmlTeam: 'River Dogs', ip: '62.1', ab: '' },
    { year: 2023, fullName: 'Duvall, Adam', rmlTeam: 'Gypsies', ip: '', ab: '320' },
    { year: 2023, fullName: 'Edman, Tommy', rmlTeam: 'Yellow Jackets', ip: '', ab: '479' },
    { year: 2023, fullName: 'Edwards Jr, Carl', rmlTeam: 'Reds', ip: '31.2', ab: '' },
    { year: 2023, fullName: 'Eflin, Zach', rmlTeam: 'Expos', ip: '177.2', ab: '' },
    { year: 2023, fullName: 'Elder, Bryce', rmlTeam: 'Twins', ip: '174.2', ab: '' },
    { year: 2023, fullName: 'Encarnacion-Strand, Christian', rmlTeam: 'Stars', ip: '', ab: '222' },
    { year: 2023, fullName: 'Englert, Mason', rmlTeam: 'Z-Unowned', ip: '56', ab: '' },
    { year: 2023, fullName: 'Eovaldi, Nathan', rmlTeam: 'Colt .45s', ip: '144', ab: '' },
    { year: 2023, fullName: 'Erceg, Lucas', rmlTeam: 'Z-Unowned', ip: '55', ab: '' },
    { year: 2023, fullName: 'Escobar, Eduardo', rmlTeam: 'River Dogs', ip: '', ab: '288' },
    { year: 2023, fullName: 'Espinal, Santiago', rmlTeam: 'Gypsies', ip: '', ab: '230' },
    { year: 2023, fullName: 'Estevez, Carlos', rmlTeam: 'Knights', ip: '62.1', ab: '' },
    { year: 2023, fullName: 'Estrada, Thairo', rmlTeam: 'Pilgrims', ip: '', ab: '495' },
    { year: 2023, fullName: 'Faedo, Alex', rmlTeam: 'Pelicans', ip: '64.2', ab: '' },
    { year: 2023, fullName: 'Fairbanks, Pete', rmlTeam: 'Knights', ip: '45.1', ab: '' },
    { year: 2023, fullName: 'Fairchild, Stuart', rmlTeam: 'Bandits', ip: '', ab: '219' },
    { year: 2023, fullName: 'Falter, Bailey', rmlTeam: 'Knights', ip: '80.2', ab: '' },
    { year: 2023, fullName: 'Farmer, Buck', rmlTeam: 'Yellow Jackets', ip: '75', ab: '' },
    { year: 2023, fullName: 'Farmer, Kyle', rmlTeam: 'Colt .45s', ip: '', ab: '336' },
    { year: 2023, fullName: 'Feltner, Ryan', rmlTeam: 'Z-Unowned', ip: '43.1', ab: '' },
    { year: 2023, fullName: 'Ferguson, Caleb', rmlTeam: 'Stars', ip: '60.1', ab: '' },
    { year: 2023, fullName: 'Fermin, Freddy', rmlTeam: 'Reds', ip: '', ab: '217' },
    { year: 2023, fullName: 'Ferrer, Jose', rmlTeam: 'Z-Unowned', ip: '34', ab: '' },
    { year: 2023, fullName: 'Finnegan, Kyle', rmlTeam: 'Clown Princes', ip: '69.1', ab: '' },
    { year: 2023, fullName: 'Flaherty, Jack', rmlTeam: 'Pilgrims', ip: '144.1', ab: '' },
    { year: 2023, fullName: 'Flexen, Chris', rmlTeam: 'Z-Unowned', ip: '102.1', ab: '' },
    { year: 2023, fullName: 'Flores, Wilmer', rmlTeam: 'Colt .45s', ip: '', ab: '405' },
    { year: 2023, fullName: 'Floro, Dylan', rmlTeam: 'Z-Unowned', ip: '56.2', ab: '' },
    { year: 2023, fullName: 'Foley, Jason', rmlTeam: 'Gypsies', ip: '69', ab: '' },
    { year: 2023, fullName: 'Ford, Mike', rmlTeam: 'Z-Unowned', ip: '', ab: '219' },
    { year: 2023, fullName: 'Fortes, Nick', rmlTeam: 'Hornets', ip: '', ab: '294' },
    { year: 2023, fullName: 'Fraley, Jake', rmlTeam: 'Pilots', ip: '', ab: '336' },
    { year: 2023, fullName: 'France, JP', rmlTeam: 'Expos', ip: '136.1', ab: '' },
    { year: 2023, fullName: 'France, Ty', rmlTeam: 'Titans', ip: '', ab: '587' },
    { year: 2023, fullName: 'Franco, Wander', rmlTeam: 'Pilgrims', ip: '', ab: '442' },
    { year: 2023, fullName: 'Frazier, Adam', rmlTeam: 'Z-Unowned', ip: '', ab: '412' },
    { year: 2023, fullName: 'Freeland, Kyle', rmlTeam: 'Z-Unowned', ip: '155.2', ab: '' },
    { year: 2023, fullName: 'Freeman, Freddie', rmlTeam: 'Dodgers', ip: '', ab: '637' },
    { year: 2023, fullName: 'Freeman, Tyler', rmlTeam: 'Titans', ip: '', ab: '153' },
    { year: 2023, fullName: 'Frelick, Sal', rmlTeam: 'Twins', ip: '', ab: '191' },
    { year: 2023, fullName: 'Fried, Max', rmlTeam: 'Dodgers', ip: '77.2', ab: '' },
    { year: 2023, fullName: 'Friedl, TJ', rmlTeam: 'Gypsies', ip: '', ab: '488' },
    { year: 2023, fullName: 'Fry, David', rmlTeam: 'Z-Unowned', ip: '', ab: '101' },
    { year: 2023, fullName: 'Fujinami, Shintaro', rmlTeam: 'Titans', ip: '79', ab: '' },
    { year: 2023, fullName: 'Fulmer, Michael', rmlTeam: 'Twins', ip: '57', ab: '' },
    { year: 2023, fullName: 'Gallagher, Cam', rmlTeam: 'Z-Unowned', ip: '', ab: '143' },
    { year: 2023, fullName: 'Gallegos, Giovanny', rmlTeam: 'Expos', ip: '55', ab: '' },
    { year: 2023, fullName: 'Gallen, Zac', rmlTeam: 'Yellow Jackets', ip: '210', ab: '' },
    { year: 2023, fullName: 'Gallo, Joey', rmlTeam: 'Browns', ip: '', ab: '282' },
    { year: 2023, fullName: 'Garcia, Adolis', rmlTeam: 'Expos', ip: '', ab: '555' },
    { year: 2023, fullName: 'Garcia, Avisail', rmlTeam: 'Z-Unowned', ip: '', ab: '108' },
    { year: 2023, fullName: 'Garcia, Luis', rmlTeam: 'Knights', ip: '', ab: '447' },
    { year: 2023, fullName: 'Garcia, Luis', rmlTeam: 'Z-Unowned', ip: '59.2', ab: '' },
    { year: 2023, fullName: 'Garcia, Maikel', rmlTeam: 'Pilots', ip: '', ab: '464' },
    { year: 2023, fullName: 'Garcia, Yimi', rmlTeam: 'Z-Unowned', ip: '66', ab: '' },
    { year: 2023, fullName: 'Garrett, Braxton', rmlTeam: 'Blaze', ip: '159.2', ab: '' },
    { year: 2023, fullName: 'Garrett, Stone', rmlTeam: 'Gypsies', ip: '', ab: '234' },
    { year: 2023, fullName: 'Garver, Mitch', rmlTeam: 'Grays', ip: '', ab: '296' },
    { year: 2023, fullName: 'Gausman, Kevin', rmlTeam: 'Titans', ip: '185', ab: '' },
    { year: 2023, fullName: 'Gelof, Zack', rmlTeam: 'Reds', ip: '', ab: '270' },
    { year: 2023, fullName: 'German, Domingo', rmlTeam: 'Knights', ip: '108.2', ab: '' },
    { year: 2023, fullName: 'Gibaut, Ian', rmlTeam: 'Colt .45s', ip: '75.2', ab: '' },
    { year: 2023, fullName: 'Gibson, Kyle', rmlTeam: 'Pelicans', ip: '192', ab: '' },
    { year: 2023, fullName: 'Gilbert, Logan', rmlTeam: 'RockHounds', ip: '190.2', ab: '' },
    { year: 2023, fullName: 'Gimenez, Andres', rmlTeam: 'Blaze', ip: '', ab: '557' },
    { year: 2023, fullName: 'Ginkel, Kevin', rmlTeam: 'RockHounds', ip: '65.1', ab: '' },
    { year: 2023, fullName: 'Giolito, Lucas', rmlTeam: 'River Dogs', ip: '184.1', ab: '' },
    { year: 2023, fullName: 'Glasnow, Tyler', rmlTeam: 'Grays', ip: '120', ab: '' },
    { year: 2023, fullName: 'Goldschmidt, Paul', rmlTeam: 'Colt .45s', ip: '', ab: '593' },
    { year: 2023, fullName: 'Gomber, Austin', rmlTeam: 'Stars', ip: '139', ab: '' },
    { year: 2023, fullName: 'Gomes, Yan', rmlTeam: 'Titans', ip: '', ab: '382' },
    { year: 2023, fullName: 'Gonsolin, Tony', rmlTeam: 'Titans', ip: '103', ab: '' },
    { year: 2023, fullName: 'Gonzales, Marco', rmlTeam: 'Z-Unowned', ip: '50', ab: '' },
    { year: 2023, fullName: 'Gonzales, Nick', rmlTeam: 'Pelicans', ip: '', ab: '115' },
    { year: 2023, fullName: 'Gonzalez, Oscar', rmlTeam: 'River Dogs', ip: '', ab: '173' },
    { year: 2023, fullName: 'Gonzalez, Victor', rmlTeam: 'Z-Unowned', ip: '33.2', ab: '' },
    { year: 2023, fullName: 'Gore, Mackenzie', rmlTeam: 'Hornets', ip: '136.1', ab: '' },
    { year: 2023, fullName: 'Gorman, Nolan', rmlTeam: 'RockHounds', ip: '', ab: '406' },
    { year: 2023, fullName: 'Gott, Trevor', rmlTeam: 'Z-Unowned', ip: '58', ab: '' },
    { year: 2023, fullName: 'Grandal, Yasmani', rmlTeam: 'Monarchs', ip: '', ab: '363' },
    { year: 2023, fullName: 'Graterol, Brusdar', rmlTeam: 'River Dogs', ip: '67.1', ab: '' },
    { year: 2023, fullName: 'Graveman, Kendall', rmlTeam: 'Hornets', ip: '66.1', ab: '' },
    { year: 2023, fullName: 'Gray, Jon', rmlTeam: 'Reds', ip: '157.1', ab: '' },
    { year: 2023, fullName: 'Gray, Josiah', rmlTeam: 'RockHounds', ip: '159', ab: '' },
    { year: 2023, fullName: 'Gray, Sonny', rmlTeam: 'Grays', ip: '184', ab: '' },
    { year: 2023, fullName: 'Greene, Hunter', rmlTeam: 'Clown Princes', ip: '112', ab: '' },
    { year: 2023, fullName: 'Greene, Riley', rmlTeam: 'Twins', ip: '', ab: '378' },
    { year: 2023, fullName: 'Greinke, Zack', rmlTeam: 'Expos', ip: '142.1', ab: '' },
    { year: 2023, fullName: 'Grichuk, Randal', rmlTeam: 'Clown Princes', ip: '', ab: '434' },
    { year: 2023, fullName: 'Grisham, Trent', rmlTeam: 'TinCaps', ip: '', ab: '469' },
    { year: 2023, fullName: 'Grossman, Robbie', rmlTeam: 'Clown Princes', ip: '', ab: '353' },
    { year: 2023, fullName: 'Grove, Michael', rmlTeam: 'Expos', ip: '69', ab: '' },
    { year: 2023, fullName: 'Guerrero Jr, Vladimir', rmlTeam: 'Pilgrims', ip: '', ab: '602' },
    { year: 2023, fullName: 'Guillorme, Luis', rmlTeam: 'Z-Unowned', ip: '', ab: '107' },
    { year: 2023, fullName: 'Gurriel Jr, Lourdes', rmlTeam: 'RockHounds', ip: '', ab: '551' },
    { year: 2023, fullName: 'Gurriel, Yuli', rmlTeam: 'Expos', ip: '', ab: '298' },
    { year: 2023, fullName: 'Haase, Eric', rmlTeam: 'River Dogs', ip: '', ab: '274' },
    { year: 2023, fullName: 'Hader, Josh', rmlTeam: 'Colt .45s', ip: '56.1', ab: '' },
    { year: 2023, fullName: 'Hamilton, Ian', rmlTeam: 'Blaze', ip: '58', ab: '' },
    { year: 2023, fullName: 'Hampson, Garrett', rmlTeam: 'Reds', ip: '', ab: '221' },
    { year: 2023, fullName: 'Hand, Brad', rmlTeam: 'Z-Unowned', ip: '53.2', ab: '' },
    { year: 2023, fullName: 'Haniger, Mitch', rmlTeam: 'Expos', ip: '', ab: '211' },
    { year: 2023, fullName: 'Happ, Ian', rmlTeam: 'Reds', ip: '', ab: '580' },
    { year: 2023, fullName: 'Harper, Bryce', rmlTeam: 'Grays', ip: '', ab: '457' },
    { year: 2023, fullName: 'Harris II, Michael', rmlTeam: 'Pelicans', ip: '', ab: '505' },
    { year: 2023, fullName: 'Harris, Hogan', rmlTeam: 'Monarchs', ip: '63', ab: '' },
    { year: 2023, fullName: 'Harrison, Josh', rmlTeam: 'Z-Unowned', ip: '', ab: '103' },
    { year: 2023, fullName: 'Harvey, Hunter', rmlTeam: 'RockHounds', ip: '60.2', ab: '' },
    { year: 2023, fullName: 'Hayes, Ke\'Bryan', rmlTeam: 'Monarchs', ip: '', ab: '494' },
    { year: 2023, fullName: 'Hays, Austin', rmlTeam: 'Stars', ip: '', ab: '520' },
    { year: 2023, fullName: 'Heaney, Andrew', rmlTeam: 'Browns', ip: '147.1', ab: '' },
    { year: 2023, fullName: 'Hedges, Austin', rmlTeam: 'Z-Unowned', ip: '', ab: '185' },
    { year: 2023, fullName: 'Heim, Jonah', rmlTeam: 'Blaze', ip: '', ab: '457' },
    { year: 2023, fullName: 'Helsley, Ryan', rmlTeam: 'Knights', ip: '36.2', ab: '' },
    { year: 2023, fullName: 'Henderson, Gunnar', rmlTeam: 'Monarchs', ip: '', ab: '560' },
    { year: 2023, fullName: 'Hendricks, Kyle', rmlTeam: 'Reds', ip: '137', ab: '' },
    { year: 2023, fullName: 'Henry, Tommy', rmlTeam: 'Yellow Jackets', ip: '89', ab: '' },
    { year: 2023, fullName: 'Hentges, Sam', rmlTeam: 'River Dogs', ip: '52.1', ab: '' },
    { year: 2023, fullName: 'Hernandez, Carlos', rmlTeam: 'Z-Unowned', ip: '70', ab: '' },
    { year: 2023, fullName: 'Hernandez, Enrique', rmlTeam: 'Captains', ip: '', ab: '465' },
    { year: 2023, fullName: 'Hernandez, Jonathan', rmlTeam: 'Z-Unowned', ip: '31.2', ab: '' },
    { year: 2023, fullName: 'Hernandez, Jose', rmlTeam: 'Z-Unowned', ip: '50.2', ab: '' },
    { year: 2023, fullName: 'Hernandez, Teoscar', rmlTeam: 'Browns', ip: '', ab: '625' },
    { year: 2023, fullName: 'Herrera, Jose', rmlTeam: 'Z-Unowned', ip: '', ab: '101' },
    { year: 2023, fullName: 'Heyward, Jason', rmlTeam: 'River Dogs', ip: '', ab: '334' },
    { year: 2023, fullName: 'Hicks, Aaron', rmlTeam: 'Blaze', ip: '', ab: '269' },
    { year: 2023, fullName: 'Hicks, Jordan', rmlTeam: 'Grays', ip: '65.2', ab: '' },
    { year: 2023, fullName: 'Higashioka, Kyle', rmlTeam: 'Clown Princes', ip: '', ab: '242' },
    { year: 2023, fullName: 'Hill, Rich', rmlTeam: 'Z-Unowned', ip: '146.1', ab: '' },
    { year: 2023, fullName: 'Hill, Tim', rmlTeam: 'Captains', ip: '44.1', ab: '' },
    { year: 2023, fullName: 'Hoeing, Bryan', rmlTeam: 'Z-Unowned', ip: '70.2', ab: '' },
    { year: 2023, fullName: 'Hoerner, Nico', rmlTeam: 'Browns', ip: '', ab: '619' },
    { year: 2023, fullName: 'Hoffman, Jeff', rmlTeam: 'Browns', ip: '52.1', ab: '' },
    { year: 2023, fullName: 'Holderman, Colin', rmlTeam: 'Bandits', ip: '56', ab: '' },
    { year: 2023, fullName: 'Holmes, Clay', rmlTeam: 'TinCaps', ip: '63', ab: '' },
    { year: 2023, fullName: 'Holton, Tyler', rmlTeam: 'Browns', ip: '85.1', ab: '' },
    { year: 2023, fullName: 'Honeywell Jr, Brent', rmlTeam: 'Yellow Jackets', ip: '52.1', ab: '' },
    { year: 2023, fullName: 'Houck, Tanner', rmlTeam: 'Blaze', ip: '106', ab: '' },
    { year: 2023, fullName: 'Houser, Adrian', rmlTeam: 'Knights', ip: '111.1', ab: '' },
    { year: 2023, fullName: 'Hudson, Dakota', rmlTeam: 'Captains', ip: '81.1', ab: '' },
    { year: 2023, fullName: 'Ibanez, Andy', rmlTeam: 'Pelicans', ip: '', ab: '356' },
    { year: 2023, fullName: 'Iglesias, Raisel', rmlTeam: 'Z-Unowned', ip: '55.2', ab: '' },
    { year: 2023, fullName: 'India, Jonathan', rmlTeam: 'Pilgrims', ip: '', ab: '454' },
    { year: 2023, fullName: 'Irvin, Cole', rmlTeam: 'Hornets', ip: '77.1', ab: '' },
    { year: 2023, fullName: 'Irvin, Jake', rmlTeam: 'Monarchs', ip: '121', ab: '' },
    { year: 2023, fullName: 'Isbel, Kyle', rmlTeam: 'Browns', ip: '', ab: '292' },
    { year: 2023, fullName: 'Jackson, Andre', rmlTeam: 'Z-Unowned', ip: '61.1', ab: '' },
    { year: 2023, fullName: 'Jackson, Luke', rmlTeam: 'Z-Unowned', ip: '33.1', ab: '' },
    { year: 2023, fullName: 'Jankowski, Travis', rmlTeam: 'Gypsies', ip: '', ab: '247' },
    { year: 2023, fullName: 'Jansen, Danny', rmlTeam: 'Pilgrims', ip: '', ab: '268' },
    { year: 2023, fullName: 'Jansen, Kenley', rmlTeam: 'Colt .45s', ip: '44.2', ab: '' },
    { year: 2023, fullName: 'Javier, Cristian', rmlTeam: 'River Dogs', ip: '162', ab: '' },
    { year: 2023, fullName: 'Jax, Griffin', rmlTeam: 'Reds', ip: '65.1', ab: '' },
    { year: 2023, fullName: 'Jeffers, Ryan', rmlTeam: 'Colt .45s', ip: '', ab: '286' },
    { year: 2023, fullName: 'Jimenez, Eloy', rmlTeam: 'Monarchs', ip: '', ab: '456' },
    { year: 2023, fullName: 'Jimenez, Joe', rmlTeam: 'Pelicans', ip: '56.1', ab: '' },
    { year: 2023, fullName: 'Joe, Connor', rmlTeam: 'Gypsies', ip: '', ab: '413' },
    { year: 2023, fullName: 'Johnson, Pierce', rmlTeam: 'Z-Unowned', ip: '62.2', ab: '' },
    { year: 2023, fullName: 'Jones, Nolan', rmlTeam: 'Dodgers', ip: '', ab: '367' },
    { year: 2023, fullName: 'Judge, Aaron', rmlTeam: 'Colt .45s', ip: '', ab: '367' },
    { year: 2023, fullName: 'Julien, Edouard', rmlTeam: 'Yellow Jackets', ip: '', ab: '338' },
    { year: 2023, fullName: 'Julks, Corey', rmlTeam: 'Clown Princes', ip: '', ab: '298' },
    { year: 2023, fullName: 'Jung, Josh', rmlTeam: 'Browns', ip: '', ab: '478' },
    { year: 2023, fullName: 'Junis, Jakob', rmlTeam: 'Clown Princes', ip: '86', ab: '' },
    { year: 2023, fullName: 'Kahnle, Tommy', rmlTeam: 'Grays', ip: '40.2', ab: '' },
    { year: 2023, fullName: 'Kaprielian, James', rmlTeam: 'Browns', ip: '61', ab: '' },
    { year: 2023, fullName: 'Karinchak, James', rmlTeam: 'Z-Unowned', ip: '39', ab: '' },
    { year: 2023, fullName: 'Kelenic, Jarred', rmlTeam: 'Twins', ip: '', ab: '372' },
    { year: 2023, fullName: 'Keller, Mitch', rmlTeam: 'RockHounds', ip: '194.1', ab: '' },
    { year: 2023, fullName: 'Kelly, Carson', rmlTeam: 'Browns', ip: '', ab: '136' },
    { year: 2023, fullName: 'Kelly, Joe', rmlTeam: 'Z-Unowned', ip: '39.1', ab: '' },
    { year: 2023, fullName: 'Kelly, Kevin', rmlTeam: 'Twins', ip: '67', ab: '' },
    { year: 2023, fullName: 'Kelly, Merrill', rmlTeam: 'Titans', ip: '177.2', ab: '' },
    { year: 2023, fullName: 'Kemp, Tony', rmlTeam: 'Clown Princes', ip: '', ab: '359' },
    { year: 2023, fullName: 'Kepler, Max', rmlTeam: 'Yellow Jackets', ip: '', ab: '438' },
    { year: 2023, fullName: 'Kershaw, Clayton', rmlTeam: 'Gypsies', ip: '131.2', ab: '' },
    { year: 2023, fullName: 'Kiermaier, Kevin', rmlTeam: 'Blaze', ip: '', ab: '370' },
    { year: 2023, fullName: 'Kikuchi, Yusei', rmlTeam: 'Pelicans', ip: '167.2', ab: '' },
    { year: 2023, fullName: 'Kim, Ha-Seong', rmlTeam: 'Grays', ip: '', ab: '538' },
    { year: 2023, fullName: 'Kimbrel, Craig', rmlTeam: 'Titans', ip: '69', ab: '' },
    { year: 2023, fullName: 'Kiner-Falefa, Isiah', rmlTeam: 'Expos', ip: '', ab: '326' },
    { year: 2023, fullName: 'King, John', rmlTeam: 'Z-Unowned', ip: '37.1', ab: '' },
    { year: 2023, fullName: 'King, Michael', rmlTeam: 'Grays', ip: '104.2', ab: '' },
    { year: 2023, fullName: 'Kirby, George', rmlTeam: 'Colt .45s', ip: '190.2', ab: '' },
    { year: 2023, fullName: 'Kirilloff, Alex', rmlTeam: 'Titans', ip: '', ab: '281' },
    { year: 2023, fullName: 'Kirk, Alejandro', rmlTeam: 'Hornets', ip: '', ab: '372' },
    { year: 2023, fullName: 'Knizner, Andrew', rmlTeam: 'Expos', ip: '', ab: '224' },
    { year: 2023, fullName: 'Koch, Matt', rmlTeam: 'Z-Unowned', ip: '38.2', ab: '' },
    { year: 2023, fullName: 'Kopech, Michael', rmlTeam: 'RockHounds', ip: '129.1', ab: '' },
    { year: 2023, fullName: 'Kremer, Dean', rmlTeam: 'Pilots', ip: '172.2', ab: '' },
    { year: 2023, fullName: 'Kwan, Steven', rmlTeam: 'River Dogs', ip: '', ab: '638' },
    { year: 2023, fullName: 'Lambert, Jimmy', rmlTeam: 'Z-Unowned', ip: '37.2', ab: '' },
    { year: 2023, fullName: 'Lambert, Peter', rmlTeam: 'Z-Unowned', ip: '87.1', ab: '' },
    { year: 2023, fullName: 'Lange, Alex', rmlTeam: 'Pilots', ip: '66', ab: '' },
    { year: 2023, fullName: 'Langeliers, Shea', rmlTeam: 'Knights', ip: '', ab: '448' },
    { year: 2023, fullName: 'Larnach, Trevor', rmlTeam: 'Dodgers', ip: '', ab: '183' },
    { year: 2023, fullName: 'Laureano, Ramon', rmlTeam: 'Captains', ip: '', ab: '361' },
    { year: 2023, fullName: 'Law, Derek', rmlTeam: 'Z-Unowned', ip: '55', ab: '' },
    { year: 2023, fullName: 'Lawrence, Justin', rmlTeam: 'Z-Unowned', ip: '75', ab: '' },
    { year: 2023, fullName: 'LeClerc, Jose', rmlTeam: 'Titans', ip: '57', ab: '' },
    { year: 2023, fullName: 'Leiter Jr, Mark', rmlTeam: 'RockHounds', ip: '64.1', ab: '' },
    { year: 2023, fullName: 'Lemahieu, DJ', rmlTeam: 'River Dogs', ip: '', ab: '497' },
    { year: 2023, fullName: 'Leone, Dominic', rmlTeam: 'Z-Unowned', ip: '54', ab: '' },
    { year: 2023, fullName: 'Lewis, Royce', rmlTeam: 'RockHounds', ip: '', ab: '217' },
    { year: 2023, fullName: 'Liberatore, Matthew', rmlTeam: 'RockHounds', ip: '61.2', ab: '' },
    { year: 2023, fullName: 'Lindor, Francisco', rmlTeam: 'Dodgers', ip: '', ab: '602' },
    { year: 2023, fullName: 'Littell, Zack', rmlTeam: 'Bandits', ip: '90', ab: '' },
    { year: 2023, fullName: 'Lively, Ben', rmlTeam: 'Twins', ip: '88.2', ab: '' },
    { year: 2023, fullName: 'Llovera, Mauricio', rmlTeam: 'Z-Unowned', ip: '35', ab: '' },
    { year: 2023, fullName: 'Long, Sam', rmlTeam: 'Z-Unowned', ip: '45', ab: '' },
    { year: 2023, fullName: 'Longoria, Evan', rmlTeam: 'Z-Unowned', ip: '', ab: '211' },
    { year: 2023, fullName: 'Lopez, Jorge', rmlTeam: 'Z-Unowned', ip: '59', ab: '' },
    { year: 2023, fullName: 'Lopez, Nicky', rmlTeam: 'TinCaps', ip: '', ab: '225' },
    { year: 2023, fullName: 'Lopez, Pablo', rmlTeam: 'Captains', ip: '194', ab: '' },
    { year: 2023, fullName: 'Lopez, Reynaldo', rmlTeam: 'Captains', ip: '66', ab: '' },
    { year: 2023, fullName: 'Lorenzen, Michael', rmlTeam: 'Gypsies', ip: '153', ab: '' },
    { year: 2023, fullName: 'Loup, Aaron', rmlTeam: 'Z-Unowned', ip: '48.2', ab: '' },
    { year: 2023, fullName: 'Lowe, Brandon', rmlTeam: 'Stars', ip: '', ab: '377' },
    { year: 2023, fullName: 'Lowe, Josh', rmlTeam: 'Knights', ip: '', ab: '466' },
    { year: 2023, fullName: 'Lowe, Nathaniel', rmlTeam: 'Stars', ip: '', ab: '623' },
    { year: 2023, fullName: 'Lugo, Seth', rmlTeam: 'Stars', ip: '146.1', ab: '' },
    { year: 2023, fullName: 'Luzardo, Jesus', rmlTeam: 'Monarchs', ip: '178.2', ab: '' },
    { year: 2023, fullName: 'Lyles, Jordan', rmlTeam: 'Clown Princes', ip: '177.2', ab: '' },
    { year: 2023, fullName: 'Lynn, Lance', rmlTeam: 'Twins', ip: '183.2', ab: '' },
    { year: 2023, fullName: 'Machado, Andres', rmlTeam: 'Z-Unowned', ip: '50', ab: '' },
    { year: 2023, fullName: 'Machado, Manny', rmlTeam: 'Gypsies', ip: '', ab: '543' },
    { year: 2023, fullName: 'Madrigal, Nick', rmlTeam: 'Bandits', ip: '', ab: '270' },
    { year: 2023, fullName: 'Maeda, Kenta', rmlTeam: 'Expos', ip: '104.1', ab: '' },
    { year: 2023, fullName: 'Maile, Luke', rmlTeam: 'Z-Unowned', ip: '', ab: '179' },
    { year: 2023, fullName: 'Maldonado, Martin', rmlTeam: 'Z-Unowned', ip: '', ab: '362' },
    { year: 2023, fullName: 'Manaea, Sean', rmlTeam: 'Clown Princes', ip: '117.2', ab: '' },
    { year: 2023, fullName: 'Mancini, Trey', rmlTeam: 'Z-Unowned', ip: '', ab: '235' },
    { year: 2023, fullName: 'Manning, Matt', rmlTeam: 'Knights', ip: '78', ab: '' },
    { year: 2023, fullName: 'Manoah, Alek', rmlTeam: 'Dodgers', ip: '87.1', ab: '' },
    { year: 2023, fullName: 'Mantiply, Joe', rmlTeam: 'Z-Unowned', ip: '39', ab: '' },
    { year: 2023, fullName: 'Marcano, Tucupita', rmlTeam: 'Z-Unowned', ip: '', ab: '202' },
    { year: 2023, fullName: 'Margot, Manuel', rmlTeam: 'Hornets', ip: '', ab: '311' },
    { year: 2023, fullName: 'Marinaccio, Ron', rmlTeam: 'Clown Princes', ip: '47.1', ab: '' },
    { year: 2023, fullName: 'Marsh, Alec', rmlTeam: 'Monarchs', ip: '74.1', ab: '' },
    { year: 2023, fullName: 'Marsh, Brandon', rmlTeam: 'Monarchs', ip: '', ab: '404' },
    { year: 2023, fullName: 'Marte, Ketel', rmlTeam: 'Dodgers', ip: '', ab: '569' },
    { year: 2023, fullName: 'Marte, Noelvi', rmlTeam: 'Browns', ip: '', ab: '114' },
    { year: 2023, fullName: 'Marte, Starling', rmlTeam: 'River Dogs', ip: '', ab: '315' },
    { year: 2023, fullName: 'Marte, Yunior', rmlTeam: 'Z-Unowned', ip: '39.1', ab: '' },
    { year: 2023, fullName: 'Martin, Chris', rmlTeam: 'Grays', ip: '51.1', ab: '' },
    { year: 2023, fullName: 'Martinez, JD', rmlTeam: 'Captains', ip: '', ab: '432' },
    { year: 2023, fullName: 'Martinez, Nick', rmlTeam: 'Twins', ip: '110.1', ab: '' },
    { year: 2023, fullName: 'Martinez, Seth', rmlTeam: 'Z-Unowned', ip: '43', ab: '' },
    { year: 2023, fullName: 'Massey, Michael', rmlTeam: 'Colt .45s', ip: '', ab: '428' },
    { year: 2023, fullName: 'Mastrobuoni, Miles', rmlTeam: 'Knights', ip: '', ab: '133' },
    { year: 2023, fullName: 'Mateo, Jorge', rmlTeam: 'Monarchs', ip: '', ab: '318' },
    { year: 2023, fullName: 'Maton, Nick', rmlTeam: 'Z-Unowned', ip: '', ab: '249' },
    { year: 2023, fullName: 'Maton, Phil', rmlTeam: 'Browns', ip: '66', ab: '' },
    { year: 2023, fullName: 'Matos, Luis', rmlTeam: 'Yellow Jackets', ip: '', ab: '228' },
    { year: 2023, fullName: 'Matz, Steven', rmlTeam: 'Hornets', ip: '105', ab: '' },
    { year: 2023, fullName: 'Mauricio, Ronny', rmlTeam: 'Knights', ip: '', ab: '101' },
    { year: 2023, fullName: 'May, Trevor', rmlTeam: 'Pilgrims', ip: '46.2', ab: '' },
    { year: 2023, fullName: 'Mayza, Tim', rmlTeam: 'Pilgrims', ip: '53.1', ab: '' },
    { year: 2023, fullName: 'McCann, James', rmlTeam: 'Z-Unowned', ip: '', ab: '207' },
    { year: 2023, fullName: 'McCarthy, Jake', rmlTeam: 'Monarchs', ip: '', ab: '276' },
    { year: 2023, fullName: 'McClanahan, Shane', rmlTeam: 'Captains', ip: '115', ab: '' },
    { year: 2023, fullName: 'McCormick, Chas', rmlTeam: 'Yellow Jackets', ip: '', ab: '403' },
    { year: 2023, fullName: 'McCutchen, Andrew', rmlTeam: 'Expos', ip: '', ab: '390' },
    { year: 2023, fullName: 'McGough, Scott', rmlTeam: 'Colt .45s', ip: '70.1', ab: '' },
    { year: 2023, fullName: 'McGuire, Reese', rmlTeam: 'Z-Unowned', ip: '', ab: '187' },
    { year: 2023, fullName: 'McHugh, Collin', rmlTeam: 'Z-Unowned', ip: '58.2', ab: '' },
    { year: 2023, fullName: 'McKenna, Ryan', rmlTeam: 'Z-Unowned', ip: '', ab: '122' },
    { year: 2023, fullName: 'McKinney, Billy', rmlTeam: 'Z-Unowned', ip: '', ab: '128' },
    { year: 2023, fullName: 'McKinstry, Zach', rmlTeam: 'Gypsies', ip: '', ab: '464' },
    { year: 2023, fullName: 'McLain, Matt', rmlTeam: 'Titans', ip: '', ab: '365' },
    { year: 2023, fullName: 'McMahon, Ryan', rmlTeam: 'Clown Princes', ip: '', ab: '555' },
    { year: 2023, fullName: 'McNeil, Jeff', rmlTeam: 'Twins', ip: '', ab: '585' },
    { year: 2023, fullName: 'Meadows, Parker', rmlTeam: 'Reds', ip: '', ab: '125' },
    { year: 2023, fullName: 'Medina, Luis', rmlTeam: 'River Dogs', ip: '109.2', ab: '' },
    { year: 2023, fullName: 'Megill, Trevor', rmlTeam: 'Z-Unowned', ip: '34.2', ab: '' },
    { year: 2023, fullName: 'Megill, Tylor', rmlTeam: 'Titans', ip: '126.1', ab: '' },
    { year: 2023, fullName: 'Mejia, Francisco', rmlTeam: 'Z-Unowned', ip: '', ab: '150' },
    { year: 2023, fullName: 'Melendez, MJ', rmlTeam: 'Knights', ip: '', ab: '533' },
    { year: 2023, fullName: 'Meneses, Joey', rmlTeam: 'Bandits', ip: '', ab: '611' },
    { year: 2023, fullName: 'Merrifield, Whit', rmlTeam: 'Expos', ip: '', ab: '547' },
    { year: 2023, fullName: 'Merryweather, Julian', rmlTeam: 'Pilgrims', ip: '72', ab: '' },
    { year: 2023, fullName: 'Meyers, Jake', rmlTeam: 'Colt .45s', ip: '', ab: '309' },
    { year: 2023, fullName: 'Middleton, Keynan', rmlTeam: 'Z-Unowned', ip: '50.2', ab: '' },
    { year: 2023, fullName: 'Mikolas, Miles', rmlTeam: 'Colt .45s', ip: '201.1', ab: '' },
    { year: 2023, fullName: 'Miley, Wade', rmlTeam: 'Monarchs', ip: '120.1', ab: '' },
    { year: 2023, fullName: 'Miller, Bobby', rmlTeam: 'Grays', ip: '124.1', ab: '' },
    { year: 2023, fullName: 'Miller, Bryce', rmlTeam: 'Pilgrims', ip: '131.1', ab: '' },
    { year: 2023, fullName: 'Miller, Owen', rmlTeam: 'Z-Unowned', ip: '', ab: '291' },
    { year: 2023, fullName: 'Miller, Shelby', rmlTeam: 'Blaze', ip: '42', ab: '' },
    { year: 2023, fullName: 'Milner, Hoby', rmlTeam: 'Captains', ip: '64.1', ab: '' },
    { year: 2023, fullName: 'Minter, AJ', rmlTeam: 'Pelicans', ip: '64.2', ab: '' },
    { year: 2023, fullName: 'Miranda, Jose', rmlTeam: 'Pilots', ip: '', ab: '142' },
    { year: 2023, fullName: 'Mlodzinski, Carmen', rmlTeam: 'Captains', ip: '36', ab: '' },
    { year: 2023, fullName: 'Moll, Sam', rmlTeam: 'Expos', ip: '62.1', ab: '' },
    { year: 2023, fullName: 'Monasterio, Andruw', rmlTeam: 'Hornets', ip: '', ab: '282' },
    { year: 2023, fullName: 'Moncada, Yoan', rmlTeam: 'Stars', ip: '', ab: '334' },
    { year: 2023, fullName: 'Moniak, Mickey', rmlTeam: 'Reds', ip: '', ab: '311' },
    { year: 2023, fullName: 'Montero, Elehuris', rmlTeam: 'Clown Princes', ip: '', ab: '284' },
    { year: 2023, fullName: 'Montero, Rafael', rmlTeam: 'Z-Unowned', ip: '67.1', ab: '' },
    { year: 2023, fullName: 'Montgomery, Jordan', rmlTeam: 'Monarchs', ip: '188.2', ab: '' },
    { year: 2023, fullName: 'Moore, Dylan', rmlTeam: 'Knights', ip: '', ab: '145' },
    { year: 2023, fullName: 'Moore, Matt', rmlTeam: 'Browns', ip: '52.2', ab: '' },
    { year: 2023, fullName: 'Moran, Jovani', rmlTeam: 'Clown Princes', ip: '42.1', ab: '' },
    { year: 2023, fullName: 'Morel, Christopher', rmlTeam: 'Yellow Jackets', ip: '', ab: '388' },
    { year: 2023, fullName: 'Moreno, Gabriel', rmlTeam: 'TinCaps', ip: '', ab: '341' },
    { year: 2023, fullName: 'Moreta, Dauri', rmlTeam: 'Knights', ip: '58', ab: '' },
    { year: 2023, fullName: 'Morgan, Eli', rmlTeam: 'Pilots', ip: '67.1', ab: '' },
    { year: 2023, fullName: 'Morton, Charlie', rmlTeam: 'Expos', ip: '163.1', ab: '' },
    { year: 2023, fullName: 'Mountcastle, Ryan', rmlTeam: 'RockHounds', ip: '', ab: '423' },
    { year: 2023, fullName: 'Moustakas, Mike', rmlTeam: 'Captains', ip: '', ab: '352' },
    { year: 2023, fullName: 'Muller, Kyle', rmlTeam: 'Z-Unowned', ip: '77', ab: '' },
    { year: 2023, fullName: 'Mullins, Cedric', rmlTeam: 'Dodgers', ip: '', ab: '404' },
    { year: 2023, fullName: 'Muncy, Max', rmlTeam: 'Grays', ip: '', ab: '482' },
    { year: 2023, fullName: 'Munoz, Andres', rmlTeam: 'Knights', ip: '49', ab: '' },
    { year: 2023, fullName: 'Murphy, Sean', rmlTeam: 'Yellow Jackets', ip: '', ab: '370' },
    { year: 2023, fullName: 'Murphy, Tom', rmlTeam: 'Colt .45s', ip: '', ab: '145' },
    { year: 2023, fullName: 'Musgrove, Joe', rmlTeam: 'Pelicans', ip: '97.1', ab: '' },
    { year: 2023, fullName: 'Myers, Wil', rmlTeam: 'Z-Unowned', ip: '', ab: '127' },
    { year: 2023, fullName: 'Nardi, Andrew', rmlTeam: 'Titans', ip: '57.1', ab: '' },
    { year: 2023, fullName: 'Narvaez, Omar', rmlTeam: 'Z-Unowned', ip: '', ab: '128' },
    { year: 2023, fullName: 'Naylor, Bo', rmlTeam: 'Stars', ip: '', ab: '198' },
    { year: 2023, fullName: 'Naylor, Josh', rmlTeam: 'Captains', ip: '', ab: '452' },
    { year: 2023, fullName: 'Nelson, Kyle', rmlTeam: 'Pilots', ip: '56', ab: '' },
    { year: 2023, fullName: 'Nelson, Ryne', rmlTeam: 'Knights', ip: '144', ab: '' },
    { year: 2023, fullName: 'Neris, Hector', rmlTeam: 'Pelicans', ip: '68.1', ab: '' },
    { year: 2023, fullName: 'Neto, Zach', rmlTeam: 'Grays', ip: '', ab: '289' },
    { year: 2023, fullName: 'Newman, Kevin', rmlTeam: 'Gypsies', ip: '', ab: '225' },
    { year: 2023, fullName: 'Nimmo, Brandon', rmlTeam: 'Pilgrims', ip: '', ab: '592' },
    { year: 2023, fullName: 'Noda, Ryan', rmlTeam: 'Gypsies', ip: '', ab: '406' },
    { year: 2023, fullName: 'Nola, Aaron', rmlTeam: 'Yellow Jackets', ip: '193.2', ab: '' },
    { year: 2023, fullName: 'Nola, Austin', rmlTeam: 'Z-Unowned', ip: '', ab: '130' },
    { year: 2023, fullName: 'Nootbaar, Lars', rmlTeam: 'Blaze', ip: '', ab: '426' },
    { year: 2023, fullName: 'Ober, Bailey', rmlTeam: 'Clown Princes', ip: '144.1', ab: '' },
    { year: 2023, fullName: 'Odor, Rougned', rmlTeam: 'Z-Unowned', ip: '', ab: '138' },
    { year: 2023, fullName: 'O\'Hearn, Ryan', rmlTeam: 'RockHounds', ip: '', ab: '346' },
    { year: 2023, fullName: 'O\'Hoppe, Logan', rmlTeam: 'Pilgrims', ip: '', ab: '182' },
    { year: 2023, fullName: 'Ohtani, Shohei', rmlTeam: 'Titans', ip: '132', ab: '497' },
    { year: 2023, fullName: 'Okert, Steven', rmlTeam: 'Dodgers', ip: '58.2', ab: '' },
    { year: 2023, fullName: 'Olivares, Edward', rmlTeam: 'Reds', ip: '', ab: '354' },
    { year: 2023, fullName: 'Olson, Matt', rmlTeam: 'Reds', ip: '', ab: '608' },
    { year: 2023, fullName: 'Olson, Reese', rmlTeam: 'Gypsies', ip: '103.2', ab: '' },
    { year: 2023, fullName: 'O\'Neill, Tyler', rmlTeam: 'Titans', ip: '', ab: '238' },
    { year: 2023, fullName: 'Ortega, Rafael', rmlTeam: 'Z-Unowned', ip: '', ab: '114' },
    { year: 2023, fullName: 'Ortiz, Luis', rmlTeam: 'Hornets', ip: '86.2', ab: '' },
    { year: 2023, fullName: 'Ottavino, Adam', rmlTeam: 'Captains', ip: '61.2', ab: '' },
    { year: 2023, fullName: 'Outman, James', rmlTeam: 'Pilots', ip: '', ab: '483' },
    { year: 2023, fullName: 'Oviedo, Johan', rmlTeam: 'River Dogs', ip: '177.2', ab: '' },
    { year: 2023, fullName: 'Ozuna, Marcell', rmlTeam: 'Pilgrims', ip: '', ab: '530' },
    { year: 2023, fullName: 'Pagan, Emilio', rmlTeam: 'Titans', ip: '69.1', ab: '' },
    { year: 2023, fullName: 'Palacios, Joshua', rmlTeam: 'Z-Unowned', ip: '', ab: '247' },
    { year: 2023, fullName: 'Pallante, Andre', rmlTeam: 'Knights', ip: '68', ab: '' },
    { year: 2023, fullName: 'Paredes, Isaac', rmlTeam: 'Pelicans', ip: '', ab: '492' },
    { year: 2023, fullName: 'Pasquantino, Vinnie', rmlTeam: 'TinCaps', ip: '', ab: '231' },
    { year: 2023, fullName: 'Paxton, James', rmlTeam: 'Pilgrims', ip: '96', ab: '' },
    { year: 2023, fullName: 'Payamps, Joel', rmlTeam: 'Expos', ip: '70.2', ab: '' },
    { year: 2023, fullName: 'Pearson, Nate', rmlTeam: 'Grays', ip: '42.2', ab: '' },
    { year: 2023, fullName: 'Pederson, Joc', rmlTeam: 'Captains', ip: '', ab: '358' },
    { year: 2023, fullName: 'Peguero, Elvis', rmlTeam: 'Blaze', ip: '61.1', ab: '' },
    { year: 2023, fullName: 'Peguero, Liover', rmlTeam: 'Pilgrims', ip: '', ab: '198' },
    { year: 2023, fullName: 'Pena, Jeremy', rmlTeam: 'Pilots', ip: '', ab: '577' },
    { year: 2023, fullName: 'Peralta, David', rmlTeam: 'Z-Unowned', ip: '', ab: '394' },
    { year: 2023, fullName: 'Peralta, Freddy', rmlTeam: 'Stars', ip: '165.2', ab: '' },
    { year: 2023, fullName: 'Peralta, Wandy', rmlTeam: 'Yellow Jackets', ip: '54', ab: '' },
    { year: 2023, fullName: 'Peraza, Oswald', rmlTeam: 'Stars', ip: '', ab: '173' },
    { year: 2023, fullName: 'Perdomo, Angel', rmlTeam: 'Z-Unowned', ip: '29', ab: '' },
    { year: 2023, fullName: 'Perdomo, Geraldo', rmlTeam: 'Browns', ip: '', ab: '407' },
    { year: 2023, fullName: 'Perez, Carlos', rmlTeam: 'Z-Unowned', ip: '', ab: '168' },
    { year: 2023, fullName: 'Perez, Cionel', rmlTeam: 'Pilots', ip: '53.1', ab: '' },
    { year: 2023, fullName: 'Perez, Eury', rmlTeam: 'Stars', ip: '91.1', ab: '' },
    { year: 2023, fullName: 'Perez, Martin', rmlTeam: 'Pelicans', ip: '141.2', ab: '' },
    { year: 2023, fullName: 'Perez, Salvador', rmlTeam: 'Gypsies', ip: '', ab: '538' },
    { year: 2023, fullName: 'Perkins, Blake', rmlTeam: 'Z-Unowned', ip: '', ab: '143' },
    { year: 2023, fullName: 'Peterson, David', rmlTeam: 'Bandits', ip: '111', ab: '' },
    { year: 2023, fullName: 'Peterson, Jace', rmlTeam: 'Z-Unowned', ip: '', ab: '374' },
    { year: 2023, fullName: 'Pfaadt, Brandon', rmlTeam: 'Pilgrims', ip: '96', ab: '' },
    { year: 2023, fullName: 'Pham, Tommy', rmlTeam: 'Expos', ip: '', ab: '426' },
    { year: 2023, fullName: 'Phillips, Evan', rmlTeam: 'Gypsies', ip: '61.1', ab: '' },
    { year: 2023, fullName: 'Pillar, Kevin', rmlTeam: 'Pelicans', ip: '', ab: '197' },
    { year: 2023, fullName: 'Pinto, Rene', rmlTeam: 'Blaze', ip: '', ab: '103' },
    { year: 2023, fullName: 'Pivetta, Nick', rmlTeam: 'Clown Princes', ip: '142.2', ab: '' },
    { year: 2023, fullName: 'Poche, Colin', rmlTeam: 'Hornets', ip: '60.2', ab: '' },
    { year: 2023, fullName: 'Polanco, Jorge', rmlTeam: 'Pilgrims', ip: '', ab: '302' },
    { year: 2023, fullName: 'Pollock, AJ', rmlTeam: 'Z-Unowned', ip: '', ab: '133' },
    { year: 2023, fullName: 'Pratto, Nick', rmlTeam: 'Knights', ip: '', ab: '306' },
    { year: 2023, fullName: 'Pressly, Ryan', rmlTeam: 'Pilots', ip: '65.1', ab: '' },
    { year: 2023, fullName: 'Profar, Jurickson', rmlTeam: 'Twins', ip: '', ab: '459' },
    { year: 2023, fullName: 'Pruitt, Austin', rmlTeam: 'TinCaps', ip: '48.1', ab: '' },
    { year: 2023, fullName: 'Puk, AJ', rmlTeam: 'RockHounds', ip: '56.2', ab: '' },
    { year: 2023, fullName: 'Quantrill, Cal', rmlTeam: 'Colt .45s', ip: '99.2', ab: '' },
    { year: 2023, fullName: 'Quintana, Jose', rmlTeam: 'Grays', ip: '75.2', ab: '' },
    { year: 2023, fullName: 'Ragans, Cole', rmlTeam: 'Blaze', ip: '96', ab: '' },
    { year: 2023, fullName: 'Raleigh, Cal', rmlTeam: 'Stars', ip: '', ab: '513' },
    { year: 2023, fullName: 'Raley, Brooks', rmlTeam: 'Expos', ip: '54.2', ab: '' },
    { year: 2023, fullName: 'Raley, Luke', rmlTeam: 'Gypsies', ip: '', ab: '357' },
    { year: 2023, fullName: 'Ramirez, Erasmo', rmlTeam: 'Z-Unowned', ip: '60.1', ab: '' },
    { year: 2023, fullName: 'Ramirez, Harold', rmlTeam: 'Titans', ip: '', ab: '400' },
    { year: 2023, fullName: 'Ramirez, Jose', rmlTeam: 'Pilgrims', ip: '', ab: '611' },
    { year: 2023, fullName: 'Ramirez, Nick', rmlTeam: 'Z-Unowned', ip: '40.2', ab: '' },
    { year: 2023, fullName: 'Ramirez, Yohan', rmlTeam: 'Z-Unowned', ip: '38.1', ab: '' },
    { year: 2023, fullName: 'Rea, Colin', rmlTeam: 'Reds', ip: '124.2', ab: '' },
    { year: 2023, fullName: 'Realmuto, JT', rmlTeam: 'Pelicans', ip: '', ab: '489' },
    { year: 2023, fullName: 'Refsnyder, Rob', rmlTeam: 'Reds', ip: '', ab: '202' },
    { year: 2023, fullName: 'Remillard, Zach', rmlTeam: 'Z-Unowned', ip: '', ab: '147' },
    { year: 2023, fullName: 'Rendon, Anthony', rmlTeam: 'Captains', ip: '', ab: '148' },
    { year: 2023, fullName: 'Renfroe, Hunter', rmlTeam: 'Expos', ip: '', ab: '498' },
    { year: 2023, fullName: 'Rengifo, Luis', rmlTeam: 'RockHounds', ip: '', ab: '394' },
    { year: 2023, fullName: 'Reyes, Pablo', rmlTeam: 'Z-Unowned', ip: '', ab: '167' },
    { year: 2023, fullName: 'Reynolds, Bryan', rmlTeam: 'Captains', ip: '', ab: '574' },
    { year: 2023, fullName: 'Richards, Trevor', rmlTeam: 'Z-Unowned', ip: '72.2', ab: '' },
    { year: 2023, fullName: 'Riley, Austin', rmlTeam: 'Titans', ip: '', ab: '636' },
    { year: 2023, fullName: 'Rivas, Alfonso', rmlTeam: 'Z-Unowned', ip: '', ab: '109' },
    { year: 2023, fullName: 'Rivera, Emmanuel', rmlTeam: 'Bandits', ip: '', ab: '257' },
    { year: 2023, fullName: 'Rizzo, Anthony', rmlTeam: 'Yellow Jackets', ip: '', ab: '373' },
    { year: 2023, fullName: 'Robert Jr, Luis', rmlTeam: 'RockHounds', ip: '', ab: '546' },
    { year: 2023, fullName: 'Robertson, David', rmlTeam: 'Browns', ip: '65.1', ab: '' },
    { year: 2023, fullName: 'Robles, Victor', rmlTeam: 'Z-Unowned', ip: '', ab: '107' },
    { year: 2023, fullName: 'Rodgers, Brendan', rmlTeam: 'Stars', ip: '', ab: '178' },
    { year: 2023, fullName: 'Rodon, Carlos', rmlTeam: 'Blaze', ip: '64.1', ab: '' },
    { year: 2023, fullName: 'Rodriguez, Eduardo', rmlTeam: 'Hornets', ip: '152.2', ab: '' },
    { year: 2023, fullName: 'Rodriguez, Endy', rmlTeam: 'RockHounds', ip: '', ab: '186' },
    { year: 2023, fullName: 'Rodriguez, Grayson', rmlTeam: 'RockHounds', ip: '122', ab: '' },
    { year: 2023, fullName: 'Rodriguez, Julio', rmlTeam: 'Grays', ip: '', ab: '654' },
    { year: 2023, fullName: 'Rogers, Jake', rmlTeam: 'Bandits', ip: '', ab: '331' },
    { year: 2023, fullName: 'Rogers, Taylor', rmlTeam: 'Clown Princes', ip: '51.2', ab: '' },
    { year: 2023, fullName: 'Rogers, Tyler', rmlTeam: 'Browns', ip: '74', ab: '' },
    { year: 2023, fullName: 'Rojas, Johan', rmlTeam: 'Stars', ip: '', ab: '149' },
    { year: 2023, fullName: 'Rojas, Josh', rmlTeam: 'Z-Unowned', ip: '', ab: '314' },
    { year: 2023, fullName: 'Rojas, Miguel', rmlTeam: 'Twins', ip: '', ab: '385' },
    { year: 2023, fullName: 'Romano, Jordan', rmlTeam: 'Knights', ip: '59', ab: '' },
    { year: 2023, fullName: 'Rooker, Brent', rmlTeam: 'Bandits', ip: '', ab: '463' },
    { year: 2023, fullName: 'Rosario, Amed', rmlTeam: 'Stars', ip: '', ab: '510' },
    { year: 2023, fullName: 'Rosario, Eddie', rmlTeam: 'Pilgrims', ip: '', ab: '478' },
    { year: 2023, fullName: 'Rucker, Michael', rmlTeam: 'Z-Unowned', ip: '40.1', ab: '' },
    { year: 2023, fullName: 'Ruiz, Esteury', rmlTeam: 'Knights', ip: '', ab: '449' },
    { year: 2023, fullName: 'Ruiz, Jose', rmlTeam: 'Z-Unowned', ip: '44.1', ab: '' },
    { year: 2023, fullName: 'Ruiz, Keibert', rmlTeam: 'Bandits', ip: '', ab: '523' },
    { year: 2023, fullName: 'Rutschman, Adley', rmlTeam: 'Grays', ip: '', ab: '588' },
    { year: 2023, fullName: 'Ryan, Joe', rmlTeam: 'Blaze', ip: '161.2', ab: '' },
    { year: 2023, fullName: 'Ryu, Hyun Jin', rmlTeam: 'Bandits', ip: '52', ab: '' },
    { year: 2023, fullName: 'Sabol, Blake', rmlTeam: 'Pilots', ip: '', ab: '310' },
    { year: 2023, fullName: 'Sale, Chris', rmlTeam: 'Grays', ip: '102.2', ab: '' },
    { year: 2023, fullName: 'Sanchez, Cristopher', rmlTeam: 'Stars', ip: '99.1', ab: '' },
    { year: 2023, fullName: 'Sanchez, Gary', rmlTeam: 'Monarchs', ip: '', ab: '240' },
    { year: 2023, fullName: 'Sanchez, Jesus', rmlTeam: 'Reds', ip: '', ab: '360' },
    { year: 2023, fullName: 'Sandlin, Nick', rmlTeam: 'Hornets', ip: '60', ab: '' },
    { year: 2023, fullName: 'Sandoval, Patrick', rmlTeam: 'TinCaps', ip: '144.2', ab: '' },
    { year: 2023, fullName: 'Santana, Carlos', rmlTeam: 'Monarchs', ip: '', ab: '550' },
    { year: 2023, fullName: 'Santander, Anthony', rmlTeam: 'Pelicans', ip: '', ab: '591' },
    { year: 2023, fullName: 'Santos, Gregory', rmlTeam: 'Reds', ip: '66.1', ab: '' },
    { year: 2023, fullName: 'Saucedo, Tayler', rmlTeam: 'Yellow Jackets', ip: '47.2', ab: '' },
    { year: 2023, fullName: 'Sborz, Josh', rmlTeam: 'Z-Unowned', ip: '52.1', ab: '' },
    { year: 2023, fullName: 'Schanuel, Nolan', rmlTeam: 'Blaze', ip: '', ab: '109' },
    { year: 2023, fullName: 'Scherzer, Max', rmlTeam: 'Yellow Jackets', ip: '152.2', ab: '' },
    { year: 2023, fullName: 'Schmidt, Clarke', rmlTeam: 'Clown Princes', ip: '159', ab: '' },
    { year: 2023, fullName: 'Schmitt, Casey', rmlTeam: 'Knights', ip: '', ab: '253' },
    { year: 2023, fullName: 'Schneider, Davis', rmlTeam: 'RockHounds', ip: '', ab: '116' },
    { year: 2023, fullName: 'Scholtens, Jesse', rmlTeam: 'Monarchs', ip: '85', ab: '' },
    { year: 2023, fullName: 'Schoop, Jonathan', rmlTeam: 'Z-Unowned', ip: '', ab: '136' },
    { year: 2023, fullName: 'Schreiber, John', rmlTeam: 'Monarchs', ip: '46.2', ab: '' },
    { year: 2023, fullName: 'Schwarber, Kyle', rmlTeam: 'Dodgers', ip: '', ab: '585' },
    { year: 2023, fullName: 'Scott, Tanner', rmlTeam: 'Twins', ip: '78', ab: '' },
    { year: 2023, fullName: 'Seabold, Connor', rmlTeam: 'Z-Unowned', ip: '87.1', ab: '' },
    { year: 2023, fullName: 'Seager, Corey', rmlTeam: 'Reds', ip: '', ab: '477' },
    { year: 2023, fullName: 'Sears, JP', rmlTeam: 'Pilots', ip: '172.1', ab: '' },
    { year: 2023, fullName: 'Segura, Jean', rmlTeam: 'Z-Unowned', ip: '', ab: '301' },
    { year: 2023, fullName: 'Semien, Marcus', rmlTeam: 'Yellow Jackets', ip: '', ab: '670' },
    { year: 2023, fullName: 'Senga, Kodai', rmlTeam: 'TinCaps', ip: '166.1', ab: '' },
    { year: 2023, fullName: 'Senzel, Nick', rmlTeam: 'Browns', ip: '', ab: '301' },
    { year: 2023, fullName: 'Severino, Luis', rmlTeam: 'Reds', ip: '89.1', ab: '' },
    { year: 2023, fullName: 'Sewald, Paul', rmlTeam: 'Pilots', ip: '60.2', ab: '' },
    { year: 2023, fullName: 'Shaw, Bryan', rmlTeam: 'Z-Unowned', ip: '45.2', ab: '' },
    { year: 2023, fullName: 'Sheehan, Emmet', rmlTeam: 'Titans', ip: '60.1', ab: '' },
    { year: 2023, fullName: 'Sheets, Gavin', rmlTeam: 'TinCaps', ip: '', ab: '311' },
    { year: 2023, fullName: 'Short, Zack', rmlTeam: 'Z-Unowned', ip: '', ab: '221' },
    { year: 2023, fullName: 'Shreve, Chasen', rmlTeam: 'Z-Unowned', ip: '44.2', ab: '' },
    { year: 2023, fullName: 'Shuster, Jared', rmlTeam: 'Yellow Jackets', ip: '52.2', ab: '' },
    { year: 2023, fullName: 'Sims, Lucas', rmlTeam: 'Yellow Jackets', ip: '61', ab: '' },
    { year: 2023, fullName: 'Singer, Brady', rmlTeam: 'Colt .45s', ip: '159.2', ab: '' },
    { year: 2023, fullName: 'Siri, Jose', rmlTeam: 'RockHounds', ip: '', ab: '338' },
    { year: 2023, fullName: 'Skubal, Tarik', rmlTeam: 'Pilots', ip: '80.1', ab: '' },
    { year: 2023, fullName: 'Slater, Austin', rmlTeam: 'Z-Unowned', ip: '', ab: '185' },
    { year: 2023, fullName: 'Smith, Dominic', rmlTeam: 'RockHounds', ip: '', ab: '527' },
    { year: 2023, fullName: 'Smith, Drew', rmlTeam: 'Pilots', ip: '56.1', ab: '' },
    { year: 2023, fullName: 'Smith, Josh H', rmlTeam: 'Hornets', ip: '', ab: '195' },
    { year: 2023, fullName: 'Smith, Kevin', rmlTeam: 'Z-Unowned', ip: '', ab: '135' },
    { year: 2023, fullName: 'Smith, Pavin', rmlTeam: 'Clown Princes', ip: '', ab: '191' },
    { year: 2023, fullName: 'Smith, Will', rmlTeam: 'Captains', ip: '', ab: '464' },
    { year: 2023, fullName: 'Smith, Will', rmlTeam: 'Grays', ip: '57.1', ab: '' },
    { year: 2023, fullName: 'Smyly, Drew', rmlTeam: 'Stars', ip: '142.1', ab: '' },
    { year: 2023, fullName: 'Snell, Blake', rmlTeam: 'Blaze', ip: '180', ab: '' },
    { year: 2023, fullName: 'Soderstrom, Tyler', rmlTeam: 'River Dogs', ip: '', ab: '125' },
    { year: 2023, fullName: 'Solano, Donovan', rmlTeam: 'Clown Princes', ip: '', ab: '394' },
    { year: 2023, fullName: 'Soler, Jorge', rmlTeam: 'RockHounds', ip: '', ab: '504' },
    { year: 2023, fullName: 'Soriano, Jose', rmlTeam: 'Z-Unowned', ip: '42', ab: '' },
    { year: 2023, fullName: 'Sosa, Edmundo', rmlTeam: 'Yellow Jackets', ip: '', ab: '279' },
    { year: 2023, fullName: 'Sosa, Lenyn', rmlTeam: 'Z-Unowned', ip: '', ab: '164' },
    { year: 2023, fullName: 'Soto, Gregory', rmlTeam: 'RockHounds', ip: '60.1', ab: '' },
    { year: 2023, fullName: 'Soto, Juan', rmlTeam: 'Stars', ip: '', ab: '568' },
    { year: 2023, fullName: 'Speier, Gabe', rmlTeam: 'Reds', ip: '54.2', ab: '' },
    { year: 2023, fullName: 'Springer, George', rmlTeam: 'Monarchs', ip: '', ab: '613' },
    { year: 2023, fullName: 'Stallings, Jacob', rmlTeam: 'Z-Unowned', ip: '', ab: '241' },
    { year: 2023, fullName: 'Stanek, Ryne', rmlTeam: 'Yellow Jackets', ip: '50.2', ab: '' },
    { year: 2023, fullName: 'Stanton, Giancarlo', rmlTeam: 'Dodgers', ip: '', ab: '371' },
    { year: 2023, fullName: 'Steele, Justin', rmlTeam: 'Reds', ip: '173.1', ab: '' },
    { year: 2023, fullName: 'Steer, Spencer', rmlTeam: 'Expos', ip: '', ab: '582' },
    { year: 2023, fullName: 'Stephan, Trevor', rmlTeam: 'River Dogs', ip: '68.2', ab: '' },
    { year: 2023, fullName: 'Stephenson, Robert', rmlTeam: 'Twins', ip: '52.1', ab: '' },
    { year: 2023, fullName: 'Stephenson, Tyler', rmlTeam: 'Expos', ip: '', ab: '465' },
    { year: 2023, fullName: 'Stewart, DJ', rmlTeam: 'Z-Unowned', ip: '', ab: '160' },
    { year: 2023, fullName: 'Story, Trevor', rmlTeam: 'Colt .45s', ip: '', ab: '158' },
    { year: 2023, fullName: 'Stott, Bryson', rmlTeam: 'Twins', ip: '', ab: '585' },
    { year: 2023, fullName: 'Strahm, Matt', rmlTeam: 'Stars', ip: '87.2', ab: '' },
    { year: 2023, fullName: 'Stratton, Chris', rmlTeam: 'Reds', ip: '82.2', ab: '' },
    { year: 2023, fullName: 'Straw, Myles', rmlTeam: 'TinCaps', ip: '', ab: '462' },
    { year: 2023, fullName: 'Strider, Spencer', rmlTeam: 'Hornets', ip: '186.2', ab: '' },
    { year: 2023, fullName: 'Stripling, Ross', rmlTeam: 'Monarchs', ip: '89', ab: '' },
    { year: 2023, fullName: 'Stroman, Marcus', rmlTeam: 'Pilgrims', ip: '136.2', ab: '' },
    { year: 2023, fullName: 'Strzelecki, Peter', rmlTeam: 'Z-Unowned', ip: '37', ab: '' },
    { year: 2023, fullName: 'Stubbs, Garrett', rmlTeam: 'Gypsies', ip: '', ab: '113' },
    { year: 2023, fullName: 'Suarez, Eugenio', rmlTeam: 'Browns', ip: '', ab: '598' },
    { year: 2023, fullName: 'Suarez, Ranger', rmlTeam: 'Browns', ip: '125', ab: '' },
    { year: 2023, fullName: 'Suter, Brent', rmlTeam: 'Hornets', ip: '69.1', ab: '' },
    { year: 2023, fullName: 'Suwinski, Jack', rmlTeam: 'Colt .45s', ip: '', ab: '447' },
    { year: 2023, fullName: 'Suzuki, Seiya', rmlTeam: 'TinCaps', ip: '', ab: '515' },
    { year: 2023, fullName: 'Swanson, Dansby', rmlTeam: 'Gypsies', ip: '', ab: '565' },
    { year: 2023, fullName: 'Swanson, Erik', rmlTeam: 'TinCaps', ip: '66.2', ab: '' },
    { year: 2023, fullName: 'Syndergaard, Noah', rmlTeam: 'Monarchs', ip: '88.2', ab: '' },
    { year: 2023, fullName: 'Taillon, Jameson', rmlTeam: 'Pilots', ip: '154.1', ab: '' },
    { year: 2023, fullName: 'Tapia, Raimel', rmlTeam: 'Z-Unowned', ip: '', ab: '148' },
    { year: 2023, fullName: 'Tatis Jr, Fernando', rmlTeam: 'Expos', ip: '', ab: '575' },
    { year: 2023, fullName: 'Tauchman, Mike', rmlTeam: 'Hornets', ip: '', ab: '337' },
    { year: 2023, fullName: 'Taveras, Leody', rmlTeam: 'Dodgers', ip: '', ab: '511' },
    { year: 2023, fullName: 'Taylor, Chris', rmlTeam: 'Blaze', ip: '', ab: '338' },
    { year: 2023, fullName: 'Taylor, Michael A', rmlTeam: 'Hornets', ip: '', ab: '355' },
    { year: 2023, fullName: 'Taylor, Tyrone', rmlTeam: 'Browns', ip: '', ab: '231' },
    { year: 2023, fullName: 'Teheran, Julio', rmlTeam: 'Z-Unowned', ip: '71.2', ab: '' },
    { year: 2023, fullName: 'Tellez, Rowdy', rmlTeam: 'Z-Unowned', ip: '', ab: '311' },
    { year: 2023, fullName: 'Thaiss, Matt', rmlTeam: 'Yellow Jackets', ip: '', ab: '262' },
    { year: 2023, fullName: 'Thielbar, Caleb', rmlTeam: 'TinCaps', ip: '30.2', ab: '' },
    { year: 2023, fullName: 'Thomas, Alek', rmlTeam: 'Bandits', ip: '', ab: '374' },
    { year: 2023, fullName: 'Thomas, Lane', rmlTeam: 'RockHounds', ip: '', ab: '628' },
    { year: 2023, fullName: 'Thompson, Mason', rmlTeam: 'Z-Unowned', ip: '54', ab: '' },
    { year: 2023, fullName: 'Thompson, Ryan', rmlTeam: 'Z-Unowned', ip: '30.2', ab: '' },
    { year: 2023, fullName: 'Thompson, Trayce', rmlTeam: 'Z-Unowned', ip: '', ab: '153' },
    { year: 2023, fullName: 'Thompson, Zack', rmlTeam: 'Stars', ip: '66.1', ab: '' },
    { year: 2023, fullName: 'Toglia, Michael', rmlTeam: 'Reds', ip: '', ab: '141' },
    { year: 2023, fullName: 'Tonkin, Michael', rmlTeam: 'Monarchs', ip: '80', ab: '' },
    { year: 2023, fullName: 'Topa, Justin', rmlTeam: 'Twins', ip: '69', ab: '' },
    { year: 2023, fullName: 'Torkelson, Spencer', rmlTeam: 'Pilots', ip: '', ab: '606' },
    { year: 2023, fullName: 'Torres, Gleyber', rmlTeam: 'Gypsies', ip: '', ab: '596' },
    { year: 2023, fullName: 'Toussaint, Touki', rmlTeam: 'Twins', ip: '87', ab: '' },
    { year: 2023, fullName: 'Tovar, Ezequiel', rmlTeam: 'Blaze', ip: '', ab: '581' },
    { year: 2023, fullName: 'Trejo, Alan', rmlTeam: 'Clown Princes', ip: '', ab: '207' },
    { year: 2023, fullName: 'Trevino, Jose', rmlTeam: 'Gypsies', ip: '', ab: '157' },
    { year: 2023, fullName: 'Triolo, Jared', rmlTeam: 'Yellow Jackets', ip: '', ab: '181' },
    { year: 2023, fullName: 'Trout, Mike', rmlTeam: 'Captains', ip: '', ab: '308' },
    { year: 2023, fullName: 'Tucker, Kyle', rmlTeam: 'Stars', ip: '', ab: '574' },
    { year: 2023, fullName: 'Turang, Brice', rmlTeam: 'Blaze', ip: '', ab: '404' },
    { year: 2023, fullName: 'Turner, Justin', rmlTeam: 'Stars', ip: '', ab: '558' },
    { year: 2023, fullName: 'Turner, Trea', rmlTeam: 'Blaze', ip: '', ab: '639' },
    { year: 2023, fullName: 'Urena, Jose', rmlTeam: 'Z-Unowned', ip: '44.2', ab: '' },
    { year: 2023, fullName: 'Urias, Julio', rmlTeam: 'Stars', ip: '117.1', ab: '' },
    { year: 2023, fullName: 'Urias, Luis', rmlTeam: 'Z-Unowned', ip: '', ab: '144' },
    { year: 2023, fullName: 'Urias, Ramon', rmlTeam: 'Reds', ip: '', ab: '360' },
    { year: 2023, fullName: 'Uribe, Abner', rmlTeam: 'River Dogs', ip: '30.2', ab: '' },
    { year: 2023, fullName: 'Urquidy, Jose', rmlTeam: 'TinCaps', ip: '63', ab: '' },
    { year: 2023, fullName: 'Urshela, Gio', rmlTeam: 'Twins', ip: '', ab: '214' },
    { year: 2023, fullName: 'Valdez, Enmanuel', rmlTeam: 'Bandits', ip: '', ab: '139' },
    { year: 2023, fullName: 'Valdez, Framber', rmlTeam: 'Twins', ip: '198', ab: '' },
    { year: 2023, fullName: 'Vargas, Ildemaro', rmlTeam: 'Captains', ip: '', ab: '262' },
    { year: 2023, fullName: 'Vargas, Miguel', rmlTeam: 'Dodgers', ip: '', ab: '256' },
    { year: 2023, fullName: 'Varland, Louie', rmlTeam: 'Pilots', ip: '68', ab: '' },
    { year: 2023, fullName: 'Varsho, Daulton', rmlTeam: 'TinCaps', ip: '', ab: '527' },
    { year: 2023, fullName: 'Vasquez, Andrew', rmlTeam: 'Z-Unowned', ip: '48.1', ab: '' },
    { year: 2023, fullName: 'Vaughn, Andrew', rmlTeam: 'Hornets', ip: '', ab: '566' },
    { year: 2023, fullName: 'Vazquez, Christian', rmlTeam: 'Knights', ip: '', ab: '327' },
    { year: 2023, fullName: 'Velazquez, Nelson', rmlTeam: 'Grays', ip: '', ab: '162' },
    { year: 2023, fullName: 'Verdugo, Alex', rmlTeam: 'Dodgers', ip: '', ab: '546' },
    { year: 2023, fullName: 'VerHagen, Drew', rmlTeam: 'Z-Unowned', ip: '61', ab: '' },
    { year: 2023, fullName: 'Verlander, Justin', rmlTeam: 'Gypsies', ip: '162.1', ab: '' },
    { year: 2023, fullName: 'Vesia, Alex', rmlTeam: 'Twins', ip: '49.2', ab: '' },
    { year: 2023, fullName: 'Vest, Will', rmlTeam: 'Knights', ip: '48.1', ab: '' },
    { year: 2023, fullName: 'Vientos, Mark', rmlTeam: 'Blaze', ip: '', ab: '218' },
    { year: 2023, fullName: 'Vierling, Matt', rmlTeam: 'Gypsies', ip: '', ab: '479' },
    { year: 2023, fullName: 'Villar, David', rmlTeam: 'Z-Unowned', ip: '', ab: '124' },
    { year: 2023, fullName: 'Vogelbach, Daniel', rmlTeam: 'Hornets', ip: '', ab: '275' },
    { year: 2023, fullName: 'Volpe, Anthony', rmlTeam: 'Hornets', ip: '', ab: '541' },
    { year: 2023, fullName: 'Votto, Joey', rmlTeam: 'Monarchs', ip: '', ab: '208' },
    { year: 2023, fullName: 'Wacha, Michael', rmlTeam: 'Blaze', ip: '134.1', ab: '' },
    { year: 2023, fullName: 'Wade Jr, LaMonte', rmlTeam: 'Hornets', ip: '', ab: '429' },
    { year: 2023, fullName: 'Wainwright, Adam', rmlTeam: 'Z-Unowned', ip: '101', ab: '' },
    { year: 2023, fullName: 'Waldichuk, Ken', rmlTeam: 'Pilots', ip: '141', ab: '' },
    { year: 2023, fullName: 'Walker, Christian', rmlTeam: 'Pelicans', ip: '', ab: '582' },
    { year: 2023, fullName: 'Walker, Jordan', rmlTeam: 'TinCaps', ip: '', ab: '420' },
    { year: 2023, fullName: 'Walker, Ryan', rmlTeam: 'Bandits', ip: '61.1', ab: '' },
    { year: 2023, fullName: 'Walker, Taijuan', rmlTeam: 'Dodgers', ip: '172.2', ab: '' },
    { year: 2023, fullName: 'Wallach, Chad', rmlTeam: 'Z-Unowned', ip: '', ab: '157' },
    { year: 2023, fullName: 'Wallner, Matt', rmlTeam: 'Blaze', ip: '', ab: '213' },
    { year: 2023, fullName: 'Walls, Taylor', rmlTeam: 'Hornets', ip: '', ab: '303' },
    { year: 2023, fullName: 'Walsh, Jared', rmlTeam: 'Z-Unowned', ip: '', ab: '104' },
    { year: 2023, fullName: 'Ward, Taylor', rmlTeam: 'Pelicans', ip: '', ab: '356' },
    { year: 2023, fullName: 'Waters, Drew', rmlTeam: 'Pilots', ip: '', ab: '302' },
    { year: 2023, fullName: 'Weathers, Ryan', rmlTeam: 'Colt .45s', ip: '57.2', ab: '' },
    { year: 2023, fullName: 'Weaver, Luke', rmlTeam: 'Monarchs', ip: '123.2', ab: '' },
    { year: 2023, fullName: 'Webb, Jacob', rmlTeam: 'Z-Unowned', ip: '53.2', ab: '' },
    { year: 2023, fullName: 'Webb, Logan', rmlTeam: 'Reds', ip: '216', ab: '' },
    { year: 2023, fullName: 'Weems, Jordan', rmlTeam: 'Z-Unowned', ip: '54.2', ab: '' },
    { year: 2023, fullName: 'Wells, Tyler', rmlTeam: 'Pelicans', ip: '118.2', ab: '' },
    { year: 2023, fullName: 'Wendle, Joey', rmlTeam: 'Pelicans', ip: '', ab: '297' },
    { year: 2023, fullName: 'Wentz, Joey', rmlTeam: 'Z-Unowned', ip: '105.2', ab: '' },
    { year: 2023, fullName: 'Wesneski, Hayden', rmlTeam: 'Stars', ip: '89.1', ab: '' },
    { year: 2023, fullName: 'Westburg, Jordan', rmlTeam: 'Bandits', ip: '', ab: '208' },
    { year: 2023, fullName: 'Wheeler, Zack', rmlTeam: 'Pilgrims', ip: '192', ab: '' },
    { year: 2023, fullName: 'White, Brendan', rmlTeam: 'Z-Unowned', ip: '40.2', ab: '' },
    { year: 2023, fullName: 'Whitlock, Garrett', rmlTeam: 'TinCaps', ip: '71.2', ab: '' },
    { year: 2023, fullName: 'Wiemer, Joey', rmlTeam: 'River Dogs', ip: '', ab: '367' },
    { year: 2023, fullName: 'Williams, Alika', rmlTeam: 'River Dogs', ip: '', ab: '101' },
    { year: 2023, fullName: 'Williams, Devin', rmlTeam: 'Stars', ip: '58.2', ab: '' },
    { year: 2023, fullName: 'Williams, Gavin', rmlTeam: 'Clown Princes', ip: '82', ab: '' },
    { year: 2023, fullName: 'Williams, Trevor', rmlTeam: 'Z-Unowned', ip: '144.1', ab: '' },
    { year: 2023, fullName: 'Williamson, Brandon', rmlTeam: 'Reds', ip: '117', ab: '' },
    { year: 2023, fullName: 'Wilson, Bryse', rmlTeam: 'Stars', ip: '76.2', ab: '' },
    { year: 2023, fullName: 'Wilson, Steven', rmlTeam: 'Blaze', ip: '53', ab: '' },
    { year: 2023, fullName: 'Winckowski, Josh', rmlTeam: 'Colt .45s', ip: '84.1', ab: '' },
    { year: 2023, fullName: 'Winker, Jesse', rmlTeam: 'Z-Unowned', ip: '', ab: '166' },
    { year: 2023, fullName: 'Winn, Masyn', rmlTeam: 'Pilgrims', ip: '', ab: '122' },
    { year: 2023, fullName: 'Wisdom, Patrick', rmlTeam: 'Hornets', ip: '', ab: '268' },
    { year: 2023, fullName: 'Wisely, Brett', rmlTeam: 'Pilots', ip: '', ab: '120' },
    { year: 2023, fullName: 'Witt, Bobby', rmlTeam: 'Twins', ip: '', ab: '641' },
    { year: 2023, fullName: 'Wong, Connor', rmlTeam: 'Pilots', ip: '', ab: '371' },
    { year: 2023, fullName: 'Wong, Kolten', rmlTeam: 'Z-Unowned', ip: '', ab: '224' },
    { year: 2023, fullName: 'Woo, Bryan', rmlTeam: 'Knights', ip: '87.2', ab: '' },
    { year: 2023, fullName: 'Wood, Alex', rmlTeam: 'Expos', ip: '97.2', ab: '' },
    { year: 2023, fullName: 'Woodruff, Brandon', rmlTeam: 'Pilgrims', ip: '67', ab: '' },
    { year: 2023, fullName: 'Wynns, Austin', rmlTeam: 'Pelicans', ip: '', ab: '130' },
    { year: 2023, fullName: 'Yarbrough, Ryan', rmlTeam: 'Pelicans', ip: '89.2', ab: '' },
    { year: 2023, fullName: 'Yastrzemski, Mike', rmlTeam: 'Gypsies', ip: '', ab: '330' },
    { year: 2023, fullName: 'Yates, Kirby', rmlTeam: 'Yellow Jackets', ip: '60.1', ab: '' },
    { year: 2023, fullName: 'Yelich, Christian', rmlTeam: 'Titans', ip: '', ab: '550' },
    { year: 2023, fullName: 'Yoshida, Masataka', rmlTeam: 'TinCaps', ip: '', ab: '537' },
    { year: 2023, fullName: 'Young, Alex', rmlTeam: 'Z-Unowned', ip: '53.2', ab: '' },
    { year: 2023, fullName: 'Young, Jacob', rmlTeam: 'Z-Unowned', ip: '', ab: '107' },
    { year: 2023, fullName: 'Zavala, Seby', rmlTeam: 'Z-Unowned', ip: '', ab: '175' },
    { year: 2023, fullName: 'Zunino, Mike', rmlTeam: 'Bandits', ip: '', ab: '124' },
];

function roundInnings(ip) {
    if (!ip) return null;
    if (ip.endsWith('.2')) {
        return Math.ceil(ip);
    } else {
        return Math.floor(ip);
    }
}

cardedPlayers.forEach((player, index) => {
    const nameParts = player.fullName.split(', ');
    cardedPlayers[index].abbrevName = nameParts[0] + ',' + nameParts[1][0];
    cardedPlayers[index].ip = roundInnings(player.ip);
    cardedPlayers[index].ab = parseInt(player.ab) || null;
});

module.exports = cardedPlayers;
