const cardedPlayers = [
    { name: 'Abbott,A', team: 'Clown Princes' },
    { name: 'Abrams,C', team: 'RockHounds' },
    { name: 'Abreu,A', team: 'River Dogs' },
    { name: 'Abreu,B', team: 'TinCaps' },
    { name: 'Abreu,J', team: 'Bandits' },
    { name: 'Acuna Jr,R', team: 'Grays' },
    { name: 'Adam,J', team: 'Gypsies' },
    { name: 'Adames,W', team: 'Knights' },
    { name: 'Adams,R', team: 'Z-Unowned' },
    { name: 'Adon,J', team: 'Z-Unowned' },
    { name: 'Aguilar,J', team: 'Z-Unowned' },
    { name: 'Ahmed,N', team: 'Monarchs' },
    { name: 'Albies,O', team: 'Titans' },
    { name: 'Alcantara,S', team: 'Bandits' },
    { name: 'Alexander,S', team: 'Z-Unowned' },
    { name: 'Allen,L', team: 'Expos' },
    { name: 'Allen,N', team: 'Browns' },
    { name: 'Almonte,Y', team: 'Z-Unowned' },
    { name: 'Alonso,P', team: 'Blaze' },
    { name: 'Altuve,J', team: 'Grays' },
    { name: 'Alu,J', team: 'Z-Unowned' },
    { name: 'Alvarado,J', team: 'Stars' },
    { name: 'Alvarez,F', team: 'Twins' },
    { name: 'Alvarez,Y', team: 'Grays' },
    { name: 'Alzolay,A', team: 'Blaze' },
    { name: 'Amaya,M', team: 'River Dogs' },
    { name: 'Anderson,B', team: 'Z-Unowned' },
    { name: 'Anderson,C', team: 'Z-Unowned' },
    { name: 'Anderson,N', team: 'Z-Unowned' },
    { name: 'Anderson,T', team: 'Captains' },
    { name: 'Anderson,T', team: 'Bandits' },
    { name: 'Andrus,E', team: 'River Dogs' },
    { name: 'Arcia,O', team: 'Bandits' },
    { name: 'Arenado,N', team: 'Dodgers' },
    { name: 'Arias,G', team: 'TinCaps' },
    { name: 'Armstrong,S', team: 'Z-Unowned' },
    { name: 'Arozarena,R', team: 'Monarchs' },
    { name: 'Arraez,L', team: 'Captains' },
    { name: 'Arroyo,C', team: 'Z-Unowned' },
    { name: 'Ashcraft,G', team: 'Titans' },
    { name: 'Assad,J', team: 'TinCaps' },
    { name: 'Baddoo,A', team: 'River Dogs' },
    { name: 'Bader,H', team: 'Titans' },
    { name: 'Bae,J', team: 'Stars' },
    { name: 'Baez,J', team: 'Pelicans' },
    { name: 'Bailey,P', team: 'Monarchs' },
    { name: 'Baker,B', team: 'Pilgrims' },
    { name: 'Banks,T', team: 'Z-Unowned' },
    { name: 'Bard,D', team: 'Z-Unowned' },
    { name: 'Barlow,S', team: 'Reds' },
    { name: 'Barnes,A', team: 'Z-Unowned' },
    { name: 'Barnhart,T', team: 'Z-Unowned' },
    { name: 'Barrero,J', team: 'Z-Unowned' },
    { name: 'Barria,J', team: 'Z-Unowned' },
    { name: 'Bassitt,C', team: 'Browns' },
    { name: 'Batten,M', team: 'Z-Unowned' },
    { name: 'Baty,B', team: 'RockHounds' },
    { name: 'Bauers,J', team: 'Z-Unowned' },
    { name: 'Baumann,M', team: 'Z-Unowned' },
    { name: 'Bautista,F', team: 'Grays' },
    { name: 'Beck,T', team: 'Z-Unowned' },
    { name: 'Bednar,D', team: 'Captains' },
    { name: 'Beeks,J', team: 'Hornets' },
    { name: 'Bell,J', team: 'Browns' },
    { name: 'Bellinger,C', team: 'Pilgrims' },
    { name: 'Bello,B', team: 'RockHounds' },
    { name: 'Belt,B', team: 'Yellow Jackets' },
    { name: 'Benintendi,A', team: 'Yellow Jackets' },
    { name: 'Benson,W', team: 'Z-Unowned' },
    { name: 'Bernardino,B', team: 'Z-Unowned' },
    { name: 'Berrios,J', team: 'Yellow Jackets' },
    { name: 'Berti,J', team: 'Reds' },
    { name: 'Bethancourt,C', team: 'Z-Unowned' },
    { name: 'Betts,M', team: 'Grays' },
    { name: 'Bibee,T', team: 'River Dogs' },
    { name: 'Bichette,B', team: 'Twins' },
    { name: 'Bickford,P', team: 'Titans' },
    { name: 'Bieber,S', team: 'Captains' },
    { name: 'Bielak,B', team: 'Z-Unowned' },
    { name: 'Biggio,C', team: 'Clown Princes' },
    { name: 'Bird,J', team: 'Z-Unowned' },
    { name: 'Blach,T', team: 'Z-Unowned' },
    { name: 'Blackburn,P', team: 'Titans' },
    { name: 'Blackmon,C', team: 'Pilgrims' },
    { name: 'Blanco,D', team: 'Z-Unowned' },
    { name: 'Bleday,J', team: 'Dodgers' },
    { name: 'Bogaerts,X', team: 'Colt .45s' },
    { name: 'Bohm,A', team: 'Blaze' },
    { name: 'Borucki,R', team: 'Z-Unowned' },
    { name: 'Boyd,M', team: 'Hornets' },
    { name: 'Bradish,K', team: 'Hornets' },
    { name: 'Bradley Jr,J', team: 'Z-Unowned' },
    { name: 'Bradley,T', team: 'Grays' },
    { name: 'Brash,M', team: 'Hornets' },
    { name: 'Brasier,R', team: 'Pelicans' },
    { name: 'Brazoban,H', team: 'Z-Unowned' },
    { name: 'Brebbia,J', team: 'Yellow Jackets' },
    { name: 'Bregman,A', team: 'Colt .45s' },
    { name: 'Brennan,W', team: 'Pilots' },
    { name: 'Brigham,J', team: 'Z-Unowned' },
    { name: 'Brito,J', team: 'Pilots' },
    { name: 'Brown,H', team: 'River Dogs' },
    { name: 'Brown,S', team: 'Knights' },
    { name: 'Bryant,K', team: 'Stars' },
    { name: 'Bummer,A', team: 'Z-Unowned' },
    { name: 'Burger,J', team: 'Yellow Jackets' },
    { name: 'Burke,B', team: 'TinCaps' },
    { name: 'Burleson,A', team: 'Bandits' },
    { name: 'Burnes,C', team: 'Dodgers' },
    { name: 'Butler,L', team: 'Colt .45s' },
    { name: 'Buxton,B', team: 'Bandits' },
    { name: 'Caballero,J', team: 'Z-Unowned' },
    { name: 'Cabrera,E', team: 'RockHounds' },
    { name: 'Cabrera,G', team: 'Z-Unowned' },
    { name: 'Cabrera,M', team: 'Expos' },
    { name: 'Cabrera,O', team: 'Bandits' },
    { name: 'Calhoun,K', team: 'Z-Unowned' },
    { name: 'Calhoun,W', team: 'Twins' },
    { name: 'Call,A', team: 'Dodgers' },
    { name: 'Campusano,L', team: 'RockHounds' },
    { name: 'Candelario,J', team: 'Pelicans' },
    { name: 'Canha,M', team: 'Captains' },
    { name: 'Canning,G', team: 'Dodgers' },
    { name: 'Cano,Y', team: 'Z-Unowned' },
    { name: 'Canzone,D', team: 'Bandits' },
    { name: 'Caratini,V', team: 'Z-Unowned' },
    { name: 'Carlson,D', team: 'TinCaps' },
    { name: 'Carpenter,K', team: 'Pilots' },
    { name: 'Carpenter,M', team: 'Z-Unowned' },
    { name: 'Carrasco,C', team: 'Z-Unowned' },
    { name: 'Carroll,C', team: 'Colt .45s' },
    { name: 'Casas,T', team: 'Reds' },
    { name: 'Castellanos,N', team: 'Gypsies' },
    { name: 'Castillo,L', team: 'Captains' },
    { name: 'Castro,H', team: 'Z-Unowned' },
    { name: 'Castro,M', team: 'Z-Unowned' },
    { name: 'Castro,R', team: 'Z-Unowned' },
    { name: 'Castro,W', team: 'TinCaps' },
    { name: 'Cave,J', team: 'Z-Unowned' },
    { name: 'Cease,D', team: 'Browns' },
    { name: 'Chafin,A', team: 'Reds' },
    { name: 'Chang,Y', team: 'Z-Unowned' },
    { name: 'Chapman,A', team: 'Clown Princes' },
    { name: 'Chapman,M', team: 'Blaze' },
    { name: 'Chargois,J', team: 'Expos' },
    { name: 'Chavez,J', team: 'Z-Unowned' },
    { name: 'Chirinos,Y', team: 'Blaze' },
    { name: 'Chisholm Jr,J', team: 'Pelicans' },
    { name: 'Choi,J', team: 'Z-Unowned' },
    { name: 'Cisnero,J', team: 'Z-Unowned' },
    { name: 'Civale,A', team: 'River Dogs' },
    { name: 'Clarke,T', team: 'Z-Unowned' },
    { name: 'Clase,E', team: 'Captains' },
    { name: 'Clemens,K', team: 'Z-Unowned' },
    { name: 'Clevinger,M', team: 'Gypsies' },
    { name: 'Cobb,A', team: 'Monarchs' },
    { name: 'Colas,O', team: 'RockHounds' },
    { name: 'Cole,G', team: 'Gypsies' },
    { name: 'Conforto,M', team: 'Pilgrims' },
    { name: 'Contreras,R', team: 'Reds' },
    { name: 'Contreras,W', team: 'Browns' },
    { name: 'Contreras,W', team: 'Colt .45s' },
    { name: 'Cooper,G', team: 'Twins' },
    { name: 'Corbin,P', team: 'Z-Unowned' },
    { name: 'Cordero,J', team: 'Z-Unowned' },
    { name: 'Correa,C', team: 'Clown Princes' },
    { name: 'Cortes,N', team: 'Clown Princes' },
    { name: 'Cosgrove,T', team: 'Z-Unowned' },
    { name: 'Coulombe,D', team: 'Gypsies' },
    { name: 'Crawford,B', team: 'Z-Unowned' },
    { name: 'Crawford,J', team: 'Titans' },
    { name: 'Crawford,K', team: 'Browns' },
    { name: 'Cron,C', team: 'Z-Unowned' },
    { name: 'Cronenworth,J', team: 'Hornets' },
    { name: 'Cruz,F', team: 'Z-Unowned' },
    { name: 'Cruz,N', team: 'Z-Unowned' },
    { name: 'Cuas,J', team: 'Z-Unowned' },
    { name: 'Cueto,J', team: 'Z-Unowned' },
    { name: 'Curry,X', team: 'Pilots' },
    { name: 'd\'Arnaud,T', team: 'Titans' },
    { name: 'Darvish,Y', team: 'Grays' },
    { name: 'Davidson,T', team: 'Z-Unowned' },
    { name: 'Davies,Z', team: 'Browns' },
    { name: 'Davis,H', team: 'RockHounds' },
    { name: 'Davis,J', team: 'Colt .45s' },
    { name: 'De La Cruz,B', team: 'Pilgrims' },
    { name: 'De La Cruz,E', team: 'RockHounds' },
    { name: 'De Los Santos,E', team: 'Stars' },
    { name: 'DeJong,P', team: 'Yellow Jackets' },
    { name: 'Delay,J', team: 'Z-Unowned' },
    { name: 'DeSclafani,A', team: 'Bandits' },
    { name: 'Detmers,R', team: 'Knights' },
    { name: 'Devenski,C', team: 'Z-Unowned' },
    { name: 'Devers,R', team: 'Knights' },
    { name: 'Diaz,A', team: 'Z-Unowned' },
    { name: 'Diaz,A', team: 'Bandits' },
    { name: 'Diaz,E', team: 'TinCaps' },
    { name: 'Diaz,J', team: 'Colt .45s' },
    { name: 'Diaz,Y', team: 'Twins' },
    { name: 'Diaz,Y', team: 'River Dogs' },
    { name: 'Dickerson,C', team: 'Z-Unowned' },
    { name: 'Diekman,J', team: 'Z-Unowned' },
    { name: 'Dominguez,S', team: 'River Dogs' },
    { name: 'Donaldson,J', team: 'Z-Unowned' },
    { name: 'Donovan,B', team: 'Pilots' },
    { name: 'Doval,C', team: 'River Dogs' },
    { name: 'Doyle,B', team: 'River Dogs' },
    { name: 'Drury,B', team: 'Stars' },
    { name: 'Duarte,D', team: 'Z-Unowned' },
    { name: 'Dubon,M', team: 'Twins' },
    { name: 'Duffy,M', team: 'Z-Unowned' },
    { name: 'Dunning,D', team: 'Captains' },
    { name: 'Duran,E', team: 'Monarchs' },
    { name: 'Duran,J', team: 'Grays' },
    { name: 'Duran,J', team: 'River Dogs' },
    { name: 'Duvall,A', team: 'Gypsies' },
    { name: 'Edman,T', team: 'Yellow Jackets' },
    { name: 'Edwards Jr,C', team: 'Reds' },
    { name: 'Eflin,Z', team: 'Expos' },
    { name: 'Elder,B', team: 'Twins' },
    { name: 'Encarnacion-Strand,C', team: 'Stars' },
    { name: 'Englert,M', team: 'Z-Unowned' },
    { name: 'Eovaldi,N', team: 'Colt .45s' },
    { name: 'Erceg,L', team: 'Z-Unowned' },
    { name: 'Escobar,E', team: 'Z-Unowned' },
    { name: 'Espinal,S', team: 'Gypsies' },
    { name: 'Estevez,C', team: 'Knights' },
    { name: 'Estrada,T', team: 'Pilgrims' },
    { name: 'Faedo,A', team: 'Pelicans' },
    { name: 'Fairbanks,P', team: 'Knights' },
    { name: 'Fairchild,S', team: 'Bandits' },
    { name: 'Falter,B', team: 'Knights' },
    { name: 'Farmer,B', team: 'Yellow Jackets' },
    { name: 'Farmer,K', team: 'Colt .45s' },
    { name: 'Feltner,R', team: 'Z-Unowned' },
    { name: 'Ferguson,C', team: 'Stars' },
    { name: 'Fermin,F', team: 'Z-Unowned' },
    { name: 'Ferrer,J', team: 'Z-Unowned' },
    { name: 'Finnegan,K', team: 'Clown Princes' },
    { name: 'Flaherty,J', team: 'Pilgrims' },
    { name: 'Flexen,C', team: 'Z-Unowned' },
    { name: 'Flores,W', team: 'Colt .45s' },
    { name: 'Floro,D', team: 'Z-Unowned' },
    { name: 'Foley,J', team: 'Z-Unowned' },
    { name: 'Ford,M', team: 'Z-Unowned' },
    { name: 'Fortes,N', team: 'Hornets' },
    { name: 'Fraley,J', team: 'Pilots' },
    { name: 'France,J', team: 'Z-Unowned' },
    { name: 'France,T', team: 'Z-Unowned' },
    { name: 'Franco,W', team: 'Pilgrims' },
    { name: 'Frazier,A', team: 'RockHounds' },
    { name: 'Freeland,K', team: 'Z-Unowned' },
    { name: 'Freeman,F', team: 'Dodgers' },
    { name: 'Freeman,T', team: 'Titans' },
    { name: 'Frelick,S', team: 'Twins' },
    { name: 'Fried,M', team: 'Dodgers' },
    { name: 'Friedl,T', team: 'Gypsies' },
    { name: 'Fry,D', team: 'Z-Unowned' },
    { name: 'Fujinami,S', team: 'Z-Unowned' },
    { name: 'Fulmer,M', team: 'Twins' },
    { name: 'Gallagher,C', team: 'Z-Unowned' },
    { name: 'Gallegos,G', team: 'Expos' },
    { name: 'Gallen,Z', team: 'Yellow Jackets' },
    { name: 'Gallo,J', team: 'Browns' },
    { name: 'Garcia,A', team: 'Expos' },
    { name: 'Garcia,A', team: 'Z-Unowned' },
    { name: 'Garcia,L', team: 'Knights' },
    { name: 'Garcia,L', team: 'Z-Unowned' },
    { name: 'Garcia,M', team: 'Pilots' },
    { name: 'Garcia,Y', team: 'Z-Unowned' },
    { name: 'Garrett,B', team: 'Blaze' },
    { name: 'Garrett,S', team: 'Gypsies' },
    { name: 'Garver,M', team: 'Grays' },
    { name: 'Gausman,K', team: 'Titans' },
    { name: 'Gelof,Z', team: 'Reds' },
    { name: 'German,D', team: 'Knights' },
    { name: 'Gibaut,I', team: 'Z-Unowned' },
    { name: 'Gibson,K', team: 'Z-Unowned' },
    { name: 'Gilbert,L', team: 'RockHounds' },
    { name: 'Gimenez,A', team: 'Blaze' },
    { name: 'Ginkel,K', team: 'Z-Unowned' },
    { name: 'Giolito,L', team: 'River Dogs' },
    { name: 'Glasnow,T', team: 'Grays' },
    { name: 'Goldschmidt,P', team: 'Colt .45s' },
    { name: 'Gomber,A', team: 'Stars' },
    { name: 'Gomes,Y', team: 'Titans' },
    { name: 'Gonsolin,T', team: 'Titans' },
    { name: 'Gonzales,M', team: 'Z-Unowned' },
    { name: 'Gonzales,N', team: 'Pelicans' },
    { name: 'Gonzalez,O', team: 'River Dogs' },
    { name: 'Gonzalez,V', team: 'Z-Unowned' },
    { name: 'Gore,M', team: 'Hornets' },
    { name: 'Gorman,N', team: 'Rockhounds' },
    { name: 'Gott,T', team: 'Z-Unowned' },
    { name: 'Grandal,Y', team: 'Monarchs' },
    { name: 'Graterol,B', team: 'River Dogs' },
    { name: 'Graveman,K', team: 'Hornets' },
    { name: 'Gray,J', team: 'Reds' },
    { name: 'Gray,J', team: 'RockHounds' },
    { name: 'Gray,S', team: 'Grays' },
    { name: 'Greene,H', team: 'Clown Princes' },
    { name: 'Greene,R', team: 'Twins' },
    { name: 'Greinke,Z', team: 'Z-Unowned' },
    { name: 'Grichuk,R', team: 'Clown Princes' },
    { name: 'Grisham,T', team: 'TinCaps' },
    { name: 'Grossman,R', team: 'Clown Princes' },
    { name: 'Grove,M', team: 'Expos' },
    { name: 'Guerrero Jr,V', team: 'Pilgrims' },
    { name: 'Guillorme,L', team: 'Z-Unowned' },
    { name: 'Gurriel Jr,L', team: 'RockHounds' },
    { name: 'Gurriel,Y', team: 'Expos' },
    { name: 'Haase,E', team: 'Z-Unowned' },
    { name: 'Hader,J', team: 'Colt .45s' },
    { name: 'Hamilton,I', team: 'Z-Unowned' },
    { name: 'Hampson,G', team: 'Reds' },
    { name: 'Hand,B', team: 'Z-Unowned' },
    { name: 'Haniger,M', team: 'Z-Unowned' },
    { name: 'Happ,I', team: 'Reds' },
    { name: 'Harper,B', team: 'Grays' },
    { name: 'Harris II,M', team: 'Pelicans' },
    { name: 'Harris,H', team: 'Z-Unowned' },
    { name: 'Harrison,J', team: 'Z-Unowned' },
    { name: 'Harvey,H', team: 'Clown Princes' },
    { name: 'Hayes,K', team: 'Monarchs' },
    { name: 'Hays,A', team: 'Stars' },
    { name: 'Heaney,A', team: 'Browns' },
    { name: 'Hedges,A', team: 'Z-Unowned' },
    { name: 'Heim,J', team: 'Blaze' },
    { name: 'Helsley,R', team: 'Knights' },
    { name: 'Henderson,G', team: 'Monarchs' },
    { name: 'Hendricks,K', team: 'Reds' },
    { name: 'Henry,T', team: 'Yellow Jackets' },
    { name: 'Hentges,S', team: 'River Dogs' },
    { name: 'Hernandez,C', team: 'Z-Unowned' },
    { name: 'Hernandez,E', team: 'Captains' },
    { name: 'Hernandez,J', team: 'Z-Unowned' },
    { name: 'Hernandez,J', team: 'Z-Unowned' },
    { name: 'Hernandez,T', team: 'Browns' },
    { name: 'Herrera,J', team: 'Z-Unowned' },
    { name: 'Heyward,J', team: 'River Dogs' },
    { name: 'Hicks,A', team: 'Z-Unowned' },
    { name: 'Hicks,J', team: 'Grays' },
    { name: 'Higashioka,K', team: 'Clown Princes' },
    { name: 'Hill,R', team: 'Z-Unowned' },
    { name: 'Hill,T', team: 'Captains' },
    { name: 'Hoeing,B', team: 'Z-Unowned' },
    { name: 'Hoerner,N', team: 'Browns' },
    { name: 'Hoffman,J', team: 'Z-Unowned' },
    { name: 'Holderman,C', team: 'Bandits' },
    { name: 'Holmes,C', team: 'TinCaps' },
    { name: 'Holton,T', team: 'Z-Unowned' },
    { name: 'Honeywell Jr,B', team: 'Yellow Jackets' },
    { name: 'Houck,T', team: 'Blaze' },
    { name: 'Houser,A', team: 'Knights' },
    { name: 'Hudson,D', team: 'Captains' },
    { name: 'Ibanez,A', team: 'Z-Unowned' },
    { name: 'Iglesias,R', team: 'Z-Unowned' },
    { name: 'India,J', team: 'Pilgrims' },
    { name: 'Irvin,C', team: 'Hornets' },
    { name: 'Irvin,J', team: 'Z-Unowned' },
    { name: 'Isbel,K', team: 'Z-Unowned' },
    { name: 'Jackson,A', team: 'Z-Unowned' },
    { name: 'Jackson,L', team: 'Z-Unowned' },
    { name: 'Jankowski,T', team: 'Gypsies' },
    { name: 'Jansen,D', team: 'Pilgrims' },
    { name: 'Jansen,K', team: 'Z-Unowned' },
    { name: 'Javier,C', team: 'River Dogs' },
    { name: 'Jax,G', team: 'Reds' },
    { name: 'Jeffers,R', team: 'Colt .45s' },
    { name: 'Jimenez,E', team: 'Monarchs' },
    { name: 'Jimenez,J', team: 'Pelicans' },
    { name: 'Joe,C', team: 'Gypsies' },
    { name: 'Johnson,P', team: 'Z-Unowned' },
    { name: 'Jones,N', team: 'Dodgers' },
    { name: 'Judge,A', team: 'Colt .45s' },
    { name: 'Julien,E', team: 'Yellow Jackets' },
    { name: 'Julks,C', team: 'Z-Unowned' },
    { name: 'Jung,J', team: 'Browns' },
    { name: 'Junis,J', team: 'Bandits' },
    { name: 'Kahnle,T', team: 'Z-Unowned' },
    { name: 'Kaprielian,J', team: 'Browns' },
    { name: 'Karinchak,J', team: 'Z-Unowned' },
    { name: 'Kelenic,J', team: 'Twins' },
    { name: 'Keller,M', team: 'RockHounds' },
    { name: 'Kelly,C', team: 'Browns' },
    { name: 'Kelly,J', team: 'Z-Unowned' },
    { name: 'Kelly,K', team: 'Z-Unowned' },
    { name: 'Kelly,M', team: 'Gypsies' },
    { name: 'Kemp,T', team: 'Z-Unowned' },
    { name: 'Kepler,M', team: 'Yellow Jackets' },
    { name: 'Kershaw,C', team: 'Gypsies' },
    { name: 'Kiermaier,K', team: 'Blaze' },
    { name: 'Kikuchi,Y', team: 'Z-Unowned' },
    { name: 'Kim,H', team: 'Grays' },
    { name: 'Kimbrel,C', team: 'Titans' },
    { name: 'Kiner-Falefa,I', team: 'Expos' },
    { name: 'King,J', team: 'Z-Unowned' },
    { name: 'King,M', team: 'Grays' },
    { name: 'Kirby,G', team: 'Colt .45s' },
    { name: 'Kirilloff,A', team: 'Titans' },
    { name: 'Kirk,A', team: 'Hornets' },
    { name: 'Knizner,A', team: 'Expos' },
    { name: 'Koch,M', team: 'Z-Unowned' },
    { name: 'Kopech,M', team: 'RockHounds' },
    { name: 'Kremer,D', team: 'Pilots' },
    { name: 'Kwan,S', team: 'River Dogs' },
    { name: 'Lambert,J', team: 'Z-Unowned' },
    { name: 'Lambert,P', team: 'Z-Unowned' },
    { name: 'Lange,A', team: 'Pilots' },
    { name: 'Langeliers,S', team: 'Knights' },
    { name: 'Larnach,T', team: 'Dodgers' },
    { name: 'Laureano,R', team: 'Captains' },
    { name: 'Law,D', team: 'Z-Unowned' },
    { name: 'Lawrence,J', team: 'Z-Unowned' },
    { name: 'LeClerc,J', team: 'Titans' },
    { name: 'Leiter Jr,M', team: 'RockHounds' },
    { name: 'Lemahieu,D', team: 'Z-Unowned' },
    { name: 'Leone,D', team: 'Z-Unowned' },
    { name: 'Lewis,R', team: 'RockHounds' },
    { name: 'Liberatore,M', team: 'Rockhounds' },
    { name: 'Lindor,F', team: 'Dodgers' },
    { name: 'Littell,Z', team: 'Z-Unowned' },
    { name: 'Lively,B', team: 'Z-Unowned' },
    { name: 'Llovera,M', team: 'Z-Unowned' },
    { name: 'Long,S', team: 'Z-Unowned' },
    { name: 'Longoria,E', team: 'Z-Unowned' },
    { name: 'Lopez,J', team: 'Z-Unowned' },
    { name: 'Lopez,N', team: 'TinCaps' },
    { name: 'Lopez,P', team: 'Captains' },
    { name: 'Lopez,R', team: 'Captains' },
    { name: 'Lorenzen,M', team: 'Gypsies' },
    { name: 'Loup,A', team: 'Z-Unowned' },
    { name: 'Lowe,B', team: 'Stars' },
    { name: 'Lowe,J', team: 'Knights' },
    { name: 'Lowe,N', team: 'Stars' },
    { name: 'Lugo,S', team: 'Stars' },
    { name: 'Luzardo,J', team: 'Monarchs' },
    { name: 'Lyles,J', team: 'Z-Unowned' },
    { name: 'Lynn,L', team: 'Z-Unowned' },
    { name: 'Machado,A', team: 'Z-Unowned' },
    { name: 'Machado,M', team: 'Gypsies' },
    { name: 'Madrigal,N', team: 'Bandits' },
    { name: 'Maeda,K', team: 'Expos' },
    { name: 'Maile,L', team: 'Z-Unowned' },
    { name: 'Maldonado,M', team: 'Z-Unowned' },
    { name: 'Manaea,S', team: 'Clown Princes' },
    { name: 'Mancini,T', team: 'Z-Unowned' },
    { name: 'Manning,M', team: 'Knights' },
    { name: 'Manoah,A', team: 'Blaze' },
    { name: 'Mantiply,J', team: 'Z-Unowned' },
    { name: 'Marcano,T', team: 'Z-Unowned' },
    { name: 'Margot,M', team: 'Z-Unowned' },
    { name: 'Marinaccio,R', team: 'Clown Princes' },
    { name: 'Marsh,A', team: 'Z-Unowned' },
    { name: 'Marsh,B', team: 'Monarchs' },
    { name: 'Marte,K', team: 'Dodgers' },
    { name: 'Marte,N', team: 'Browns' },
    { name: 'Marte,S', team: 'Z-Unowned' },
    { name: 'Marte,Y', team: 'Z-Unowned' },
    { name: 'Martin,C', team: 'Grays' },
    { name: 'Martinez,J', team: 'Captains' },
    { name: 'Martinez,N', team: 'Twins' },
    { name: 'Martinez,S', team: 'Z-Unowned' },
    { name: 'Massey,M', team: 'Colt .45s' },
    { name: 'Mastrobuoni,M', team: 'Z-Unowned' },
    { name: 'Mateo,J', team: 'Monarchs' },
    { name: 'Maton,N', team: 'Z-Unowned' },
    { name: 'Maton,P', team: 'Z-Unowned' },
    { name: 'Matos,L', team: 'Yellow Jackets' },
    { name: 'Matz,S', team: 'Hornets' },
    { name: 'Mauricio,R', team: 'Knights' },
    { name: 'May,T', team: 'Z-Unowned' },
    { name: 'Mayza,T', team: 'Pilgrims' },
    { name: 'McCann,J', team: 'Z-Unowned' },
    { name: 'McCarthy,J', team: 'Monarchs' },
    { name: 'McClanahan,S', team: 'Captains' },
    { name: 'McCormick,C', team: 'Yellow Jackets' },
    { name: 'McCutchen,A', team: 'Expos' },
    { name: 'McGough,S', team: 'Z-Unowned' },
    { name: 'McGuire,R', team: 'Z-Unowned' },
    { name: 'McHugh,C', team: 'Z-Unowned' },
    { name: 'McKenna,R', team: 'Z-Unowned' },
    { name: 'McKinney,B', team: 'Z-Unowned' },
    { name: 'McKinstry,Z', team: 'Z-Unowned' },
    { name: 'McLain,M', team: 'Titans' },
    { name: 'McMahon,R', team: 'Clown Princes' },
    { name: 'McNeil,J', team: 'Twins' },
    { name: 'Meadows,P', team: 'Reds' },
    { name: 'Medina,L', team: 'River Dogs' },
    { name: 'Megill,T', team: 'Z-Unowned' },
    { name: 'Megill,T', team: 'Titans' },
    { name: 'Mejia,F', team: 'Z-Unowned' },
    { name: 'Melendez,M', team: 'Knights' },
    { name: 'Meneses,J', team: 'Bandits' },
    { name: 'Merrifield,W', team: 'Expos' },
    { name: 'Merryweather,J', team: 'Z-Unowned' },
    { name: 'Meyers,J', team: 'Colt .45s' },
    { name: 'Middleton,K', team: 'Z-Unowned' },
    { name: 'Mikolas,M', team: 'Colt .45s' },
    { name: 'Miley,W', team: 'Monarchs' },
    { name: 'Miller,B', team: 'Grays' },
    { name: 'Miller,B', team: 'Pilgrims' },
    { name: 'Miller,O', team: 'Z-Unowned' },
    { name: 'Miller,S', team: 'Z-Unowned' },
    { name: 'Milner,H', team: 'Captains' },
    { name: 'Minter,A', team: 'Pelicans' },
    { name: 'Miranda,J', team: 'Pilots' },
    { name: 'Mlodzinski,C', team: 'Z-Unowned' },
    { name: 'Moll,S', team: 'Expos' },
    { name: 'Monasterio,A', team: 'Z-Unowned' },
    { name: 'Moncada,Y', team: 'Stars' },
    { name: 'Moniak,M', team: 'Reds' },
    { name: 'Montero,E', team: 'Clown Princes' },
    { name: 'Montero,R', team: 'Z-Unowned' },
    { name: 'Montgomery,J', team: 'Monarchs' },
    { name: 'Moore,D', team: 'Knights' },
    { name: 'Moore,M', team: 'Browns' },
    { name: 'Moran,J', team: 'Clown Princes' },
    { name: 'Morel,C', team: 'Yellow Jackets' },
    { name: 'Moreno,G', team: 'TinCaps' },
    { name: 'Moreta,D', team: 'Knights' },
    { name: 'Morgan,E', team: 'Pilots' },
    { name: 'Morton,C', team: 'Expos' },
    { name: 'Mountcastle,R', team: 'RockHounds' },
    { name: 'Moustakas,M', team: 'Z-Unowned' },
    { name: 'Muller,K', team: 'Z-Unowned' },
    { name: 'Mullins,C', team: 'Dodgers' },
    { name: 'Muncy,M', team: 'Grays' },
    { name: 'Munoz,A', team: 'Knights' },
    { name: 'Murphy,S', team: 'Yellow Jackets' },
    { name: 'Murphy,T', team: 'Colt .45s' },
    { name: 'Musgrove,J', team: 'Pelicans' },
    { name: 'Myers,W', team: 'Z-Unowned' },
    { name: 'Nardi,A', team: 'Gypsies' },
    { name: 'Narvaez,O', team: 'Z-Unowned' },
    { name: 'Naylor,B', team: 'Stars' },
    { name: 'Naylor,J', team: 'Captains' },
    { name: 'Nelson,K', team: 'Pilots' },
    { name: 'Nelson,R', team: 'Knights' },
    { name: 'Neris,H', team: 'Pelicans' },
    { name: 'Neto,Z', team: 'Grays' },
    { name: 'Newman,K', team: 'Gypsies' },
    { name: 'Nimmo,B', team: 'Pilgrims' },
    { name: 'Noda,R', team: 'Gypsies' },
    { name: 'Nola,A', team: 'Yellow Jackets' },
    { name: 'Nola,A', team: 'Z-Unowned' },
    { name: 'Nootbaar,L', team: 'Blaze' },
    { name: 'Ober,B', team: 'Clown Princes' },
    { name: 'Odor,R', team: 'Z-Unowned' },
    { name: 'O\'Hearn,R', team: 'Z-Unowned' },
    { name: 'O\'Hoppe,L', team: 'Pilgrims' },
    { name: 'Ohtani,S', team: 'Titans' },
    { name: 'Okert,S', team: 'Dodgers' },
    { name: 'Olivares,E', team: 'Reds' },
    { name: 'Olson,M', team: 'Reds' },
    { name: 'Olson,R', team: 'Gypsies' },
    { name: 'O\'Neill,T', team: 'Titans' },
    { name: 'Ortega,R', team: 'Z-Unowned' },
    { name: 'Ortiz,L', team: 'Hornets' },
    { name: 'Ottavino,A', team: 'Z-Unowned' },
    { name: 'Outman,J', team: 'Pilots' },
    { name: 'Oviedo,J', team: 'River Dogs' },
    { name: 'Ozuna,M', team: 'Pilgrims' },
    { name: 'Pagan,E', team: 'Titans' },
    { name: 'Palacios,J', team: 'Z-Unowned' },
    { name: 'Pallante,A', team: 'Knights' },
    { name: 'Paredes,I', team: 'Pelicans' },
    { name: 'Pasquantino,V', team: 'TinCaps' },
    { name: 'Paxton,J', team: 'Pilgrims' },
    { name: 'Payamps,J', team: 'Expos' },
    { name: 'Pearson,N', team: 'Grays' },
    { name: 'Pederson,J', team: 'Z-Unowned' },
    { name: 'Peguero,E', team: 'Z-Unowned' },
    { name: 'Peguero,L', team: 'Pilgrims' },
    { name: 'Pena,J', team: 'Pilots' },
    { name: 'Peralta,D', team: 'Z-Unowned' },
    { name: 'Peralta,F', team: 'Stars' },
    { name: 'Peralta,W', team: 'Z-Unowned' },
    { name: 'Peraza,O', team: 'Stars' },
    { name: 'Perdomo,A', team: 'Z-Unowned' },
    { name: 'Perdomo,G', team: 'Bandits' },
    { name: 'Perez,C', team: 'Z-Unowned' },
    { name: 'Perez,C', team: 'Pilots' },
    { name: 'Perez,E', team: 'Stars' },
    { name: 'Perez,M', team: 'Z-Unowned' },
    { name: 'Perez,S', team: 'Gypsies' },
    { name: 'Perkins,B', team: 'Z-Unowned' },
    { name: 'Peterson,D', team: 'Z-Unowned' },
    { name: 'Peterson,J', team: 'Z-Unowned' },
    { name: 'Pfaadt,B', team: 'Pilgrims' },
    { name: 'Pham,T', team: 'Expos' },
    { name: 'Phillips,E', team: 'Gypsies' },
    { name: 'Pillar,K', team: 'Pelicans' },
    { name: 'Pinto,R', team: 'Z-Unowned' },
    { name: 'Pivetta,N', team: 'Clown Princes' },
    { name: 'Poche,C', team: 'Hornets' },
    { name: 'Polanco,J', team: 'Pilgrims' },
    { name: 'Pollock,A', team: 'Z-Unowned' },
    { name: 'Pratto,N', team: 'Knights' },
    { name: 'Pressly,R', team: 'Pilots' },
    { name: 'Profar,J', team: 'Twins' },
    { name: 'Pruitt,A', team: 'TinCaps' },
    { name: 'Puk,A', team: 'RockHounds' },
    { name: 'Quantrill,C', team: 'Z-Unowned' },
    { name: 'Quintana,J', team: 'Grays' },
    { name: 'Ragans,C', team: 'Blaze' },
    { name: 'Raleigh,C', team: 'Stars' },
    { name: 'Raley,B', team: 'Expos' },
    { name: 'Raley,L', team: 'Gypsies' },
    { name: 'Ramirez,E', team: 'Z-Unowned' },
    { name: 'Ramirez,H', team: 'Titans' },
    { name: 'Ramirez,J', team: 'Pilgrims' },
    { name: 'Ramirez,N', team: 'Z-Unowned' },
    { name: 'Ramirez,Y', team: 'Z-Unowned' },
    { name: 'Rea,C', team: 'Z-Unowned' },
    { name: 'Realmuto,J', team: 'Pelicans' },
    { name: 'Refsnyder,R', team: 'Reds' },
    { name: 'Remillard,Z', team: 'Z-Unowned' },
    { name: 'Rendon,A', team: 'Captains' },
    { name: 'Renfroe,H', team: 'Z-Unowned' },
    { name: 'Rengifo,L', team: 'RockHounds' },
    { name: 'Reyes,P', team: 'Z-Unowned' },
    { name: 'Reynolds,B', team: 'Captains' },
    { name: 'Richards,T', team: 'Z-Unowned' },
    { name: 'Riley,A', team: 'Titans' },
    { name: 'Rivas,A', team: 'Z-Unowned' },
    { name: 'Rivera,E', team: 'Browns' },
    { name: 'Rizzo,A', team: 'Yellow Jackets' },
    { name: 'Robert Jr,L', team: 'RockHounds' },
    { name: 'Robertson,D', team: 'Browns' },
    { name: 'Robles,V', team: 'Z-Unowned' },
    { name: 'Rodgers,B', team: 'Stars' },
    { name: 'Rodon,C', team: 'Blaze' },
    { name: 'Rodriguez,E', team: 'Hornets' },
    { name: 'Rodriguez,E', team: 'RockHounds' },
    { name: 'Rodriguez,G', team: 'RockHounds' },
    { name: 'Rodriguez,J', team: 'Grays' },
    { name: 'Rogers,J', team: 'Bandits' },
    { name: 'Rogers,T', team: 'Clown Princes' },
    { name: 'Rogers,T', team: 'Browns' },
    { name: 'Rojas,J', team: 'Stars' },
    { name: 'Rojas,J', team: 'Z-Unowned' },
    { name: 'Rojas,M', team: 'Twins' },
    { name: 'Romano,J', team: 'Knights' },
    { name: 'Rooker,B', team: 'Bandits' },
    { name: 'Rosario,A', team: 'Stars' },
    { name: 'Rosario,E', team: 'Pilgrims' },
    { name: 'Rucker,M', team: 'Z-Unowned' },
    { name: 'Ruiz,E', team: 'Knights' },
    { name: 'Ruiz,J', team: 'Z-Unowned' },
    { name: 'Ruiz,K', team: 'Bandits' },
    { name: 'Rutschman,A', team: 'Grays' },
    { name: 'Ryan,J', team: 'Blaze' },
    { name: 'Ryu,H', team: 'Bandits' },
    { name: 'Sabol,B', team: 'Pilots' },
    { name: 'Sale,C', team: 'Grays' },
    { name: 'Sanchez,C', team: 'Z-Unowned' },
    { name: 'Sanchez,G', team: 'Monarchs' },
    { name: 'Sanchez,J', team: 'Reds' },
    { name: 'Sandlin,N', team: 'Hornets' },
    { name: 'Sandoval,P', team: 'TinCaps' },
    { name: 'Santana,C', team: 'Monarchs' },
    { name: 'Santander,A', team: 'Pelicans' },
    { name: 'Santos,G', team: 'Reds' },
    { name: 'Saucedo,T', team: 'Z-Unowned' },
    { name: 'Sborz,J', team: 'Z-Unowned' },
    { name: 'Schanuel,N', team: 'Blaze' },
    { name: 'Scherzer,M', team: 'Yellow Jackets' },
    { name: 'Schmidt,C', team: 'Clown Princes' },
    { name: 'Schmitt,C', team: 'Knights' },
    { name: 'Schneider,D', team: 'Z-Unowned' },
    { name: 'Scholtens,J', team: 'Z-Unowned' },
    { name: 'Schoop,J', team: 'Z-Unowned' },
    { name: 'Schreiber,J', team: 'Bandits' },
    { name: 'Schwarber,K', team: 'Dodgers' },
    { name: 'Scott,T', team: 'Twins' },
    { name: 'Seabold,C', team: 'Z-Unowned' },
    { name: 'Seager,C', team: 'Reds' },
    { name: 'Sears,J', team: 'Pilots' },
    { name: 'Segura,J', team: 'Reds' },
    { name: 'Semien,M', team: 'Yellow Jackets' },
    { name: 'Senga,K', team: 'TinCaps' },
    { name: 'Senzel,N', team: 'Browns' },
    { name: 'Severino,L', team: 'Reds' },
    { name: 'Sewald,P', team: 'Pilots' },
    { name: 'Shaw,B', team: 'Z-Unowned' },
    { name: 'Sheehan,E', team: 'Titans' },
    { name: 'Sheets,G', team: 'TinCaps' },
    { name: 'Short,Z', team: 'Z-Unowned' },
    { name: 'Shreve,C', team: 'Z-Unowned' },
    { name: 'Shuster,J', team: 'Yellow Jackets' },
    { name: 'Sims,L', team: 'Z-Unowned' },
    { name: 'Singer,B', team: 'Z-Unowned' },
    { name: 'Siri,J', team: 'RockHounds' },
    { name: 'Skubal,T', team: 'Pilots' },
    { name: 'Slater,A', team: 'Z-Unowned' },
    { name: 'Smith,D', team: 'RockHounds' },
    { name: 'Smith,D', team: 'Pilots' },
    { name: 'Smith,J', team: 'Hornets' },
    { name: 'Smith,K', team: 'Z-Unowned' },
    { name: 'Smith,P', team: 'Clown Princes' },
    { name: 'Smith,W', team: 'Captains' },
    { name: 'Smith,W', team: 'Grays' },
    { name: 'Smyly,D', team: 'Stars' },
    { name: 'Snell,B', team: 'Blaze' },
    { name: 'Soderstrom,T', team: 'River Dogs' },
    { name: 'Solano,D', team: 'Clown Princes' },
    { name: 'Soler,J', team: 'RockHounds' },
    { name: 'Soriano,J', team: 'Z-Unowned' },
    { name: 'Sosa,E', team: 'Yellow Jackets' },
    { name: 'Sosa,L', team: 'Z-Unowned' },
    { name: 'Soto,G', team: 'RockHounds' },
    { name: 'Soto,J', team: 'Stars' },
    { name: 'Speier,G', team: 'Gypsies' },
    { name: 'Springer,G', team: 'Monarchs' },
    { name: 'Stallings,J', team: 'Z-Unowned' },
    { name: 'Stanek,R', team: 'Yellow Jackets' },
    { name: 'Stanton,G', team: 'Dodgers' },
    { name: 'Steele,J', team: 'Reds' },
    { name: 'Steer,S', team: 'Expos' },
    { name: 'Stephan,T', team: 'River Dogs' },
    { name: 'Stephenson,R', team: 'Z-Unowned' },
    { name: 'Stephenson,T', team: 'Expos' },
    { name: 'Stewart,D', team: 'Z-Unowned' },
    { name: 'Story,T', team: 'Colt .45s' },
    { name: 'Stott,B', team: 'Twins' },
    { name: 'Strahm,M', team: 'Stars' },
    { name: 'Stratton,C', team: 'Reds' },
    { name: 'Straw,M', team: 'TinCaps' },
    { name: 'Strider,S', team: 'Hornets' },
    { name: 'Stripling,R', team: 'Z-Unowned' },
    { name: 'Stroman,M', team: 'Pilgrims' },
    { name: 'Strzelecki,P', team: 'Z-Unowned' },
    { name: 'Stubbs,G', team: 'Gypsies' },
    { name: 'Suarez,E', team: 'Browns' },
    { name: 'Suarez,R', team: 'Browns' },
    { name: 'Suter,B', team: 'Hornets' },
    { name: 'Suwinski,J', team: 'Colt .45s' },
    { name: 'Suzuki,S', team: 'TinCaps' },
    { name: 'Swanson,D', team: 'Gypsies' },
    { name: 'Swanson,E', team: 'TinCaps' },
    { name: 'Syndergaard,N', team: 'Z-Unowned' },
    { name: 'Taillon,J', team: 'Pilots' },
    { name: 'Tapia,R', team: 'Z-Unowned' },
    { name: 'Tatis Jr,F', team: 'Expos' },
    { name: 'Tauchman,M', team: 'Z-Unowned' },
    { name: 'Taveras,L', team: 'Dodgers' },
    { name: 'Taylor,C', team: 'Z-Unowned' },
    { name: 'Taylor,M', team: 'Hornets' },
    { name: 'Taylor,T', team: 'Browns' },
    { name: 'Teheran,J', team: 'Z-Unowned' },
    { name: 'Tellez,R', team: 'Z-Unowned' },
    { name: 'Thaiss,M', team: 'Z-Unowned' },
    { name: 'Thielbar,C', team: 'Z-Unowned' },
    { name: 'Thomas,A', team: 'Bandits' },
    { name: 'Thomas,L', team: 'Clown Princes' },
    { name: 'Thompson,M', team: 'Z-Unowned' },
    { name: 'Thompson,R', team: 'Z-Unowned' },
    { name: 'Thompson,T', team: 'Z-Unowned' },
    { name: 'Thompson,Z', team: 'Z-Unowned' },
    { name: 'Toglia,M', team: 'Reds' },
    { name: 'Tonkin,M', team: 'Z-Unowned' },
    { name: 'Topa,J', team: 'Z-Unowned' },
    { name: 'Torkelson,S', team: 'Pilots' },
    { name: 'Torres,G', team: 'Titans' },
    { name: 'Toussaint,T', team: 'Z-Unowned' },
    { name: 'Tovar,E', team: 'Blaze' },
    { name: 'Trejo,A', team: 'Clown Princes' },
    { name: 'Trevino,J', team: 'Gypsies' },
    { name: 'Triolo,J', team: 'Yellow Jackets' },
    { name: 'Trout,M', team: 'Captains' },
    { name: 'Tucker,K', team: 'Stars' },
    { name: 'Turang,B', team: 'Blaze' },
    { name: 'Turner,J', team: 'Stars' },
    { name: 'Turner,T', team: 'Blaze' },
    { name: 'Urena,J', team: 'Z-Unowned' },
    { name: 'Urias,J', team: 'Stars' },
    { name: 'Urias,L', team: 'Z-Unowned' },
    { name: 'Urias,R', team: 'Reds' },
    { name: 'Uribe,A', team: 'Z-Unowned' },
    { name: 'Urquidy,J', team: 'TinCaps' },
    { name: 'Urshela,G', team: 'Twins' },
    { name: 'Valdez,E', team: 'Z-Unowned' },
    { name: 'Valdez,F', team: 'Twins' },
    { name: 'Vargas,I', team: 'Z-Unowned' },
    { name: 'Vargas,M', team: 'Dodgers' },
    { name: 'Varland,L', team: 'Pilots' },
    { name: 'Varsho,D', team: 'TinCaps' },
    { name: 'Vasquez,A', team: 'Z-Unowned' },
    { name: 'Vaughn,A', team: 'Hornets' },
    { name: 'Vazquez,C', team: 'Z-Unowned' },
    { name: 'Velazquez,N', team: 'Grays' },
    { name: 'Verdugo,A', team: 'Dodgers' },
    { name: 'VerHagen,D', team: 'Z-Unowned' },
    { name: 'Verlander,J', team: 'Gypsies' },
    { name: 'Vesia,A', team: 'Twins' },
    { name: 'Vest,W', team: 'Knights' },
    { name: 'Vientos,M', team: 'Blaze' },
    { name: 'Vierling,M', team: 'Gypsies' },
    { name: 'Villar,D', team: 'Z-Unowned' },
    { name: 'Vogelbach,D', team: 'Z-Unowned' },
    { name: 'Volpe,A', team: 'Hornets' },
    { name: 'Votto,J', team: 'Monarchs' },
    { name: 'Wacha,M', team: 'Z-Unowned' },
    { name: 'Wade Jr,L', team: 'Hornets' },
    { name: 'Wainwright,A', team: 'Z-Unowned' },
    { name: 'Waldichuk,K', team: 'Pilots' },
    { name: 'Walker,C', team: 'Pelicans' },
    { name: 'Walker,J', team: 'TinCaps' },
    { name: 'Walker,R', team: 'Z-Unowned' },
    { name: 'Walker,T', team: 'Dodgers' },
    { name: 'Wallach,C', team: 'Z-Unowned' },
    { name: 'Wallner,M', team: 'Blaze' },
    { name: 'Walls,T', team: 'Hornets' },
    { name: 'Walsh,J', team: 'Z-Unowned' },
    { name: 'Ward,T', team: 'Pelicans' },
    { name: 'Waters,D', team: 'Pilots' },
    { name: 'Weathers,R', team: 'Colt .45s' },
    { name: 'Weaver,L', team: 'Z-Unowned' },
    { name: 'Webb,J', team: 'Z-Unowned' },
    { name: 'Webb,L', team: 'Reds' },
    { name: 'Weems,J', team: 'Z-Unowned' },
    { name: 'Wells,T', team: 'Pelicans' },
    { name: 'Wendle,J', team: 'Pelicans' },
    { name: 'Wentz,J', team: 'RockHounds' },
    { name: 'Wesneski,H', team: 'Stars' },
    { name: 'Westburg,J', team: 'Bandits' },
    { name: 'Wheeler,Z', team: 'Pilgrims' },
    { name: 'White,B', team: 'Z-Unowned' },
    { name: 'Whitlock,G', team: 'TinCaps' },
    { name: 'Wiemer,J', team: 'River Dogs' },
    { name: 'Williams,A', team: 'River Dogs' },
    { name: 'Williams,D', team: 'Stars' },
    { name: 'Williams,G', team: 'Clown Princes' },
    { name: 'Williams,T', team: 'Z-Unowned' },
    { name: 'Williamson,B', team: 'Reds' },
    { name: 'Wilson,B', team: 'Stars' },
    { name: 'Wilson,S', team: 'Blaze' },
    { name: 'Winckowski,J', team: 'Z-Unowned' },
    { name: 'Winker,J', team: 'Z-Unowned' },
    { name: 'Winn,M', team: 'Pilgrims' },
    { name: 'Wisdom,P', team: 'Hornets' },
    { name: 'Wisely,B', team: 'Z-Unowned' },
    { name: 'Witt,B', team: 'Twins' },
    { name: 'Wong,C', team: 'Pilots' },
    { name: 'Wong,K', team: 'Z-Unowned' },
    { name: 'Woo,B', team: 'Knights' },
    { name: 'Wood,A', team: 'Expos' },
    { name: 'Woodruff,B', team: 'Pilgrims' },
    { name: 'Wynns,A', team: 'Pelicans' },
    { name: 'Yarbrough,R', team: 'Pelicans' },
    { name: 'Yastrzemski,M', team: 'Gypsies' },
    { name: 'Yates,K', team: 'Z-Unowned' },
    { name: 'Yelich,C', team: 'Titans' },
    { name: 'Yoshida,M', team: 'TinCaps' },
    { name: 'Young,A', team: 'Z-Unowned' },
    { name: 'Young,J', team: 'Z-Unowned' },
    { name: 'Zavala,S', team: 'Reds' },
    { name: 'Zunino,M', team: 'Bandits' },
];

module.exports = cardedPlayers;
