type MultiTeamHitters = {
    name: string;
    team: string;
    bats: string;
    ab: number;
};

type AllHitters = {
    id: string;
    name: string;
    team: string;
    ab: number;
};

type HittersOnIndividualTeams = {
    year: number;
    name: string;
    bats: string;
    team: string;
    ab: number;
};

const multiTeamHitters: Record<string, MultiTeamHitters> = {
    // paste here the formatted column from the 'Carded' sheet of the 'Hitter_Stats_20xx.xlsx' file... only the hitters whose team is 'TOT'
    biggica01: { name: 'Biggio, Cavan', team: 'TOT', bats: 'L', ab: 188 },
    canhama01: { name: 'Canha, Mark', team: 'TOT', bats: 'R', ab: 393 },
    carlsdy01: { name: 'Carlson, Dylan', team: 'TOT', bats: 'S', ab: 235 },
    chishja01: { name: 'Chisholm Jr, Jazz', team: 'TOT', bats: 'L', ab: 562 },
    coopega03: { name: 'Cooper, Garrett', team: 'TOT', bats: 'R', ab: 107 },
    davisjd01: { name: 'Davis, JD', team: 'TOT', bats: 'R', ab: 142 },
    delacbr01: { name: 'De La Cruz, Bryan', team: 'TOT', bats: 'R', ab: 584 },
    dejonpa01: { name: 'DeJong, Paul', team: 'TOT', bats: 'R', ab: 445 },
    diazel01: { name: 'Diaz, Elias', team: 'TOT', bats: 'R', ab: 325 },
    francty01: { name: 'France, Ty', team: 'TOT', bats: 'R', ab: 479 },
    grossro01: { name: 'Grossman, Robbie', team: 'TOT', bats: 'S', ab: 208 },
    guilllu01: { name: 'Guillorme, Luis', team: 'TOT', bats: 'L', ab: 161 },
    haysau01: { name: 'Hays, Austin', team: 'TOT', bats: 'R', ab: 235 },
    heywaja01: { name: 'Heyward, Jason', team: 'TOT', bats: 'L', ab: 228 },
    hillde01: { name: 'Hill, Derek', team: 'TOT', bats: 'R', ab: 162 },
    janseda01: { name: 'Jansen, Danny', team: 'TOT', bats: 'R', ab: 278 },
    jimenel02: { name: 'Jimenez, Eloy', team: 'TOT', bats: 'R', ab: 324 },
    kellyca02: { name: 'Kelly, Carson', team: 'TOT', bats: 'R', ab: 281 },
    kiermke01: { name: 'Kiermaier, Kevin', team: 'TOT', bats: 'L', ab: 259 },
    kineris01: { name: 'Kiner-Falefa, Isiah', team: 'TOT', bats: 'R', ab: 465 },
    laurera01: { name: 'Laureano, Ramon', team: 'TOT', bats: 'R', ab: 286 },
    loperjo01: { name: 'Loperfido, Joey', team: 'TOT', bats: 'L', ab: 243 },
    merriwh01: { name: 'Merrifield, Whit', team: 'TOT', bats: 'R', ab: 293 },
    morelch01: { name: 'Morel, Christopher', team: 'TOT', bats: 'R', ab: 535 },
    nidoto01: { name: 'Nido, Tomas', team: 'TOT', bats: 'R', ab: 130 },
    norbyco01: { name: 'Norby, Connor', team: 'TOT', bats: 'R', ab: 178 },
    pachecr01: { name: 'Pache, Cristian', team: 'TOT', bats: 'R', ab: 165 },
    paredis01: { name: 'Paredes, Isaac', team: 'TOT', bats: 'R', ab: 542 },
    phamth01: { name: 'Pham, Tommy', team: 'TOT', bats: 'R', ab: 440 },
    pillake01: { name: 'Pillar, Kevin', team: 'TOT', bats: 'R', ab: 284 },
    ramirha02: { name: 'Ramirez, Harold', team: 'TOT', bats: 'R', ab: 238 },
    riverem01: { name: 'Rivera, Emmanuel', team: 'TOT', bats: 'R', ab: 265 },
    roblevi01: { name: 'Robles, Victor', team: 'TOT', bats: 'R', ab: 254 },
    rosaram01: { name: 'Rosario, Amed', team: 'TOT', bats: 'R', ab: 332 },
    rosared01: { name: 'Rosario, Eddie', team: 'TOT', bats: 'L', ab: 297 },
    senzeni01: { name: 'Senzel, Nick', team: 'TOT', bats: 'R', ab: 236 },
    slateau01: { name: 'Slater, Austin', team: 'TOT', bats: 'R', ab: 177 },
    smithdo02: { name: 'Smith, Dominic', team: 'TOT', bats: 'L', ab: 275 },
    solerjo01: { name: 'Soler, Jorge', team: 'TOT', bats: 'R', ab: 493 },
    stoweky01: { name: 'Stowers, Kyle', team: 'TOT', bats: 'L', ab: 192 },
    tenajo01: { name: 'Tena, Jose', team: 'TOT', bats: 'L', ab: 161 },
    thomala02: { name: 'Thomas, Lane', team: 'TOT', bats: 'R', ab: 472 },
    turneju01: { name: 'Turner, Justin', team: 'TOT', bats: 'R', ab: 460 },
    urshegi01: { name: 'Urshela, Gio', team: 'TOT', bats: 'R', ab: 432 },
    vargami01: { name: 'Vargas, Miguel', team: 'TOT', bats: 'R', ab: 206 },
    winkeje01: { name: 'Winker, Jesse', team: 'TOT', bats: 'L', ab: 430 },
};

const allHitters: AllHitters[] = [
    // paste here the formatted column from the 'Original_with_Ind_Teams' sheet of the 'Hitter_Stats_20xx.xlsx' file... including all hitters
    { id: 'judgeaa01', name: 'Aaron Judge', team: 'NYY', ab: 559 },
    { id: 'ohtansh01', name: 'Shohei Ohtani*', team: 'LAD', ab: 636 },
    { id: 'santaan02', name: 'Anthony Santander#', team: 'BAL', ab: 595 },
    { id: 'sotoju01', name: 'Juan Soto*', team: 'NYY', ab: 576 },
    { id: 'ozunama01', name: 'Marcell Ozuna', team: 'ATL', ab: 606 },
    { id: 'ramirjo01', name: 'José Ramírez#', team: 'CLE', ab: 620 },
    { id: 'rookebr01', name: 'Brent Rooker', team: 'OAK', ab: 546 },
    { id: 'schwaky01', name: 'Kyle Schwarber*', team: 'PHI', ab: 573 },
    { id: 'hendegu01', name: 'Gunnar Henderson*', team: 'BAL', ab: 630 },
    { id: 'marteke01', name: 'Ketel Marte#', team: 'ARI', ab: 504 },
    { id: 'alvaryo01', name: 'Yordan Alvarez*', team: 'HOU', ab: 552 },
    { id: 'alonspe01', name: 'Pete Alonso', team: 'NYM', ab: 608 },
    { id: 'raleica01', name: 'Cal Raleigh#', team: 'SEA', ab: 546 },
    { id: 'hernate01', name: 'Teoscar Hernández', team: 'LAD', ab: 589 },
    { id: 'lindofr01', name: 'Francisco Lindor#', team: 'NYM', ab: 618 },
    { id: 'adamewi01', name: 'Willy Adames', team: 'MIL', ab: 610 },
    { id: 'wittbo02', name: 'Bobby Witt Jr.', team: 'KCR', ab: 636 },
    { id: 'naylojo01', name: 'Josh Naylor*', team: 'CLE', ab: 563 },
    { id: 'oneilty01', name: 'Tyler O\'Neill', team: 'BOS', ab: 411 },
    { id: 'guerrvl02', name: 'Vladimir Guerrero Jr.', team: 'TOR', ab: 616 },
    { id: 'harpebr03', name: 'Bryce Harper*', team: 'PHI', ab: 550 },
    { id: 'seageco01', name: 'Corey Seager*', team: 'TEX', ab: 475 },
    { id: 'suareeu01', name: 'Eugenio Suárez', team: 'ARI', ab: 571 },
    { id: 'burgeja01', name: 'Jake Burger', team: 'MIA', ab: 535 },
    { id: 'langesh01', name: 'Shea Langeliers', team: 'OAK', ab: 482 },
    { id: 'machama01', name: 'Manny Machado', team: 'SDP', ab: 593 },
    { id: 'olsonma02', name: 'Matt Olson*', team: 'ATL', ab: 600 },
    { id: 'deverra01', name: 'Rafael Devers*', team: 'BOS', ab: 525 },
    { id: 'chapmma01', name: 'Matt Chapman', team: 'SFG', ab: 575 },
    { id: 'perezsa02', name: 'Salvador Perez', team: 'KCR', ab: 590 },
    { id: 'stantmi03', name: 'Giancarlo Stanton', team: 'NYY', ab: 417 },
    { id: 'vientma01', name: 'Mark Vientos', team: 'NYM', ab: 413 },
    { id: 'bregmal01', name: 'Alex Bregman', team: 'HOU', ab: 581 },
    { id: 'hoskirh01', name: 'Rhys Hoskins', team: 'MIL', ab: 449 },
    { id: 'tovarez01', name: 'Ezequiel Tovar', team: 'COL', ab: 655 },
    { id: 'walkech02', name: 'Christian Walker', team: 'ARI', ab: 479 },
    { id: 'delacel01', name: 'Elly De La Cruz#', team: 'CIN', ab: 618 },
    { id: 'garciad02', name: 'Adolis García', team: 'TEX', ab: 580 },
    { id: 'happia01', name: 'Ian Happ#', team: 'CHC', ab: 569 },
    { id: 'toglimi01', name: 'Michael Toglia#', team: 'COL', ab: 399 },
    { id: 'wardta01', name: 'Taylor Ward', team: 'LAA', ab: 585 },
    { id: 'cowseco01', name: 'Colton Cowser*', team: 'BAL', ab: 499 },
    { id: 'greenri03', name: 'Riley Greene*', team: 'DET', ab: 512 },
    { id: 'merrija01', name: 'Jackson Merrill*', team: 'SDP', ab: 554 },
    { id: 'profaju01', name: 'Jurickson Profar#', team: 'SDP', ab: 564 },
    { id: 'reynobr01', name: 'Bryan Reynolds#', team: 'PIT', ab: 622 },
    { id: 'dejonpa01', name: 'Paul DeJong', team: 'TOT', ab: 445 },
    { id: 'dejonpa01', name: 'Paul DeJong', team: 'CHW', ab: 337 },
    { id: 'dejonpa01', name: 'Paul DeJong', team: 'KCR', ab: 108 },
    { id: 'chishja01', name: 'Jazz Chisholm Jr.*', team: 'TOT', ab: 562 },
    { id: 'chishja01', name: 'Jazz Chisholm Jr.*', team: 'MIA', ab: 386 },
    { id: 'chishja01', name: 'Jazz Chisholm Jr.*', team: 'NYY', ab: 176 },
    { id: 'casteni01', name: 'Nick Castellanos', team: 'PHI', ab: 606 },
    { id: 'contrwi02', name: 'William Contreras', team: 'MIL', ab: 595 },
    { id: 'doylebr02', name: 'Brenton Doyle', team: 'COL', ab: 542 },
    { id: 'netoza01', name: 'Zach Neto', team: 'LAA', ab: 542 },
    { id: 'nimmobr01', name: 'Brandon Nimmo*', team: 'NYM', ab: 571 },
    { id: 'pederjo01', name: 'Joc Pederson*', team: 'ARI', ab: 367 },
    { id: 'santaca01', name: 'Carlos Santana#', team: 'MIN', ab: 521 },
    { id: 'semiema01', name: 'Marcus Semien', team: 'TEX', ab: 650 },
    { id: 'tuckeky01', name: 'Kyle Tucker*', team: 'HOU', ab: 277 },
    { id: 'butlela01', name: 'Lawrence Butler*', team: 'OAK', ab: 412 },
    { id: 'carroco02', name: 'Corbin Carroll*', team: 'ARI', ab: 589 },
    { id: 'freemfr01', name: 'Freddie Freeman*', team: 'LAD', ab: 542 },
    { id: 'goldspa01', name: 'Paul Goldschmidt', team: 'STL', ab: 599 },
    { id: 'raleylu01', name: 'Luke Raley*', team: 'SEA', ab: 404 },
    { id: 'ramoshe02', name: 'Heliot Ramos', team: 'SFG', ab: 475 },
    { id: 'burleal01', name: 'Alec Burleson*', team: 'STL', ab: 547 },
    { id: 'buschmi02', name: 'Michael Busch*', team: 'CHC', ab: 496 },
    { id: 'chourja01', name: 'Jackson Chourio', team: 'MIL', ab: 528 },
    { id: 'cruzon01', name: 'Oneil Cruz*', team: 'PIT', ab: 541 },
    { id: 'duranja01', name: 'Jarren Duran*', team: 'BOS', ab: 671 },
    { id: 'jeffery01', name: 'Ryan Jeffers', team: 'MIN', ab: 412 },
    { id: 'lowebr01', name: 'Brandon Lowe*', team: 'TBR', ab: 385 },
    { id: 'suzukse01', name: 'Seiya Suzuki', team: 'CHC', ab: 512 },
    { id: 'tatisfe02', name: 'Fernando Tatis Jr.', team: 'SDP', ab: 398 },
    { id: 'turnetr01', name: 'Trea Turner', team: 'PHI', ab: 505 },
    { id: 'delacbr01', name: 'Bryan De La Cruz', team: 'TOT', ab: 584 },
    { id: 'delacbr01', name: 'Bryan De La Cruz', team: 'MIA', ab: 424 },
    { id: 'delacbr01', name: 'Bryan De La Cruz', team: 'PIT', ab: 160 },
    { id: 'solerjo01', name: 'Jorge Soler', team: 'TOT', ab: 493 },
    { id: 'solerjo01', name: 'Jorge Soler', team: 'ATL', ab: 152 },
    { id: 'solerjo01', name: 'Jorge Soler', team: 'SFG', ab: 341 },
    { id: 'morelch01', name: 'Christopher Morel', team: 'TOT', ab: 535 },
    { id: 'morelch01', name: 'Christopher Morel', team: 'CHC', ab: 362 },
    { id: 'morelch01', name: 'Christopher Morel', team: 'TBR', ab: 173 },
    { id: 'abramcj01', name: 'CJ Abrams*', team: 'WSN', ab: 541 },
    { id: 'adelljo01', name: 'Jo Adell', team: 'LAA', ab: 405 },
    { id: 'altuvjo01', name: 'Jose Altuve', team: 'HOU', ab: 628 },
    { id: 'beninan01', name: 'Andrew Benintendi*', team: 'CHW', ab: 477 },
    { id: 'bledajj01', name: 'JJ Bleday*', team: 'OAK', ab: 572 },
    { id: 'candeje01', name: 'Jeimer Candelario#', team: 'CIN', ab: 427 },
    { id: 'confomi01', name: 'Michael Conforto*', team: 'SFG', ab: 438 },
    { id: 'mccutan01', name: 'Andrew McCutchen', team: 'PIT', ab: 448 },
    { id: 'mcmahry01', name: 'Ryan McMahon*', team: 'COL', ab: 567 },
    { id: 'ohopplo01', name: 'Logan O\'Hoppe', team: 'LAA', ab: 479 },
    { id: 'rodriju01', name: 'Julio Rodríguez', team: 'SEA', ab: 567 },
    { id: 'smithwi05', name: 'Will Smith', team: 'LAD', ab: 476 },
    { id: 'steersp01', name: 'Spencer Steer', team: 'CIN', ab: 574 },
    { id: 'arozara01', name: 'Randy Arozarena', team: 'TOT', ab: 549 },
    { id: 'arozara01', name: 'Randy Arozarena', team: 'SEA', ab: 199 },
    { id: 'arozara01', name: 'Randy Arozarena', team: 'TBR', ab: 350 },
    { id: 'bettsmo01', name: 'Mookie Betts', team: 'LAD', ab: 450 },
    { id: 'gormano01', name: 'Nolan Gorman*', team: 'STL', ab: 365 },
    { id: 'pasquvi01', name: 'Vinnie Pasquantino*', team: 'KCR', ab: 496 },
    { id: 'rileyau01', name: 'Austin Riley', team: 'ATL', ab: 425 },
    { id: 'rutscad01', name: 'Adley Rutschman#', team: 'BAL', ab: 571 },
    { id: 'springe01', name: 'George Springer', team: 'TOR', ab: 545 },
    { id: 'stephty01', name: 'Tyler Stephenson', team: 'CIN', ab: 457 },
    { id: 'vaughan01', name: 'Andrew Vaughn', team: 'CHW', ab: 570 },
    { id: 'belljo02', name: 'Josh Bell#', team: 'TOT', ab: 538 },
    { id: 'belljo02', name: 'Josh Bell#', team: 'ARI', ab: 140 },
    { id: 'belljo02', name: 'Josh Bell#', team: 'MIA', ab: 398 },
    { id: 'paredis01', name: 'Isaac Paredes', team: 'TOT', ab: 542 },
    { id: 'paredis01', name: 'Isaac Paredes', team: 'CHC', ab: 179 },
    { id: 'paredis01', name: 'Isaac Paredes', team: 'TBR', ab: 363 },
    { id: 'bellico01', name: 'Cody Bellinger*', team: 'CHC', ab: 516 },
    { id: 'buxtoby01', name: 'Byron Buxton', team: 'MIN', ab: 355 },
    { id: 'carpeke01', name: 'Kerry Carpenter*', team: 'DET', ab: 264 },
    { id: 'garcilu04', name: 'Luis García Jr.*', team: 'WSN', ab: 500 },
    { id: 'gurrilo01', name: 'Lourdes Gurriel Jr.', team: 'ARI', ab: 513 },
    { id: 'mullice01', name: 'Cedric Mullins*', team: 'BAL', ab: 444 },
    { id: 'sanchje02', name: 'Jesús Sánchez*', team: 'MIA', ab: 489 },
    { id: 'sirijo01', name: 'Jose Siri', team: 'TBR', ab: 402 },
    { id: 'varshda01', name: 'Daulton Varsho*', team: 'TOR', ab: 459 },
    { id: 'westbjo01', name: 'Jordan Westburg', team: 'BAL', ab: 416 },
    { id: 'yastrmi01', name: 'Mike Yastrzemski*', team: 'SFG', ab: 428 },
    { id: 'arciaor01', name: 'Orlando Arcia', team: 'ATL', ab: 551 },
    { id: 'croneja01', name: 'Jake Cronenworth*', team: 'SDP', ab: 577 },
    { id: 'gelofza01', name: 'Zack Gelof', team: 'OAK', ab: 497 },
    { id: 'higasky01', name: 'Kyle Higashioka', team: 'SDP', ab: 246 },
    { id: 'melenmj01', name: 'MJ Melendez*', team: 'KCR', ab: 412 },
    { id: 'arenano01', name: 'Nolan Arenado', team: 'STL', ab: 578 },
    { id: 'diazya02', name: 'Yainer Diaz', team: 'HOU', ab: 585 },
    { id: 'harrimi04', name: 'Michael Harris II*', team: 'ATL', ab: 440 },
    { id: 'langfwy01', name: 'Wyatt Langford', team: 'TEX', ab: 499 },
    { id: 'lewisro02', name: 'Royce Lewis', team: 'MIN', ab: 292 },
    { id: 'lowena01', name: 'Nathaniel Lowe*', team: 'TEX', ab: 486 },
    { id: 'marshbr02', name: 'Brandon Marsh*', team: 'PHI', ab: 418 },
    { id: 'martijd02', name: 'J.D. Martinez', team: 'NYM', ab: 434 },
    { id: 'polanjo01', name: 'Jorge Polanco#', team: 'SEA', ab: 417 },
    { id: 'swansda01', name: 'Dansby Swanson', team: 'CHC', ab: 534 },
    { id: 'vierlma01', name: 'Matt Vierling', team: 'DET', ab: 518 },
    { id: 'abreuwi02', name: 'Wilyer Abreu*', team: 'BOS', ab: 399 },
    { id: 'bohmal01', name: 'Alec Bohm', team: 'PHI', ab: 554 },
    { id: 'contrwi01', name: 'Willson Contreras', team: 'STL', ab: 301 },
    { id: 'darnatr01', name: 'Travis d\'Arnaud', team: 'ATL', ab: 307 },
    { id: 'fitzgty01', name: 'Tyler Fitzgerald', team: 'SFG', ab: 314 },
    { id: 'garvemi01', name: 'Mitch Garver', team: 'SEA', ab: 367 },
    { id: 'indiajo01', name: 'Jonathan India', team: 'CIN', ab: 533 },
    { id: 'kelenja01', name: 'Jarred Kelenic*', team: 'ATL', ab: 412 },
    { id: 'larnatr01', name: 'Trevor Larnach*', team: 'MIN', ab: 355 },
    { id: 'muncyma01', name: 'Max Muncy*', team: 'LAD', ab: 237 },
    { id: 'ohearry01', name: 'Ryan O\'Hearn*', team: 'BAL', ab: 443 },
    { id: 'penaje02', name: 'Jeremy Peña', team: 'HOU', ab: 602 },
    { id: 'rafaece01', name: 'Ceddanne Rafaela', team: 'BOS', ab: 544 },
    { id: 'renfrhu01', name: 'Hunter Renfroe', team: 'KCR', ab: 385 },
    { id: 'torregl01', name: 'Gleyber Torres', team: 'NYY', ab: 587 },
    { id: 'winnma01', name: 'Masyn Winn', team: 'STL', ab: 587 },
    { id: 'thomala02', name: 'Lane Thomas', team: 'TOT', ab: 472 },
    { id: 'thomala02', name: 'Lane Thomas', team: 'CLE', ab: 172 },
    { id: 'thomala02', name: 'Lane Thomas', team: 'WSN', ab: 300 },
    { id: 'bensowi01', name: 'Will Benson*', team: 'CIN', ab: 343 },
    { id: 'brownse01', name: 'Seth Brown*', team: 'OAK', ab: 372 },
    { id: 'correca01', name: 'Carlos Correa', team: 'MIN', ab: 319 },
    { id: 'diazya01', name: 'Yandy Díaz', team: 'TBR', ab: 563 },
    { id: 'donovbr01', name: 'Brendan Donovan*', team: 'STL', ab: 587 },
    { id: 'fryda01', name: 'David Fry', team: 'CLE', ab: 335 },
    { id: 'kwanst01', name: 'Steven Kwan*', team: 'CLE', ab: 480 },
    { id: 'massemi02', name: 'Michael Massey*', team: 'KCR', ab: 332 },
    { id: 'moniami01', name: 'Mickey Moniak*', team: 'LAA', ab: 392 },
    { id: 'realmjt01', name: 'J.T. Realmuto', team: 'PHI', ab: 380 },
    { id: 'roberlu01', name: 'Luis Robert Jr.', team: 'CHW', ab: 393 },
    { id: 'winkeje01', name: 'Jesse Winker*', team: 'TOT', ab: 430 },
    { id: 'winkeje01', name: 'Jesse Winker*', team: 'NYM', ab: 115 },
    { id: 'winkeje01', name: 'Jesse Winker*', team: 'WSN', ab: 315 },
    { id: 'bartjo01', name: 'Joey Bart', team: 'PIT', ab: 253 },
    { id: 'casastr01', name: 'Triston Casas*', team: 'BOS', ab: 212 },
    { id: 'friedtj01', name: 'TJ Friedl*', team: 'CIN', ab: 297 },
    { id: 'goodmhu01', name: 'Hunter Goodman', team: 'COL', ab: 211 },
    { id: 'heimjo01', name: 'Jonah Heim#', team: 'TEX', ab: 459 },
    { id: 'keithco01', name: 'Colt Keith*', team: 'DET', ab: 516 },
    { id: 'meyerja02', name: 'Jake Meyers', team: 'HOU', ab: 461 },
    { id: 'mountry01', name: 'Ryan Mountcastle', team: 'BAL', ab: 473 },
    { id: 'naylobo01', name: 'Bo Naylor*', team: 'CLE', ab: 354 },
    { id: 'noeljh01', name: 'Jhonkensy Noel', team: 'CLE', ab: 179 },
    { id: 'pagesan01', name: 'Andy Pages', team: 'LAD', ab: 403 },
    { id: 'rodgebr02', name: 'Brendan Rodgers', team: 'COL', ab: 501 },
    { id: 'ruizke01', name: 'Keibert Ruiz#', team: 'WSN', ab: 459 },
    { id: 'schanno01', name: 'Nolan Schanuel*', team: 'LAA', ab: 519 },
    { id: 'schneda03', name: 'Davis Schneider', team: 'TOR', ab: 397 },
    { id: 'singljo02', name: 'Jon Singleton*', team: 'HOU', ab: 355 },
    { id: 'smithjo11', name: 'Josh Smith*', team: 'TEX', ab: 523 },
    { id: 'tellero01', name: 'Rowdy Tellez*', team: 'PIT', ab: 383 },
    { id: 'verdual01', name: 'Alex Verdugo*', team: 'NYY', ab: 559 },
    { id: 'wallnma01', name: 'Matt Wallner*', team: 'MIN', ab: 220 },
    { id: 'wellsau01', name: 'Austin Wells*', team: 'NYY', ab: 354 },
    { id: 'wongco01', name: 'Connor Wong', team: 'BOS', ab: 447 },
    { id: 'francty01', name: 'Ty France', team: 'TOT', ab: 479 },
    { id: 'francty01', name: 'Ty France', team: 'CIN', ab: 179 },
    { id: 'francty01', name: 'Ty France', team: 'SEA', ab: 300 },
    { id: 'baderha01', name: 'Harrison Bader', team: 'NYM', ab: 402 },
    { id: 'bauerja01', name: 'Jake Bauers*', team: 'MIL', ab: 302 },
    { id: 'blackch02', name: 'Charlie Blackmon*', team: 'COL', ab: 449 },
    { id: 'castrwi01', name: 'Willi Castro#', team: 'MIN', ab: 558 },
    { id: 'clemeer01', name: 'Ernie Clement', team: 'TOR', ab: 434 },
    { id: 'grichra01', name: 'Randal Grichuk', team: 'ARI', ab: 254 },
    { id: 'hanigmi01', name: 'Mitch Haniger', team: 'SEA', ab: 380 },
    { id: 'hernaen02', name: 'Kiké Hernández', team: 'LAD', ab: 362 },
    { id: 'horwisp01', name: 'Spencer Horwitz*', team: 'TOR', ab: 328 },
    { id: 'leeko01', name: 'Korey Lee', team: 'CHW', ab: 377 },
    { id: 'mcneije01', name: 'Jeff McNeil*', team: 'NYM', ab: 424 },
    { id: 'nootbla01', name: 'Lars Nootbaar*', team: 'STL', ab: 348 },
    { id: 'taverle01', name: 'Leody Taveras#', team: 'TEX', ab: 480 },
    { id: 'volpean01', name: 'Anthony Volpe', team: 'NYY', ab: 637 },
    { id: 'alvarfr01', name: 'Francisco Alvarez', team: 'NYM', ab: 308 },
    { id: 'bogaexa01', name: 'Xander Bogaerts', team: 'SDP', ab: 428 },
    { id: 'bridejo01', name: 'Jonah Bride', team: 'MIA', ab: 232 },
    { id: 'duvalad01', name: 'Adam Duvall', team: 'ATL', ab: 303 },
    { id: 'kimha01', name: 'Ha-Seong Kim', team: 'SDP', ab: 403 },
    { id: 'ortizjo06', name: 'Joey Ortiz', team: 'MIL', ab: 440 },
    { id: 'refsnro01', name: 'Rob Refsnyder', team: 'BOS', ab: 272 },
    { id: 'sanchga02', name: 'Gary Sánchez', team: 'MIL', ab: 245 },
    { id: 'stottbr01', name: 'Bryson Stott*', team: 'PHI', ab: 506 },
    { id: 'uriasra01', name: 'Ramón Urías', team: 'BAL', ab: 272 },
    { id: 'yelicch01', name: 'Christian Yelich*', team: 'MIL', ab: 270 },
    { id: 'turneju01', name: 'Justin Turner', team: 'TOT', ab: 460 },
    { id: 'turneju01', name: 'Justin Turner', team: 'SEA', ab: 159 },
    { id: 'turneju01', name: 'Justin Turner', team: 'TOR', ab: 301 },
    { id: 'laurera01', name: 'Ramón Laureano', team: 'TOT', ab: 286 },
    { id: 'laurera01', name: 'Ramón Laureano', team: 'ATL', ab: 216 },
    { id: 'laurera01', name: 'Ramón Laureano', team: 'CLE', ab: 70 },
    { id: 'albieoz01', name: 'Ozzie Albies#', team: 'ATL', ab: 399 },
    { id: 'crowape01', name: 'Pete Crow-Armstrong*', team: 'CHC', ab: 372 },
    { id: 'gallojo01', name: 'Joey Gallo*', team: 'WSN', ab: 223 },
    { id: 'hillisa01', name: 'Sam Hilliard*', team: 'COL', ab: 138 },
    { id: 'lowejo01', name: 'Josh Lowe*', team: 'TBR', ab: 353 },
    { id: 'luxga01', name: 'Gavin Lux*', team: 'LAD', ab: 439 },
    { id: 'mooredy01', name: 'Dylan Moore', team: 'SEA', ab: 368 },
    { id: 'murphse01', name: 'Sean Murphy', team: 'ATL', ab: 233 },
    { id: 'rogerja03', name: 'Jake Rogers', team: 'DET', ab: 310 },
    { id: 'sheetga01', name: 'Gavin Sheets*', team: 'CHW', ab: 451 },
    { id: 'torkesp01', name: 'Spencer Torkelson', team: 'DET', ab: 342 },
    { id: 'troutmi01', name: 'Mike Trout', team: 'LAA', ab: 109 },
    { id: 'yoshima02', name: 'Masataka Yoshida*', team: 'BOS', ab: 378 },
    { id: 'rosared01', name: 'Eddie Rosario*', team: 'TOT', ab: 297 },
    { id: 'rosared01', name: 'Eddie Rosario*', team: 'ATL', ab: 78 },
    { id: 'rosared01', name: 'Eddie Rosario*', team: 'WSN', ab: 219 },
    { id: 'heywaja01', name: 'Jason Heyward*', team: 'TOT', ab: 228 },
    { id: 'heywaja01', name: 'Jason Heyward*', team: 'HOU', ab: 55 },
    { id: 'heywaja01', name: 'Jason Heyward*', team: 'LAD', ab: 173 },
    { id: 'cabaljo01', name: 'José Caballero', team: 'TBR', ab: 441 },
    { id: 'grishtr01', name: 'Trent Grisham*', team: 'NYY', ab: 179 },
    { id: 'crawfjp01', name: 'J.P. Crawford*', team: 'SEA', ab: 392 },
    { id: 'espinsa01', name: 'Santiago Espinal', team: 'CIN', ab: 357 },
    { id: 'estrath01', name: 'Thairo Estrada', team: 'SFG', ab: 364 },
    { id: 'gimenan01', name: 'Andrés Giménez*', team: 'CLE', ab: 583 },
    { id: 'grandya01', name: 'Yasmani Grandal#', team: 'PIT', ab: 215 },
    { id: 'joeco01', name: 'Connor Joe', team: 'PIT', ab: 364 },
    { id: 'meadopa01', name: 'Parker Meadows*', team: 'DET', ab: 270 },
    { id: 'miranjo01', name: 'José Miranda', team: 'MIN', ab: 401 },
    { id: 'perezwe01', name: 'Wenceel Pérez#', team: 'DET', ab: 389 },
    { id: 'smithpa04', name: 'Pavin Smith*', team: 'ARI', ab: 137 },
    { id: 'soderty01', name: 'Tyler Soderstrom*', team: 'OAK', ab: 189 },
    { id: 'stallja01', name: 'Jacob Stallings', team: 'COL', ab: 243 },
    { id: 'suwinja01', name: 'Jack Suwinski*', team: 'PIT', ab: 247 },
    { id: 'triolja01', name: 'Jared Triolo', team: 'PIT', ab: 394 },
    { id: 'woodja03', name: 'James Wood*', team: 'WSN', ab: 295 },
    { id: 'kellyca02', name: 'Carson Kelly', team: 'TOT', ab: 281 },
    { id: 'kellyca02', name: 'Carson Kelly', team: 'DET', ab: 179 },
    { id: 'kellyca02', name: 'Carson Kelly', team: 'TEX', ab: 102 },
    { id: 'janseda01', name: 'Danny Jansen', team: 'TOT', ab: 278 },
    { id: 'janseda01', name: 'Danny Jansen', team: 'BOS', ab: 80 },
    { id: 'janseda01', name: 'Danny Jansen', team: 'TOR', ab: 198 },
    { id: 'norbyco01', name: 'Connor Norby', team: 'TOT', ab: 178 },
    { id: 'norbyco01', name: 'Connor Norby', team: 'BAL', ab: 32 },
    { id: 'norbyco01', name: 'Connor Norby', team: 'MIA', ab: 146 },
    { id: 'phamth01', name: 'Tommy Pham', team: 'TOT', ab: 372 },
    { id: 'phamth01', name: 'Tommy Pham', team: 'TOT', ab: 440 },
    { id: 'phamth01', name: 'Tommy Pham', team: 'CHW', ab: 271 },
    { id: 'phamth01', name: 'Tommy Pham', team: 'KCR', ab: 101 },
    { id: 'phamth01', name: 'Tommy Pham', team: 'STL', ab: 68 },
    { id: 'urshegi01', name: 'Gio Urshela', team: 'TOT', ab: 432 },
    { id: 'urshegi01', name: 'Gio Urshela', team: 'ATL', ab: 132 },
    { id: 'urshegi01', name: 'Gio Urshela', team: 'DET', ab: 300 },
    { id: 'amayami01', name: 'Miguel Amaya', team: 'CHC', ab: 328 },
    { id: 'bailepa01', name: 'Patrick Bailey#', team: 'SFG', ab: 401 },
    { id: 'brennwi02', name: 'Will Brennan*', team: 'CLE', ab: 330 },
    { id: 'cabreos01', name: 'Oswaldo Cabrera#', team: 'NYY', ab: 299 },
    { id: 'campulu01', name: 'Luis Campusano', team: 'SDP', ab: 277 },
    { id: 'canzodo01', name: 'Dominic Canzone*', team: 'SEA', ab: 168 },
    { id: 'caratvi01', name: 'Victor Caratini#', team: 'HOU', ab: 245 },
    { id: 'faircst01', name: 'Stuart Fairchild', team: 'CIN', ab: 209 },
    { id: 'gordoni01', name: 'Nick Gordon*', team: 'MIA', ab: 260 },
    { id: 'hamilda03', name: 'David Hamilton*', team: 'BOS', ab: 294 },
    { id: 'isbelky01', name: 'Kyle Isbel*', team: 'KCR', ab: 384 },
    { id: 'julieed01', name: 'Edouard Julien*', team: 'MIN', ab: 266 },
    { id: 'keplema01', name: 'Max Kepler*', team: 'MIN', ab: 368 },
    { id: 'malloju02', name: 'Justyn-Henry Malloy', team: 'DET', ab: 202 },
    { id: 'mccanja02', name: 'James McCann', team: 'BAL', ab: 214 },
    { id: 'mccarja02', name: 'Jake McCarthy*', team: 'ARI', ab: 442 },
    { id: 'mitchga01', name: 'Garrett Mitchell*', team: 'MIL', ab: 196 },
    { id: 'peralda01', name: 'David Peralta*', team: 'SDP', ab: 236 },
    { id: 'rizzoan01', name: 'Anthony Rizzo*', team: 'NYY', ab: 337 },
    { id: 'rocchbr01', name: 'Brayan Rocchio#', team: 'CLE', ab: 383 },
    { id: 'rojasjo01', name: 'Josh Rojas*', team: 'SEA', ab: 422 },
    { id: 'solando01', name: 'Donovan Solano', team: 'SDP', ab: 283 },
    { id: 'sosale01', name: 'Lenyn Sosa', team: 'CHW', ab: 351 },
    { id: 'trevijo01', name: 'Jose Trevino', team: 'NYY', ab: 209 },
    { id: 'velazne01', name: 'Nelson Velázquez', team: 'KCR', ab: 205 },
    { id: 'wadela01', name: 'LaMonte Wade Jr.*', team: 'SFG', ab: 331 },
    { id: 'wisdopa01', name: 'Patrick Wisdom', team: 'CHC', ab: 158 },
    { id: 'pillake01', name: 'Kevin Pillar', team: 'TOT', ab: 284 },
    { id: 'pillake01', name: 'Kevin Pillar', team: 'CHW', ab: 25 },
    { id: 'pillake01', name: 'Kevin Pillar', team: 'LAA', ab: 259 },
    { id: 'kineris01', name: 'Isiah Kiner-Falefa', team: 'TOT', ab: 465 },
    { id: 'kineris01', name: 'Isiah Kiner-Falefa', team: 'PIT', ab: 208 },
    { id: 'kineris01', name: 'Isiah Kiner-Falefa', team: 'TOR', ab: 257 },
    { id: 'bargead01', name: 'Addison Barger*', team: 'TOR', ab: 208 },
    { id: 'canhama01', name: 'Mark Canha', team: 'TOT', ab: 393 },
    { id: 'canhama01', name: 'Mark Canha', team: 'DET', ab: 320 },
    { id: 'canhama01', name: 'Mark Canha', team: 'SFG', ab: 73 },
    { id: 'caveja01', name: 'Jake Cave*', team: 'COL', ab: 323 },
    { id: 'freemty01', name: 'Tyler Freeman', team: 'CLE', ab: 330 },
    { id: 'garcima01', name: 'Maikel Garcia', team: 'KCR', ab: 575 },
    { id: 'gonzani01', name: 'Nick Gonzales', team: 'PIT', ab: 359 },
    { id: 'hoernni01', name: 'Nico Hoerner', team: 'CHC', ab: 582 },
    { id: 'jungjo01', name: 'Josh Jung', team: 'TEX', ab: 178 },
    { id: 'martest01', name: 'Starling Marte', team: 'NYM', ab: 335 },
    { id: 'nevinty01', name: 'Tyler Nevin', team: 'OAK', ab: 245 },
    { id: 'pagespe02', name: 'Pedro Pagés', team: 'STL', ab: 202 },
    { id: 'ricebe01', name: 'Ben Rice*', team: 'NYY', ab: 152 },
    { id: 'schuema01', name: 'Max Schuemann', team: 'OAK', ab: 396 },
    { id: 'senzeni01', name: 'Nick Senzel', team: 'TOT', ab: 236 },
    { id: 'senzeni01', name: 'Nick Senzel', team: 'CHW', ab: 30 },
    { id: 'senzeni01', name: 'Nick Senzel', team: 'WSN', ab: 206 },
    { id: 'sosaed01', name: 'Edmundo Sosa', team: 'PHI', ab: 249 },
    { id: 'tauchmi01', name: 'Mike Tauchman*', team: 'CHC', ab: 298 },
    { id: 'tayloty01', name: 'Tyrone Taylor', team: 'NYM', ab: 319 },
    { id: 'turanbr02', name: 'Brice Turang*', team: 'MIL', ab: 559 },
    { id: 'vazquch01', name: 'Christian Vázquez', team: 'MIN', ab: 294 },
    { id: 'hillde01', name: 'Derek Hill', team: 'TOT', ab: 119 },
    { id: 'hillde01', name: 'Derek Hill', team: 'TOT', ab: 162 },
    { id: 'hillde01', name: 'Derek Hill', team: 'MIA', ab: 107 },
    { id: 'hillde01', name: 'Derek Hill', team: 'SFG', ab: 12 },
    { id: 'hillde01', name: 'Derek Hill', team: 'TEX', ab: 43 },
    { id: 'arandjo01', name: 'Jonathan Aranda*', team: 'TBR', ab: 128 },
    { id: 'baezja01', name: 'Javier Báez', team: 'DET', ab: 272 },
    { id: 'caminju01', name: 'Junior Caminero', team: 'TBR', ab: 165 },
    { id: 'delucjo01', name: 'Jonny DeLuca', team: 'TBR', ab: 332 },
    { id: 'edmanto01', name: 'Tommy Edman#', team: 'LAD', ab: 139 },
    { id: 'fermifr01', name: 'Freddy Fermin', team: 'KCR', ab: 339 },
    { id: 'gonzaro01', name: 'Romy González', team: 'BOS', ab: 199 },
    { id: 'lopezot01', name: 'Otto López', team: 'MIA', ab: 403 },
    { id: 'perkibl01', name: 'Blake Perkins#', team: 'MIL', ab: 383 },
    { id: 'rengilu01', name: 'Luis Rengifo#', team: 'LAA', ab: 283 },
    { id: 'rojasmi02', name: 'Miguel Rojas', team: 'LAD', ab: 307 },
    { id: 'schmica01', name: 'Casey Schmitt', team: 'SFG', ab: 107 },
    { id: 'smithdo02', name: 'Dominic Smith*', team: 'TOT', ab: 275 },
    { id: 'smithdo02', name: 'Dominic Smith*', team: 'BOS', ab: 249 },
    { id: 'smithdo02', name: 'Dominic Smith*', team: 'CIN', ab: 26 },
    { id: 'toroab01', name: 'Abraham Toro#', team: 'OAK', ab: 337 },
    { id: 'valdeen01', name: 'Enmanuel Valdéz*', team: 'BOS', ab: 201 },
    { id: 'yepezju01', name: 'Juan Yepez', team: 'WSN', ab: 226 },
    { id: 'diazel01', name: 'Elias Díaz', team: 'TOT', ab: 325 },
    { id: 'diazel01', name: 'Elias Díaz', team: 'COL', ab: 304 },
    { id: 'diazel01', name: 'Elias Díaz', team: 'SDP', ab: 21 },
    { id: 'jimenel02', name: 'Eloy Jiménez', team: 'TOT', ab: 324 },
    { id: 'jimenel02', name: 'Eloy Jiménez', team: 'BAL', ab: 95 },
    { id: 'jimenel02', name: 'Eloy Jiménez', team: 'CHW', ab: 229 },
    { id: 'calhowi01', name: 'Willie Calhoun*', team: 'LAA', ab: 229 },
    { id: 'camerda01', name: 'Daz Cameron', team: 'OAK', ab: 170 },
    { id: 'carteev01', name: 'Evan Carter*', team: 'TEX', ab: 144 },
    { id: 'clemeko01', name: 'Kody Clemens*', team: 'PHI', ab: 114 },
    { id: 'encarje01', name: 'Jerar Encarnación', team: 'SFG', ab: 113 },
    { id: 'farmeky01', name: 'Kyle Farmer', team: 'MIN', ab: 215 },
    { id: 'fraleja01', name: 'Jake Fraley*', team: 'CIN', ab: 350 },
    { id: 'haaseer01', name: 'Eric Haase', team: 'MIL', ab: 66 },
    { id: 'herreiv01', name: 'Iván Herrera', team: 'STL', ab: 229 },
    { id: 'hindsre01', name: 'Rece Hinds', team: 'CIN', ab: 46 },
    { id: 'hollija01', name: 'Jackson Holliday*', team: 'BAL', ab: 190 },
    { id: 'ibanean01', name: 'Andy Ibáñez', team: 'DET', ab: 224 },
    { id: 'kirilal01', name: 'Alex Kirilloff*', team: 'MIN', ab: 159 },
    { id: 'kirkal01', name: 'Alejandro Kirk', team: 'TOR', ab: 340 },
    { id: 'manzaky01', name: 'Kyle Manzardo*', team: 'CLE', ab: 145 },
    { id: 'martini02', name: 'Nick Martini*', team: 'CIN', ab: 146 },
    { id: 'mateojo01', name: 'Jorge Mateo', team: 'BAL', ab: 192 },
    { id: 'matoslu02', name: 'Luis Matos', team: 'SFG', ab: 150 },
    { id: 'mccanky01', name: 'Kyle McCann*', team: 'OAK', ab: 140 },
    { id: 'mccorch01', name: 'Chas McCormick', team: 'HOU', ab: 242 },
    { id: 'mccragr01', name: 'Grant McCray*', team: 'SFG', ab: 124 },
    { id: 'morenga01', name: 'Gabriel Moreno', team: 'ARI', ab: 305 },
    { id: 'olivaed02', name: 'Edward Olivares', team: 'PIT', ab: 174 },
    { id: 'palacri01', name: 'Richie Palacios*', team: 'TBR', ab: 264 },
    { id: 'schneda04', name: 'Daniel Schneemann*', team: 'CLE', ab: 193 },
    { id: 'stewadj01', name: 'DJ Stewart*', team: 'NYM', ab: 158 },
    { id: 'taylomi02', name: 'Michael A. Taylor', team: 'PIT', ab: 269 },
    { id: 'walkejo02', name: 'Jordan Walker', team: 'STL', ab: 164 },
    { id: 'bethach01', name: 'Christian Bethancourt', team: 'TOT', ab: 139 },
    { id: 'bethach01', name: 'Christian Bethancourt', team: 'CHC', ab: 57 },
    { id: 'bethach01', name: 'Christian Bethancourt', team: 'MIA', ab: 82 },
    { id: 'kiermke01', name: 'Kevin Kiermaier*', team: 'TOT', ab: 259 },
    { id: 'kiermke01', name: 'Kevin Kiermaier*', team: 'LAD', ab: 59 },
    { id: 'kiermke01', name: 'Kevin Kiermaier*', team: 'TOR', ab: 200 },
    { id: 'riverem01', name: 'Emmanuel Rivera', team: 'TOT', ab: 265 },
    { id: 'riverem01', name: 'Emmanuel Rivera', team: 'BAL', ab: 64 },
    { id: 'riverem01', name: 'Emmanuel Rivera', team: 'MIA', ab: 201 },
    { id: 'biggica01', name: 'Cavan Biggio*', team: 'TOT', ab: 78 },
    { id: 'biggica01', name: 'Cavan Biggio*', team: 'TOT', ab: 188 },
    { id: 'biggica01', name: 'Cavan Biggio*', team: 'ATL', ab: 5 },
    { id: 'biggica01', name: 'Cavan Biggio*', team: 'LAD', ab: 73 },
    { id: 'biggica01', name: 'Cavan Biggio*', team: 'TOR', ab: 110 },
    { id: 'haysau01', name: 'Austin Hays', team: 'TOT', ab: 235 },
    { id: 'haysau01', name: 'Austin Hays', team: 'BAL', ab: 157 },
    { id: 'haysau01', name: 'Austin Hays', team: 'PHI', ab: 78 },
    { id: 'vargami01', name: 'Miguel Vargas', team: 'TOT', ab: 206 },
    { id: 'vargami01', name: 'Miguel Vargas', team: 'CHW', ab: 135 },
    { id: 'vargami01', name: 'Miguel Vargas', team: 'LAD', ab: 71 },
    { id: 'acunaro01', name: 'Ronald Acuña Jr.', team: 'ATL', ab: 192 },
    { id: 'andujmi01', name: 'Miguel Andujar', team: 'OAK', ab: 302 },
    { id: 'arraelu01', name: 'Luis Arráez*', team: 'TOT', ab: 637 },
    { id: 'arraelu01', name: 'Luis Arráez*', team: 'MIA', ab: 137 },
    { id: 'arraelu01', name: 'Luis Arráez*', team: 'SDP', ab: 500 },
    { id: 'batybr01', name: 'Brett Baty*', team: 'NYM', ab: 153 },
    { id: 'bichebo01', name: 'Bo Bichette', team: 'TOR', ab: 311 },
    { id: 'blancda02', name: 'Dairon Blanco', team: 'KCR', ab: 120 },
    { id: 'carpema01', name: 'Matt Carpenter*', team: 'STL', ab: 137 },
    { id: 'chapaan01', name: 'Andrés Chaparro', team: 'WSN', ab: 121 },
    { id: 'davisjd01', name: 'J.D. Davis', team: 'TOT', ab: 142 },
    { id: 'davisjd01', name: 'J.D. Davis', team: 'NYY', ab: 19 },
    { id: 'davisjd01', name: 'J.D. Davis', team: 'OAK', ab: 123 },
    { id: 'delcaad01', name: 'Adrian Del Castillo*', team: 'ARI', ab: 80 },
    { id: 'drurybr01', name: 'Brandon Drury', team: 'LAA', ab: 325 },
    { id: 'dubonma01', name: 'Mauricio Dubón', team: 'HOU', ab: 402 },
    { id: 'florewi01', name: 'Wilmer Flores', team: 'SFG', ab: 214 },
    { id: 'forteni01', name: 'Nick Fortes', team: 'MIA', ab: 308 },
    { id: 'fraziad01', name: 'Adam Frazier*', team: 'KCR', ab: 262 },
    { id: 'hayeske01', name: 'Ke\'Bryan Hayes', team: 'PIT', ab: 365 },
    { id: 'iglesjo01', name: 'Jose Iglesias', team: 'NYM', ab: 270 },
    { id: 'jimenle01', name: 'Leo Jiménez', team: 'TOR', ab: 179 },
    { id: 'kavadni01', name: 'Niko Kavadas*', team: 'LAA', ab: 93 },
    { id: 'kjershe01', name: 'Heston Kjerstad*', team: 'BAL', ab: 99 },
    { id: 'maldoma01', name: 'Martín Maldonado', team: 'CHW', ab: 135 },
    { id: 'margoma01', name: 'Manuel Margot', team: 'MIN', ab: 315 },
    { id: 'marteno01', name: 'Noelvi Marté', team: 'CIN', ab: 229 },
    { id: 'mckinza01', name: 'Zach McKinstry*', team: 'DET', ab: 297 },
    { id: 'monteel01', name: 'Elehuris Montero', team: 'COL', ab: 224 },
    { id: 'outmaja01', name: 'James Outman*', team: 'LAD', ab: 136 },
    { id: 'roblevi01', name: 'Víctor Robles', team: 'TOT', ab: 254 },
    { id: 'roblevi01', name: 'Víctor Robles', team: 'SEA', ab: 229 },
    { id: 'roblevi01', name: 'Víctor Robles', team: 'WSN', ab: 25 },
    { id: 'sweentr01', name: 'Trey Sweeney*', team: 'DET', ab: 110 },
    { id: 'tayloch03', name: 'Chris Taylor', team: 'LAD', ab: 213 },
    { id: 'uriaslu01', name: 'Luis Urías', team: 'SEA', ab: 94 },
    { id: 'wiselbr01', name: 'Brett Wisely*', team: 'SFG', ab: 252 },
    { id: 'merriwh01', name: 'Whit Merrifield', team: 'TOT', ab: 293 },
    { id: 'merriwh01', name: 'Whit Merrifield', team: 'ATL', ab: 137 },
    { id: 'merriwh01', name: 'Whit Merrifield', team: 'PHI', ab: 156 },
    { id: 'nidoto01', name: 'Tomás Nido', team: 'TOT', ab: 130 },
    { id: 'nidoto01', name: 'Tomás Nido', team: 'CHC', ab: 47 },
    { id: 'nidoto01', name: 'Tomás Nido', team: 'NYM', ab: 83 },
    { id: 'loperjo01', name: 'Joey Loperfido*', team: 'TOT', ab: 243 },
    { id: 'loperjo01', name: 'Joey Loperfido*', team: 'HOU', ab: 106 },
    { id: 'loperjo01', name: 'Joey Loperfido*', team: 'TOR', ab: 137 },
    { id: 'acunajo01', name: 'Luisangel Acuña', team: 'NYM', ab: 39 },
    { id: 'alexabl01', name: 'Blaze Alexander', team: 'ARI', ab: 166 },
    { id: 'ariasga01', name: 'Gabriel Arias', team: 'CLE', ab: 153 },
    { id: 'beckjo01', name: 'Jordan Beck', team: 'COL', ab: 170 },
    { id: 'callal02', name: 'Alex Call', team: 'WSN', ab: 99 },
    { id: 'carlsdy01', name: 'Dylan Carlson#', team: 'TOT', ab: 235 },
    { id: 'carlsdy01', name: 'Dylan Carlson#', team: 'STL', ab: 121 },
    { id: 'carlsdy01', name: 'Dylan Carlson#', team: 'TBR', ab: 114 },
    { id: 'coningr01', name: 'Griffin Conine*', team: 'MIA', ab: 82 },
    { id: 'cookbi01', name: 'Billy Cook', team: 'PIT', ab: 49 },
    { id: 'crewsdy01', name: 'Dylan Crews', team: 'WSN', ab: 119 },
    { id: 'dahlda01', name: 'David Dahl*', team: 'PHI', ab: 58 },
    { id: 'duranez01', name: 'Ezequiel Durán', team: 'TEX', ab: 268 },
    { id: 'flories01', name: 'Estevan Florial*', team: 'CLE', ab: 98 },
    { id: 'grossro01', name: 'Robbie Grossman#', team: 'TOT', ab: 208 },
    { id: 'grossro01', name: 'Robbie Grossman#', team: 'CHW', ab: 71 },
    { id: 'grossro01', name: 'Robbie Grossman#', team: 'KCR', ab: 32 },
    { id: 'grossro01', name: 'Robbie Grossman#', team: 'TEX', ab: 105 },
    { id: 'harribr02', name: 'Brett Harris', team: 'OAK', ab: 103 },
    { id: 'jacksal02', name: 'Alex Jackson', team: 'TBR', ab: 139 },
    { id: 'jonesno01', name: 'Nolan Jones*', team: 'COL', ab: 256 },
    { id: 'julksco01', name: 'Corey Julks', team: 'CHW', ab: 173 },
    { id: 'leebr02', name: 'Brooks Lee#', team: 'MIN', ab: 172 },
    { id: 'marchra01', name: 'Rafael Marchán#', team: 'PHI', ab: 51 },
    { id: 'martian02', name: 'Ángel Martínez#', team: 'CLE', ab: 151 },
    { id: 'mcguire01', name: 'Reese McGuire*', team: 'BOS', ab: 139 },
    { id: 'mendida01', name: 'Danny Mendick', team: 'CHW', ab: 132 },
    { id: 'menesjo01', name: 'Joey Meneses', team: 'WSN', ab: 281 },
    { id: 'myersda01', name: 'Dane Myers', team: 'MIA', ab: 95 },
    { id: 'newmake01', name: 'Kevin Newman', team: 'ARI', ab: 288 },
    { id: 'perdoge01', name: 'Geraldo Perdomo#', team: 'ARI', ab: 337 },
    { id: 'ramosbr01', name: 'Bryan Ramos', team: 'CHW', ab: 99 },
    { id: 'rojasjo03', name: 'Johan Rojas', team: 'PHI', ab: 338 },
    { id: 'rortvbe01', name: 'Ben Rortvedt*', team: 'TBR', ab: 290 },
    { id: 'rosareg01', name: 'Eguy Rosario', team: 'SDP', ab: 53 },
    { id: 'tenajo01', name: 'José Tena*', team: 'TOT', ab: 161 },
    { id: 'tenajo01', name: 'José Tena*', team: 'CLE', ab: 4 },
    { id: 'tenajo01', name: 'José Tena*', team: 'WSN', ab: 157 },
    { id: 'thomaal01', name: 'Alek Thomas*', team: 'ARI', ab: 95 },
    { id: 'torrelu01', name: 'Luis Torrens', team: 'NYM', ab: 118 },
    { id: 'wilsowe01', name: 'Weston Wilson', team: 'PHI', ab: 88 },
    { id: 'youngja03', name: 'Jacob Young', team: 'WSN', ab: 468 },
    { id: 'rosaram01', name: 'Amed Rosario', team: 'TOT', ab: 68 },
    { id: 'rosaram01', name: 'Amed Rosario', team: 'TOT', ab: 332 },
    { id: 'rosaram01', name: 'Amed Rosario', team: 'CIN', ab: 57 },
    { id: 'rosaram01', name: 'Amed Rosario', team: 'LAD', ab: 11 },
    { id: 'rosaram01', name: 'Amed Rosario', team: 'TBR', ab: 264 },
    { id: 'stoweky01', name: 'Kyle Stowers*', team: 'TOT', ab: 192 },
    { id: 'stoweky01', name: 'Kyle Stowers*', team: 'BAL', ab: 36 },
    { id: 'stoweky01', name: 'Kyle Stowers*', team: 'MIA', ab: 156 },
    { id: 'abreujo02', name: 'José Abreu', team: 'HOU', ab: 113 },
    { id: 'adamsri03', name: 'Riley Adams', team: 'WSN', ab: 116 },
    { id: 'baddoak01', name: 'Akil Baddoo*', team: 'DET', ab: 73 },
    { id: 'bakerlu01', name: 'Luken Baker', team: 'STL', ab: 40 },
    { id: 'baldwbr01', name: 'Brooks Baldwin#', team: 'CHW', ab: 114 },
    { id: 'blissry01', name: 'Ryan Bliss', team: 'SEA', ab: 63 },
    { id: 'brujavi01', name: 'Vidal Bruján#', team: 'MIA', ab: 248 },
    { id: 'bryankr01', name: 'Kris Bryant', team: 'COL', ab: 133 },
    { id: 'dezenza01', name: 'Zach Dezenzo', team: 'HOU', ab: 62 },
    { id: 'dominja01', name: 'Jasson Domínguez#', team: 'NYY', ab: 56 },
    { id: 'encarch01', name: 'Christian Encarnacion-Strand', team: 'CIN', ab: 116 },
    { id: 'frelisa01', name: 'Sal Frelick*', team: 'MIL', ab: 475 },
    { id: 'garciav01', name: 'Avisaíl García', team: 'MIA', ab: 50 },
    { id: 'gomesya01', name: 'Yan Gomes', team: 'CHC', ab: 91 },
    { id: 'hedgeau01', name: 'Austin Hedges', team: 'CLE', ab: 132 },
    { id: 'leblach01', name: 'Charles Leblanc', team: 'LAA', ab: 21 },
    { id: 'leeju01', name: 'Jung Hoo Lee*', team: 'SFG', ab: 145 },
    { id: 'lemahdj01', name: 'DJ LeMahieu', team: 'NYY', ab: 201 },
    { id: 'locklty01', name: 'Tyler Locklear', team: 'SEA', ab: 45 },
    { id: 'mailelu01', name: 'Luke Maile', team: 'CIN', ab: 135 },
    { id: 'mckenry01', name: 'Ryan McKenna', team: 'TOT', ab: 14 },
    { id: 'mckenry01', name: 'Ryan McKenna', team: 'BAL', ab: 8 },
    { id: 'mckenry01', name: 'Ryan McKenna', team: 'SFG', ab: 6 },
    { id: 'palacjo01', name: 'Joshua Palacios*', team: 'PIT', ab: 67 },
    { id: 'paulegr01', name: 'Graham Pauley*', team: 'SDP', ab: 32 },
    { id: 'pintore02', name: 'René Pinto', team: 'TBR', ab: 42 },
    { id: 'ruizes01', name: 'Esteury Ruiz', team: 'OAK', ab: 55 },
    { id: 'sanomi01', name: 'Miguel Sanó', team: 'LAA', ab: 83 },
    { id: 'schunaa01', name: 'Aaron Schunk', team: 'COL', ab: 94 },
    { id: 'scottvi01', name: 'Victor Scott II*', team: 'STL', ab: 145 },
    { id: 'sianimi01', name: 'Michael Siani*', team: 'STL', ab: 298 },
    { id: 'storytr01', name: 'Trevor Story', team: 'BOS', ab: 94 },
    { id: 'thaisma01', name: 'Matt Thaiss*', team: 'LAA', ab: 157 },
    { id: 'wagamer01', name: 'Eric Wagaman', team: 'LAA', ab: 72 },
    { id: 'wagnewi01', name: 'Will Wagner*', team: 'TOR', ab: 82 },
    { id: 'westbja02', name: 'Jamie Westbrook', team: 'BOS', ab: 40 },
    { id: 'yorkeni01', name: 'Nick Yorke', team: 'PIT', ab: 37 },
    { id: 'ahmedni01', name: 'Nick Ahmed', team: 'TOT', ab: 210 },
    { id: 'ahmedni01', name: 'Nick Ahmed', team: 'LAD', ab: 48 },
    { id: 'ahmedni01', name: 'Nick Ahmed', team: 'SDP', ab: 7 },
    { id: 'ahmedni01', name: 'Nick Ahmed', team: 'SFG', ab: 155 },
    { id: 'ramirha02', name: 'Harold Ramírez', team: 'TOT', ab: 238 },
    { id: 'ramirha02', name: 'Harold Ramírez', team: 'TBR', ab: 164 },
    { id: 'ramirha02', name: 'Harold Ramírez', team: 'WSN', ab: 74 },
    { id: 'slateau01', name: 'Austin Slater', team: 'TOT', ab: 108 },
    { id: 'slateau01', name: 'Austin Slater', team: 'TOT', ab: 177 },
    { id: 'slateau01', name: 'Austin Slater', team: 'BAL', ab: 69 },
    { id: 'slateau01', name: 'Austin Slater', team: 'CIN', ab: 18 },
    { id: 'slateau01', name: 'Austin Slater', team: 'SFG', ab: 90 },
    { id: 'adamsjo03', name: 'Jordyn Adams', team: 'LAA', ab: 35 },
    { id: 'adriaeh01', name: 'Ehire Adrianza#', team: 'LAA', ab: 26 },
    { id: 'allenni02', name: 'Nick Allen', team: 'OAK', ab: 97 },
    { id: 'barneau01', name: 'Austin Barnes', team: 'LAD', ab: 140 },
    { id: 'bertijo01', name: 'Jon Berti', team: 'NYY', ab: 66 },
    { id: 'bouchse01', name: 'Sean Bouchard', team: 'COL', ab: 91 },
    { id: 'cabbatr01', name: 'Trey Cabbage*', team: 'HOU', ab: 86 },
    { id: 'campegu01', name: 'Gustavo Campero#', team: 'LAA', ab: 46 },
    { id: 'canaral01', name: 'Alexander Canario', team: 'CHC', ab: 25 },
    { id: 'casalcu01', name: 'Curt Casali', team: 'SFG', ab: 108 },
    { id: 'clasejo01', name: 'Jonatan Clase#', team: 'TOT', ab: 61 },
    { id: 'clasejo01', name: 'Jonatan Clase#', team: 'SEA', ab: 41 },
    { id: 'clasejo01', name: 'Jonatan Clase#', team: 'TOR', ab: 20 },
    { id: 'coopega03', name: 'Garrett Cooper', team: 'TOT', ab: 107 },
    { id: 'coopega03', name: 'Garrett Cooper', team: 'BOS', ab: 70 },
    { id: 'coopega03', name: 'Garrett Cooper', team: 'CHC', ab: 37 },
    { id: 'crawfbr01', name: 'Brandon Crawford*', team: 'STL', ab: 71 },
    { id: 'dalbebo01', name: 'Bobby Dalbec', team: 'BOS', ab: 83 },
    { id: 'davishe01', name: 'Henry Davis', team: 'PIT', ab: 104 },
    { id: 'deloaza01', name: 'Zach DeLoach*', team: 'CHW', ab: 67 },
    { id: 'dingldi01', name: 'Dillon Dingler', team: 'DET', ab: 84 },
    { id: 'drisclo01', name: 'Logan Driscoll*', team: 'TBR', ab: 35 },
    { id: 'dunnbl01', name: 'Blake Dunn', team: 'CIN', ab: 26 },
    { id: 'dunnol01', name: 'Oliver Dunn*', team: 'MIL', ab: 95 },
    { id: 'edwarxa01', name: 'Xavier Edwards#', team: 'MIA', ab: 265 },
    { id: 'fletcdo01', name: 'Dominic Fletcher*', team: 'CHW', ab: 223 },
    { id: 'fordmi01', name: 'Mike Ford*', team: 'CIN', ab: 60 },
    { id: 'gamelbe01', name: 'Ben Gamel*', team: 'TOT', ab: 81 },
    { id: 'gamelbe01', name: 'Ben Gamel*', team: 'HOU', ab: 58 },
    { id: 'gamelbe01', name: 'Ben Gamel*', team: 'NYM', ab: 23 },
    { id: 'garrest01', name: 'Stone Garrett', team: 'WSN', ab: 5 },
    { id: 'harridu01', name: 'Dustin Harris*', team: 'TEX', ab: 6 },
    { id: 'henslda01', name: 'David Hensley', team: 'MIA', ab: 52 },
    { id: 'hernada04', name: 'Darell Hernaiz', team: 'OAK', ab: 120 },
    { id: 'herrejo04', name: 'José Herrera#', team: 'ARI', ab: 97 },
    { id: 'hicksaa01', name: 'Aaron Hicks#', team: 'LAA', ab: 57 },
    { id: 'jankotr01', name: 'Travis Jankowski*', team: 'TEX', ab: 190 },
    { id: 'jonesja08', name: 'Jahmai Jones', team: 'NYY', ab: 42 },
    { id: 'jonesgr02', name: 'Greg Jones#', team: 'COL', ab: 5 },
    { id: 'keirsda01', name: 'DaShawn Keirsey*', team: 'MIN', ab: 13 },
    { id: 'kennebu01', name: 'Buddy Kennedy', team: 'TOT', ab: 21 },
    { id: 'kennebu01', name: 'Buddy Kennedy', team: 'DET', ab: 10 },
    { id: 'kennebu01', name: 'Buddy Kennedy', team: 'PHI', ab: 11 },
    { id: 'kniznan01', name: 'Andrew Knizner', team: 'TEX', ab: 90 },
    { id: 'kreidry01', name: 'Ryan Kreidler', team: 'DET', ab: 59 },
    { id: 'lipsctr01', name: 'Trey Lipscomb', team: 'WSN', ab: 190 },
    { id: 'lockrbr01', name: 'Brandon Lockridge', team: 'SDP', ab: 12 },
    { id: 'loftini01', name: 'Nick Loftin', team: 'KCR', ab: 148 },
    { id: 'lopezni01', name: 'Nicky Lopez*', team: 'CHW', ab: 398 },
    { id: 'lopezja03', name: 'Jack López', team: 'LAA', ab: 67 },
    { id: 'lukesna01', name: 'Nathan Lukes*', team: 'TOR', ab: 76 },
    { id: 'madribl01', name: 'Bligh Madris*', team: 'DET', ab: 67 },
    { id: 'martiau01', name: 'Austin Martin', team: 'MIN', ab: 233 },
    { id: 'meadcu01', name: 'Curtis Mead', team: 'TBR', ab: 122 },
    { id: 'milladr01', name: 'Drew Millas#', team: 'WSN', ab: 57 },
    { id: 'monasan01', name: 'Andruw Monasterio', team: 'MIL', ab: 125 },
    { id: 'murphto04', name: 'Tom Murphy', team: 'SFG', ab: 34 },
    { id: 'nodary01', name: 'Ryan Noda*', team: 'OAK', ab: 95 },
    { id: 'pachecr01', name: 'Cristian Pache', team: 'TOT', ab: 164 },
    { id: 'pachecr01', name: 'Cristian Pache', team: 'TOT', ab: 165 },
    { id: 'pachecr01', name: 'Cristian Pache', team: 'BAL', ab: 1 },
    { id: 'pachecr01', name: 'Cristian Pache', team: 'MIA', ab: 60 },
    { id: 'pachecr01', name: 'Cristian Pache', team: 'PHI', ab: 104 },
    { id: 'parisky01', name: 'Kyren Paris', team: 'LAA', ab: 51 },
    { id: 'perazos02', name: 'Oswald Peraza', team: 'NYY', ab: 10 },
    { id: 'reetzja01', name: 'Jakson Reetz', team: 'SFG', ab: 14 },
    { id: 'saggeth01', name: 'Thomas Saggese', team: 'STL', ab: 49 },
    { id: 'shentau01', name: 'Austin Shenton*', team: 'TBR', ab: 42 },
    { id: 'shewmbr01', name: 'Braden Shewmake*', team: 'CHW', ab: 64 },
    { id: 'stubbga01', name: 'Garrett Stubbs*', team: 'PHI', ab: 164 },
    { id: 'sullibr01', name: 'Brett Sullivan*', team: 'SDP', ab: 16 },
    { id: 'vargail01', name: 'Ildemaro Vargas#', team: 'WSN', ab: 272 },
    { id: 'viladry01', name: 'Ryan Vilade', team: 'DET', ab: 45 },
    { id: 'villada01', name: 'David Villar', team: 'SFG', ab: 35 },
    { id: 'vogelda01', name: 'Daniel Vogelbach*', team: 'TOR', ab: 70 },
    { id: 'wallsta01', name: 'Taylor Walls#', team: 'TBR', ab: 218 },
    { id: 'walshja01', name: 'Jared Walsh*', team: 'TEX', ab: 53 },
    { id: 'waltodo01', name: 'Donovan Walton*', team: 'SFG', ab: 22 },
    { id: 'wendzda01', name: 'Davis Wendzel', team: 'TEX', ab: 47 },
    { id: 'whiteel04', name: 'Eli White', team: 'ATL', ab: 39 },
    { id: 'zavalse01', name: 'Seby Zavala', team: 'SEA', ab: 39 },
    { id: 'alcanke01', name: 'Kevin Alcántara', team: 'CHC', ab: 10 },
    { id: 'alexacj01', name: 'CJ Alexander*', team: 'KCR', ab: 8 },
    { id: 'alvarna01', name: 'Nacho Alvarez Jr.', team: 'ATL', ab: 30 },
    { id: 'alvared01', name: 'Eddy Alvarez*', team: 'NYM', ab: 9 },
    { id: 'alvarar01', name: 'Armando Alvarez', team: 'OAK', ab: 37 },
    { id: 'amadoad01', name: 'Adael Amador#', team: 'COL', ab: 35 },
    { id: 'amayaja01', name: 'Jacob Amaya', team: 'TOT', ab: 68 },
    { id: 'amayaja01', name: 'Jacob Amaya', team: 'CHW', ab: 67 },
    { id: 'amayaja01', name: 'Jacob Amaya', team: 'HOU', ab: 1 },
    { id: 'anderti01', name: 'Tim Anderson', team: 'MIA', ab: 234 },
    { id: 'anderbr06', name: 'Brian Anderson', team: 'ATL', ab: 5 },
    { id: 'anderch01', name: 'Chase Anderson', team: 'BOS', ab: 0 },
    { id: 'avilape01', name: 'Pedro Avila', team: 'CLE', ab: 0 },
    { id: 'azocajo01', name: 'José Azocar', team: 'SDP', ab: 73 },
    { id: 'baeji01', name: 'Ji Hwan Bae*', team: 'PIT', ab: 74 },
    { id: 'bakerda02', name: 'Darren Baker*', team: 'WSN', ab: 14 },
    { id: 'banueda01', name: 'David Bañuelos', team: 'BAL', ab: 1 },
    { id: 'barnhtu01', name: 'Tucker Barnhart*', team: 'ARI', ab: 81 },
    { id: 'barrojo01', name: 'Jorge Barrosa#', team: 'ARI', ab: 17 },
    { id: 'battema01', name: 'Matthew Batten', team: 'SDP', ab: 3 },
    { id: 'baumami01', name: 'Mike Baumann', team: 'TOT', ab: 0 },
    { id: 'baumami01', name: 'Mike Baumann', team: 'BAL', ab: 0 },
    { id: 'baumami01', name: 'Mike Baumann', team: 'SEA', ab: 0 },
    { id: 'beeksja02', name: 'Jalen Beeks*', team: 'COL', ab: 0 },
    { id: 'bernabr01', name: 'Brennan Bernardino*', team: 'BOS', ab: 0 },
    { id: 'berrost01', name: 'Steward Berroa#', team: 'TOR', ab: 37 },
    { id: 'blackty01', name: 'Tyler Black*', team: 'MIL', ab: 49 },
    { id: 'blanktr01', name: 'Travis Blankenhorn*', team: 'WSN', ab: 31 },
    { id: 'boteda01', name: 'David Bote', team: 'CHC', ab: 46 },
    { id: 'brantro01', name: 'Rob Brantly*', team: 'TBR', ab: 9 },
    { id: 'brebbjo01', name: 'John Brebbia*', team: 'CHW', ab: 0 },
    { id: 'britojh01', name: 'Jhony Brito', team: 'SDP', ab: 0 },
    { id: 'brooktr01', name: 'Trenton Brooks*', team: 'SFG', ab: 25 },
    { id: 'bubickr01', name: 'Kris Bubic*', team: 'KCR', ab: 0 },
    { id: 'cabrege01', name: 'Génesis Cabrera*', team: 'TOR', ab: 0 },
    { id: 'camarja01', name: 'Jair Camargo', team: 'MIN', ab: 6 },
    { id: 'campbis01', name: 'Isaiah Campbell', team: 'BOS', ab: 0 },
    { id: 'capelco01', name: 'Conner Capel*', team: 'CIN', ab: 8 },
    { id: 'capravi01', name: 'Vinny Capra', team: 'MIL', ab: 9 },
    { id: 'castidi02', name: 'Diego Castillo', team: 'MIN', ab: 6 },
    { id: 'castilu02', name: 'Luis Castillo', team: 'SEA', ab: 1 },
    { id: 'colasos01', name: 'Oscar Colás*', team: 'CHW', ab: 33 },
    { id: 'colliis01', name: 'Isaac Collins#', team: 'MIL', ab: 17 },
    { id: 'couloda01', name: 'Danny Coulombe*', team: 'BAL', ab: 0 },
    { id: 'criswje01', name: 'Jeff Criswell', team: 'COL', ab: 0 },
    { id: 'cruzfe01', name: 'Fernando Cruz#', team: 'CIN', ab: 0 },
    { id: 'delayja01', name: 'Jason Delay', team: 'PIT', ab: 15 },
    { id: 'deloslu03', name: 'Luis De Los Santos', team: 'TOR', ab: 29 },
    { id: 'deverjo01', name: 'José Devers*', team: 'MIA', ab: 4 },
    { id: 'diazed04', name: 'Edwin Díaz', team: 'NYM', ab: 0 },
    { id: 'diazal02', name: 'Aledmys Díaz', team: 'TOT', ab: 33 },
    { id: 'diazal02', name: 'Aledmys Díaz', team: 'HOU', ab: 4 },
    { id: 'diazal02', name: 'Aledmys Díaz', team: 'OAK', ab: 29 },
    { id: 'diazal03', name: 'Alexis Díaz', team: 'CIN', ab: 0 },
    { id: 'diekmja01', name: 'Jake Diekman', team: 'NYM', ab: 0 },
    { id: 'dominse01', name: 'Seranthony Domínguez', team: 'BAL', ab: 0 },
    { id: 'duffyma01', name: 'Matt Duffy', team: 'TEX', ab: 7 },
    { id: 'ellisdu01', name: 'Duke Ellis*', team: 'TOT', ab: 5 },
    { id: 'ellisdu01', name: 'Duke Ellis*', team: 'CHW', ab: 4 },
    { id: 'ellisdu01', name: 'Duke Ellis*', team: 'NYY', ab: 1 },
    { id: 'englema01', name: 'Mason Englert#', team: 'DET', ab: 0 },
    { id: 'fabiasa01', name: 'Sandro Fabian', team: 'TEX', ab: 5 },
    { id: 'farmebu01', name: 'Buck Farmer*', team: 'CIN', ab: 0 },
    { id: 'feduchu01', name: 'Hunter Feduccia*', team: 'LAD', ab: 12 },
    { id: 'fermijo01', name: 'José Fermín', team: 'STL', ab: 71 },
    { id: 'fernary01', name: 'Ryan Fernandez', team: 'STL', ab: 0 },
    { id: 'finneky01', name: 'Kyle Finnegan', team: 'WSN', ab: 0 },
    { id: 'fletcda02', name: 'David Fletcher', team: 'ATL', ab: 8 },
    { id: 'foleyja01', name: 'Jason Foley', team: 'DET', ab: 0 },
    { id: 'foscuju01', name: 'Justin Foscue', team: 'TEX', ab: 42 },
    { id: 'freelky01', name: 'Kyle Freeland*', team: 'COL', ab: 0 },
    { id: 'friaslu01', name: 'Luis Frías', team: 'ARI', ab: 0 },
    { id: 'gaddihu01', name: 'Hunter Gaddis', team: 'CLE', ab: 0 },
    { id: 'garciar01', name: 'Aramis Garcia', team: 'PHI', ab: 7 },
    { id: 'gaspemi01', name: 'Mickey Gasper#', team: 'BOS', ab: 18 },
    { id: 'gentrty01', name: 'Tyler Gentry', team: 'KCR', ab: 5 },
    { id: 'ginkeke01', name: 'Kevin Ginkel*', team: 'ARI', ab: 0 },
    { id: 'goodrni01', name: 'Niko Goodrum#', team: 'TOT', ab: 29 },
    { id: 'goodrni01', name: 'Niko Goodrum#', team: 'LAA', ab: 13 },
    { id: 'goodrni01', name: 'Niko Goodrum#', team: 'TBR', ab: 16 },
    { id: 'gourryu01', name: 'Yuli Gurriel', team: 'KCR', ab: 54 },
    { id: 'graytr01', name: 'Tristan Gray*', team: 'TOT', ab: 28 },
    { id: 'graytr01', name: 'Tristan Gray*', team: 'MIA', ab: 7 },
    { id: 'graytr01', name: 'Tristan Gray*', team: 'OAK', ab: 21 },
    { id: 'greench03', name: 'Chad Green*', team: 'TOR', ab: 0 },
    { id: 'grissva01', name: 'Vaughn Grissom', team: 'BOS', ab: 105 },
    { id: 'guilllu01', name: 'Luis Guillorme*', team: 'TOT', ab: 57 },
    { id: 'guilllu01', name: 'Luis Guillorme*', team: 'TOT', ab: 161 },
    { id: 'guilllu01', name: 'Luis Guillorme*', team: 'ARI', ab: 37 },
    { id: 'guilllu01', name: 'Luis Guillorme*', team: 'ATL', ab: 20 },
    { id: 'guilllu01', name: 'Luis Guillorme*', team: 'LAA', ab: 104 },
    { id: 'haderjo01', name: 'Josh Hader*', team: 'HOU', ab: 0 },
    { id: 'haggesa01', name: 'Sam Haggerty#', team: 'SEA', ab: 15 },
    { id: 'halvose01', name: 'Seth Halvorsen', team: 'COL', ab: 0 },
    { id: 'hampsga01', name: 'Garrett Hampson', team: 'KCR', ab: 213 },
    { id: 'harvehu01', name: 'Hunter Harvey', team: 'KCR', ab: 0 },
    { id: 'heasljo01', name: 'Jonathan Heasley', team: 'BAL', ab: 0 },
    { id: 'heinety01', name: 'Tyler Heineman#', team: 'TOT', ab: 12 },
    { id: 'heinety01', name: 'Tyler Heineman#', team: 'BOS', ab: 2 },
    { id: 'heinety01', name: 'Tyler Heineman#', team: 'TOR', ab: 10 },
    { id: 'helmami01', name: 'Michael Helman', team: 'MIN', ab: 10 },
    { id: 'helslry01', name: 'Ryan Helsley', team: 'STL', ab: 0 },
    { id: 'hergeke01', name: 'Kevin Herget*', team: 'MIL', ab: 0 },
    { id: 'hernajo02', name: 'Jonathan Hernández', team: 'TEX', ab: 0 },
    { id: 'hicklbr01', name: 'Brewer Hicklen', team: 'MIL', ab: 5 },
    { id: 'hiurake01', name: 'Keston Hiura', team: 'LAA', ab: 27 },
    { id: 'hodgepo01', name: 'Porter Hodge', team: 'CHC', ab: 0 },
    { id: 'howarsp01', name: 'Spencer Howard', team: 'CLE', ab: 0 },
    { id: 'hudsojo03', name: 'Joe Hudson', team: 'NYM', ab: 0 },
    { id: 'huffsa01', name: 'Sam Huff', team: 'TEX', ab: 3 },
    { id: 'hummeco01', name: 'Cooper Hummel#', team: 'HOU', ab: 8 },
    { id: 'hurtuja01', name: 'Jacob Hurtubise*', team: 'CIN', ab: 54 },
    { id: 'janseke01', name: 'Kenley Jansen#', team: 'BOS', ab: 0 },
    { id: 'jarvibr01', name: 'Bryce Jarvis*', team: 'ARI', ab: 0 },
    { id: 'johnsbr03', name: 'Bryce Johnson#', team: 'SDP', ab: 63 },
    { id: 'johnsda07', name: 'Daniel Johnson*', team: 'BAL', ab: 1 },
    { id: 'jordale01', name: 'Levi Jordan', team: 'CIN', ab: 10 },
    { id: 'jungja01', name: 'Jace Jung*', team: 'DET', ab: 79 },
    { id: 'kempto01', name: 'Tony Kemp*', team: 'BAL', ab: 9 },
    { id: 'kessigr01', name: 'Grae Kessinger', team: 'HOU', ab: 21 },
    { id: 'kimbrcr01', name: 'Craig Kimbrel', team: 'BAL', ab: 0 },
    { id: 'kingbr02', name: 'Bryan King', team: 'HOU', ab: 0 },
    { id: 'kingjo01', name: 'John King*', team: 'STL', ab: 0 },
    { id: 'kinlety01', name: 'Tyler Kinley', team: 'COL', ab: 0 },
    { id: 'kittran01', name: 'Andrew Kittredge', team: 'STL', ab: 0 },
    { id: 'knappan01', name: 'Andrew Knapp#', team: 'SFG', ab: 6 },
    { id: 'kochgr01', name: 'Grant Koch', team: 'PIT', ab: 7 },
    { id: 'kochma01', name: 'Matt Koch*', team: 'COL', ab: 0 },
    { id: 'kopecmi01', name: 'Michael Kopech', team: 'CHW', ab: 0 },
    { id: 'lambepe01', name: 'Peter Lambert', team: 'COL', ab: 0 },
    { id: 'latzja01', name: 'Jacob Latz', team: 'TEX', ab: 0 },
    { id: 'lawde01', name: 'Derek Law', team: 'WSN', ab: 0 },
    { id: 'lawreju01', name: 'Justin Lawrence', team: 'COL', ab: 0 },
    { id: 'leahyky01', name: 'Kyle Leahy#', team: 'STL', ab: 0 },
    { id: 'leclejo01', name: 'José Leclerc', team: 'TEX', ab: 0 },
    { id: 'leonpe01', name: 'Pedro León', team: 'HOU', ab: 20 },
    { id: 'lopezjo02', name: 'Jorge López', team: 'NYM', ab: 0 },
    { id: 'luciama01', name: 'Marco Luciano', team: 'SFG', ab: 76 },
    { id: 'madrini01', name: 'Nick Madrigal', team: 'CHC', ab: 86 },
    { id: 'mantijo01', name: 'Joe Mantiply', team: 'ARI', ab: 0 },
    { id: 'marloca01', name: 'Cade Marlowe*', team: 'SEA', ab: 8 },
    { id: 'martior01', name: 'Orelvis Martínez', team: 'TOR', ab: 3 },
    { id: 'martiju01', name: 'Justin Martínez', team: 'ARI', ab: 0 },
    { id: 'martich02', name: 'Chris Martin', team: 'BOS', ab: 0 },
    { id: 'martijp01', name: 'J.P. Martínez*', team: 'ATL', ab: 10 },
    { id: 'mastrmi01', name: 'Miles Mastrobuoni*', team: 'CHC', ab: 98 },
    { id: 'matonni01', name: 'Nick Maton*', team: 'BAL', ab: 5 },
    { id: 'mayoco01', name: 'Coby Mayo', team: 'BAL', ab: 41 },
    { id: 'mcartja01', name: 'James McArthur', team: 'KCR', ab: 0 },
    { id: 'mccoyma01', name: 'Mason McCoy', team: 'SDP', ab: 49 },
    { id: 'mcgousc01', name: 'Scott McGough', team: 'ARI', ab: 1 },
    { id: 'mckinbi01', name: 'Billy McKinney*', team: 'PIT', ab: 25 },
    { id: 'mearsni01', name: 'Nick Mears', team: 'COL', ab: 0 },
    { id: 'megiltr01', name: 'Trevor Megill*', team: 'MIL', ab: 0 },
    { id: 'merryju01', name: 'Julian Merryweather', team: 'CHC', ab: 0 },
    { id: 'mervima01', name: 'Matt Mervis*', team: 'CHC', ab: 26 },
    { id: 'milleow01', name: 'Owen Miller', team: 'MIL', ab: 27 },
    { id: 'milneho01', name: 'Hoby Milner*', team: 'MIL', ab: 0 },
    { id: 'misneka01', name: 'Kameron Misner*', team: 'TBR', ab: 15 },
    { id: 'moncayo01', name: 'Yoán Moncada#', team: 'CHW', ab: 40 },
    { id: 'narvaom01', name: 'Omar Narváez*', team: 'NYM', ab: 65 },
    { id: 'narvaca01', name: 'Carlos Narváez', team: 'NYY', ab: 13 },
    { id: 'nerishe01', name: 'Héctor Neris', team: 'CHC', ab: 0 },
    { id: 'nunezna01', name: 'Nasim Nuñez#', team: 'WSN', ab: 61 },
    { id: 'orneljo01', name: 'Jonathan Ornelas', team: 'TEX', ab: 37 },
    { id: 'ortegra01', name: 'Rafael Ortega*', team: 'CHW', ab: 14 },
    { id: 'payamjo01', name: 'Joel Payamps', team: 'MIL', ab: 0 },
    { id: 'pegueel01', name: 'Elvis Peguero', team: 'MIL', ab: 0 },
    { id: 'pegueli01', name: 'Liover Peguero', team: 'PIT', ab: 10 },
    { id: 'penroza01', name: 'Zach Penrod*', team: 'BOS', ab: 0 },
    { id: 'peredjh01', name: 'Jhonny Pereda', team: 'MIA', ab: 39 },
    { id: 'peterja01', name: 'Jace Peterson*', team: 'ARI', ab: 22 },
    { id: 'pressry01', name: 'Ryan Pressly', team: 'HOU', ab: 0 },
    { id: 'pukaj01', name: 'A.J. Puk*', team: 'ARI', ab: 0 },
    { id: 'quijajo01', name: 'José Quijada*', team: 'LAA', ab: 0 },
    { id: 'remilza01', name: 'Zach Remillard', team: 'CHW', ab: 33 },
    { id: 'rendoan01', name: 'Anthony Rendon', team: 'LAA', ab: 206 },
    { id: 'reyespa01', name: 'Pablo Reyes', team: 'TOT', ab: 60 },
    { id: 'reyespa01', name: 'Pablo Reyes', team: 'BOS', ab: 60 },
    { id: 'reyespa01', name: 'Pablo Reyes', team: 'NYM', ab: 0 },
    { id: 'riosed01', name: 'Edwin Ríos*', team: 'CIN', ab: 9 },
    { id: 'rivasle01', name: 'Leo Rivas#', team: 'SEA', ab: 73 },
    { id: 'roberda08', name: 'David Robertson', team: 'TEX', ab: 0 },
    { id: 'robinch04', name: 'Chuckie Robinson', team: 'CHW', ab: 70 },
    { id: 'rodriye01', name: 'Yerry Rodríguez', team: 'TEX', ab: 0 },
    { id: 'rodrijo10', name: 'Johnathan Rodríguez', team: 'CLE', ab: 31 },
    { id: 'rollech01', name: 'Chris Roller', team: 'MIL', ab: 1 },
    { id: 'romerjo01', name: 'JoJo Romero*', team: 'STL', ab: 0 },
    { id: 'romodr01', name: 'Drew Romo#', team: 'COL', ab: 51 },
    { id: 'sabolbl01', name: 'Blake Sabol*', team: 'SFG', ab: 32 },
    { id: 'salazce01', name: 'César Salazar*', team: 'HOU', ab: 25 },
    { id: 'sanchal04', name: 'Alí Sánchez', team: 'MIA', ab: 84 },
    { id: 'sanojja01', name: 'Javier Sanoja', team: 'MIA', ab: 35 },
    { id: 'servebr01', name: 'Brian Serven', team: 'TOR', ab: 63 },
    { id: 'sewalpa01', name: 'Paul Sewald', team: 'ARI', ab: 0 },
    { id: 'shortza01', name: 'Zack Short', team: 'TOT', ab: 63 },
    { id: 'shortza01', name: 'Zack Short', team: 'TOT', ab: 70 },
    { id: 'shortza01', name: 'Zack Short', team: 'ATL', ab: 54 },
    { id: 'shortza01', name: 'Zack Short', team: 'BOS', ab: 7 },
    { id: 'shortza01', name: 'Zack Short', team: 'NYM', ab: 9 },
    { id: 'shugach01', name: 'Chase Shugart*', team: 'BOS', ab: 0 },
    { id: 'simslu01', name: 'Lucas Sims', team: 'CIN', ab: 0 },
    { id: 'smithke05', name: 'Kevin Smith', team: 'NYY', ab: 0 },
    { id: 'sogarni01', name: 'Nick Sogard#', team: 'BOS', ab: 77 },
    { id: 'sotoli01', name: 'Liván Soto*', team: 'TOT', ab: 13 },
    { id: 'sotoli01', name: 'Liván Soto*', team: 'BAL', ab: 10 },
    { id: 'sotoli01', name: 'Liván Soto*', team: 'CIN', ab: 3 },
    { id: 'stanery01', name: 'Ryne Stanek', team: 'SEA', ab: 0 },
    { id: 'stefami01', name: 'Michael Stefanic', team: 'LAA', ab: 110 },
    { id: 'steveca01', name: 'Cal Stevenson*', team: 'PHI', ab: 24 },
    { id: 'strawmy01', name: 'Myles Straw', team: 'CLE', ab: 4 },
    { id: 'suareal01', name: 'Albert Suárez', team: 'BAL', ab: 0 },
    { id: 'taylosa04', name: 'Samad Taylor', team: 'SEA', ab: 5 },
    { id: 'teodobr01', name: 'Bryce Teodosio', team: 'LAA', ab: 12 },
    { id: 'thompbu01', name: 'Bubba Thompson', team: 'CIN', ab: 18 },
    { id: 'thompry02', name: 'Ryan Thompson', team: 'ARI', ab: 0 },
    { id: 'thorntr01', name: 'Trent Thornton', team: 'SEA', ab: 0 },
    { id: 'trammta01', name: 'Taylor Trammell*', team: 'TOT', ab: 7 },
    { id: 'trammta01', name: 'Taylor Trammell*', team: 'LAD', ab: 6 },
    { id: 'trammta01', name: 'Taylor Trammell*', team: 'NYY', ab: 1 },
    { id: 'trejoal01', name: 'Alan Trejo', team: 'COL', ab: 63 },
    { id: 'trompch01', name: 'Chadwick Tromp', team: 'ATL', ab: 52 },
    { id: 'tuckeco01', name: 'Cole Tucker#', team: 'LAA', ab: 50 },
    { id: 'urenajo01', name: 'José Ureña', team: 'TEX', ab: 0 },
    { id: 'vazqulu01', name: 'Luis Vázquez', team: 'CHC', ab: 12 },
    { id: 'vodnivi01', name: 'Victor Vodnik', team: 'COL', ab: 0 },
    { id: 'vosleja01', name: 'Jason Vosler*', team: 'SEA', ab: 28 },
    { id: 'vothau01', name: 'Austin Voth', team: 'SEA', ab: 0 },
    { id: 'wadety01', name: 'Tyler Wade*', team: 'SDP', ab: 138 },
    { id: 'wallfo01', name: 'Forrest Wall*', team: 'TOT', ab: 32 },
    { id: 'wallfo01', name: 'Forrest Wall*', team: 'ATL', ab: 29 },
    { id: 'wallfo01', name: 'Forrest Wall*', team: 'MIA', ab: 3 },
    { id: 'waterdr01', name: 'Drew Waters#', team: 'KCR', ab: 16 },
    { id: 'webbja01', name: 'Jacob Webb', team: 'BAL', ab: 0 },
    { id: 'wendljo01', name: 'Joey Wendle*', team: 'NYM', ab: 36 },
    { id: 'whitcsh01', name: 'Shay Whitcomb', team: 'HOU', ab: 41 },
    { id: 'whitemi03', name: 'Mitch White', team: 'MIL', ab: 0 },
    { id: 'whiteow01', name: 'Owen White', team: 'TEX', ab: 0 },
    { id: 'wiemejo01', name: 'Joey Wiemer', team: 'TOT', ab: 26 },
    { id: 'wiemejo01', name: 'Joey Wiemer', team: 'CIN', ab: 0 },
    { id: 'wiemejo01', name: 'Joey Wiemer', team: 'MIL', ab: 26 },
    { id: 'willilu01', name: 'Luke Williams', team: 'ATL', ab: 46 },
    { id: 'willial04', name: 'Alika Williams', team: 'PIT', ab: 87 },
    { id: 'wilsoju10', name: 'Justin Wilson*', team: 'CIN', ab: 0 },
    { id: 'wilsoja05', name: 'Jacob Wilson', team: 'OAK', ab: 92 },
    { id: 'winckjo01', name: 'Josh Winckowski', team: 'BOS', ab: 0 },
    { id: 'wynnsau01', name: 'Austin Wynns', team: 'CIN', ab: 19 },
    { id: 'yanger01', name: 'Eric Yang', team: 'CIN', ab: 1 },
    { id: 'yateski01', name: 'Kirby Yates*', team: 'TEX', ab: 0 },
    { id: 'youngal01', name: 'Alex Young*', team: 'CIN', ab: 0 },
    { id: 'zuniggu01', name: 'Guillo Zuñiga', team: 'LAA', ab: 0 },
];

export function convertToCsv() {
    const hittersOnIndividualTeams: HittersOnIndividualTeams[] = [];

    allHitters.forEach(indTeam => {
        if (indTeam.team !== 'TOT' && multiTeamHitters[indTeam.id]) {
            const nameParts = multiTeamHitters[indTeam.id].name.split(', ');
            hittersOnIndividualTeams.push({
                year: 2024,
                name: nameParts[0] + ',' + nameParts[1][0],
                bats: multiTeamHitters[indTeam.id].bats,
                team: indTeam.team,
                ab: indTeam.ab,
            });
        }
    });

    return hittersOnIndividualTeams;
}
