type MultiTeamHitters = {
    name: string;
    team: string;
    bats: string;
    ab: number;
};

type AllHitters = {
    id: string;
    name: string;
    team: string;
    ab: number;
};

type HittersOnIndividualTeams = {
    year: number;
    name: string;
    bats: string;
    team: string;
    ab: number;
};

const multiTeamHitters: Record<string, MultiTeamHitters> = {
    // paste here the formatted column from the 'Carded' sheet of the 'Hitter_Stats_20xx.xlsx' file... only the hitters whose team is 'TOT'
    andujmi01: { name: 'Andujar, Miguel', team: 'TOT', bats: 'R', ab: 321 },
    arciaor01: { name: 'Arcia, Orlando', team: 'TOT', bats: 'R', ab: 203 },
    baderha01: { name: 'Bader, Harrison', team: 'TOT', bats: 'R', ab: 448 },
    bridejo01: { name: 'Bride, Jonah', team: 'TOT', bats: 'R', ab: 112 },
    cabaljo01: { name: 'Caballero, Jose', team: 'TOT', bats: 'R', ab: 314 },
    callal02: { name: 'Call, Alex', team: 'TOT', bats: 'R', ab: 270 },
    castrwi01: { name: 'Castro, Willi', team: 'TOT', bats: 'S', ab: 402 },
    clemeko01: { name: 'Clemens, Kody', team: 'TOT', bats: 'L', ab: 348 },
    correca01: { name: 'Correa, Carlos', team: 'TOT', bats: 'R', ab: 537 },
    deverra01: { name: 'Devers, Rafael', team: 'TOT', bats: 'L', ab: 607 },
    fermifr01: { name: 'Fermin, Freddy', team: 'TOT', bats: 'R', ab: 319 },
    forteni01: { name: 'Fortes, Nick', team: 'TOT', bats: 'R', ab: 218 },
    fraleja01: { name: 'Fraley, Jake', team: 'TOT', bats: 'L', ab: 191 },
    francty01: { name: 'France, Ty', team: 'TOT', bats: 'R', ab: 444 },
    fraziad01: { name: 'Frazier, Adam', team: 'TOT', bats: 'L', ab: 419 },
    grichra01: { name: 'Grichuk, Randal', team: 'TOT', bats: 'R', ab: 272 },
    hayeske01: { name: 'Hayes, Ke\'Bryan', team: 'TOT', bats: 'R', ab: 527 },
    hillde01: { name: 'Hill, Derek', team: 'TOT', bats: 'R', ab: 134 },
    janseda01: { name: 'Jansen, Danny', team: 'TOT', bats: 'R', ab: 288 },
    kimha01: { name: 'Kim, Ha-Seong', team: 'TOT', bats: 'R', ab: 171 },
    kineris01: { name: 'Kiner-Falefa, Isiah', team: 'TOT', bats: 'R', ab: 431 },
    laurera01: { name: 'Laureano, Ramon', team: 'TOT', bats: 'R', ab: 441 },
    lockrbr01: { name: 'Lockridge, Brandon', team: 'TOT', bats: 'R', ab: 134 },
    lowena01: { name: 'Lowe, Nathaniel', team: 'TOT', bats: 'L', ab: 540 },
    mcmahry01: { name: 'McMahon, Ryan', team: 'TOT', bats: 'L', ab: 509 },
    meadcu01: { name: 'Mead, Curtis', team: 'TOT', bats: 'R', ab: 240 },
    mooredy01: { name: 'Moore, Dylan', team: 'TOT', bats: 'R', ab: 219 },
    mullice01: { name: 'Mullins, Cedric', team: 'TOT', bats: 'L', ab: 435 },
    naylojo01: { name: 'Naylor, Josh', team: 'TOT', bats: 'L', ab: 543 },
    ohearry01: { name: 'O\'Hearn, Ryan', team: 'TOT', bats: 'L', ab: 474 },
    outmaja01: { name: 'Outman, James', team: 'TOT', bats: 'L', ab: 134 },
    perazos02: { name: 'Peraza, Oswald', team: 'TOT', bats: 'R', ab: 244 },
    rodenal01: { name: 'Roden, Alan', team: 'TOT', bats: 'L', ab: 136 },
    rortvbe01: { name: 'Rortvedt, Ben', team: 'TOT', bats: 'L', ab: 112 },
    rosaram01: { name: 'Rosario, Amed', team: 'TOT', bats: 'R', ab: 181 },
    sanchje02: { name: 'Sanchez, Jesus', team: 'TOT', bats: 'L', ab: 451 },
    santaca01: { name: 'Santana, Carlos', team: 'TOT', bats: 'S', ab: 415 },
    slateau01: { name: 'Slater, Austin', team: 'TOT', bats: 'R', ab: 148 },
    solando01: { name: 'Solano, Donovan', team: 'TOT', bats: 'R', ab: 166 },
    stallja01: { name: 'Stallings, Jacob', team: 'TOT', bats: 'R', ab: 119 },
    suareeu01: { name: 'Suarez, Eugenio', team: 'TOT', bats: 'R', ab: 588 },
    taverle01: { name: 'Taveras, Leody', team: 'TOT', bats: 'S', ab: 171 },
    tayloch03: { name: 'Taylor, Chris', team: 'TOT', bats: 'R', ab: 113 },
    tellero01: { name: 'Tellez, Rowdy', team: 'TOT', bats: 'L', ab: 289 },
    thaisma01: { name: 'Thaiss, Matt', team: 'TOT', bats: 'L', ab: 156 },
    uriasra01: { name: 'Urias, Ramon', team: 'TOT', bats: 'R', ab: 352 },
    vaughan01: { name: 'Vaughn, Andrew', team: 'TOT', bats: 'R', ab: 406 },
    wadela01: { name: 'Wade Jr, LaMonte', team: 'TOT', bats: 'L', ab: 209 },
    wagnewi01: { name: 'Wagner, Will', team: 'TOT', bats: 'L', ab: 129 },
    wynnsau01: { name: 'Wynns, Austin', team: 'TOT', bats: 'R', ab: 103 },
    yastrmi01: { name: 'Yastrzemski, Mike', team: 'TOT', bats: 'L', ab: 477 },
};

const allHitters: AllHitters[] = [
    // paste here the formatted column from the 'Original_with_Ind_Teams' sheet of the 'Hitter_Stats_20xx.xlsx' file... including all hitters
    { id: 'alexabl01', name: 'Alexander, Blaze', team: 'ARI', ab: 230 },
    { id: 'backhky01', name: 'Backhus, Kyle', team: 'ARI', ab: 0 },
    { id: 'barrojo01', name: 'Barrosa, Jorge', team: 'ARI', ab: 71 },
    { id: 'carroco02', name: 'Carroll, Corbin', team: 'ARI', ab: 564 },
    { id: 'curtijo02', name: 'Curtiss, John', team: 'ARI', ab: 0 },
    { id: 'delcaad01', name: 'Del Castillo, Adrian', team: 'ARI', ab: 120 },
    { id: 'englitr01', name: 'English, Tristin', team: 'ARI', ab: 22 },
    { id: 'garciar01', name: 'Garcia, Aramis', team: 'ARI', ab: 4 },
    { id: 'garcibr02', name: 'Garcia, Brandyn', team: 'ARI', ab: 0 },
    { id: 'grichra01', name: 'Grichuk, Randal', team: 'ARI', ab: 175 },
    { id: 'gurrilo01', name: 'Gurriel Jr, Lourdes', team: 'ARI', ab: 500 },
    { id: 'hampsga01', name: 'Hampson, Garrett', team: 'ARI', ab: 30 },
    { id: 'herrejo04', name: 'Herrera, Jose', team: 'ARI', ab: 166 },
    { id: 'jamesdr01', name: 'Jameson, Drey', team: 'ARI', ab: 0 },
    { id: 'kaiseco01', name: 'Kaiser, Connor', team: 'ARI', ab: 18 },
    { id: 'lawlajo01', name: 'Lawlar, Jordan', team: 'ARI', ab: 66 },
    { id: 'locklty01', name: 'Locklear, Tyler', team: 'ARI', ab: 103 },
    { id: 'mantijo01', name: 'Mantiply, Joe', team: 'ARI', ab: 0 },
    { id: 'marteke01', name: 'Marte, Ketel', team: 'ARI', ab: 480 },
    { id: 'martiju01', name: 'Martinez, Justin', team: 'ARI', ab: 0 },
    { id: 'mccanja02', name: 'McCann, James', team: 'ARI', ab: 123 },
    { id: 'mccarja02', name: 'McCarthy, Jake', team: 'ARI', ab: 206 },
    { id: 'millesh01', name: 'Miller, Shelby', team: 'ARI', ab: 0 },
    { id: 'morenga01', name: 'Moreno, Gabriel', team: 'ARI', ab: 277 },
    { id: 'morilju02', name: 'Morillo, Juan', team: 'ARI', ab: 0 },
    { id: 'naylojo01', name: 'Naylor, Josh', team: 'ARI', ab: 349 },
    { id: 'nelsory01', name: 'Nelson, Ryne', team: 'ARI', ab: 1 },
    { id: 'perdoge01', name: 'Perdomo, Geraldo', team: 'ARI', ab: 597 },
    { id: 'pukaj01', name: 'Puk, AJ', team: 'ARI', ab: 0 },
    { id: 'saalfan01', name: 'Saalfrank, Andrew', team: 'ARI', ab: 0 },
    { id: 'smithpa04', name: 'Smith, Pavin', team: 'ARI', ab: 244 },
    { id: 'suareeu01', name: 'Suarez, Eugenio', team: 'ARI', ab: 387 },
    { id: 'tawati01', name: 'Tawa, Tim', team: 'ARI', ab: 199 },
    { id: 'thomaal01', name: 'Thomas, Alek', team: 'ARI', ab: 433 },
    { id: 'thompry02', name: 'Thompson, Ryan', team: 'ARI', ab: 0 },
    { id: 'vargail01', name: 'Vargas, Ildemaro', team: 'ARI', ab: 115 },
    { id: 'alexacj01', name: 'Alexander, CJ', team: 'ATH', ab: 17 },
    { id: 'alvarel01', name: 'Alvarado, Elvis', team: 'ATH', ab: 0 },
    { id: 'andujmi01', name: 'Andujar, Miguel', team: 'ATH', ab: 218 },
    { id: 'avansdr01', name: 'Avans, Drew', team: 'ATH', ab: 15 },
    { id: 'bledajj01', name: 'Bleday, JJ', team: 'ATH', ab: 307 },
    { id: 'brownse01', name: 'Brown, Seth', team: 'ATH', ab: 65 },
    { id: 'butlela01', name: 'Butler, Lawrence', team: 'ATH', ab: 569 },
    { id: 'clarkde02', name: 'Clarke, Denzel', team: 'ATH', ab: 148 },
    { id: 'corteca01', name: 'Cortes, Carlos', team: 'ATH', ab: 94 },
    { id: 'davidlo01', name: 'Davidson, Logan', team: 'ATH', ab: 20 },
    { id: 'ferguty01', name: 'Ferguson, Tyler', team: 'ATH', ab: 0 },
    { id: 'gelofza01', name: 'Gelof, Zack', team: 'ATH', ab: 92 },
    { id: 'harribr02', name: 'Harris, Brett', team: 'ATH', ab: 73 },
    { id: 'hernada04', name: 'Hernaiz, Darell', team: 'ATH', ab: 173 },
    { id: 'kellymi03', name: 'Kelly, Michael', team: 'ATH', ab: 0 },
    { id: 'kurtzni01', name: 'Kurtz, Nick', team: 'ATH', ab: 420 },
    { id: 'langesh01', name: 'Langeliers, Shea', team: 'ATH', ab: 481 },
    { id: 'macivwi01', name: 'MacIver, Willie', team: 'ATH', ab: 102 },
    { id: 'muncyma02', name: 'Muncy, Max', team: 'ATH', ab: 206 },
    { id: 'peredjh01', name: 'Pereda, Jhonny', team: 'ATH', ab: 40 },
    { id: 'rookebr01', name: 'Rooker, Brent', team: 'ATH', ab: 626 },
    { id: 'schuema01', name: 'Schuemann, Max', team: 'ATH', ab: 183 },
    { id: 'soderty01', name: 'Soderstrom, Tyler', team: 'ATH', ab: 561 },
    { id: 'thomaco03', name: 'Thomas, Colby', team: 'ATH', ab: 120 },
    { id: 'uriaslu01', name: 'Urias, Luis', team: 'ATH', ab: 287 },
    { id: 'urshegi01', name: 'Urshela, Gio', team: 'ATH', ab: 181 },
    { id: 'wilsoja05', name: 'Wilson, Jacob', team: 'ATH', ab: 486 },
    { id: 'wynnsau01', name: 'Wynns, Austin', team: 'ATH', ab: 63 },
    { id: 'acunaro01', name: 'Acuna Jr, Ronald', team: 'ATL', ab: 338 },
    { id: 'albieoz01', name: 'Albies, Ozzie', team: 'ATL', ab: 603 },
    { id: 'allenni02', name: 'Allen, Nick', team: 'ATL', ab: 371 },
    { id: 'alvarna01', name: 'Alvarez Jr, Nacho', team: 'ATL', ab: 188 },
    { id: 'arciaor01', name: 'Arcia, Orlando', team: 'ATL', ab: 31 },
    { id: 'azocajo01', name: 'Azocar, Jose', team: 'ATL', ab: 1 },
    { id: 'baldwdr01', name: 'Baldwin, Drake', team: 'ATL', ab: 405 },
    { id: 'brujavi01', name: 'Brujan, Vidal', team: 'ATL', ab: 41 },
    { id: 'delacbr01', name: 'De La Cruz, Bryan', team: 'ATL', ab: 47 },
    { id: 'faircst01', name: 'Fairchild, Stuart', team: 'ATL', ab: 51 },
    { id: 'fraleja01', name: 'Fraley, Jake', team: 'ATL', ab: 23 },
    { id: 'harrimi04', name: 'Harris II, Michael', team: 'ATL', ab: 611 },
    { id: 'kelenja01', name: 'Kelenic, Jarred', team: 'ATL', ab: 60 },
    { id: 'kimha01', name: 'Kim, Ha-Seong', team: 'ATL', ab: 87 },
    { id: 'leonsa01', name: 'Leon, Sandy', team: 'ATL', ab: 12 },
    { id: 'murphse01', name: 'Murphy, Sean', team: 'ATL', ab: 291 },
    { id: 'olsonma02', name: 'Olson, Matt', team: 'ATL', ab: 624 },
    { id: 'orneljo01', name: 'Ornelas, Jonathan', team: 'ATL', ab: 4 },
    { id: 'ozunama01', name: 'Ozuna, Marcell', team: 'ATL', ab: 487 },
    { id: 'profaju01', name: 'Profar, Jurickson', team: 'ATL', ab: 318 },
    { id: 'rileyau01', name: 'Riley, Austin', team: 'ATL', ab: 416 },
    { id: 'rosared01', name: 'Rosario, Eddie', team: 'ATL', ab: 4 },
    { id: 'trompch01', name: 'Tromp, Chadwick', team: 'ATL', ab: 5 },
    { id: 'verdual01', name: 'Verdugo, Alex', team: 'ATL', ab: 197 },
    { id: 'whiteel04', name: 'White, Eli', team: 'ATL', ab: 256 },
    { id: 'willilu01', name: 'Williams, Luke', team: 'ATL', ab: 31 },
    { id: 'wiselbr01', name: 'Wisely, Brett', team: 'ATL', ab: 6 },
    { id: 'adamsjo03', name: 'Adams, Jordyn', team: 'BAL', ab: 5 },
    { id: 'akinke01', name: 'Akin, Keegan', team: 'BAL', ab: 0 },
    { id: 'allengr01', name: 'Allen, Greg', team: 'BAL', ab: 14 },
    { id: 'bakerbr01', name: 'Baker, Bryan', team: 'BAL', ab: 0 },
    { id: 'banueda01', name: 'Banuelos, David', team: 'BAL', ab: 1 },
    { id: 'basalsa01', name: 'Basallo, Samuel', team: 'BAL', ab: 109 },
    { id: 'bautife01', name: 'Bautista, Felix', team: 'BAL', ab: 0 },
    { id: 'beavedy01', name: 'Beavers, Dylan', team: 'BAL', ab: 110 },
    { id: 'bowmama01', name: 'Bowman, Matt', team: 'BAL', ab: 0 },
    { id: 'brujavi01', name: 'Brujan, Vidal', team: 'BAL', ab: 1 },
    { id: 'canoye01', name: 'Cano, Yennier', team: 'BAL', ab: 0 },
    { id: 'carlsdy01', name: 'Carlson, Dylan', team: 'BAL', ab: 217 },
    { id: 'cowseco01', name: 'Cowser, Colton', team: 'BAL', ab: 327 },
    { id: 'dominse01', name: 'Dominguez, Seranthony', team: 'BAL', ab: 0 },
    { id: 'ennsdi01', name: 'Enns, Dietrich', team: 'BAL', ab: 0 },
    { id: 'handlma01', name: 'Handley, Maverick', team: 'BAL', ab: 41 },
    { id: 'hendegu01', name: 'Henderson, Gunnar', team: 'BAL', ab: 577 },
    { id: 'hollija01', name: 'Holliday, Jackson', team: 'BAL', ab: 586 },
    { id: 'hummeco01', name: 'Hummel, Cooper', team: 'BAL', ab: 1 },
    { id: 'jacksal02', name: 'Jackson, Alex', team: 'BAL', ab: 91 },
    { id: 'jacksje02', name: 'Jackson, Jeremiah', team: 'BAL', ab: 170 },
    { id: 'johnsda07', name: 'Johnson, Daniel', team: 'BAL', ab: 24 },
    { id: 'kittran01', name: 'Kittredge, Andrew', team: 'BAL', ab: 0 },
    { id: 'kjershe01', name: 'Kjerstad, Heston', team: 'BAL', ab: 156 },
    { id: 'laurera01', name: 'Laureano, Ramon', team: 'BAL', ab: 259 },
    { id: 'machivi01', name: 'Machin, Vimael', team: 'BAL', ab: 11 },
    { id: 'mateojo01', name: 'Mateo, Jorge', team: 'BAL', ab: 79 },
    { id: 'mayoco01', name: 'Mayo, Coby', team: 'BAL', ab: 263 },
    { id: 'mountry01', name: 'Mountcastle, Ryan', team: 'BAL', ab: 332 },
    { id: 'mullice01', name: 'Mullins, Cedric', team: 'BAL', ab: 314 },
    { id: 'nodary01', name: 'Noda, Ryan', team: 'BAL', ab: 13 },
    { id: 'ohearry01', name: 'O\'Hearn, Ryan', team: 'BAL', ab: 311 },
    { id: 'oneilty01', name: 'O\'Neill, Tyler', team: 'BAL', ab: 181 },
    { id: 'perezci01', name: 'Perez, Cionel', team: 'BAL', ab: 0 },
    { id: 'riverem01', name: 'Rivera, Emmanuel', team: 'BAL', ab: 120 },
    { id: 'rogertr01', name: 'Rogers, Trevor', team: 'BAL', ab: 2 },
    { id: 'rutscad01', name: 'Rutschman, Adley', team: 'BAL', ab: 322 },
    { id: 'sanchga02', name: 'Sanchez, Gary', team: 'BAL', ab: 91 },
    { id: 'stallja01', name: 'Stallings, Jacob', team: 'BAL', ab: 35 },
    { id: 'trompch01', name: 'Tromp, Chadwick', team: 'BAL', ab: 16 },
    { id: 'uriasra01', name: 'Urias, Ramon', team: 'BAL', ab: 258 },
    { id: 'vavrate01', name: 'Vavra, Terrin', team: 'BAL', ab: 1 },
    { id: 'vazqulu01', name: 'Vazquez, Luis', team: 'BAL', ab: 50 },
    { id: 'westbjo01', name: 'Westburg, Jordan', team: 'BAL', ab: 328 },
    { id: 'abreuwi02', name: 'Abreu, Wilyer', team: 'BOS', ab: 373 },
    { id: 'anthoro01', name: 'Anthony, Roman', team: 'BOS', ab: 257 },
    { id: 'bernabr01', name: 'Bernardino, Brennan', team: 'BOS', ab: 0 },
    { id: 'bregmal01', name: 'Bregman, Alex', team: 'BOS', ab: 433 },
    { id: 'campbkr01', name: 'Campbell, Kristian', team: 'BOS', ab: 229 },
    { id: 'casastr01', name: 'Casas, Triston', team: 'BOS', ab: 99 },
    { id: 'chapmar01', name: 'Chapman, Aroldis', team: 'BOS', ab: 0 },
    { id: 'deverra01', name: 'Devers, Rafael', team: 'BOS', ab: 272 },
    { id: 'duranja01', name: 'Duran, Jarren', team: 'BOS', ab: 620 },
    { id: 'eatonna01', name: 'Eaton, Nate', team: 'BOS', ab: 81 },
    { id: 'garcijh01', name: 'Garcia, Jhostynxon', team: 'BOS', ab: 7 },
    { id: 'gonzaro01', name: 'Gonzalez, Romy', team: 'BOS', ab: 315 },
    { id: 'hamilda03', name: 'Hamilton, David', team: 'BOS', ab: 177 },
    { id: 'lowena01', name: 'Lowe, Nathaniel', team: 'BOS', ab: 100 },
    { id: 'mayerma01', name: 'Mayer, Marcelo', team: 'BOS', ab: 127 },
    { id: 'narvaca01', name: 'Narvaez, Carlos', team: 'BOS', ab: 403 },
    { id: 'rafaece01', name: 'Rafaela, Ceddanne', team: 'BOS', ab: 546 },
    { id: 'refsnro01', name: 'Refsnyder, Rob', team: 'BOS', ab: 182 },
    { id: 'sabolbl01', name: 'Sabol, Blake', team: 'BOS', ab: 16 },
    { id: 'sanchal04', name: 'Sanchez, Ali', team: 'BOS', ab: 2 },
    { id: 'sogarni01', name: 'Sogard, Nick', team: 'BOS', ab: 96 },
    { id: 'storytr01', name: 'Story, Trevor', team: 'BOS', ab: 612 },
    { id: 'toroab01', name: 'Toro, Abraham', team: 'BOS', ab: 259 },
    { id: 'whitlga01', name: 'Whitlock, Garrett', team: 'BOS', ab: 0 },
    { id: 'wongco01', name: 'Wong, Connor', team: 'BOS', ab: 168 },
    { id: 'yoshima02', name: 'Yoshida, Masataka', team: 'BOS', ab: 188 },
    { id: 'alcanke01', name: 'Alcantara, Kevin', team: 'CHC', ab: 11 },
    { id: 'amayami01', name: 'Amaya, Miguel', team: 'CHC', ab: 96 },
    { id: 'ballemo01', name: 'Ballesteros, Moises', team: 'CHC', ab: 57 },
    { id: 'bertijo01', name: 'Berti, Jon', team: 'CHC', ab: 100 },
    { id: 'brujavi01', name: 'Brujan, Vidal', team: 'CHC', ab: 45 },
    { id: 'buschmi02', name: 'Busch, Michael', team: 'CHC', ab: 524 },
    { id: 'caissow01', name: 'Caissie, Owen', team: 'CHC', ab: 26 },
    { id: 'castrwi01', name: 'Castro, Willi', team: 'CHC', ab: 100 },
    { id: 'crowape01', name: 'Crow-Armstrong, Pete', team: 'CHC', ab: 591 },
    { id: 'happia01', name: 'Happ, Ian', team: 'CHC', ab: 569 },
    { id: 'hoernni01', name: 'Hoerner, Nico', team: 'CHC', ab: 599 },
    { id: 'kellyca02', name: 'Kelly, Carson', team: 'CHC', ab: 369 },
    { id: 'lopezni01', name: 'Lopez, Nicky', team: 'CHC', ab: 18 },
    { id: 'mcguire01', name: 'McGuire, Reese', team: 'CHC', ab: 133 },
    { id: 'reaco01', name: 'Rea, Colin', team: 'CHC', ab: 1 },
    { id: 'santaca01', name: 'Santana, Carlos', team: 'CHC', ab: 19 },
    { id: 'shawma01', name: 'Shaw, Matt', team: 'CHC', ab: 393 },
    { id: 'suzukse01', name: 'Suzuki, Seiya', team: 'CHC', ab: 571 },
    { id: 'swansda01', name: 'Swanson, Dansby', team: 'CHC', ab: 590 },
    { id: 'tuckeky01', name: 'Tucker, Kyle', team: 'CHC', ab: 500 },
    { id: 'turneju01', name: 'Turner, Justin', team: 'CHC', ab: 169 },
    { id: 'workmga01', name: 'Workman, Gage', team: 'CHC', ab: 14 },
    { id: 'alexaty01', name: 'Alexander, Tyler', team: 'CHW', ab: 1 },
    { id: 'amayaja01', name: 'Amaya, Jacob', team: 'CHW', ab: 66 },
    { id: 'baldwbr01', name: 'Baldwin, Brooks', team: 'CHW', ab: 300 },
    { id: 'beninan01', name: 'Benintendi, Andrew', team: 'CHW', ab: 420 },
    { id: 'capravi01', name: 'Capra, Vinny', team: 'CHW', ab: 42 },
    { id: 'dalbebo01', name: 'Dalbec, Bobby', team: 'CHW', ab: 18 },
    { id: 'elkoti01', name: 'Elko, Tim', team: 'CHW', ab: 67 },
    { id: 'fletcdo01', name: 'Fletcher, Dominic', team: 'CHW', ab: 32 },
    { id: 'hillde01', name: 'Hill, Derek', team: 'CHW', ab: 7 },
    { id: 'jankotr01', name: 'Jankowski, Travis', team: 'CHW', ab: 14 },
    { id: 'jonesgr02', name: 'Jones, Greg', team: 'CHW', ab: 2 },
    { id: 'julksco01', name: 'Julks, Corey', team: 'CHW', ab: 12 },
    { id: 'leasujo01', name: 'Leasure, Jordan', team: 'CHW', ab: 0 },
    { id: 'leeko01', name: 'Lee, Korey', team: 'CHW', ab: 35 },
    { id: 'matonni01', name: 'Maton, Nick', team: 'CHW', ab: 54 },
    { id: 'meadcu01', name: 'Mead, Curtis', team: 'CHW', ab: 125 },
    { id: 'meidrch01', name: 'Meidroth, Chase', team: 'CHW', ab: 450 },
    { id: 'montgco01', name: 'Montgomery, Colson', team: 'CHW', ab: 255 },
    { id: 'narvaom01', name: 'Narvaez, Omar', team: 'CHW', ab: 7 },
    { id: 'nodary01', name: 'Noda, Ryan', team: 'CHW', ab: 34 },
    { id: 'palacjo01', name: 'Palacios, Joshua', team: 'CHW', ab: 128 },
    { id: 'queroed01', name: 'Quero, Edgar', team: 'CHW', ab: 365 },
    { id: 'ramosbr01', name: 'Ramos, Bryan', team: 'CHW', ab: 12 },
    { id: 'roberlu01', name: 'Robert Jr, Luis', team: 'CHW', ab: 382 },
    { id: 'roberwi02', name: 'Robertson, Will', team: 'CHW', ab: 60 },
    { id: 'rojasjo01', name: 'Rojas, Josh', team: 'CHW', ab: 189 },
    { id: 'slateau01', name: 'Slater, Austin', team: 'CHW', ab: 123 },
    { id: 'sosale01', name: 'Sosa, Lenyn', team: 'CHW', ab: 518 },
    { id: 'tauchmi01', name: 'Tauchman, Mike', team: 'CHW', ab: 335 },
    { id: 'taylomi02', name: 'Taylor, Michael A', team: 'CHW', ab: 295 },
    { id: 'teelky01', name: 'Teel, Kyle', team: 'CHW', ab: 253 },
    { id: 'thaisma01', name: 'Thaiss, Matt', team: 'CHW', ab: 85 },
    { id: 'vargami01', name: 'Vargas, Miguel', team: 'CHW', ab: 504 },
    { id: 'vaughan01', name: 'Vaughn, Andrew', team: 'CHW', ab: 185 },
    { id: 'wilsobr02', name: 'Wilson, Bryse', team: 'CHW', ab: 0 },
    { id: 'workmga01', name: 'Workman, Gage', team: 'CHW', ab: 2 },
    { id: 'andujmi01', name: 'Andujar, Miguel', team: 'CIN', ab: 103 },
    { id: 'banfiwi01', name: 'Banfield, Will', team: 'CIN', ab: 10 },
    { id: 'bensowi01', name: 'Benson, Will', team: 'CIN', ab: 230 },
    { id: 'callity01', name: 'Callihan, Tyler', team: 'CIN', ab: 6 },
    { id: 'candeje01', name: 'Candelario, Jeimer', team: 'CIN', ab: 80 },
    { id: 'delacel01', name: 'De La Cruz, Elly', team: 'CIN', ab: 629 },
    { id: 'dunnbl01', name: 'Dunn, Blake', team: 'CIN', ab: 60 },
    { id: 'encarch01', name: 'Encarnacion-Strand, Christian', team: 'CIN', ab: 130 },
    { id: 'espinsa01', name: 'Espinal, Santiago', team: 'CIN', ab: 301 },
    { id: 'fraleja01', name: 'Fraley, Jake', team: 'CIN', ab: 168 },
    { id: 'friedtj01', name: 'Friedl, TJ', team: 'CIN', ab: 579 },
    { id: 'hampsga01', name: 'Hampson, Garrett', team: 'CIN', ab: 18 },
    { id: 'hayeske01', name: 'Hayes, Ke\'Bryan', team: 'CIN', ab: 158 },
    { id: 'haysau01', name: 'Hays, Austin', team: 'CIN', ab: 380 },
    { id: 'hindsre01', name: 'Hinds, Rece', team: 'CIN', ab: 43 },
    { id: 'hurtuja01', name: 'Hurtubise, Jacob', team: 'CIN', ab: 12 },
    { id: 'joeco01', name: 'Joe, Connor', team: 'CIN', ab: 61 },
    { id: 'luxga01', name: 'Lux, Gavin', team: 'CIN', ab: 446 },
    { id: 'marteno01', name: 'Marte, Noelvi', team: 'CIN', ab: 339 },
    { id: 'mclaima01', name: 'McLain, Matt', team: 'CIN', ab: 510 },
    { id: 'steersp01', name: 'Steer, Spencer', team: 'CIN', ab: 509 },
    { id: 'stephty01', name: 'Stephenson, Tyler', team: 'CIN', ab: 299 },
    { id: 'stewasa02', name: 'Stewart, Sal', team: 'CIN', ab: 55 },
    { id: 'trevijo01', name: 'Trevino, Jose', team: 'CIN', ab: 282 },
    { id: 'viladry01', name: 'Vilade, Ryan', team: 'CIN', ab: 0 },
    { id: 'wynnsau01', name: 'Wynns, Austin', team: 'CIN', ab: 40 },
    { id: 'ariasga01', name: 'Arias, Gabriel', team: 'CLE', ab: 432 },
    { id: 'brennwi02', name: 'Brennan, Will', team: 'CLE', ab: 11 },
    { id: 'claseem01', name: 'Clase, Emmanuel', team: 'CLE', ab: 0 },
    { id: 'festama01', name: 'Festa, Matt', team: 'CLE', ab: 0 },
    { id: 'fryda01', name: 'Fry, David', team: 'CLE', ab: 146 },
    { id: 'halpipe01', name: 'Halpin, Petey', team: 'CLE', ab: 6 },
    { id: 'hedgeau01', name: 'Hedges, Austin', team: 'CLE', ab: 155 },
    { id: 'herriti01', name: 'Herrin, Tim', team: 'CLE', ab: 0 },
    { id: 'jonesno01', name: 'Jones, Nolan', team: 'CLE', ab: 355 },
    { id: 'kayfucj01', name: 'Kayfus, CJ', team: 'CLE', ab: 123 },
    { id: 'kwanst01', name: 'Kwan, Steven', team: 'CLE', ab: 625 },
    { id: 'manzaky01', name: 'Manzardo, Kyle', team: 'CLE', ab: 470 },
    { id: 'martian02', name: 'Martinez, Angel', team: 'CLE', ab: 446 },
    { id: 'naylobo01', name: 'Naylor, Bo', team: 'CLE', ab: 359 },
    { id: 'noeljh01', name: 'Noel, Jhonkensy', team: 'CLE', ab: 148 },
    { id: 'nunezdo01', name: 'Nunez, Dom', team: 'CLE', ab: 7 },
    { id: 'ramirjo01', name: 'Ramirez, Jose', team: 'CLE', ab: 593 },
    { id: 'rocchbr01', name: 'Rocchio, Brayan', team: 'CLE', ab: 344 },
    { id: 'rodrijo10', name: 'Rodriguez, Johnathan', team: 'CLE', ab: 71 },
    { id: 'santaca01', name: 'Santana, Carlos', team: 'CLE', ab: 396 },
    { id: 'schneda04', name: 'Schneemann, Daniel', team: 'CLE', ab: 379 },
    { id: 'thomala02', name: 'Thomas, Lane', team: 'CLE', ab: 125 },
    { id: 'valerge01', name: 'Valera, George', team: 'CLE', ab: 41 },
    { id: 'wilsowi03', name: 'Wilson, Will', team: 'CLE', ab: 78 },
    { id: 'agnosza01', name: 'Agnos, Zach', team: 'COL', ab: 0 },
    { id: 'amadoad01', name: 'Amador, Adael', team: 'COL', ab: 113 },
    { id: 'arciaor01', name: 'Arcia, Orlando', team: 'COL', ab: 172 },
    { id: 'beckjo01', name: 'Beck, Jordan', team: 'COL', ab: 539 },
    { id: 'bernawa01', name: 'Bernabel, Warming', team: 'COL', ab: 139 },
    { id: 'birdja01', name: 'Bird, Jake', team: 'COL', ab: 0 },
    { id: 'bouchse01', name: 'Bouchard, Sean', team: 'COL', ab: 66 },
    { id: 'bryankr01', name: 'Bryant, Kris', team: 'COL', ab: 39 },
    { id: 'chivian01', name: 'Chivilli, Angel', team: 'COL', ab: 0 },
    { id: 'crimbl01', name: 'Crim, Blaine', team: 'COL', ab: 54 },
    { id: 'doylebr02', name: 'Doyle, Brenton', team: 'COL', ab: 502 },
    { id: 'estrath01', name: 'Estrada, Thairo', team: 'COL', ab: 154 },
    { id: 'farmeky01', name: 'Farmer, Kyle', team: 'COL', ab: 277 },
    { id: 'fernaya01', name: 'Fernandez, Yanquiel', team: 'COL', ab: 138 },
    { id: 'freemty01', name: 'Freeman, Tyler', team: 'COL', ab: 377 },
    { id: 'fulfobr01', name: 'Fulford, Braxton', team: 'COL', ab: 108 },
    { id: 'goodmhu01', name: 'Goodman, Hunter', team: 'COL', ab: 540 },
    { id: 'halvose01', name: 'Halvorsen, Seth', team: 'COL', ab: 0 },
    { id: 'hillisa01', name: 'Hilliard, Sam', team: 'COL', ab: 51 },
    { id: 'hiurake01', name: 'Hiura, Keston', team: 'COL', ab: 18 },
    { id: 'karroky01', name: 'Karros, Kyle', team: 'COL', ab: 137 },
    { id: 'martini02', name: 'Martini, Nick', team: 'COL', ab: 102 },
    { id: 'mcmahry01', name: 'McMahon, Ryan', team: 'COL', ab: 350 },
    { id: 'mejiaju01', name: 'Mejia, Juan', team: 'COL', ab: 0 },
    { id: 'milleow01', name: 'Miller, Owen', team: 'COL', ab: 14 },
    { id: 'moniami01', name: 'Moniak, Mickey', team: 'COL', ab: 434 },
    { id: 'nolaau01', name: 'Nola, Austin', team: 'COL', ab: 38 },
    { id: 'rittery01', name: 'Ritter, Ryan', team: 'COL', ab: 187 },
    { id: 'romodr01', name: 'Romo, Drew', team: 'COL', ab: 3 },
    { id: 'schunaa01', name: 'Schunk, Aaron', team: 'COL', ab: 32 },
    { id: 'stallja01', name: 'Stallings, Jacob', team: 'COL', ab: 84 },
    { id: 'toglimi01', name: 'Toglia, Michael', team: 'COL', ab: 306 },
    { id: 'tovarez01', name: 'Tovar, Ezequiel', team: 'COL', ab: 360 },
    { id: 'trejoal01', name: 'Trejo, Alan', team: 'COL', ab: 40 },
    { id: 'veenza01', name: 'Veen, Zac', team: 'COL', ab: 34 },
    { id: 'vodnivi01', name: 'Vodnik, Victor', team: 'COL', ab: 0 },
    { id: 'baddoak01', name: 'Baddoo, Akil', team: 'DET', ab: 17 },
    { id: 'baezja01', name: 'Baez, Javier', team: 'DET', ab: 417 },
    { id: 'brebbjo01', name: 'Brebbia, John', team: 'DET', ab: 0 },
    { id: 'carpeke01', name: 'Carpenter, Kerry', team: 'DET', ab: 433 },
    { id: 'dingldi01', name: 'Dingler, Dillon', team: 'DET', ab: 435 },
    { id: 'greenri03', name: 'Greene, Riley', team: 'DET', ab: 600 },
    { id: 'hicklbr01', name: 'Hicklen, Brewer', team: 'DET', ab: 3 },
    { id: 'ibanean01', name: 'Ibanez, Andy', team: 'DET', ab: 176 },
    { id: 'jonesja08', name: 'Jones, Jahmai', team: 'DET', ab: 129 },
    { id: 'jungja01', name: 'Jung, Jace', team: 'DET', ab: 47 },
    { id: 'kahnlto01', name: 'Kahnle, Tommy', team: 'DET', ab: 0 },
    { id: 'keithco01', name: 'Keith, Colt', team: 'DET', ab: 414 },
    { id: 'kreidry01', name: 'Kreidler, Ryan', team: 'DET', ab: 38 },
    { id: 'malloju02', name: 'Malloy, Justyn-Henry', team: 'DET', ab: 104 },
    { id: 'margoma01', name: 'Margot, Manuel', team: 'DET', ab: 19 },
    { id: 'mckinza01', name: 'McKinstry, Zach', team: 'DET', ab: 452 },
    { id: 'meadopa01', name: 'Meadows, Parker', team: 'DET', ab: 191 },
    { id: 'nidoto01', name: 'Nido, Tomas', team: 'DET', ab: 35 },
    { id: 'owensty01', name: 'Owens, Tyler', team: 'DET', ab: 0 },
    { id: 'perezwe01', name: 'Perez, Wenceel', team: 'DET', ab: 344 },
    { id: 'rogerja03', name: 'Rogers, Jake', team: 'DET', ab: 123 },
    { id: 'sweentr01', name: 'Sweeney, Trey', team: 'DET', ab: 296 },
    { id: 'torkesp01', name: 'Torkelson, Spencer', team: 'DET', ab: 563 },
    { id: 'torregl01', name: 'Torres, Gleyber', team: 'DET', ab: 532 },
    { id: 'vierlma01', name: 'Vierling, Matt', team: 'DET', ab: 88 },
    { id: 'abreubr01', name: 'Abreu, Bryan', team: 'HOU', ab: 0 },
    { id: 'altuvjo01', name: 'Altuve, Jose', team: 'HOU', ab: 588 },
    { id: 'alvaryo01', name: 'Alvarez, Yordan', team: 'HOU', ab: 165 },
    { id: 'caratvi01', name: 'Caratini, Victor', team: 'HOU', ab: 344 },
    { id: 'coleza01', name: 'Cole, Zach', team: 'HOU', ab: 47 },
    { id: 'coronke01', name: 'Corona, Kenedy', team: 'HOU', ab: 2 },
    { id: 'correca01', name: 'Correa, Carlos', team: 'HOU', ab: 200 },
    { id: 'delosen01', name: 'De Los Santos, Enyel', team: 'HOU', ab: 0 },
    { id: 'dezenza01', name: 'Dezenzo, Zach', team: 'HOU', ab: 98 },
    { id: 'diazya02', name: 'Diaz, Yainer', team: 'HOU', ab: 542 },
    { id: 'dubonma01', name: 'Dubon, Mauricio', team: 'HOU', ab: 369 },
    { id: 'guilllu01', name: 'Guillorme, Luis', team: 'HOU', ab: 20 },
    { id: 'haderjo01', name: 'Hader, Josh', team: 'HOU', ab: 0 },
    { id: 'hummeco01', name: 'Hummel, Cooper', team: 'HOU', ab: 87 },
    { id: 'matthbr01', name: 'Matthews, Brice', team: 'HOU', ab: 42 },
    { id: 'mccorch01', name: 'McCormick, Chas', team: 'HOU', ab: 100 },
    { id: 'meltoja01', name: 'Melton, Jacob', team: 'HOU', ab: 70 },
    { id: 'meyerja02', name: 'Meyers, Jake', team: 'HOU', ab: 343 },
    { id: 'ortka01', name: 'Ort, Kaleb', team: 'HOU', ab: 0 },
    { id: 'paredis01', name: 'Paredes, Isaac', team: 'HOU', ab: 378 },
    { id: 'penaje02', name: 'Pena, Jeremy', team: 'HOU', ab: 493 },
    { id: 'rodgebr02', name: 'Rodgers, Brendan', team: 'HOU', ab: 115 },
    { id: 'salazce01', name: 'Salazar, Cesar', team: 'HOU', ab: 13 },
    { id: 'sanchje02', name: 'Sanchez, Jesus', team: 'HOU', ab: 146 },
    { id: 'shortza01', name: 'Short, Zack', team: 'HOU', ab: 50 },
    { id: 'singljo02', name: 'Singleton, Jon', team: 'HOU', ab: 9 },
    { id: 'smithca07', name: 'Smith, Cam', team: 'HOU', ab: 441 },
    { id: 'sousabe01', name: 'Sousa, Bennett', team: 'HOU', ab: 0 },
    { id: 'trammta01', name: 'Trammell, Taylor', team: 'HOU', ab: 117 },
    { id: 'uriasra01', name: 'Urias, Ramon', team: 'HOU', ab: 94 },
    { id: 'walkech02', name: 'Walker, Christian', team: 'HOU', ab: 585 },
    { id: 'whitcsh01', name: 'Whitcomb, Shay', team: 'HOU', ab: 32 },
    { id: 'avilalu02', name: 'Avila, Luinder', team: 'KCR', ab: 0 },
    { id: 'biggica01', name: 'Biggio, Cavan', team: 'KCR', ab: 69 },
    { id: 'blancda02', name: 'Blanco, Dairon', team: 'KCR', ab: 6 },
    { id: 'caglija01', name: 'Caglianone, Jac', team: 'KCR', ab: 210 },
    { id: 'canhama01', name: 'Canha, Mark', team: 'KCR', ab: 113 },
    { id: 'clarkta01', name: 'Clarke, Taylor', team: 'KCR', ab: 0 },
    { id: 'cruzst01', name: 'Cruz, Steven', team: 'KCR', ab: 0 },
    { id: 'erceglu01', name: 'Erceg, Lucas', team: 'KCR', ab: 0 },
    { id: 'estevca01', name: 'Estevez, Carlos', team: 'KCR', ab: 0 },
    { id: 'fermifr01', name: 'Fermin, Freddy', team: 'KCR', ab: 192 },
    { id: 'fraziad01', name: 'Frazier, Adam', team: 'KCR', ab: 184 },
    { id: 'garcima01', name: 'Garcia, Maikel', team: 'KCR', ab: 595 },
    { id: 'grichra01', name: 'Grichuk, Randal', team: 'KCR', ab: 97 },
    { id: 'indiajo01', name: 'India, Jonathan', team: 'KCR', ab: 497 },
    { id: 'isbelky01', name: 'Isbel, Kyle', team: 'KCR', ab: 368 },
    { id: 'jenseca01', name: 'Jensen, Carter', team: 'KCR', ab: 60 },
    { id: 'loftini01', name: 'Loftin, Nick', team: 'KCR', ab: 168 },
    { id: 'longsa01', name: 'Long, Sam', team: 'KCR', ab: 0 },
    { id: 'lynchda02', name: 'Lynch IV, Daniel', team: 'KCR', ab: 0 },
    { id: 'mailelu01', name: 'Maile, Luke', team: 'KCR', ab: 45 },
    { id: 'massemi02', name: 'Massey, Michael', team: 'KCR', ab: 262 },
    { id: 'melenmj01', name: 'Melendez, MJ', team: 'KCR', ab: 60 },
    { id: 'pasquvi01', name: 'Pasquantino, Vinnie', team: 'KCR', ab: 621 },
    { id: 'perezsa02', name: 'Perez, Salvador', team: 'KCR', ab: 597 },
    { id: 'ravejo01', name: 'Rave, John', team: 'KCR', ab: 153 },
    { id: 'renfrhu01', name: 'Renfroe, Hunter', team: 'KCR', ab: 99 },
    { id: 'richatr01', name: 'Richards, Trevor', team: 'KCR', ab: 0 },
    { id: 'schrejo01', name: 'Schreiber, John', team: 'KCR', ab: 0 },
    { id: 'tolbety01', name: 'Tolbert, Tyler', team: 'KCR', ab: 50 },
    { id: 'waterdr01', name: 'Waters, Drew', team: 'KCR', ab: 206 },
    { id: 'wittbo02', name: 'Witt Jr, Bobby', team: 'KCR', ab: 623 },
    { id: 'yastrmi01', name: 'Yastrzemski, Mike', team: 'KCR', ab: 156 },
    { id: 'adelljo01', name: 'Adell, Jo', team: 'LAA', ab: 526 },
    { id: 'anderti01', name: 'Anderson, Tim', team: 'LAA', ab: 83 },
    { id: 'campegu01', name: 'Campero, Gustavo', team: 'LAA', ab: 58 },
    { id: 'darnatr01', name: 'd\'Arnaud, Travis', team: 'LAA', ab: 213 },
    { id: 'davidlo01', name: 'Davidson, Logan', team: 'LAA', ab: 22 },
    { id: 'davisjd01', name: 'Davis, JD', team: 'LAA', ab: 9 },
    { id: 'guzmade01', name: 'Guzman, Denzer', team: 'LAA', ab: 42 },
    { id: 'janseke01', name: 'Jansen, Kenley', team: 'LAA', ab: 0 },
    { id: 'kavadni01', name: 'Kavadas, Niko', team: 'LAA', ab: 20 },
    { id: 'kieboca01', name: 'Kieboom, Carter', team: 'LAA', ab: 8 },
    { id: 'kingesc01', name: 'Kingery, Scott', team: 'LAA', ab: 27 },
    { id: 'lopezni01', name: 'Lopez, Nicky', team: 'LAA', ab: 6 },
    { id: 'lugoma01', name: 'Lugo, Matthew', team: 'LAA', ab: 69 },
    { id: 'moncayo01', name: 'Moncada, Yoan', team: 'LAA', ab: 248 },
    { id: 'moorech03', name: 'Moore, Christian', team: 'LAA', ab: 162 },
    { id: 'netoza01', name: 'Neto, Zach', team: 'LAA', ab: 502 },
    { id: 'newmake01', name: 'Newman, Kevin', team: 'LAA', ab: 114 },
    { id: 'ohopplo01', name: 'O\'Hoppe, Logan', team: 'LAA', ab: 423 },
    { id: 'parisky01', name: 'Paris, Kyren', team: 'LAA', ab: 126 },
    { id: 'perazos02', name: 'Peraza, Oswald', team: 'LAA', ab: 86 },
    { id: 'rengilu01', name: 'Rengifo, Luis', team: 'LAA', ab: 501 },
    { id: 'riverse01', name: 'Rivero, Sebastian', team: 'LAA', ab: 33 },
    { id: 'schanno01', name: 'Schanuel, Nolan', team: 'LAA', ab: 488 },
    { id: 'solerjo01', name: 'Soler, Jorge', team: 'LAA', ab: 279 },
    { id: 'stevech02', name: 'Stevens, Chad', team: 'LAA', ab: 13 },
    { id: 'tayloch03', name: 'Taylor, Chris', team: 'LAA', ab: 78 },
    { id: 'teodobr01', name: 'Teodosio, Bryce', team: 'LAA', ab: 138 },
    { id: 'troutmi01', name: 'Trout, Mike', team: 'LAA', ab: 456 },
    { id: 'wadela01', name: 'Wade Jr, LaMonte', team: 'LAA', ab: 65 },
    { id: 'wallach01', name: 'Wallach, Chad', team: 'LAA', ab: 0 },
    { id: 'wardta01', name: 'Ward, Taylor', team: 'LAA', ab: 579 },
    { id: 'bandaan01', name: 'Banda, Anthony', team: 'LAD', ab: 0 },
    { id: 'barneau01', name: 'Barnes, Austin', team: 'LAD', ab: 42 },
    { id: 'bettsmo01', name: 'Betts, Mookie', team: 'LAD', ab: 589 },
    { id: 'callal02', name: 'Call, Alex', team: 'LAD', ab: 73 },
    { id: 'confomi01', name: 'Conforto, Michael', team: 'LAD', ab: 418 },
    { id: 'deanju01', name: 'Dean, Justin', team: 'LAD', ab: 2 },
    { id: 'edmanto01', name: 'Edman, Tommy', team: 'LAD', ab: 346 },
    { id: 'feduchu01', name: 'Feduccia, Hunter', team: 'LAD', ab: 2 },
    { id: 'freelal01', name: 'Freeland, Alex', team: 'LAD', ab: 84 },
    { id: 'freemfr01', name: 'Freeman, Freddie', team: 'LAD', ab: 556 },
    { id: 'hernaen02', name: 'Hernandez, Kike', team: 'LAD', ab: 232 },
    { id: 'hernate01', name: 'Hernandez, Teoscar', team: 'LAD', ab: 511 },
    { id: 'kennebu01', name: 'Kennedy, Buddy', team: 'LAD', ab: 17 },
    { id: 'kimhy02', name: 'Kim, Hyeseong', team: 'LAD', ab: 161 },
    { id: 'muncyma01', name: 'Muncy, Max', team: 'LAD', ab: 313 },
    { id: 'ohtansh01', name: 'Ohtani, Shohei', team: 'LAD', ab: 611 },
    { id: 'outmaja01', name: 'Outman, James', team: 'LAD', ab: 39 },
    { id: 'pagesan01', name: 'Pages, Andy', team: 'LAD', ab: 581 },
    { id: 'robinch04', name: 'Robinson, Chuckie', team: 'LAD', ab: 1 },
    { id: 'rojasmi02', name: 'Rojas, Miguel', team: 'LAD', ab: 290 },
    { id: 'rortvbe01', name: 'Rortvedt, Ben', team: 'LAD', ab: 49 },
    { id: 'rosared01', name: 'Rosario, Eddie', team: 'LAD', ab: 4 },
    { id: 'ruizes01', name: 'Ruiz, Esteury', team: 'LAD', ab: 21 },
    { id: 'rushida01', name: 'Rushing, Dalton', team: 'LAD', ab: 142 },
    { id: 'scottta01', name: 'Scott, Tanner', team: 'LAD', ab: 0 },
    { id: 'smithwi05', name: 'Smith, Will', team: 'LAD', ab: 362 },
    { id: 'tayloch03', name: 'Taylor, Chris', team: 'LAD', ab: 35 },
    { id: 'acostma02', name: 'Acosta, Maximo', team: 'MIA', ab: 54 },
    { id: 'brantro01', name: 'Brantly, Rob', team: 'MIA', ab: 7 },
    { id: 'bridejo01', name: 'Bride, Jonah', team: 'MIA', ab: 40 },
    { id: 'coningr01', name: 'Conine, Griffin', team: 'MIA', ab: 79 },
    { id: 'edwarxa01', name: 'Edwards, Xavier', team: 'MIA', ab: 561 },
    { id: 'forteni01', name: 'Fortes, Nick', team: 'MIA', ab: 129 },
    { id: 'hernahe01', name: 'Hernandez, Heriberto', team: 'MIA', ab: 256 },
    { id: 'hicksli01', name: 'Hicks, Liam', team: 'MIA', ab: 332 },
    { id: 'hillde01', name: 'Hill, Derek', team: 'MIA', ab: 127 },
    { id: 'johnstr02', name: 'Johnston, Troy', team: 'MIA', ab: 112 },
    { id: 'lopezot01', name: 'Lopez, Otto', team: 'MIA', ab: 544 },
    { id: 'marseja01', name: 'Marsee, Jakob', team: 'MIA', ab: 209 },
    { id: 'mervima01', name: 'Mervis, Matt', team: 'MIA', ab: 120 },
    { id: 'mesavi01', name: 'Mesa Jr, Victor', team: 'MIA', ab: 32 },
    { id: 'myersda01', name: 'Myers, Dane', team: 'MIA', ab: 307 },
    { id: 'navarbr01', name: 'Navarreto, Brian', team: 'MIA', ab: 14 },
    { id: 'norbyco01', name: 'Norby, Connor', team: 'MIA', ab: 311 },
    { id: 'paulegr01', name: 'Pauley, Graham', team: 'MIA', ab: 161 },
    { id: 'ramirag01', name: 'Ramirez, Agustin', team: 'MIA', ab: 537 },
    { id: 'sanchje02', name: 'Sanchez, Jesus', team: 'MIA', ab: 305 },
    { id: 'sanojja01', name: 'Sanoja, Javier', team: 'MIA', ab: 313 },
    { id: 'simonro01', name: 'Simon, Ronny', team: 'MIA', ab: 47 },
    { id: 'stoweky01', name: 'Stowers, Kyle', team: 'MIA', ab: 399 },
    { id: 'wagamer01', name: 'Wagaman, Eric', team: 'MIA', ab: 476 },
    { id: 'wiemejo01', name: 'Wiemer, Joey', team: 'MIA', ab: 55 },
    { id: 'winklja01', name: 'Winkler, Jack', team: 'MIA', ab: 16 },
    { id: 'avansdr01', name: 'Avans, Drew', team: 'MIL', ab: 2 },
    { id: 'bauerja01', name: 'Bauers, Jake', team: 'MIL', ab: 183 },
    { id: 'berrost01', name: 'Berroa, Steward', team: 'MIL', ab: 5 },
    { id: 'blackty01', name: 'Black, Tyler', team: 'MIL', ab: 8 },
    { id: 'camerda01', name: 'Cameron, Daz', team: 'MIL', ab: 41 },
    { id: 'capravi01', name: 'Capra, Vinny', team: 'MIL', ab: 54 },
    { id: 'chourja01', name: 'Chourio, Jackson', team: 'MIL', ab: 549 },
    { id: 'colliis01', name: 'Collins, Isaac', team: 'MIL', ab: 372 },
    { id: 'contrwi02', name: 'Contreras, William', team: 'MIL', ab: 566 },
    { id: 'dunnol01', name: 'Dunn, Oliver', team: 'MIL', ab: 36 },
    { id: 'durbica01', name: 'Durbin, Caleb', team: 'MIL', ab: 445 },
    { id: 'frelisa01', name: 'Frelick, Sal', team: 'MIL', ab: 528 },
    { id: 'haaseer01', name: 'Haase, Eric', team: 'MIL', ab: 70 },
    { id: 'hoskirh01', name: 'Hoskins, Rhys', team: 'MIL', ab: 279 },
    { id: 'janseda01', name: 'Jansen, Danny', team: 'MIL', ab: 67 },
    { id: 'lockrbr01', name: 'Lockridge, Brandon', team: 'MIL', ab: 46 },
    { id: 'mitchga01', name: 'Mitchell, Garrett', team: 'MIL', ab: 68 },
    { id: 'monasan01', name: 'Monasterio, Andruw', team: 'MIL', ab: 126 },
    { id: 'ortizjo06', name: 'Ortiz, Joey', team: 'MIL', ab: 470 },
    { id: 'perkibl01', name: 'Perkins, Blake', team: 'MIL', ab: 155 },
    { id: 'seiglan01', name: 'Seigler, Anthony', team: 'MIL', ab: 62 },
    { id: 'turanbr02', name: 'Turang, Brice', team: 'MIL', ab: 584 },
    { id: 'vaughan01', name: 'Vaughn, Andrew', team: 'MIL', ab: 221 },
    { id: 'yelicch01', name: 'Yelich, Christian', team: 'MIL', ab: 573 },
    { id: 'baderha01', name: 'Bader, Harrison', team: 'MIN', ab: 271 },
    { id: 'bridejo01', name: 'Bride, Jonah', team: 'MIN', ab: 72 },
    { id: 'buxtoby01', name: 'Buxton, Byron', team: 'MIN', ab: 488 },
    { id: 'castrwi01', name: 'Castro, Willi', team: 'MIN', ab: 302 },
    { id: 'clemeko01', name: 'Clemens, Kody', team: 'MIN', ab: 342 },
    { id: 'correca01', name: 'Correa, Carlos', team: 'MIN', ab: 337 },
    { id: 'duranjh01', name: 'Duran, Jhoan', team: 'MIN', ab: 0 },
    { id: 'fitzgry01', name: 'Fitzgerald, Ryan', team: 'MIN', ab: 46 },
    { id: 'francty01', name: 'France, Ty', team: 'MIN', ab: 350 },
    { id: 'fundeko01', name: 'Funderburk, Kody', team: 'MIN', ab: 0 },
    { id: 'gaspemi01', name: 'Gasper, Mickey', team: 'MIN', ab: 95 },
    { id: 'jaxgr01', name: 'Jax, Griffin', team: 'MIN', ab: 0 },
    { id: 'jeffery01', name: 'Jeffers, Ryan', team: 'MIN', ab: 406 },
    { id: 'julieed01', name: 'Julien, Edouard', team: 'MIN', ab: 182 },
    { id: 'keasclu01', name: 'Keaschall, Luke', team: 'MIN', ab: 182 },
    { id: 'keirsda01', name: 'Keirsey Jr, DaShawn', team: 'MIN', ab: 84 },
    { id: 'larnatr01', name: 'Larnach, Trevor', team: 'MIN', ab: 503 },
    { id: 'leebr02', name: 'Lee, Brooks', team: 'MIN', ab: 487 },
    { id: 'lewisro02', name: 'Lewis, Royce', team: 'MIN', ab: 376 },
    { id: 'martiau01', name: 'Martin, Austin', team: 'MIN', ab: 156 },
    { id: 'mccusca01', name: 'McCusker, Carson', team: 'MIN', ab: 29 },
    { id: 'miranjo01', name: 'Miranda, Jose', team: 'MIN', ab: 36 },
    { id: 'outmaja01', name: 'Outman, James', team: 'MIN', ab: 95 },
    { id: 'peredjh01', name: 'Pereda, Jhonny', team: 'MIN', ab: 29 },
    { id: 'rodenal01', name: 'Roden, Alan', team: 'MIN', ab: 38 },
    { id: 'vazquch01', name: 'Vazquez, Christian', team: 'MIN', ab: 190 },
    { id: 'wallnma01', name: 'Wallner, Matt', team: 'MIN', ab: 336 },
    { id: 'acunajo01', name: 'Acuna, Luisangel', team: 'NYM', ab: 175 },
    { id: 'alonspe01', name: 'Alonso, Pete', team: 'NYM', ab: 624 },
    { id: 'alvarfr01', name: 'Alvarez, Francisco', team: 'NYM', ab: 246 },
    { id: 'azocajo01', name: 'Azocar, Jose', team: 'NYM', ab: 18 },
    { id: 'batybr01', name: 'Baty, Brett', team: 'NYM', ab: 393 },
    { id: 'diazed04', name: 'Diaz, Edwin', team: 'NYM', ab: 0 },
    { id: 'jankotr01', name: 'Jankowski, Travis', team: 'NYM', ab: 0 },
    { id: 'lindofr01', name: 'Lindor, Francisco', team: 'NYM', ab: 644 },
    { id: 'martest01', name: 'Marte, Starling', team: 'NYM', ab: 293 },
    { id: 'mauriro01', name: 'Mauricio, Ronny', team: 'NYM', ab: 168 },
    { id: 'mcneije01', name: 'McNeil, Jeff', team: 'NYM', ab: 399 },
    { id: 'mullice01', name: 'Mullins, Cedric', team: 'NYM', ab: 121 },
    { id: 'nimmobr01', name: 'Nimmo, Brandon', team: 'NYM', ab: 587 },
    { id: 'sengeha01', name: 'Senger, Hayden', team: 'NYM', ab: 72 },
    { id: 'sirijo01', name: 'Siri, Jose', team: 'NYM', ab: 32 },
    { id: 'sotoju01', name: 'Soto, Juan', team: 'NYM', ab: 577 },
    { id: 'stanery01', name: 'Stanek, Ryne', team: 'NYM', ab: 0 },
    { id: 'tayloty01', name: 'Taylor, Tyrone', team: 'NYM', ab: 310 },
    { id: 'torrelu01', name: 'Torrens, Luis', team: 'NYM', ab: 261 },
    { id: 'vientma01', name: 'Vientos, Mark', team: 'NYM', ab: 424 },
    { id: 'winkeje01', name: 'Winker, Jesse', team: 'NYM', ab: 70 },
    { id: 'youngja02', name: 'Young, Jared', team: 'NYM', ab: 43 },
    { id: 'bellico01', name: 'Bellinger, Cody', team: 'NYY', ab: 588 },
    { id: 'cabaljo01', name: 'Caballero, Jose', team: 'NYY', ab: 79 },
    { id: 'cabreos01', name: 'Cabrera, Oswaldo', team: 'NYY', ab: 107 },
    { id: 'chishja01', name: 'Chisholm Jr, Jazz', team: 'NYY', ab: 462 },
    { id: 'delosye01', name: 'De los Santos, Yerry', team: 'NYY', ab: 0 },
    { id: 'dominja01', name: 'Dominguez, Jasson', team: 'NYY', ab: 381 },
    { id: 'escarjc01', name: 'Escarra, JC', team: 'NYY', ab: 84 },
    { id: 'goldspa01', name: 'Goldschmidt, Paul', team: 'NYY', ab: 489 },
    { id: 'grishtr01', name: 'Grisham, Trent', team: 'NYY', ab: 494 },
    { id: 'judgeaa01', name: 'Judge, Aaron', team: 'NYY', ab: 541 },
    { id: 'lemahdj01', name: 'LeMahieu, DJ', team: 'NYY', ab: 128 },
    { id: 'matzety01', name: 'Matzek, Tyler', team: 'NYY', ab: 0 },
    { id: 'mcmahry01', name: 'McMahon, Ryan', team: 'NYY', ab: 159 },
    { id: 'perazos02', name: 'Peraza, Oswald', team: 'NYY', ab: 158 },
    { id: 'reyespa01', name: 'Reyes, Pablo', team: 'NYY', ab: 31 },
    { id: 'ricebe01', name: 'Rice, Ben', team: 'NYY', ab: 467 },
    { id: 'rosaram01', name: 'Rosario, Amed', team: 'NYY', ab: 33 },
    { id: 'slateau01', name: 'Slater, Austin', team: 'NYY', ab: 25 },
    { id: 'stantmi03', name: 'Stanton, Giancarlo', team: 'NYY', ab: 249 },
    { id: 'vivasjo01', name: 'Vivas, Jorbit', team: 'NYY', ab: 56 },
    { id: 'volpean01', name: 'Volpe, Anthony', team: 'NYY', ab: 539 },
    { id: 'wellsau01', name: 'Wells, Austin', team: 'NYY', ab: 401 },
    { id: 'baderha01', name: 'Bader, Harrison', team: 'PHI', ab: 177 },
    { id: 'bohmal01', name: 'Bohm, Alec', team: 'PHI', ab: 464 },
    { id: 'casteni01', name: 'Castellanos, Nick', team: 'PHI', ab: 547 },
    { id: 'clemeko01', name: 'Clemens, Kody', team: 'PHI', ab: 6 },
    { id: 'harpebr03', name: 'Harper, Bryce', team: 'PHI', ab: 501 },
    { id: 'kempot01', name: 'Kemp, Otto', team: 'PHI', ab: 197 },
    { id: 'kennebu01', name: 'Kennedy, Buddy', team: 'PHI', ab: 7 },
    { id: 'keplema01', name: 'Kepler, Max', team: 'PHI', ab: 417 },
    { id: 'marchra01', name: 'Marchan, Rafael', team: 'PHI', ab: 105 },
    { id: 'marshbr02', name: 'Marsh, Brandon', team: 'PHI', ab: 379 },
    { id: 'realmjt01', name: 'Realmuto, JT', team: 'PHI', ab: 502 },
    { id: 'rojasjo03', name: 'Rojas, Johan', team: 'PHI', ab: 152 },
    { id: 'schwaky01', name: 'Schwarber, Kyle', team: 'PHI', ab: 604 },
    { id: 'sosaed01', name: 'Sosa, Edmundo', team: 'PHI', ab: 243 },
    { id: 'steveca01', name: 'Stevenson, Cal', team: 'PHI', ab: 8 },
    { id: 'stottbr01', name: 'Stott, Bryson', team: 'PHI', ab: 499 },
    { id: 'stubbga01', name: 'Stubbs, Garrett', team: 'PHI', ab: 1 },
    { id: 'turnetr01', name: 'Turner, Trea', team: 'PHI', ab: 589 },
    { id: 'waltodo01', name: 'Walton, Donovan', team: 'PHI', ab: 8 },
    { id: 'wilsowe01', name: 'Wilson, Weston', team: 'PHI', ab: 111 },
    { id: 'baeji01', name: 'Bae, Ji Hwan', team: 'PIT', ab: 20 },
    { id: 'bartjo01', name: 'Bart, Joey', team: 'PIT', ab: 285 },
    { id: 'canaral01', name: 'Canario, Alexander', team: 'PIT', ab: 216 },
    { id: 'chengts01', name: 'Cheng, Tsung-Che', team: 'PIT', ab: 7 },
    { id: 'cookbi01', name: 'Cook, Billy', team: 'PIT', ab: 6 },
    { id: 'cruzon01', name: 'Cruz, Oneil', team: 'PIT', ab: 471 },
    { id: 'davishe01', name: 'Davis, Henry', team: 'PIT', ab: 252 },
    { id: 'devanca01', name: 'Devanney, Cam', team: 'PIT', ab: 36 },
    { id: 'florera03', name: 'Flores, Rafael', team: 'PIT', ab: 15 },
    { id: 'fraziad01', name: 'Frazier, Adam', team: 'PIT', ab: 235 },
    { id: 'gonzani01', name: 'Gonzales, Nick', team: 'PIT', ab: 381 },
    { id: 'gorskma01', name: 'Gorski, Matt', team: 'PIT', ab: 41 },
    { id: 'hayeske01', name: 'Hayes, Ke\'Bryan', team: 'PIT', ab: 369 },
    { id: 'horwisp01', name: 'Horwitz, Spencer', team: 'PIT', ab: 364 },
    { id: 'kineris01', name: 'Kiner-Falefa, Isiah', team: 'PIT', ab: 401 },
    { id: 'mccutan01', name: 'McCutchen, Andrew', team: 'PIT', ab: 477 },
    { id: 'pegueli01', name: 'Peguero, Liover', team: 'PIT', ab: 80 },
    { id: 'phamth01', name: 'Pham, Tommy', team: 'PIT', ab: 392 },
    { id: 'reynobr01', name: 'Reynolds, Bryan', team: 'PIT', ab: 587 },
    { id: 'rodrien01', name: 'Rodriguez, Endy', team: 'PIT', ab: 52 },
    { id: 'simonro01', name: 'Simon, Ronny', team: 'PIT', ab: 30 },
    { id: 'solakni01', name: 'Solak, Nick', team: 'PIT', ab: 11 },
    { id: 'sullibr01', name: 'Sullivan, Brett', team: 'PIT', ab: 6 },
    { id: 'suwinja01', name: 'Suwinski, Jack', team: 'PIT', ab: 150 },
    { id: 'triolja01', name: 'Triolo, Jared', team: 'PIT', ab: 331 },
    { id: 'valdeen01', name: 'Valdez, Enmanuel', team: 'PIT', ab: 91 },
    { id: 'yorkeni01', name: 'Yorke, Nick', team: 'PIT', ab: 69 },
    { id: 'arraelu01', name: 'Arraez, Luis', team: 'SDP', ab: 620 },
    { id: 'bogaexa01', name: 'Bogaerts, Xander', team: 'SDP', ab: 491 },
    { id: 'brooktr01', name: 'Brooks, Trenton', team: 'SDP', ab: 41 },
    { id: 'campulu01', name: 'Campusano, Luis', team: 'SDP', ab: 21 },
    { id: 'croneja01', name: 'Cronenworth, Jake', team: 'SDP', ab: 419 },
    { id: 'diazel01', name: 'Diaz, Elias', team: 'SDP', ab: 255 },
    { id: 'fermifr01', name: 'Fermin, Freddy', team: 'SDP', ab: 127 },
    { id: 'gonzaos01', name: 'Gonzalez, Oscar', team: 'SDP', ab: 59 },
    { id: 'gourryu01', name: 'Gurriel, Yuli', team: 'SDP', ab: 36 },
    { id: 'heywaja01', name: 'Heyward, Jason', team: 'SDP', ab: 85 },
    { id: 'iglesjo01', name: 'Iglesias, Jose', team: 'SDP', ab: 306 },
    { id: 'joeco01', name: 'Joe, Connor', team: 'SDP', ab: 9 },
    { id: 'johnsbr03', name: 'Johnson, Bryce', team: 'SDP', ab: 76 },
    { id: 'laurera01', name: 'Laureano, Ramon', team: 'SDP', ab: 182 },
    { id: 'lockrbr01', name: 'Lockridge, Brandon', team: 'SDP', ab: 88 },
    { id: 'machama01', name: 'Machado, Manny', team: 'SDP', ab: 615 },
    { id: 'maldoma01', name: 'Maldonado, Martin', team: 'SDP', ab: 147 },
    { id: 'mccoyma01', name: 'McCoy, Mason', team: 'SDP', ab: 22 },
    { id: 'merrija01', name: 'Merrill, Jackson', team: 'SDP', ab: 440 },
    { id: 'ohearry01', name: 'O\'Hearn, Ryan', team: 'SDP', ab: 163 },
    { id: 'ornelti01', name: 'Ornelas, Tirso', team: 'SDP', ab: 14 },
    { id: 'sheetga01', name: 'Sheets, Gavin', team: 'SDP', ab: 492 },
    { id: 'tatisfe02', name: 'Tatis Jr, Fernando', team: 'SDP', ab: 594 },
    { id: 'wadety01', name: 'Wade, Tyler', team: 'SDP', ab: 107 },
    { id: 'wagnewi01', name: 'Wagner, Will', team: 'SDP', ab: 15 },
    { id: 'arozara01', name: 'Arozarena, Randy', team: 'SEA', ab: 613 },
    { id: 'blissry01', name: 'Bliss, Ryan', team: 'SEA', ab: 35 },
    { id: 'canzodo01', name: 'Canzone, Dominic', team: 'SEA', ab: 243 },
    { id: 'castijo03', name: 'Castillo, Jose', team: 'SEA', ab: 0 },
    { id: 'crawfjp01', name: 'Crawford, JP', team: 'SEA', ab: 570 },
    { id: 'fordha01', name: 'Ford, Harry', team: 'SEA', ab: 6 },
    { id: 'garvemi01', name: 'Garver, Mitch', team: 'SEA', ab: 254 },
    { id: 'hancoem01', name: 'Hancock, Emerson', team: 'SEA', ab: 0 },
    { id: 'legumca01', name: 'Legumina, Casey', team: 'SEA', ab: 0 },
    { id: 'mastrmi01', name: 'Mastrobuoni, Miles', team: 'SEA', ab: 152 },
    { id: 'mooredy01', name: 'Moore, Dylan', team: 'SEA', ab: 192 },
    { id: 'naylojo01', name: 'Naylor, Josh', team: 'SEA', ab: 194 },
    { id: 'polanjo01', name: 'Polanco, Jorge', team: 'SEA', ab: 471 },
    { id: 'popza01', name: 'Pop, Zach', team: 'SEA', ab: 0 },
    { id: 'raleica01', name: 'Raleigh, Cal', team: 'SEA', ab: 596 },
    { id: 'raleylu01', name: 'Raley, Luke', team: 'SEA', ab: 183 },
    { id: 'rivasle01', name: 'Rivas, Leo', team: 'SEA', ab: 90 },
    { id: 'roblevi01', name: 'Robles, Victor', team: 'SEA', ab: 106 },
    { id: 'rodriju01', name: 'Rodriguez, Julio', team: 'SEA', ab: 652 },
    { id: 'solando01', name: 'Solano, Donovan', team: 'SEA', ab: 163 },
    { id: 'suareeu01', name: 'Suarez, Eugenio', team: 'SEA', ab: 201 },
    { id: 'taverle01', name: 'Taveras, Leody', team: 'SEA', ab: 92 },
    { id: 'taylosa04', name: 'Taylor, Samad', team: 'SEA', ab: 8 },
    { id: 'tellero01', name: 'Tellez, Rowdy', team: 'SEA', ab: 173 },
    { id: 'thomarh01', name: 'Thomas, Rhylan', team: 'SEA', ab: 8 },
    { id: 'thorntr01', name: 'Thornton, Trent', team: 'SEA', ab: 0 },
    { id: 'willibe03', name: 'Williamson, Ben', team: 'SEA', ab: 277 },
    { id: 'youngco01', name: 'Young, Cole', team: 'SEA', ab: 223 },
    { id: 'adamewi01', name: 'Adames, Willy', team: 'SFG', ab: 591 },
    { id: 'alcanse01', name: 'Alcantara, Sergio', team: 'SFG', ab: 4 },
    { id: 'bailepa01', name: 'Bailey, Patrick', team: 'SFG', ab: 409 },
    { id: 'birdsha01', name: 'Birdsong, Hayden', team: 'SFG', ab: 0 },
    { id: 'chapmma01', name: 'Chapman, Matt', team: 'SFG', ab: 454 },
    { id: 'deverra01', name: 'Devers, Rafael', team: 'SFG', ab: 335 },
    { id: 'eldribr01', name: 'Eldridge, Bryce', team: 'SFG', ab: 28 },
    { id: 'encarje01', name: 'Encarnacion, Jerar', team: 'SFG', ab: 55 },
    { id: 'fitzgty01', name: 'Fitzgerald, Tyler', team: 'SFG', ab: 217 },
    { id: 'florewi01', name: 'Flores, Wilmer', team: 'SFG', ab: 419 },
    { id: 'gilbedr01', name: 'Gilbert, Drew', team: 'SFG', ab: 100 },
    { id: 'huffsa01', name: 'Huff, Sam', team: 'SFG', ab: 53 },
    { id: 'johnsda07', name: 'Johnson, Daniel', team: 'SFG', ab: 29 },
    { id: 'kniznan01', name: 'Knizner, Andrew', team: 'SFG', ab: 77 },
    { id: 'kossch01', name: 'Koss, Christian', team: 'SFG', ab: 174 },
    { id: 'leeju01', name: 'Lee, Jung Hoo', team: 'SFG', ab: 560 },
    { id: 'matoslu02', name: 'Matos, Luis', team: 'SFG', ab: 172 },
    { id: 'mccragr01', name: 'McCray, Grant', team: 'SFG', ab: 22 },
    { id: 'portelo01', name: 'Porter, Logan', team: 'SFG', ab: 7 },
    { id: 'ramoshe02', name: 'Ramos, Heliot', team: 'SFG', ab: 620 },
    { id: 'rogerty01', name: 'Rogers, Tyler', team: 'SFG', ab: 0 },
    { id: 'schmica01', name: 'Schmitt, Casey', team: 'SFG', ab: 312 },
    { id: 'smithdo02', name: 'Smith, Dominic', team: 'SFG', ab: 204 },
    { id: 'villada01', name: 'Villar, David', team: 'SFG', ab: 20 },
    { id: 'wadela01', name: 'Wade Jr, LaMonte', team: 'SFG', ab: 144 },
    { id: 'walkery01', name: 'Walker, Ryan', team: 'SFG', ab: 0 },
    { id: 'wiselbr01', name: 'Wisely, Brett', team: 'SFG', ab: 48 },
    { id: 'yastrmi01', name: 'Yastrzemski, Mike', team: 'SFG', ab: 321 },
    { id: 'arenano01', name: 'Arenado, Nolan', team: 'STL', ab: 401 },
    { id: 'bakerlu01', name: 'Baker, Luken', team: 'STL', ab: 34 },
    { id: 'garcijo02', name: 'Barrero, Jose', team: 'STL', ab: 29 },
    { id: 'burleal01', name: 'Burleson, Alec', team: 'STL', ab: 497 },
    { id: 'churcna01', name: 'Church, Nathan', team: 'STL', ab: 56 },
    { id: 'contrwi01', name: 'Contreras, Willson', team: 'STL', ab: 490 },
    { id: 'crookji01', name: 'Crooks, Jimmy', team: 'STL', ab: 45 },
    { id: 'donovbr01', name: 'Donovan, Brendan', team: 'STL', ab: 460 },
    { id: 'fermijo01', name: 'Fermin, Jose', team: 'STL', ab: 60 },
    { id: 'gormano01', name: 'Gorman, Nolan', team: 'STL', ab: 351 },
    { id: 'hampsga01', name: 'Hampson, Garrett', team: 'STL', ab: 29 },
    { id: 'helslry01', name: 'Helsley, Ryan', team: 'STL', ab: 0 },
    { id: 'herreiv01', name: 'Herrera, Ivan', team: 'STL', ab: 388 },
    { id: 'matonph01', name: 'Maton, Phil', team: 'STL', ab: 0 },
    { id: 'nootbla01', name: 'Nootbaar, Lars', team: 'STL', ab: 509 },
    { id: 'pagespe02', name: 'Pages, Pedro', team: 'STL', ab: 361 },
    { id: 'pallaan01', name: 'Pallante, Andre', team: 'STL', ab: 0 },
    { id: 'pozoyo01', name: 'Pozo, Yohel', team: 'STL', ab: 160 },
    { id: 'prietce01', name: 'Prieto, Cesar', team: 'STL', ab: 6 },
    { id: 'saggeth01', name: 'Saggese, Thomas', team: 'STL', ab: 275 },
    { id: 'scottvi01', name: 'Scott II, Victor', team: 'STL', ab: 398 },
    { id: 'sianimi01', name: 'Siani, Michael', team: 'STL', ab: 17 },
    { id: 'viladry01', name: 'Vilade, Ryan', team: 'STL', ab: 13 },
    { id: 'walkejo02', name: 'Walker, Jordan', team: 'STL', ab: 363 },
    { id: 'winnma01', name: 'Winn, Masyn', team: 'STL', ab: 491 },
    { id: 'arandjo01', name: 'Aranda, Jonathan', team: 'TBR', ab: 370 },
    { id: 'cabaljo01', name: 'Caballero, Jose', team: 'TBR', ab: 235 },
    { id: 'caminju01', name: 'Caminero, Junior', team: 'TBR', ab: 602 },
    { id: 'delucjo01', name: 'DeLuca, Jonny', team: 'TBR', ab: 57 },
    { id: 'diazya01', name: 'Diaz, Yandy', team: 'TBR', ab: 583 },
    { id: 'feduchu01', name: 'Feduccia, Hunter', team: 'TBR', ab: 86 },
    { id: 'forteni01', name: 'Fortes, Nick', team: 'TBR', ab: 89 },
    { id: 'graytr01', name: 'Gray, Tristan', team: 'TBR', ab: 78 },
    { id: 'jankotr01', name: 'Jankowski, Travis', team: 'TBR', ab: 31 },
    { id: 'janseda01', name: 'Jansen, Danny', team: 'TBR', ab: 221 },
    { id: 'kellyke02', name: 'Kelly, Kevin', team: 'TBR', ab: 0 },
    { id: 'kimha01', name: 'Kim, Ha-Seong', team: 'TBR', ab: 84 },
    { id: 'lowebr01', name: 'Lowe, Brandon', team: 'TBR', ab: 507 },
    { id: 'lowejo01', name: 'Lowe, Josh', team: 'TBR', ab: 396 },
    { id: 'manguja01', name: 'Mangum, Jake', team: 'TBR', ab: 405 },
    { id: 'meadcu01', name: 'Mead, Curtis', team: 'TBR', ab: 115 },
    { id: 'misneka01', name: 'Misner, Kameron', team: 'TBR', ab: 197 },
    { id: 'monteco01', name: 'Montes, Coco', team: 'TBR', ab: 10 },
    { id: 'morelch01', name: 'Morel, Christopher', team: 'TBR', ab: 278 },
    { id: 'palacri01', name: 'Palacios, Richie', team: 'TBR', ab: 42 },
    { id: 'pereiev01', name: 'Pereira, Everson', team: 'TBR', ab: 65 },
    { id: 'petertr01', name: 'Peters, Tristan', team: 'TBR', ab: 12 },
    { id: 'rortvbe01', name: 'Rortvedt, Ben', team: 'TBR', ab: 63 },
    { id: 'seaboco01', name: 'Seabold, Connor', team: 'TBR', ab: 0 },
    { id: 'seymobo01', name: 'Seymour, Bob', team: 'TBR', ab: 78 },
    { id: 'simpsch01', name: 'Simpson, Chandler', team: 'TBR', ab: 414 },
    { id: 'thaisma01', name: 'Thaiss, Matt', team: 'TBR', ab: 71 },
    { id: 'wallsta01', name: 'Walls, Taylor', team: 'TBR', ab: 282 },
    { id: 'willica02', name: 'Williams, Carson', team: 'TBR', ab: 99 },
    { id: 'ahmedni01', name: 'Ahmed, Nick', team: 'TEX', ab: 9 },
    { id: 'armstsh01', name: 'Armstrong, Shawn', team: 'TEX', ab: 0 },
    { id: 'barnhtu01', name: 'Barnhart, Tucker', team: 'TEX', ab: 13 },
    { id: 'burgeja01', name: 'Burger, Jake', team: 'TEX', ab: 356 },
    { id: 'carteev01', name: 'Carter, Evan', team: 'TEX', ab: 194 },
    { id: 'crimbl01', name: 'Crim, Blaine', team: 'TEX', ab: 11 },
    { id: 'curvelu01', name: 'Curvelo, Luis', team: 'TEX', ab: 0 },
    { id: 'duranez01', name: 'Duran, Ezequiel', team: 'TEX', ab: 205 },
    { id: 'foscuju01', name: 'Foscue, Justin', team: 'TEX', ab: 9 },
    { id: 'freemco01', name: 'Freeman, Cody', team: 'TEX', ab: 114 },
    { id: 'garciad02', name: 'Garcia, Adolis', team: 'TEX', ab: 507 },
    { id: 'garciro04', name: 'Garcia, Robert', team: 'TEX', ab: 0 },
    { id: 'haggesa01', name: 'Haggerty, Sam', team: 'TEX', ab: 162 },
    { id: 'harridu01', name: 'Harris, Dustin', team: 'TEX', ab: 40 },
    { id: 'heimjo01', name: 'Heim, Jonah', team: 'TEX', ab: 395 },
    { id: 'helmami01', name: 'Helman, Michael', team: 'TEX', ab: 99 },
    { id: 'higasky01', name: 'Higashioka, Kyle', team: 'TEX', ab: 303 },
    { id: 'jungjo01', name: 'Jung, Josh', team: 'TEX', ab: 482 },
    { id: 'langfwy01', name: 'Langford, Wyatt', team: 'TEX', ab: 489 },
    { id: 'leiteja01', name: 'Leiter, Jack', team: 'TEX', ab: 1 },
    { id: 'mckinbi01', name: 'McKinney, Billy', team: 'TEX', ab: 20 },
    { id: 'milneho01', name: 'Milner, Hoby', team: 'TEX', ab: 0 },
    { id: 'mooredy01', name: 'Moore, Dylan', team: 'TEX', ab: 27 },
    { id: 'orneljo01', name: 'Ornelas, Jonathan', team: 'TEX', ab: 5 },
    { id: 'osunaal02', name: 'Osuna, Alejandro', team: 'TEX', ab: 151 },
    { id: 'pederjo01', name: 'Pederson, Joc', team: 'TEX', ab: 265 },
    { id: 'pillake01', name: 'Pillar, Kevin', team: 'TEX', ab: 43 },
    { id: 'seageco01', name: 'Seager, Corey', team: 'TEX', ab: 380 },
    { id: 'semiema01', name: 'Semien, Marcus', team: 'TEX', ab: 470 },
    { id: 'smithjo11', name: 'Smith, Josh', team: 'TEX', ab: 495 },
    { id: 'solando01', name: 'Solano, Donovan', team: 'TEX', ab: 3 },
    { id: 'taverle01', name: 'Taveras, Leody', team: 'TEX', ab: 79 },
    { id: 'tellero01', name: 'Tellez, Rowdy', team: 'TEX', ab: 116 },
    { id: 'bargead01', name: 'Barger, Addison', team: 'TOR', ab: 460 },
    { id: 'bichebo01', name: 'Bichette, Bo', team: 'TOR', ab: 582 },
    { id: 'clasejo01', name: 'Clase, Jonatan', team: 'TOR', ab: 100 },
    { id: 'clemeer01', name: 'Clement, Ernie', team: 'TOR', ab: 545 },
    { id: 'francty01', name: 'France, Ty', team: 'TOR', ab: 94 },
    { id: 'garciyi01', name: 'Garcia, Yimi', team: 'TOR', ab: 0 },
    { id: 'gimenan01', name: 'Gimenez, Andres', team: 'TOR', ab: 329 },
    { id: 'guerrvl02', name: 'Guerrero Jr, Vladimir', team: 'TOR', ab: 589 },
    { id: 'heinety01', name: 'Heineman, Tyler', team: 'TOR', ab: 149 },
    { id: 'hoffmje02', name: 'Hoffman, Jeff', team: 'TOR', ab: 0 },
    { id: 'jimenle01', name: 'Jimenez, Leo', team: 'TOR', ab: 29 },
    { id: 'kennebu01', name: 'Kennedy, Buddy', team: 'TOR', ab: 5 },
    { id: 'kineris01', name: 'Kiner-Falefa, Isiah', team: 'TOR', ab: 30 },
    { id: 'kirkal01', name: 'Kirk, Alejandro', team: 'TOR', ab: 451 },
    { id: 'loperjo01', name: 'Loperfido, Joey', team: 'TOR', ab: 96 },
    { id: 'lukesna01', name: 'Lukes, Nathan', team: 'TOR', ab: 388 },
    { id: 'roberwi02', name: 'Robertson, Will', team: 'TOR', ab: 10 },
    { id: 'rodenal01', name: 'Roden, Alan', team: 'TOR', ab: 98 },
    { id: 'sanchal04', name: 'Sanchez, Ali', team: 'TOR', ab: 21 },
    { id: 'sandlni01', name: 'Sandlin, Nick', team: 'TOR', ab: 0 },
    { id: 'santaan02', name: 'Santander, Anthony', team: 'TOR', ab: 194 },
    { id: 'schneda03', name: 'Schneider, Davis', team: 'TOR', ab: 188 },
    { id: 'springe01', name: 'Springer, George', team: 'TOR', ab: 498 },
    { id: 'stefami01', name: 'Stefanic, Michael', team: 'TOR', ab: 22 },
    { id: 'strawmy01', name: 'Straw, Myles', team: 'TOR', ab: 267 },
    { id: 'varshda01', name: 'Varsho, Daulton', team: 'TOR', ab: 248 },
    { id: 'wagnewi01', name: 'Wagner, Will', team: 'TOR', ab: 114 },
    { id: 'andujmi01', name: 'Andujar, Miguel', team: 'TOT', ab: 321 },
    { id: 'arciaor01', name: 'Arcia, Orlando', team: 'TOT', ab: 203 },
    { id: 'avansdr01', name: 'Avans, Drew', team: 'TOT', ab: 17 },
    { id: 'azocajo01', name: 'Azocar, Jose', team: 'TOT', ab: 19 },
    { id: 'baderha01', name: 'Bader, Harrison', team: 'TOT', ab: 448 },
    { id: 'bridejo01', name: 'Bride, Jonah', team: 'TOT', ab: 112 },
    { id: 'brujavi01', name: 'Brujan, Vidal', team: 'TOT', ab: 86 },
    { id: 'brujavi01', name: 'Brujan, Vidal', team: 'TOT', ab: 87 },
    { id: 'cabaljo01', name: 'Caballero, Jose', team: 'TOT', ab: 314 },
    { id: 'callal02', name: 'Call, Alex', team: 'TOT', ab: 270 },
    { id: 'capravi01', name: 'Capra, Vinny', team: 'TOT', ab: 96 },
    { id: 'castrwi01', name: 'Castro, Willi', team: 'TOT', ab: 402 },
    { id: 'clemeko01', name: 'Clemens, Kody', team: 'TOT', ab: 348 },
    { id: 'correca01', name: 'Correa, Carlos', team: 'TOT', ab: 537 },
    { id: 'crimbl01', name: 'Crim, Blaine', team: 'TOT', ab: 65 },
    { id: 'davidlo01', name: 'Davidson, Logan', team: 'TOT', ab: 42 },
    { id: 'deverra01', name: 'Devers, Rafael', team: 'TOT', ab: 607 },
    { id: 'feduchu01', name: 'Feduccia, Hunter', team: 'TOT', ab: 88 },
    { id: 'fermifr01', name: 'Fermin, Freddy', team: 'TOT', ab: 319 },
    { id: 'forteni01', name: 'Fortes, Nick', team: 'TOT', ab: 218 },
    { id: 'fraleja01', name: 'Fraley, Jake', team: 'TOT', ab: 191 },
    { id: 'francty01', name: 'France, Ty', team: 'TOT', ab: 444 },
    { id: 'fraziad01', name: 'Frazier, Adam', team: 'TOT', ab: 419 },
    { id: 'grichra01', name: 'Grichuk, Randal', team: 'TOT', ab: 272 },
    { id: 'hampsga01', name: 'Hampson, Garrett', team: 'TOT', ab: 77 },
    { id: 'hayeske01', name: 'Hayes, Ke\'Bryan', team: 'TOT', ab: 527 },
    { id: 'hillde01', name: 'Hill, Derek', team: 'TOT', ab: 134 },
    { id: 'hummeco01', name: 'Hummel, Cooper', team: 'TOT', ab: 88 },
    { id: 'jankotr01', name: 'Jankowski, Travis', team: 'TOT', ab: 45 },
    { id: 'jankotr01', name: 'Jankowski, Travis', team: 'TOT', ab: 45 },
    { id: 'janseda01', name: 'Jansen, Danny', team: 'TOT', ab: 288 },
    { id: 'joeco01', name: 'Joe, Connor', team: 'TOT', ab: 70 },
    { id: 'johnsda07', name: 'Johnson, Daniel', team: 'TOT', ab: 53 },
    { id: 'kennebu01', name: 'Kennedy, Buddy', team: 'TOT', ab: 24 },
    { id: 'kennebu01', name: 'Kennedy, Buddy', team: 'TOT', ab: 29 },
    { id: 'kimha01', name: 'Kim, Ha-Seong', team: 'TOT', ab: 171 },
    { id: 'kineris01', name: 'Kiner-Falefa, Isiah', team: 'TOT', ab: 431 },
    { id: 'laurera01', name: 'Laureano, Ramon', team: 'TOT', ab: 441 },
    { id: 'lockrbr01', name: 'Lockridge, Brandon', team: 'TOT', ab: 134 },
    { id: 'lopezni01', name: 'Lopez, Nicky', team: 'TOT', ab: 24 },
    { id: 'lowena01', name: 'Lowe, Nathaniel', team: 'TOT', ab: 540 },
    { id: 'mcmahry01', name: 'McMahon, Ryan', team: 'TOT', ab: 509 },
    { id: 'meadcu01', name: 'Mead, Curtis', team: 'TOT', ab: 240 },
    { id: 'mooredy01', name: 'Moore, Dylan', team: 'TOT', ab: 219 },
    { id: 'mullice01', name: 'Mullins, Cedric', team: 'TOT', ab: 435 },
    { id: 'naylojo01', name: 'Naylor, Josh', team: 'TOT', ab: 543 },
    { id: 'nodary01', name: 'Noda, Ryan', team: 'TOT', ab: 47 },
    { id: 'ohearry01', name: 'O\'Hearn, Ryan', team: 'TOT', ab: 474 },
    { id: 'orneljo01', name: 'Ornelas, Jonathan', team: 'TOT', ab: 9 },
    { id: 'outmaja01', name: 'Outman, James', team: 'TOT', ab: 134 },
    { id: 'perazos02', name: 'Peraza, Oswald', team: 'TOT', ab: 244 },
    { id: 'peredjh01', name: 'Pereda, Jhonny', team: 'TOT', ab: 69 },
    { id: 'roberwi02', name: 'Robertson, Will', team: 'TOT', ab: 70 },
    { id: 'rodenal01', name: 'Roden, Alan', team: 'TOT', ab: 136 },
    { id: 'rortvbe01', name: 'Rortvedt, Ben', team: 'TOT', ab: 112 },
    { id: 'rosaram01', name: 'Rosario, Amed', team: 'TOT', ab: 181 },
    { id: 'rosared01', name: 'Rosario, Eddie', team: 'TOT', ab: 8 },
    { id: 'sanchal04', name: 'Sanchez, Ali', team: 'TOT', ab: 23 },
    { id: 'sanchje02', name: 'Sanchez, Jesus', team: 'TOT', ab: 451 },
    { id: 'santaca01', name: 'Santana, Carlos', team: 'TOT', ab: 415 },
    { id: 'simonro01', name: 'Simon, Ronny', team: 'TOT', ab: 77 },
    { id: 'slateau01', name: 'Slater, Austin', team: 'TOT', ab: 148 },
    { id: 'solando01', name: 'Solano, Donovan', team: 'TOT', ab: 166 },
    { id: 'stallja01', name: 'Stallings, Jacob', team: 'TOT', ab: 119 },
    { id: 'suareeu01', name: 'Suarez, Eugenio', team: 'TOT', ab: 588 },
    { id: 'taverle01', name: 'Taveras, Leody', team: 'TOT', ab: 171 },
    { id: 'tayloch03', name: 'Taylor, Chris', team: 'TOT', ab: 113 },
    { id: 'tellero01', name: 'Tellez, Rowdy', team: 'TOT', ab: 289 },
    { id: 'thaisma01', name: 'Thaiss, Matt', team: 'TOT', ab: 156 },
    { id: 'trompch01', name: 'Tromp, Chadwick', team: 'TOT', ab: 21 },
    { id: 'uriasra01', name: 'Urias, Ramon', team: 'TOT', ab: 352 },
    { id: 'vaughan01', name: 'Vaughn, Andrew', team: 'TOT', ab: 406 },
    { id: 'viladry01', name: 'Vilade, Ryan', team: 'TOT', ab: 13 },
    { id: 'wadela01', name: 'Wade Jr, LaMonte', team: 'TOT', ab: 209 },
    { id: 'wagnewi01', name: 'Wagner, Will', team: 'TOT', ab: 129 },
    { id: 'wiselbr01', name: 'Wisely, Brett', team: 'TOT', ab: 54 },
    { id: 'workmga01', name: 'Workman, Gage', team: 'TOT', ab: 16 },
    { id: 'wynnsau01', name: 'Wynns, Austin', team: 'TOT', ab: 103 },
    { id: 'yastrmi01', name: 'Yastrzemski, Mike', team: 'TOT', ab: 477 },
    { id: 'abramcj01', name: 'Abrams, CJ', team: 'WSN', ab: 580 },
    { id: 'adamsri03', name: 'Adams, Riley', team: 'WSN', ab: 263 },
    { id: 'alfarjo01', name: 'Alfaro, Jorge', team: 'WSN', ab: 39 },
    { id: 'belljo02', name: 'Bell, Josh', team: 'WSN', ab: 468 },
    { id: 'callal02', name: 'Call, Alex', team: 'WSN', ab: 197 },
    { id: 'cavalca01', name: 'Cavalli, Cade', team: 'WSN', ab: 0 },
    { id: 'chapaan01', name: 'Chaparro, Andres', team: 'WSN', ab: 66 },
    { id: 'crewsdy01', name: 'Crews, Dylan', team: 'WSN', ab: 293 },
    { id: 'dejonpa01', name: 'DeJong, Paul', team: 'WSN', ab: 193 },
    { id: 'ferrejo01', name: 'Ferrer, Jose A', team: 'WSN', ab: 0 },
    { id: 'garcilu04', name: 'Garcia Jr, Luis', team: 'WSN', ab: 488 },
    { id: 'hassero02', name: 'Hassell III, Robert', team: 'WSN', ab: 197 },
    { id: 'housebr01', name: 'House, Brady', team: 'WSN', ab: 261 },
    { id: 'lileda01', name: 'Lile, Daylen', team: 'WSN', ab: 321 },
    { id: 'lipsctr01', name: 'Lipscomb, Trey', team: 'WSN', ab: 4 },
    { id: 'lowena01', name: 'Lowe, Nathaniel', team: 'WSN', ab: 440 },
    { id: 'milladr01', name: 'Millas, Drew', team: 'WSN', ab: 49 },
    { id: 'nunezna01', name: 'Nunez, Nasim', team: 'WSN', ab: 82 },
    { id: 'ogasash01', name: 'Ogasawara, Shinnosuke', team: 'WSN', ab: 1 },
    { id: 'pilkiko01', name: 'Pilkington, Konnor', team: 'WSN', ab: 0 },
    { id: 'poulipj01', name: 'Poulin, PJ', team: 'WSN', ab: 0 },
    { id: 'rosaram01', name: 'Rosario, Amed', team: 'WSN', ab: 148 },
    { id: 'ruizke01', name: 'Ruiz, Keibert', team: 'WSN', ab: 255 },
    { id: 'rutleja01', name: 'Rutledge, Jackson', team: 'WSN', ab: 0 },
    { id: 'stubbcj01', name: 'Stubbs, CJ', team: 'WSN', ab: 3 },
    { id: 'tenajo01', name: 'Tena, Jose', team: 'WSN', ab: 152 },
    { id: 'woodja03', name: 'Wood, James', team: 'WSN', ab: 598 },
    { id: 'youngja03', name: 'Young, Jacob', team: 'WSN', ab: 324 },
];

export function convertToCsv() {
    const hittersOnIndividualTeams: HittersOnIndividualTeams[] = [];

    allHitters.forEach(indTeam => {
        if (indTeam.team !== 'TOT' && multiTeamHitters[indTeam.id]) {
            const nameParts = multiTeamHitters[indTeam.id].name.split(', ');
            hittersOnIndividualTeams.push({
                year: 2025,
                name: nameParts[0] + ',' + nameParts[1][0],
                bats: multiTeamHitters[indTeam.id].bats,
                team: indTeam.team,
                ab: indTeam.ab,
            });
        }
    });

    return hittersOnIndividualTeams;
}
