type MultiTeamPitchers = {
    name: string;
    team: string;
    throws: string;
    ip: number;
};

type AllPitchers = {
    id: string;
    name: string;
    team: string;
    ip: number;
};

type PitchersOnIndividualTeams = {
    year: number;
    name: string;
    throws: string;
    team: string;
    ip: string;
};

const multiTeamPitchers: Record<string, MultiTeamPitchers> = {
    // paste here the formatted column from the 'Carded' sheet of the 'Pitcher_Stats_20xx.xlsx' file... only the pitchers whose team is 'TOT'
    alcaljo01: { name: 'Alcala, Jorge', team: 'TOT', throws: 'R', ip: 55 },
    alexaja01: { name: 'Alexander, Jason', team: 'TOT', throws: 'R', ip: 77.1 },
    alexaty01: { name: 'Alexander, Tyler', team: 'TOT', throws: 'L', ip: 97.2 },
    bakerbr01: { name: 'Baker, Bryan', team: 'TOT', throws: 'R', ip: 68.2 },
    bednada01: { name: 'Bednar, David', team: 'TOT', throws: 'R', ip: 62.2 },
    bergery01: { name: 'Bergert, Ryan', team: 'TOT', throws: 'R', ip: 76.1 },
    birdja01: { name: 'Bird, Jake', team: 'TOT', throws: 'R', ip: 55.1 },
    borucry01: { name: 'Borucki, Ryan', team: 'TOT', throws: 'L', ip: 35 },
    bradlta01: { name: 'Bradley, Taj', team: 'TOT', throws: 'R', ip: 142.2 },
    buehlwa01: { name: 'Buehler, Walker', team: 'TOT', throws: 'R', ip: 126 },
    buttojo01: { name: 'Butto, Jose', team: 'TOT', throws: 'R', ip: 67 },
    cabrege01: { name: 'Cabrera, Genesis', team: 'TOT', throws: 'L', ip: 42.2 },
    chafian01: { name: 'Chafin, Andrew', team: 'TOT', throws: 'L', ip: 33.2 },
    civalaa01: { name: 'Civale, Aaron', team: 'TOT', throws: 'R', ip: 102 },
    couloda01: { name: 'Coulombe, Danny', team: 'TOT', throws: 'L', ip: 43 },
    delosen01: { name: 'De Los Santos, Enyel', team: 'TOT', throws: 'R', ip: 66 },
    dominse01: { name: 'Dominguez, Seranthony', team: 'TOT', throws: 'R', ip: 62.2 },
    dovalca01: { name: 'Doval, Camilo', team: 'TOT', throws: 'R', ip: 65.1 },
    dubinsh01: { name: 'Dubin, Shawn', team: 'TOT', throws: 'R', ip: 33.2 },
    duranjh01: { name: 'Duran, Jhoan', team: 'TOT', throws: 'R', ip: 70 },
    falteba01: { name: 'Falter, Bailey', team: 'TOT', throws: 'L', ip: 125.1 },
    feddeer01: { name: 'Fedde, Erick', team: 'TOT', throws: 'R', ip: 141 },
    ferguca01: { name: 'Ferguson, Caleb', team: 'TOT', throws: 'L', ip: 65.1 },
    finneky01: { name: 'Finnegan, Kyle', team: 'TOT', throws: 'R', ip: 57 },
    gagema01: { name: 'Gage, Matt', team: 'TOT', throws: 'L', ip: 31 },
    garcilu03: { name: 'Garcia, Luis', team: 'TOT', throws: 'R', ip: 55.1 },
    gomezyo01: { name: 'Gomez, Yoendrys', team: 'TOT', throws: 'R', ip: 62.2 },
    gustory01: { name: 'Gusto, Ryan', team: 'TOT', throws: 'R', ip: 101.2 },
    heanean01: { name: 'Heaney, Andrew', team: 'TOT', throws: 'L', ip: 122.1 },
    helslry01: { name: 'Helsley, Ryan', team: 'TOT', throws: 'R', ip: 56 },
    hernaca04: { name: 'Hernandez, Carlos', team: 'TOT', throws: 'R', ip: 43.1 },
    hicksjo03: { name: 'Hicks, Jordan', team: 'TOT', throws: 'R', ip: 67.1 },
    housead01: { name: 'Houser, Adrian', team: 'TOT', throws: 'R', ip: 125 },
    jackslu01: { name: 'Jackson, Luke', team: 'TOT', throws: 'R', ip: 51 },
    jaxgr01: { name: 'Jax, Griffin', team: 'TOT', throws: 'R', ip: 66 },
    kellyme01: { name: 'Kelly, Merrill', team: 'TOT', throws: 'R', ip: 184 },
    kinlety01: { name: 'Kinley, Tyler', team: 'TOT', throws: 'R', ip: 72.2 },
    kittran01: { name: 'Kittredge, Andrew', team: 'TOT', throws: 'R', ip: 53 },
    kolekst01: { name: 'Kolek, Stephen', team: 'TOT', throws: 'R', ip: 112.2 },
    litteza01: { name: 'Littell, Zack', team: 'TOT', throws: 'R', ip: 186.2 },
    matonph01: { name: 'Maton, Phil', team: 'TOT', throws: 'R', ip: 61.1 },
    matzst01: { name: 'Matz, Steven', team: 'TOT', throws: 'L', ip: 76.2 },
    maydu01: { name: 'May, Dustin', team: 'TOT', throws: 'R', ip: 132.1 },
    millema03: { name: 'Miller, Mason', team: 'TOT', throws: 'R', ip: 61.2 },
    millesh01: { name: 'Miller, Shelby', team: 'TOT', throws: 'R', ip: 46 },
    montera01: { name: 'Montero, Rafael', team: 'TOT', throws: 'R', ip: 60.1 },
    mortoch02: { name: 'Morton, Charlie', team: 'TOT', throws: 'R', ip: 142 },
    nerishe01: { name: 'Neris, Hector', team: 'TOT', throws: 'R', ip: 26.2 },
    newcose01: { name: 'Newcomb, Sean', team: 'TOT', throws: 'L', ip: 92.1 },
    paddach01: { name: 'Paddack, Chris', team: 'TOT', throws: 'R', ip: 158 },
    payamjo01: { name: 'Payamps, Joel', team: 'TOT', throws: 'R', ip: 26.1 },
    quantca01: { name: 'Quantrill, Cal', team: 'TOT', throws: 'R', ip: 117.2 },
    rogerta01: { name: 'Rogers, Taylor', team: 'TOT', throws: 'L', ip: 50.2 },
    rogerty01: { name: 'Rogers, Tyler', team: 'TOT', throws: 'R', ip: 77.1 },
    searsjp01: { name: 'Sears, JP', team: 'TOT', throws: 'L', ip: 135.2 },
    sorokmi01: { name: 'Soroka, Michael', team: 'TOT', throws: 'R', ip: 89.2 },
    sotogr01: { name: 'Soto, Gregory', team: 'TOT', throws: 'L', ip: 60.1 },
    stewabr01: { name: 'Stewart, Brock', team: 'TOT', throws: 'R', ip: 37.2 },
    trivilo01: { name: 'Trivino, Lou', team: 'TOT', throws: 'R', ip: 47.2 },
    varlalo01: { name: 'Varland, Louis', team: 'TOT', throws: 'R', ip: 72.2 },
    wentzjo01: { name: 'Wentz, Joey', team: 'TOT', throws: 'L', ip: 98 },
};

const allPitchers: AllPitchers[] = [
    // paste here the formatted column from the 'Original_with_Ind_Teams' sheet of the 'Pitcher_Stats_20xx.xlsx' file... including all pitchers
    { id: 'abbotan01', name: 'Abbott, Andrew', team: 'CIN', ip: 166.1 },
    { id: 'abelmi01', name: 'Abel, Mick', team: 'TOT', ip: 39 },
    { id: 'abelmi01', name: 'Abel, Mick', team: 'PHI', ip: 25 },
    { id: 'abelmi01', name: 'Abel, Mick', team: 'MIN', ip: 14 },
    { id: 'abnerph01', name: 'Abner, Philip', team: 'ARI', ip: 3.2 },
    { id: 'abreubr01', name: 'Abreu, Bryan', team: 'HOU', ip: 71 },
    { id: 'actonga01', name: 'Acton, Garrett', team: 'TBR', ip: 1 },
    { id: 'adamja01', name: 'Adam, Jason', team: 'SDP', ip: 65.1 },
    { id: 'adamstr01', name: 'Adams, Travis', team: 'MIN', ip: 33.2 },
    { id: 'adcocty01', name: 'Adcock, Ty', team: 'NYM', ip: 3 },
    { id: 'agnosza01', name: 'Agnos, Zach', team: 'COL', ip: 31.1 },
    { id: 'akinke01', name: 'Akin, Keegan', team: 'BAL', ip: 63.1 },
    { id: 'alcaljo01', name: 'Alcala, Jorge', team: 'TOT', ip: 55 },
    { id: 'alcaljo01', name: 'Alcala, Jorge', team: 'TOT', ip: 40.2 },
    { id: 'alcaljo01', name: 'Alcala, Jorge', team: 'MIN', ip: 24.1 },
    { id: 'alcaljo01', name: 'Alcala, Jorge', team: 'BOS', ip: 16.1 },
    { id: 'alcaljo01', name: 'Alcala, Jorge', team: 'STL', ip: 14.1 },
    { id: 'alcansa01', name: 'Alcantara, Sandy', team: 'MIA', ip: 174.2 },
    { id: 'aldegsa01', name: 'Aldegheri, Sam', team: 'LAA', ip: 13.2 },
    { id: 'alexaja01', name: 'Alexander, Jason', team: 'TOT', ip: 77.1 },
    { id: 'alexaja01', name: 'Alexander, Jason', team: 'ATH', ip: 6 },
    { id: 'alexaja01', name: 'Alexander, Jason', team: 'HOU', ip: 71.1 },
    { id: 'alexasc02', name: 'Alexander, Scott', team: 'TOT', ip: 17.2 },
    { id: 'alexasc02', name: 'Alexander, Scott', team: 'COL', ip: 16.1 },
    { id: 'alexasc02', name: 'Alexander, Scott', team: 'SFG', ip: 1.1 },
    { id: 'alexaty01', name: 'Alexander, Tyler', team: 'TOT', ip: 97.2 },
    { id: 'alexaty01', name: 'Alexander, Tyler', team: 'MIL', ip: 36.1 },
    { id: 'alexaty01', name: 'Alexander, Tyler', team: 'CHW', ip: 61.1 },
    { id: 'allarko01', name: 'Allard, Kolby', team: 'CLE', ip: 65 },
    { id: 'allenlo02', name: 'Allen, Logan', team: 'CLE', ip: 156.2 },
    { id: 'altavda01', name: 'Altavilla, Dan', team: 'CHW', ip: 29 },
    { id: 'alvarel01', name: 'Alvarado, Elvis', team: 'ATH', ip: 42.1 },
    { id: 'alvarjo03', name: 'Alvarado, Jose', team: 'PHI', ip: 26 },
    { id: 'alvaran01', name: 'Alvarez, Andrew', team: 'WSN', ip: 23.1 },
    { id: 'amayaja01', name: 'Amaya, Jacob', team: 'CHW', ip: 1 },
    { id: 'andergr01', name: 'Anderson, Grant', team: 'MIL', ip: 69.2 },
    { id: 'anderia01', name: 'Anderson, Ian', team: 'LAA', ip: 9.1 },
    { id: 'anderni01', name: 'Anderson, Nick', team: 'COL', ip: 14.2 },
    { id: 'andersh01', name: 'Anderson, Shaun', team: 'LAA', ip: 11.1 },
    { id: 'anderty01', name: 'Anderson, Tyler', team: 'LAA', ip: 136.1 },
    { id: 'ariaslu01', name: 'Arias, Luarbert', team: 'MIA', ip: 10.1 },
    { id: 'armstsh01', name: 'Armstrong, Shawn', team: 'TEX', ip: 74 },
    { id: 'arrigsp01', name: 'Arrighetti, Spencer', team: 'HOU', ip: 35.1 },
    { id: 'ashbyaa01', name: 'Ashby, Aaron', team: 'MIL', ip: 66.2 },
    { id: 'ashcrbr01', name: 'Ashcraft, Braxton', team: 'PIT', ip: 69.2 },
    { id: 'ashcrgr01', name: 'Ashcraft, Graham', team: 'CIN', ip: 65.1 },
    { id: 'assadja01', name: 'Assad, Javier', team: 'CHC', ip: 37 },
    { id: 'avilalu02', name: 'Avila, Luinder', team: 'KCR', ip: 14 },
    { id: 'bachala01', name: 'Bachar, Lake', team: 'MIA', ip: 71 },
    { id: 'bachmsa01', name: 'Bachman, Sam', team: 'LAA', ip: 20.1 },
    { id: 'backhky01', name: 'Backhus, Kyle', team: 'ARI', ip: 25.1 },
    { id: 'bakerbr01', name: 'Baker, Bryan', team: 'TOT', ip: 68.2 },
    { id: 'bakerbr01', name: 'Baker, Bryan', team: 'BAL', ip: 38.1 },
    { id: 'bakerbr01', name: 'Baker, Bryan', team: 'TBR', ip: 30.1 },
    { id: 'bandaan01', name: 'Banda, Anthony', team: 'LAD', ip: 65 },
    { id: 'banksta01', name: 'Banks, Tanner', team: 'PHI', ip: 67.1 },
    { id: 'barcohu01', name: 'Barco, Hunter', team: 'PIT', ip: 3 },
    { id: 'barlosc01', name: 'Barlow, Scott', team: 'CIN', ip: 68.1 },
    { id: 'barneja01', name: 'Barnes, Jacob', team: 'TOR', ip: 8 },
    { id: 'barnema02', name: 'Barnett, Mason', team: 'ATH', ip: 22.1 },
    { id: 'barnhtu01', name: 'Barnhart, Tucker', team: 'TEX', ip: 2 },
    { id: 'bassich01', name: 'Bassitt, Chris', team: 'TOR', ip: 170.1 },
    { id: 'bassobr01', name: 'Basso, Brady', team: 'ATH', ip: 11.2 },
    { id: 'bauerja01', name: 'Bauers, Jake', team: 'MIL', ip: 5 },
    { id: 'bautife01', name: 'Bautista, Felix', team: 'BAL', ip: 34.2 },
    { id: 'bazsh01', name: 'Baz, Shane', team: 'TBR', ip: 166.1 },
    { id: 'bazared01', name: 'Bazardo, Eduard', team: 'SEA', ip: 78.2 },
    { id: 'becktr01', name: 'Beck, Tristan', team: 'SFG', ip: 56.2 },
    { id: 'bednada01', name: 'Bednar, David', team: 'TOT', ip: 62.2 },
    { id: 'bednada01', name: 'Bednar, David', team: 'PIT', ip: 38 },
    { id: 'bednada01', name: 'Bednar, David', team: 'NYY', ip: 24.2 },
    { id: 'beeksja02', name: 'Beeks, Jalen', team: 'ARI', ip: 57.1 },
    { id: 'beetecl01', name: 'Beeter, Clayton', team: 'TOT', ip: 25.1 },
    { id: 'beetecl01', name: 'Beeter, Clayton', team: 'NYY', ip: 3.2 },
    { id: 'beetecl01', name: 'Beeter, Clayton', team: 'WSN', ip: 21.2 },
    { id: 'bellobr01', name: 'Bello, Brayan', team: 'BOS', ip: 166.2 },
    { id: 'bellova01', name: 'Bellozo, Valente', team: 'MIA', ip: 81.1 },
    { id: 'bendean01', name: 'Bender, Anthony', team: 'MIA', ip: 50 },
    { id: 'bergery01', name: 'Bergert, Ryan', team: 'TOT', ip: 76.1 },
    { id: 'bergery01', name: 'Bergert, Ryan', team: 'SDP', ip: 35.2 },
    { id: 'bergery01', name: 'Bergert, Ryan', team: 'KCR', ip: 40.2 },
    { id: 'bernabr01', name: 'Bernardino, Brennan', team: 'BOS', ip: 51.2 },
    { id: 'berrijo01', name: 'Berrios, Jose', team: 'TOR', ip: 166 },
    { id: 'bertijo01', name: 'Berti, Jon', team: 'CHC', ip: 3.2 },
    { id: 'bibeeta01', name: 'Bibee, Tanner', team: 'CLE', ip: 182.1 },
    { id: 'bidoos01', name: 'Bido, Osvaldo', team: 'ATH', ip: 79.2 },
    { id: 'biebesh01', name: 'Bieber, Shane', team: 'TOR', ip: 40.1 },
    { id: 'biggehu01', name: 'Bigge, Hunter', team: 'TBR', ip: 15 },
    { id: 'birdja01', name: 'Bird, Jake', team: 'TOT', ip: 55.1 },
    { id: 'birdja01', name: 'Bird, Jake', team: 'COL', ip: 53.1 },
    { id: 'birdja01', name: 'Bird, Jake', team: 'NYY', ip: 2 },
    { id: 'birdsha01', name: 'Birdsong, Hayden', team: 'SFG', ip: 65.2 },
    { id: 'bivensp01', name: 'Bivens, Spencer', team: 'SFG', ip: 81 },
    { id: 'blackma01', name: 'Black, Mason', team: 'SFG', ip: 4 },
    { id: 'blackpa01', name: 'Blackburn, Paul', team: 'TOT', ip: 39 },
    { id: 'blackpa01', name: 'Blackburn, Paul', team: 'NYM', ip: 23.2 },
    { id: 'blackpa01', name: 'Blackburn, Paul', team: 'NYY', ip: 15.1 },
    { id: 'blalobr01', name: 'Blalock, Bradley', team: 'COL', ip: 58.2 },
    { id: 'blancro01', name: 'Blanco, Ronel', team: 'HOU', ip: 48.1 },
    { id: 'blewesc01', name: 'Blewett, Scott', team: 'TOT', ip: 44.1 },
    { id: 'blewesc01', name: 'Blewett, Scott', team: 'TOT', ip: 28 },
    { id: 'blewesc01', name: 'Blewett, Scott', team: 'MIN', ip: 4.2 },
    { id: 'blewesc01', name: 'Blewett, Scott', team: 'BAL', ip: 23.1 },
    { id: 'blewesc01', name: 'Blewett, Scott', team: 'ATL', ip: 16.1 },
    { id: 'blubaaj01', name: 'Blubaugh, AJ', team: 'HOU', ip: 32 },
    { id: 'boltoco01', name: 'Bolton, Cody', team: 'CLE', ip: 2 },
    { id: 'booseca01', name: 'Booser, Cam', team: 'CHW', ip: 31 },
    { id: 'borucry01', name: 'Borucki, Ryan', team: 'TOT', ip: 35 },
    { id: 'borucry01', name: 'Borucki, Ryan', team: 'PIT', ip: 30.2 },
    { id: 'borucry01', name: 'Borucki, Ryan', team: 'TOR', ip: 4.1 },
    { id: 'boushca01', name: 'Boushley, Caleb', team: 'TEX', ip: 43.1 },
    { id: 'bowdebe01', name: 'Bowden, Ben', team: 'ATH', ip: 10.2 },
    { id: 'bowlajo01', name: 'Bowlan, Jonathan', team: 'KCR', ip: 44.1 },
    { id: 'bowmama01', name: 'Bowman, Matt', team: 'BAL', ip: 24.2 },
    { id: 'boydma01', name: 'Boyd, Matthew', team: 'CHC', ip: 179.2 },
    { id: 'boylejo01', name: 'Boyle, Joe', team: 'TBR', ip: 52 },
    { id: 'bradiky01', name: 'Bradish, Kyle', team: 'BAL', ip: 32 },
    { id: 'bradlta01', name: 'Bradley, Taj', team: 'TOT', ip: 142.2 },
    { id: 'bradlta01', name: 'Bradley, Taj', team: 'TBR', ip: 111.1 },
    { id: 'bradlta01', name: 'Bradley, Taj', team: 'MIN', ip: 31.1 },
    { id: 'brashma01', name: 'Brash, Matt', team: 'SEA', ip: 47.1 },
    { id: 'brasiry01', name: 'Brasier, Ryan', team: 'CHC', ip: 26 },
    { id: 'brazohu01', name: 'Brazoban, Huascar', team: 'NYM', ip: 63 },
    { id: 'brebbjo01', name: 'Brebbia, John', team: 'TOT', ip: 23.1 },
    { id: 'brebbjo01', name: 'Brebbia, John', team: 'DET', ip: 18.2 },
    { id: 'brebbjo01', name: 'Brebbia, John', team: 'ATL', ip: 4.2 },
    { id: 'bridejo01', name: 'Bride, Jonah', team: 'MIN', ip: 6 },
    { id: 'briesbe01', name: 'Brieske, Beau', team: 'DET', ip: 22 },
    { id: 'brighje01', name: 'Brigham, Jeff', team: 'ARI', ip: 3.1 },
    { id: 'brogdco01', name: 'Brogdon, Connor', team: 'LAA', ip: 47 },
    { id: 'brownbe02', name: 'Brown, Ben', team: 'CHC', ip: 106.1 },
    { id: 'brownhu01', name: 'Brown, Hunter', team: 'HOU', ip: 185.1 },
    { id: 'brownmc01', name: 'Brown, McCade', team: 'COL', ip: 25.2 },
    { id: 'brubajt01', name: 'Brubaker, JT', team: 'TOT', ip: 28.2 },
    { id: 'brubajt01', name: 'Brubaker, JT', team: 'NYY', ip: 16 },
    { id: 'brubajt01', name: 'Brubaker, JT', team: 'SFG', ip: 12.2 },
    { id: 'bruihju01', name: 'Bruihl, Justin', team: 'TOR', ip: 13.2 },
    { id: 'brujavi01', name: 'Brujan, Vidal', team: 'ATL', ip: 2 },
    { id: 'brzykza01', name: 'Brzykcy, Zach', team: 'WSN', ip: 23 },
    { id: 'bubickr01', name: 'Bubic, Kris', team: 'KCR', ip: 116.1 },
    { id: 'buehlwa01', name: 'Buehler, Walker', team: 'TOT', ip: 126 },
    { id: 'buehlwa01', name: 'Buehler, Walker', team: 'BOS', ip: 112.1 },
    { id: 'buehlwa01', name: 'Buehler, Walker', team: 'PHI', ip: 13.2 },
    { id: 'bummeaa01', name: 'Bummer, Aaron', team: 'ATL', ip: 54.1 },
    { id: 'burdini01', name: 'Burdi, Nick', team: 'BOS', ip: 5.1 },
    { id: 'burgoju01', name: 'Burgos, Juan', team: 'TOT', ip: 13.1 },
    { id: 'burgoju01', name: 'Burgos, Juan', team: 'SEA', ip: 6.2 },
    { id: 'burgoju01', name: 'Burgos, Juan', team: 'ARI', ip: 6.2 },
    { id: 'burkebr01', name: 'Burke, Brock', team: 'LAA', ip: 61.2 },
    { id: 'burkese01', name: 'Burke, Sean', team: 'CHW', ip: 134.1 },
    { id: 'burleal01', name: 'Burleson, Alec', team: 'STL', ip: 1 },
    { id: 'burneco01', name: 'Burnes, Corbin', team: 'ARI', ip: 64.1 },
    { id: 'burnsch01', name: 'Burns, Chase', team: 'CIN', ip: 43.1 },
    { id: 'burrry01', name: 'Burr, Ryan', team: 'TOR', ip: 2 },
    { id: 'burromi01', name: 'Burrows, Mike', team: 'PIT', ip: 96 },
    { id: 'buttojo01', name: 'Butto, Jose', team: 'TOT', ip: 67 },
    { id: 'buttojo01', name: 'Butto, Jose', team: 'NYM', ip: 47 },
    { id: 'buttojo01', name: 'Butto, Jose', team: 'SFG', ip: 20 },
    { id: 'cabaljo01', name: 'Caballero, Jose', team: 'TBR', ip: 1 },
    { id: 'cabreed02', name: 'Cabrera, Edward', team: 'MIA', ip: 137.2 },
    { id: 'cabrege01', name: 'Cabrera, Genesis', team: 'TOT', ip: 42.2 },
    { id: 'cabrege01', name: 'Cabrera, Genesis', team: 'TOT', ip: 28 },
    { id: 'cabrege01', name: 'Cabrera, Genesis', team: 'NYM', ip: 7.2 },
    { id: 'cabrege01', name: 'Cabrera, Genesis', team: 'CHC', ip: 9.1 },
    { id: 'cabrege01', name: 'Cabrera, Genesis', team: 'PIT', ip: 11 },
    { id: 'cabrege01', name: 'Cabrera, Genesis', team: 'MIN', ip: 14.2 },
    { id: 'camerno01', name: 'Cameron, Noah', team: 'KCR', ip: 138.1 },
    { id: 'campbis01', name: 'Campbell, Isaiah', team: 'BOS', ip: 7.2 },
    { id: 'cannigr01', name: 'Canning, Griffin', team: 'NYM', ip: 76.1 },
    { id: 'cannojo02', name: 'Cannon, Jonathan', team: 'CHW', ip: 103.2 },
    { id: 'canoye01', name: 'Cano, Yennier', team: 'BAL', ip: 58 },
    { id: 'cantijo01', name: 'Cantillo, Joey', team: 'CLE', ip: 95.1 },
    { id: 'capravi01', name: 'Capra, Vinny', team: 'CHW', ip: 3 },
    { id: 'carraca01', name: 'Carrasco, Carlos', team: 'TOT', ip: 45.2 },
    { id: 'carraca01', name: 'Carrasco, Carlos', team: 'NYY', ip: 32 },
    { id: 'carraca01', name: 'Carrasco, Carlos', team: 'ATL', ip: 13.2 },
    { id: 'carrial01', name: 'Carrillo, Alex', team: 'NYM', ip: 4.2 },
    { id: 'caspabe01', name: 'Casparius, Ben', team: 'LAD', ip: 77.2 },
    { id: 'castabl01', name: 'Castano, Blas', team: 'SEA', ip: 3 },
    { id: 'castijo03', name: 'Castillo, Jose', team: 'TOT', ip: 32 },
    { id: 'castijo03', name: 'Castillo, Jose', team: 'TOT', ip: 21.2 },
    { id: 'castijo03', name: 'Castillo, Jose', team: 'TOT', ip: 10.1 },
    { id: 'castijo03', name: 'Castillo, Jose', team: 'ARI', ip: 6.1 },
    { id: 'castijo03', name: 'Castillo, Jose', team: 'NYM', ip: 15.1 },
    { id: 'castijo03', name: 'Castillo, Jose', team: 'SEA', ip: 3 },
    { id: 'castijo03', name: 'Castillo, Jose', team: 'BAL', ip: 7.1 },
    { id: 'castilu02', name: 'Castillo, Luis', team: 'SEA', ip: 180.2 },
    { id: 'castilu03', name: 'Castillo, Luis', team: 'SEA', ip: 7 },
    { id: 'castrmi01', name: 'Castro, Miguel', team: 'CHW', ip: 6 },
    { id: 'castrwi01', name: 'Castro, Willi', team: 'MIN', ip: 1 },
    { id: 'cavalca01', name: 'Cavalli, Cade', team: 'WSN', ip: 48.2 },
    { id: 'ceasedy01', name: 'Cease, Dylan', team: 'SDP', ip: 168 },
    { id: 'ceccosl01', name: 'Cecconi, Slade', team: 'CLE', ip: 132 },
    { id: 'chafian01', name: 'Chafin, Andrew', team: 'TOT', ip: 33.2 },
    { id: 'chafian01', name: 'Chafin, Andrew', team: 'WSN', ip: 20 },
    { id: 'chafian01', name: 'Chafin, Andrew', team: 'LAA', ip: 13.2 },
    { id: 'chandbu01', name: 'Chandler, Bubba', team: 'PIT', ip: 31.1 },
    { id: 'chapmar01', name: 'Chapman, Aroldis', team: 'BOS', ip: 61.1 },
    { id: 'chaveje01', name: 'Chavez, Jesse', team: 'ATL', ip: 8 },
    { id: 'chivian01', name: 'Chivilli, Angel', team: 'COL', ip: 58.2 },
    { id: 'churcma01', name: 'Church, Marc', team: 'TEX', ip: 4.2 },
    { id: 'civalaa01', name: 'Civale, Aaron', team: 'TOT', ip: 102 },
    { id: 'civalaa01', name: 'Civale, Aaron', team: 'TOT', ip: 35 },
    { id: 'civalaa01', name: 'Civale, Aaron', team: 'MIL', ip: 22 },
    { id: 'civalaa01', name: 'Civale, Aaron', team: 'CHW', ip: 67 },
    { id: 'civalaa01', name: 'Civale, Aaron', team: 'CHC', ip: 13 },
    { id: 'clarkta01', name: 'Clarke, Taylor', team: 'KCR', ip: 55.1 },
    { id: 'claseem01', name: 'Clase, Emmanuel', team: 'CLE', ip: 47.1 },
    { id: 'cleavga01', name: 'Cleavinger, Garrett', team: 'TBR', ip: 61.1 },
    { id: 'clemeko01', name: 'Clemens, Kody', team: 'MIN', ip: 1 },
    { id: 'clevimi01', name: 'Clevinger, Mike', team: 'CHW', ip: 5.2 },
    { id: 'contrlu01', name: 'Contreras, Luis', team: 'HOU', ip: 12 },
    { id: 'contrro01', name: 'Contreras, Roansy', team: 'TOT', ip: 12.2 },
    { id: 'contrro01', name: 'Contreras, Roansy', team: 'BAL', ip: 4.1 },
    { id: 'contrro01', name: 'Contreras, Roansy', team: 'COL', ip: 8.1 },
    { id: 'corbipa01', name: 'Corbin, Patrick', team: 'TEX', ip: 155.1 },
    { id: 'cornijo01', name: 'Corniell, Jose', team: 'TEX', ip: 1.2 },
    { id: 'cortene01', name: 'Cortes, Nestor', team: 'TOT', ip: 34.1 },
    { id: 'cortene01', name: 'Cortes, Nestor', team: 'MIL', ip: 8 },
    { id: 'cortene01', name: 'Cortes, Nestor', team: 'SDP', ip: 26.1 },
    { id: 'cosgrto01', name: 'Cosgrove, Tom', team: 'CHC', ip: 4 },
    { id: 'couloda01', name: 'Coulombe, Danny', team: 'TOT', ip: 43 },
    { id: 'couloda01', name: 'Coulombe, Danny', team: 'MIN', ip: 31 },
    { id: 'couloda01', name: 'Coulombe, Danny', team: 'TEX', ip: 12 },
    { id: 'coxau01', name: 'Cox, Austin', team: 'ATL', ip: 21.1 },
    { id: 'crismna01', name: 'Crismatt, Nabil', team: 'ARI', ip: 34 },
    { id: 'criswco01', name: 'Criswell, Cooper', team: 'BOS', ip: 17.2 },
    { id: 'crochga01', name: 'Crochet, Garrett', team: 'BOS', ip: 205.1 },
    { id: 'cruzfe01', name: 'Cruz, Fernando', team: 'NYY', ip: 48 },
    { id: 'cruzom01', name: 'Cruz, Omar', team: 'SDP', ip: 3.2 },
    { id: 'cruzst01', name: 'Cruz, Steven', team: 'KCR', ip: 45.2 },
    { id: 'curryxz01', name: 'Curry, Xzavion', team: 'MIA', ip: 3 },
    { id: 'curtijo02', name: 'Curtiss, John', team: 'ARI', ip: 36.2 },
    { id: 'curvelu01', name: 'Curvelo, Luis', team: 'TEX', ip: 19 },
    { id: 'danaca01', name: 'Dana, Caden', team: 'LAA', ip: 32.1 },
    { id: 'danieda01', name: 'Daniel, Davis', team: 'ATL', ip: 10 },
    { id: 'darnedu01', name: 'Darnell, Dugan', team: 'COL', ip: 11.2 },
    { id: 'darremi01', name: 'Darrell-Hicks, Michael', team: 'TOT', ip: 9.2 },
    { id: 'darremi01', name: 'Darrell-Hicks, Michael', team: 'LAA', ip: 7.2 },
    { id: 'darremi01', name: 'Darrell-Hicks, Michael', team: 'PIT', ip: 2 },
    { id: 'darviyu01', name: 'Darvish, Yu', team: 'SDP', ip: 72 },
    { id: 'davidlo01', name: 'Davidson, Logan', team: 'LAA', ip: 1 },
    { id: 'davisno01', name: 'Davis, Noah', team: 'TOT', ip: 11 },
    { id: 'davisno01', name: 'Davis, Noah', team: 'LAD', ip: 6 },
    { id: 'davisno01', name: 'Davis, Noah', team: 'MIN', ip: 5 },
    { id: 'degroja01', name: 'deGrom, Jacob', team: 'TEX', ip: 172.2 },
    { id: 'desclan01', name: 'DeSclafani, Anthony', team: 'ARI', ip: 38.2 },
    { id: 'detmere01', name: 'Detmers, Reid', team: 'LAA', ip: 63.2 },
    { id: 'devench02', name: 'Devenski, Chris', team: 'NYM', ip: 16.2 },
    { id: 'diazal03', name: 'Diaz, Alexis', team: 'TOT', ip: 17.2 },
    { id: 'diazal03', name: 'Diaz, Alexis', team: 'CIN', ip: 6 },
    { id: 'diazal03', name: 'Diaz, Alexis', team: 'LAD', ip: 9 },
    { id: 'diazal03', name: 'Diaz, Alexis', team: 'ATL', ip: 2.2 },
    { id: 'diazed04', name: 'Diaz, Edwin', team: 'NYM', ip: 66.1 },
    { id: 'diazjh01', name: 'Diaz, Jhonathan', team: 'SEA', ip: 1.1 },
    { id: 'diazyi01', name: 'Diaz, Yilber', team: 'ARI', ip: 3 },
    { id: 'dobbihu01', name: 'Dobbins, Hunter', team: 'BOS', ip: 61 },
    { id: 'dobnara01', name: 'Dobnak, Randy', team: 'MIN', ip: 5.1 },
    { id: 'dodddy01', name: 'Dodd, Dylan', team: 'ATL', ip: 35 },
    { id: 'dollach01', name: 'Dollander, Chase', team: 'COL', ip: 98 },
    { id: 'dominse01', name: 'Dominguez, Seranthony', team: 'TOT', ip: 62.2 },
    { id: 'dominse01', name: 'Dominguez, Seranthony', team: 'BAL', ip: 41.2 },
    { id: 'dominse01', name: 'Dominguez, Seranthony', team: 'TOR', ip: 21 },
    { id: 'dovalca01', name: 'Doval, Camilo', team: 'TOT', ip: 65.1 },
    { id: 'dovalca01', name: 'Doval, Camilo', team: 'SFG', ip: 46.2 },
    { id: 'dovalca01', name: 'Doval, Camilo', team: 'NYY', ip: 18.2 },
    { id: 'dreyeja01', name: 'Dreyer, Jack', team: 'LAD', ip: 76.1 },
    { id: 'dubinsh01', name: 'Dubin, Shawn', team: 'TOT', ip: 33.2 },
    { id: 'dubinsh01', name: 'Dubin, Shawn', team: 'HOU', ip: 25.2 },
    { id: 'dubinsh01', name: 'Dubin, Shawn', team: 'BAL', ip: 8 },
    { id: 'dunnida01', name: 'Dunning, Dane', team: 'TOT', ip: 20.2 },
    { id: 'dunnida01', name: 'Dunning, Dane', team: 'TEX', ip: 10.2 },
    { id: 'dunnida01', name: 'Dunning, Dane', team: 'ATL', ip: 10 },
    { id: 'duranca01', name: 'Duran, Carlos', team: 'ATH', ip: 0.1 },
    { id: 'duranez01', name: 'Duran, Ezequiel', team: 'TEX', ip: 3.1 },
    { id: 'duranjh01', name: 'Duran, Jhoan', team: 'TOT', ip: 70 },
    { id: 'duranjh01', name: 'Duran, Jhoan', team: 'MIN', ip: 49.1 },
    { id: 'duranjh01', name: 'Duran, Jhoan', team: 'PHI', ip: 20.2 },
    { id: 'earlyco01', name: 'Early, Connelly', team: 'BOS', ip: 19.1 },
    { id: 'eatonna01', name: 'Eaton, Nate', team: 'BOS', ip: 1 },
    { id: 'ederja01', name: 'Eder, Jake', team: 'LAA', ip: 18.1 },
    { id: 'effrosc01', name: 'Effross, Scott', team: 'NYY', ip: 10.2 },
    { id: 'eflinza01', name: 'Eflin, Zach', team: 'BAL', ip: 71.1 },
    { id: 'eiserbr01', name: 'Eisert, Brandon', team: 'CHW', ip: 69.2 },
    { id: 'elderbr01', name: 'Elder, Bryce', team: 'ATL', ip: 156.1 },
    { id: 'ellarfr01', name: 'Ellard, Fraser', team: 'CHW', ip: 17 },
    { id: 'englema01', name: 'Englert, Mason', team: 'TBR', ip: 44.2 },
    { id: 'ennsdi01', name: 'Enns, Dietrich', team: 'TOT', ip: 46.1 },
    { id: 'ennsdi01', name: 'Enns, Dietrich', team: 'DET', ip: 17.2 },
    { id: 'ennsdi01', name: 'Enns, Dietrich', team: 'BAL', ip: 28.2 },
    { id: 'enrigni01', name: 'Enright, Nic', team: 'CLE', ip: 31 },
    { id: 'eovalna01', name: 'Eovaldi, Nathan', team: 'TEX', ip: 130 },
    { id: 'erceglu01', name: 'Erceg, Lucas', team: 'KCR', ip: 61.1 },
    { id: 'espadjo01', name: 'Espada, Jose', team: 'BAL', ip: 3 },
    { id: 'estesjo01', name: 'Estes, Joey', team: 'ATH', ip: 11 },
    { id: 'estevca01', name: 'Estevez, Carlos', team: 'KCR', ip: 66 },
    { id: 'estraje01', name: 'Estrada, Jeremiah', team: 'SDP', ip: 73 },
    { id: 'estrala01', name: 'Estrada, Lazaro', team: 'TOR', ip: 7.1 },
    { id: 'evanslo01', name: 'Evans, Logan', team: 'SEA', ip: 81.1 },
    { id: 'fairbpe01', name: 'Fairbanks, Pete', team: 'TBR', ip: 60.1 },
    { id: 'falteba01', name: 'Falter, Bailey', team: 'TOT', ip: 125.1 },
    { id: 'falteba01', name: 'Falter, Bailey', team: 'PIT', ip: 113.1 },
    { id: 'falteba01', name: 'Falter, Bailey', team: 'KCR', ip: 12 },
    { id: 'farmeky01', name: 'Farmer, Kyle', team: 'COL', ip: 1 },
    { id: 'farrimi01', name: 'Farris, Mitch', team: 'LAA', ip: 24.1 },
    { id: 'fauchca01', name: 'Faucher, Calvin', team: 'MIA', ip: 60.1 },
    { id: 'feddeer01', name: 'Fedde, Erick', team: 'TOT', ip: 141 },
    { id: 'feddeer01', name: 'Fedde, Erick', team: 'STL', ip: 101.2 },
    { id: 'feddeer01', name: 'Fedde, Erick', team: 'ATL', ip: 23.1 },
    { id: 'feddeer01', name: 'Fedde, Erick', team: 'MIL', ip: 16 },
    { id: 'feltnry01', name: 'Feltner, Ryan', team: 'COL', ip: 30.1 },
    { id: 'ferguca01', name: 'Ferguson, Caleb', team: 'TOT', ip: 65.1 },
    { id: 'ferguca01', name: 'Ferguson, Caleb', team: 'PIT', ip: 43.1 },
    { id: 'ferguca01', name: 'Ferguson, Caleb', team: 'SEA', ip: 22 },
    { id: 'ferguty01', name: 'Ferguson, Tyler', team: 'ATH', ip: 58 },
    { id: 'fermijo02', name: 'Fermin, Jose', team: 'LAA', ip: 34.1 },
    { id: 'fernaju02', name: 'Fernandez, Julian', team: 'TOT', ip: 5 },
    { id: 'fernaju02', name: 'Fernandez, Julian', team: 'LAD', ip: 2 },
    { id: 'fernaju02', name: 'Fernandez, Julian', team: 'WSN', ip: 3 },
    { id: 'fernary01', name: 'Fernandez, Ryan', team: 'STL', ip: 30.1 },
    { id: 'festada01', name: 'Festa, David', team: 'MIN', ip: 53.1 },
    { id: 'festama01', name: 'Festa, Matt', team: 'CLE', ip: 54.2 },
    { id: 'feyerjo01', name: 'Feyereisen, JP', team: 'TOT', ip: 4 },
    { id: 'feyerjo01', name: 'Feyereisen, JP', team: 'ARI', ip: 2 },
    { id: 'feyerjo01', name: 'Feyereisen, JP', team: 'LAD', ip: 2 },
    { id: 'finneky01', name: 'Finnegan, Kyle', team: 'TOT', ip: 57 },
    { id: 'finneky01', name: 'Finnegan, Kyle', team: 'WSN', ip: 39 },
    { id: 'finneky01', name: 'Finnegan, Kyle', team: 'DET', ip: 18 },
    { id: 'fishebr02', name: 'Fisher, Braydon', team: 'TOR', ip: 50 },
    { id: 'fittsri01', name: 'Fitts, Richard', team: 'BOS', ip: 45 },
    { id: 'fitzgry01', name: 'Fitzgerald, Ryan', team: 'MIN', ip: 2 },
    { id: 'flaheja01', name: 'Flaherty, Jack', team: 'DET', ip: 161 },
    { id: 'flexech01', name: 'Flexen, Chris', team: 'CHC', ip: 43.2 },
    { id: 'fluhama01', name: 'Fluharty, Mason', team: 'TOR', ip: 52.2 },
    { id: 'francjp01', name: 'France, JP', team: 'HOU', ip: 4 },
    { id: 'francbo01', name: 'Francis, Bowden', team: 'TOR', ip: 64 },
    { id: 'freelky01', name: 'Freeland, Kyle', team: 'COL', ip: 162.2 },
    { id: 'freemca01', name: 'Freeman, Caleb', team: 'CHW', ip: 3.1 },
    { id: 'friedma01', name: 'Fried, Max', team: 'NYY', ip: 195.1 },
    { id: 'fuentdi01', name: 'Fuentes, Didier', team: 'ATL', ip: 13 },
    { id: 'fulmeca01', name: 'Fulmer, Carson', team: 'LAA', ip: 29.1 },
    { id: 'fulmemi01', name: 'Fulmer, Michael', team: 'TOT', ip: 5.2 },
    { id: 'fulmemi01', name: 'Fulmer, Michael', team: 'BOS', ip: 2.2 },
    { id: 'fulmemi01', name: 'Fulmer, Michael', team: 'CHC', ip: 3 },
    { id: 'fundeko01', name: 'Funderburk, Kody', team: 'MIN', ip: 41 },
    { id: 'gaddihu01', name: 'Gaddis, Hunter', team: 'CLE', ip: 66.2 },
    { id: 'gagema01', name: 'Gage, Matt', team: 'TOT', ip: 31 },
    { id: 'gagema01', name: 'Gage, Matt', team: 'DET', ip: 5.2 },
    { id: 'gagema01', name: 'Gage, Matt', team: 'SFG', ip: 25.1 },
    { id: 'galleza01', name: 'Gallen, Zac', team: 'ARI', ip: 192 },
    { id: 'garabge01', name: 'Garabito, Gerson', team: 'TEX', ip: 8 },
    { id: 'garcibr02', name: 'Garcia, Brandyn', team: 'TOT', ip: 14.1 },
    { id: 'garcibr02', name: 'Garcia, Brandyn', team: 'SEA', ip: 2 },
    { id: 'garcibr02', name: 'Garcia, Brandyn', team: 'ARI', ip: 12.1 },
    { id: 'garcilu03', name: 'Garcia, Luis', team: 'TOT', ip: 55.1 },
    { id: 'garcilu03', name: 'Garcia, Luis', team: 'TOT', ip: 37.1 },
    { id: 'garcilu03', name: 'Garcia, Luis', team: 'LAD', ip: 27.1 },
    { id: 'garcilu03', name: 'Garcia, Luis', team: 'WSN', ip: 10 },
    { id: 'garcilu03', name: 'Garcia, Luis', team: 'LAA', ip: 18 },
    { id: 'garcilu05', name: 'Garcia, Luis', team: 'HOU', ip: 7.2 },
    { id: 'garciri01', name: 'Garcia, Rico', team: 'TOT', ip: 34.1 },
    { id: 'garciri01', name: 'Garcia, Rico', team: 'TOT', ip: 21.2 },
    { id: 'garciri01', name: 'Garcia, Rico', team: 'NYM', ip: 12.2 },
    { id: 'garciri01', name: 'Garcia, Rico', team: 'NYY', ip: 2.2 },
    { id: 'garciri01', name: 'Garcia, Rico', team: 'BAL', ip: 19 },
    { id: 'garciro04', name: 'Garcia, Robert', team: 'TEX', ip: 64 },
    { id: 'garciyi01', name: 'Garcia, Yimi', team: 'TOR', ip: 21 },
    { id: 'garrere01', name: 'Garrett, Reed', team: 'NYM', ip: 55.1 },
    { id: 'garzaju01', name: 'Garza, Justin', team: 'NYM', ip: 6.2 },
    { id: 'gassero01', name: 'Gasser, Robert', team: 'MIL', ip: 5.2 },
    { id: 'gausmke01', name: 'Gausman, Kevin', team: 'TOR', ip: 193 },
    { id: 'gerbejo01', name: 'Gerber, Joey', team: 'TBR', ip: 4.1 },
    { id: 'gervapa01', name: 'Gervase, Paul', team: 'TOT', ip: 8.1 },
    { id: 'gervapa01', name: 'Gervase, Paul', team: 'TBR', ip: 6.1 },
    { id: 'gervapa01', name: 'Gervase, Paul', team: 'LAD', ip: 2 },
    { id: 'gibauia01', name: 'Gibaut, Ian', team: 'CIN', ip: 25.1 },
    { id: 'gibsoca01', name: 'Gibson, Cade', team: 'MIA', ip: 54.2 },
    { id: 'gibsoky01', name: 'Gibson, Kyle', team: 'BAL', ip: 12.1 },
    { id: 'gillu01', name: 'Gil, Luis', team: 'NYY', ip: 57 },
    { id: 'gilbelo01', name: 'Gilbert, Logan', team: 'SEA', ip: 131 },
    { id: 'gilbety01', name: 'Gilbert, Tyler', team: 'CHW', ip: 51 },
    { id: 'gilbrlu01', name: 'Gilbreath, Lucas', team: 'COL', ip: 1 },
    { id: 'gillalo01', name: 'Gillaspie, Logan', team: 'SDP', ip: 7 },
    { id: 'gillico01', name: 'Gillispie, Connor', team: 'MIA', ip: 26 },
    { id: 'ginkeke01', name: 'Ginkel, Kevin', team: 'ARI', ip: 25.2 },
    { id: 'ginnjt01', name: 'Ginn, JT', team: 'ATH', ip: 90.1 },
    { id: 'giolilu01', name: 'Giolito, Lucas', team: 'BOS', ip: 145 },
    { id: 'gipsosa01', name: 'Gipson-Long, Sawyer', team: 'DET', ip: 31.1 },
    { id: 'glasnty01', name: 'Glasnow, Tyler', team: 'LAD', ip: 90.1 },
    { id: 'gombeau01', name: 'Gomber, Austin', team: 'COL', ip: 57.2 },
    { id: 'gomezyo01', name: 'Gomez, Yoendrys', team: 'TOT', ip: 62.2 },
    { id: 'gomezyo01', name: 'Gomez, Yoendrys', team: 'TOT', ip: 58.1 },
    { id: 'gomezyo01', name: 'Gomez, Yoendrys', team: 'NYY', ip: 10 },
    { id: 'gomezyo01', name: 'Gomez, Yoendrys', team: 'LAD', ip: 4.1 },
    { id: 'gomezyo01', name: 'Gomez, Yoendrys', team: 'CHW', ip: 48.1 },
    { id: 'gonsoto01', name: 'Gonsolin, Tony', team: 'LAD', ip: 36 },
    { id: 'gonzawi02', name: 'Gonzalez, Wikelman', team: 'CHW', ip: 20.1 },
    { id: 'gordoco01', name: 'Gordon, Colton', team: 'HOU', ip: 86 },
    { id: 'gordota01', name: 'Gordon, Tanner', team: 'COL', ip: 75.1 },
    { id: 'gorema01', name: 'Gore, MacKenzie', team: 'WSN', ip: 159.2 },
    { id: 'gracego01', name: 'Graceffo, Gordon', team: 'STL', ip: 43 },
    { id: 'granian01', name: 'Granillo, Andre', team: 'STL', ip: 21 },
    { id: 'graveke01', name: 'Graveman, Kendall', team: 'ARI', ip: 17.2 },
    { id: 'grayjo02', name: 'Gray, Jon', team: 'TEX', ip: 14 },
    { id: 'grayso01', name: 'Gray, Sonny', team: 'STL', ip: 180.2 },
    { id: 'greench03', name: 'Green, Chad', team: 'TOR', ip: 43.2 },
    { id: 'greenhu01', name: 'Greene, Hunter', team: 'CIN', ip: 107.2 },
    { id: 'guentse01', name: 'Guenther, Sean', team: 'DET', ip: 10.1 },
    { id: 'guerrlu01', name: 'Guerrero, Luis', team: 'BOS', ip: 17.1 },
    { id: 'gustory01', name: 'Gusto, Ryan', team: 'TOT', ip: 101.2 },
    { id: 'gustory01', name: 'Gusto, Ryan', team: 'HOU', ip: 86 },
    { id: 'gustory01', name: 'Gusto, Ryan', team: 'MIA', ip: 15.2 },
    { id: 'haderjo01', name: 'Hader, Josh', team: 'HOU', ip: 52.2 },
    { id: 'hagenju01', name: 'Hagenman, Justin', team: 'NYM', ip: 23.2 },
    { id: 'hahnje01', name: 'Hahn, Jesse', team: 'SEA', ip: 5 },
    { id: 'halldl01', name: 'Hall, DL', team: 'MIL', ip: 38.2 },
    { id: 'halvose01', name: 'Halvorsen, Seth', team: 'COL', ip: 39.2 },
    { id: 'hameldo01', name: 'Hamel, Dom', team: 'NYM', ip: 1 },
    { id: 'hamilia01', name: 'Hamilton, Ian', team: 'NYY', ip: 40 },
    { id: 'hampsga01', name: 'Hampson, Garrett', team: 'STL', ip: 1 },
    { id: 'hancoem01', name: 'Hancock, Emerson', team: 'SEA', ip: 90 },
    { id: 'hanifbr01', name: 'Hanifee, Brenan', team: 'DET', ip: 60 },
    { id: 'harrito03', name: 'Harrington, Tom', team: 'PIT', ip: 8.2 },
    { id: 'harriha01', name: 'Harris, Hayden', team: 'ATL', ip: 2.2 },
    { id: 'harriho03', name: 'Harris, Hogan', team: 'ATH', ip: 64.2 },
    { id: 'harriky01', name: 'Harrison, Kyle', team: 'TOT', ip: 35.2 },
    { id: 'harriky01', name: 'Harrison, Kyle', team: 'SFG', ip: 23.2 },
    { id: 'harriky01', name: 'Harrison, Kyle', team: 'BOS', ip: 12 },
    { id: 'hartky01', name: 'Hart, Kyle', team: 'SDP', ip: 43 },
    { id: 'hartlge01', name: 'Hartlieb, Geoff', team: 'TOT', ip: 3.1 },
    { id: 'hartlge01', name: 'Hartlieb, Geoff', team: 'NYY', ip: 1.1 },
    { id: 'hartlge01', name: 'Hartlieb, Geoff', team: 'DET', ip: 2 },
    { id: 'harvehu01', name: 'Harvey, Hunter', team: 'KCR', ip: 10.2 },
    { id: 'hatchto01', name: 'Hatch, Thomas', team: 'TOT', ip: 34 },
    { id: 'hatchto01', name: 'Hatch, Thomas', team: 'KCR', ip: 1 },
    { id: 'hatchto01', name: 'Hatch, Thomas', team: 'MIN', ip: 33 },
    { id: 'headrbr01', name: 'Headrick, Brent', team: 'NYY', ip: 23 },
    { id: 'heanean01', name: 'Heaney, Andrew', team: 'TOT', ip: 122.1 },
    { id: 'heanean01', name: 'Heaney, Andrew', team: 'PIT', ip: 120.1 },
    { id: 'heanean01', name: 'Heaney, Andrew', team: 'LAD', ip: 2 },
    { id: 'hedgeau01', name: 'Hedges, Austin', team: 'CLE', ip: 3 },
    { id: 'heinety01', name: 'Heineman, Tyler', team: 'TOR', ip: 3.1 },
    { id: 'helslry01', name: 'Helsley, Ryan', team: 'TOT', ip: 56 },
    { id: 'helslry01', name: 'Helsley, Ryan', team: 'STL', ip: 36 },
    { id: 'helslry01', name: 'Helsley, Ryan', team: 'NYM', ip: 20 },
    { id: 'hendelo01', name: 'Henderson, Logan', team: 'MIL', ip: 25.1 },
    { id: 'hendrky01', name: 'Hendricks, Kyle', team: 'LAA', ip: 164.2 },
    { id: 'hendrli01', name: 'Hendriks, Liam', team: 'BOS', ip: 13.2 },
    { id: 'henried01', name: 'Henriquez, Edgardo', team: 'LAD', ip: 19 },
    { id: 'henriro01', name: 'Henriquez, Ronny', team: 'MIA', ip: 73 },
    { id: 'henryco01', name: 'Henry, Cole', team: 'WSN', ip: 52.2 },
    { id: 'henryto01', name: 'Henry, Tommy', team: 'ARI', ip: 6.2 },
    { id: 'hergeji01', name: 'Herget, Jimmy', team: 'COL', ip: 83.1 },
    { id: 'hergeke01', name: 'Herget, Kevin', team: 'TOT', ip: 13 },
    { id: 'hergeke01', name: 'Herget, Kevin', team: 'NYM', ip: 12 },
    { id: 'hergeke01', name: 'Herget, Kevin', team: 'ATL', ip: 1 },
    { id: 'hernaca04', name: 'Hernandez, Carlos', team: 'TOT', ip: 43.1 },
    { id: 'hernaca04', name: 'Hernandez, Carlos', team: 'TOT', ip: 17.2 },
    { id: 'hernaca04', name: 'Hernandez, Carlos', team: 'PHI', ip: 25.2 },
    { id: 'hernaca04', name: 'Hernandez, Carlos', team: 'DET', ip: 10.2 },
    { id: 'hernaca04', name: 'Hernandez, Carlos', team: 'CLE', ip: 7 },
    { id: 'hernada03', name: 'Hernandez, Daysbel', team: 'ATL', ip: 37 },
    { id: 'hernaen02', name: 'Hernandez, Kike', team: 'LAD', ip: 5.1 },
    { id: 'hernani01', name: 'Hernandez, Nick', team: 'HOU', ip: 10.2 },
    { id: 'herrejo04', name: 'Herrera, Jose', team: 'ARI', ip: 2 },
    { id: 'herriti01', name: 'Herrin, Tim', team: 'CLE', ip: 42.2 },
    { id: 'heuerco01', name: 'Heuer, Codi', team: 'TOT', ip: 4.2 },
    { id: 'heuerco01', name: 'Heuer, Codi', team: 'TEX', ip: 1.1 },
    { id: 'heuerco01', name: 'Heuer, Codi', team: 'DET', ip: 3.1 },
    { id: 'hicksjo03', name: 'Hicks, Jordan', team: 'TOT', ip: 67.1 },
    { id: 'hicksjo03', name: 'Hicks, Jordan', team: 'SFG', ip: 48.2 },
    { id: 'hicksjo03', name: 'Hicks, Jordan', team: 'BOS', ip: 18.2 },
    { id: 'hillja01', name: 'Hill, Jaden', team: 'COL', ip: 29.1 },
    { id: 'hillri01', name: 'Hill, Rich', team: 'KCR', ip: 9 },
    { id: 'hillti01', name: 'Hill, Tim', team: 'NYY', ip: 67 },
    { id: 'hiralya01', name: 'Hiraldo, Yaramil', team: 'BAL', ip: 19.2 },
    { id: 'hjellse01', name: 'Hjelle, Sean', team: 'SFG', ip: 15 },
    { id: 'hodgepo01', name: 'Hodge, Porter', team: 'CHC', ip: 33 },
    { id: 'hoeinbr01', name: 'Hoeing, Bryan', team: 'SDP', ip: 8 },
    { id: 'hoffmje02', name: 'Hoffman, Jeff', team: 'TOR', ip: 68 },
    { id: 'hoffmno01', name: 'Hoffman, Nolan', team: 'PHI', ip: 1 },
    { id: 'hoffman01', name: 'Hoffmann, Andrew', team: 'TOT', ip: 12 },
    { id: 'hoffman01', name: 'Hoffmann, Andrew', team: 'KCR', ip: 4.2 },
    { id: 'hoffman01', name: 'Hoffmann, Andrew', team: 'ARI', ip: 7.1 },
    { id: 'hoglugu01', name: 'Hoglund, Gunnar', team: 'ATH', ip: 32.1 },
    { id: 'holdeco01', name: 'Holderman, Colin', team: 'PIT', ip: 25.2 },
    { id: 'holloga01', name: 'Hollowell, Gavin', team: 'CHC', ip: 9.1 },
    { id: 'holmagr01', name: 'Holman, Grant', team: 'ATH', ip: 23 },
    { id: 'holmecl01', name: 'Holmes, Clay', team: 'NYM', ip: 165.2 },
    { id: 'holmegr01', name: 'Holmes, Grant', team: 'ATL', ip: 115 },
    { id: 'holtoty01', name: 'Holton, Tyler', team: 'DET', ip: 78.2 },
    { id: 'hornba01', name: 'Horn, Bailey', team: 'DET', ip: 11.1 },
    { id: 'hortoca01', name: 'Horton, Cade', team: 'CHC', ip: 118 },
    { id: 'houckta01', name: 'Houck, Tanner', team: 'BOS', ip: 43.2 },
    { id: 'housead01', name: 'Houser, Adrian', team: 'TOT', ip: 125 },
    { id: 'housead01', name: 'Houser, Adrian', team: 'CHW', ip: 68.2 },
    { id: 'housead01', name: 'Houser, Adrian', team: 'TBR', ip: 56.1 },
    { id: 'hudsobr01', name: 'Hudson, Bryan', team: 'TOT', ip: 15 },
    { id: 'hudsobr01', name: 'Hudson, Bryan', team: 'MIL', ip: 10.1 },
    { id: 'hudsobr01', name: 'Hudson, Bryan', team: 'CHW', ip: 4.2 },
    { id: 'hummeco01', name: 'Hummel, Cooper', team: 'HOU', ip: 1 },
    { id: 'hurtebr01', name: 'Hurter, Brant', team: 'DET', ip: 63 },
    { id: 'iglesra01', name: 'Iglesias, Raisel', team: 'ATL', ip: 67.1 },
    { id: 'imanash01', name: 'Imanaga, Shota', team: 'CHC', ip: 144.2 },
    { id: 'irvinja01', name: 'Irvin, Jake', team: 'WSN', ip: 180 },
    { id: 'jacksal02', name: 'Jackson, Alex', team: 'BAL', ip: 1 },
    { id: 'jackslu01', name: 'Jackson, Luke', team: 'TOT', ip: 51 },
    { id: 'jackslu01', name: 'Jackson, Luke', team: 'TEX', ip: 35 },
    { id: 'jackslu01', name: 'Jackson, Luke', team: 'DET', ip: 4.2 },
    { id: 'jackslu01', name: 'Jackson, Luke', team: 'SEA', ip: 11.1 },
    { id: 'jacobal01', name: 'Jacob, Alek', team: 'SDP', ip: 33.1 },
    { id: 'jamesdr01', name: 'Jameson, Drey', team: 'ARI', ip: 3 },
    { id: 'jankotr01', name: 'Jankowski, Travis', team: 'NYM', ip: 1 },
    { id: 'janseke01', name: 'Jansen, Kenley', team: 'LAA', ip: 59 },
    { id: 'jarvibr01', name: 'Jarvis, Bryce', team: 'ARI', ip: 22 },
    { id: 'javiecr01', name: 'Javier, Cristian', team: 'HOU', ip: 37 },
    { id: 'jaxgr01', name: 'Jax, Griffin', team: 'TOT', ip: 66 },
    { id: 'jaxgr01', name: 'Jax, Griffin', team: 'MIN', ip: 46 },
    { id: 'jaxgr01', name: 'Jax, Griffin', team: 'TBR', ip: 20 },
    { id: 'jobeja01', name: 'Jobe, Jackson', team: 'DET', ip: 49 },
    { id: 'johnspi01', name: 'Johnson, Pierce', team: 'ATL', ip: 59 },
    { id: 'johnsry01', name: 'Johnson, Ryan', team: 'LAA', ip: 14.2 },
    { id: 'johnsse01', name: 'Johnson, Seth', team: 'PHI', ip: 12.2 },
    { id: 'joycebe01', name: 'Joyce, Ben', team: 'LAA', ip: 4.1 },
    { id: 'junisja01', name: 'Junis, Jakob', team: 'CLE', ip: 66.2 },
    { id: 'junkja01', name: 'Junk, Janson', team: 'MIA', ip: 110 },
    { id: 'kahnlto01', name: 'Kahnle, Tommy', team: 'DET', ip: 63 },
    { id: 'kavadni01', name: 'Kavadas, Niko', team: 'LAA', ip: 1.2 },
    { id: 'kellebr01', name: 'Keller, Brad', team: 'CHC', ip: 69.2 },
    { id: 'kellemi03', name: 'Keller, Mitch', team: 'PIT', ip: 176.1 },
    { id: 'kellyca01', name: 'Kelly, Casey', team: 'ARI', ip: 1.2 },
    { id: 'kellyke02', name: 'Kelly, Kevin', team: 'TBR', ip: 39.2 },
    { id: 'kellyme01', name: 'Kelly, Merrill', team: 'TOT', ip: 184 },
    { id: 'kellyme01', name: 'Kelly, Merrill', team: 'ARI', ip: 128.2 },
    { id: 'kellyme01', name: 'Kelly, Merrill', team: 'TEX', ip: 55.1 },
    { id: 'kellymi03', name: 'Kelly, Michael', team: 'ATH', ip: 39.2 },
    { id: 'kellyza01', name: 'Kelly, Zack', team: 'BOS', ip: 35.1 },
    { id: 'kentza01', name: 'Kent, Zak', team: 'CLE', ip: 17.2 },
    { id: 'kerkeor01', name: 'Kerkering, Orion', team: 'PHI', ip: 60 },
    { id: 'kershcl01', name: 'Kershaw, Clayton', team: 'LAD', ip: 112.2 },
    { id: 'kikucyu01', name: 'Kikuchi, Yusei', team: 'LAA', ip: 178.1 },
    { id: 'kimbrcr01', name: 'Kimbrel, Craig', team: 'TOT', ip: 12 },
    { id: 'kimbrcr01', name: 'Kimbrel, Craig', team: 'ATL', ip: 1 },
    { id: 'kimbrcr01', name: 'Kimbrel, Craig', team: 'HOU', ip: 11 },
    { id: 'kineris01', name: 'Kiner-Falefa, Isiah', team: 'TOR', ip: 0.2 },
    { id: 'kingbr02', name: 'King, Bryan', team: 'HOU', ip: 68 },
    { id: 'kingjo01', name: 'King, John', team: 'STL', ip: 48.1 },
    { id: 'kingmi01', name: 'King, Michael', team: 'SDP', ip: 73.1 },
    { id: 'kingesc01', name: 'Kingery, Scott', team: 'LAA', ip: 2 },
    { id: 'kinlety01', name: 'Kinley, Tyler', team: 'TOT', ip: 72.2 },
    { id: 'kinlety01', name: 'Kinley, Tyler', team: 'COL', ip: 47.2 },
    { id: 'kinlety01', name: 'Kinley, Tyler', team: 'ATL', ip: 25 },
    { id: 'kirbyge01', name: 'Kirby, George', team: 'SEA', ip: 126 },
    { id: 'kittran01', name: 'Kittredge, Andrew', team: 'TOT', ip: 53 },
    { id: 'kittran01', name: 'Kittredge, Andrew', team: 'BAL', ip: 31.1 },
    { id: 'kittran01', name: 'Kittredge, Andrew', team: 'CHC', ip: 21.2 },
    { id: 'kleinwi01', name: 'Klein, Will', team: 'LAD', ip: 15.1 },
    { id: 'knackla01', name: 'Knack, Landon', team: 'LAD', ip: 42.1 },
    { id: 'kochaja01', name: 'Kochanowicz, Jack', team: 'LAA', ip: 111 },
    { id: 'koenija01', name: 'Koenig, Jared', team: 'MIL', ip: 66 },
    { id: 'kolekst01', name: 'Kolek, Stephen', team: 'TOT', ip: 112.2 },
    { id: 'kolekst01', name: 'Kolek, Stephen', team: 'SDP', ip: 79.2 },
    { id: 'kolekst01', name: 'Kolek, Stephen', team: 'KCR', ip: 33 },
    { id: 'kopecmi01', name: 'Kopech, Michael', team: 'LAD', ip: 11 },
    { id: 'kossch01', name: 'Koss, Christian', team: 'SFG', ip: 4 },
    { id: 'kowarja01', name: 'Kowar, Jackson', team: 'SEA', ip: 17 },
    { id: 'kranima01', name: 'Kranick, Max', team: 'NYM', ip: 37 },
    { id: 'kremede01', name: 'Kremer, Dean', team: 'BAL', ip: 171.2 },
    { id: 'kriskbr01', name: 'Kriske, Brooks', team: 'TOT', ip: 18 },
    { id: 'kriskbr01', name: 'Kriske, Brooks', team: 'CHC', ip: 6 },
    { id: 'kriskbr01', name: 'Kriske, Brooks', team: 'MIN', ip: 12 },
    { id: 'krookma01', name: 'Krook, Matt', team: 'ATH', ip: 3.1 },
    { id: 'langeal01', name: 'Lange, Alex', team: 'DET', ip: 1 },
    { id: 'laosa01', name: 'Lao, Sauryn', team: 'TOT', ip: 11 },
    { id: 'laosa01', name: 'Lao, Sauryn', team: 'SEA', ip: 3.1 },
    { id: 'laosa01', name: 'Lao, Sauryn', team: 'WSN', ip: 7.2 },
    { id: 'laraan01', name: 'Lara, Andry', team: 'WSN', ip: 14.1 },
    { id: 'latzja01', name: 'Latz, Jacob', team: 'TEX', ip: 85.2 },
    { id: 'lauerer01', name: 'Lauer, Eric', team: 'TOR', ip: 104.2 },
    { id: 'lawerco01', name: 'Laweryson, Cody', team: 'MIN', ip: 7.2 },
    { id: 'lawreca01', name: 'Lawrence, Casey', team: 'TOT', ip: 17.2 },
    { id: 'lawreca01', name: 'Lawrence, Casey', team: 'SEA', ip: 15 },
    { id: 'lawreca01', name: 'Lawrence, Casey', team: 'TOR', ip: 2.2 },
    { id: 'lawreju01', name: 'Lawrence, Justin', team: 'PIT', ip: 17.2 },
    { id: 'lazarma01', name: 'Lazar, Max', team: 'PHI', ip: 41.1 },
    { id: 'leahyky01', name: 'Leahy, Kyle', team: 'STL', ip: 88 },
    { id: 'leasujo01', name: 'Leasure, Jordan', team: 'CHW', ip: 64.1 },
    { id: 'leclejo01', name: 'Leclerc, Jose', team: 'ATH', ip: 9 },
    { id: 'leech02', name: 'Lee, Chase', team: 'DET', ip: 37.1 },
    { id: 'leedy01', name: 'Lee, Dylan', team: 'ATL', ip: 68.1 },
    { id: 'leeko01', name: 'Lee, Korey', team: 'CHW', ip: 3 },
    { id: 'legumca01', name: 'Legumina, Casey', team: 'SEA', ip: 49.2 },
    { id: 'leiteja01', name: 'Leiter, Jack', team: 'TEX', ip: 151.2 },
    { id: 'liberma01', name: 'Liberatore, Matthew', team: 'STL', ip: 151.2 },
    { id: 'litteza01', name: 'Littell, Zack', team: 'TOT', ip: 186.2 },
    { id: 'litteza01', name: 'Littell, Zack', team: 'TBR', ip: 133.1 },
    { id: 'litteza01', name: 'Littell, Zack', team: 'CIN', ip: 53.1 },
    { id: 'littlbr02', name: 'Little, Brendon', team: 'TOR', ip: 68.1 },
    { id: 'littlja02', name: 'Little, Jack', team: 'LAD', ip: 3 },
    { id: 'littllu01', name: 'Little, Luke', team: 'CHC', ip: 2.2 },
    { id: 'livelbe01', name: 'Lively, Ben', team: 'CLE', ip: 44.2 },
    { id: 'loaisjo01', name: 'Loaisiga, Jonathan', team: 'NYY', ip: 29.2 },
    { id: 'lodolni01', name: 'Lodolo, Nick', team: 'CIN', ip: 156.2 },
    { id: 'longsa01', name: 'Long, Sam', team: 'KCR', ip: 40.1 },
    { id: 'lopezja04', name: 'Lopez, Jacob', team: 'ATH', ip: 92.2 },
    { id: 'lopezjo02', name: 'Lopez, Jorge', team: 'WSN', ip: 24.2 },
    { id: 'lopezni01', name: 'Lopez, Nicky', team: 'LAA', ip: 0.1 },
    { id: 'lopezpa01', name: 'Lopez, Pablo', team: 'MIN', ip: 75.2 },
    { id: 'lopezre01', name: 'Lopez, Reynaldo', team: 'ATL', ip: 5 },
    { id: 'lordbr02', name: 'Lord, Brad', team: 'WSN', ip: 130.2 },
    { id: 'lorenmi01', name: 'Lorenzen, Michael', team: 'KCR', ip: 141.2 },
    { id: 'loutory01', name: 'Loutos, Ryan', team: 'TOT', ip: 12 },
    { id: 'loutory01', name: 'Loutos, Ryan', team: 'LAD', ip: 3 },
    { id: 'loutory01', name: 'Loutos, Ryan', team: 'WSN', ip: 9 },
    { id: 'lovelri01', name: 'Lovelady, Richard', team: 'TOT', ip: 11.2 },
    { id: 'lovelri01', name: 'Lovelady, Richard', team: 'TOR', ip: 1.2 },
    { id: 'lovelri01', name: 'Lovelady, Richard', team: 'NYM', ip: 10 },
    { id: 'lucasea01', name: 'Lucas, Easton', team: 'TOR', ip: 24.1 },
    { id: 'lucchjo01', name: 'Lucchesi, Joey', team: 'SFG', ip: 38.1 },
    { id: 'lugose01', name: 'Lugo, Seth', team: 'KCR', ip: 145.1 },
    { id: 'luzarje01', name: 'Luzardo, Jesus', team: 'PHI', ip: 183.2 },
    { id: 'macivwi01', name: 'MacIver, Willie', team: 'ATH', ip: 2 },
    { id: 'maedake01', name: 'Maeda, Kenta', team: 'DET', ip: 8 },
    { id: 'mahlety01', name: 'Mahle, Tyler', team: 'TEX', ip: 86.2 },
    { id: 'mailelu01', name: 'Maile, Luke', team: 'KCR', ip: 1 },
    { id: 'maldoan01', name: 'Maldonado, Anthony', team: 'ATH', ip: 6 },
    { id: 'manaese01', name: 'Manaea, Sean', team: 'NYM', ip: 60.2 },
    { id: 'mantijo01', name: 'Mantiply, Joe', team: 'ARI', ip: 9.2 },
    { id: 'marinro01', name: 'Marinaccio, Ron', team: 'SDP', ip: 10.2 },
    { id: 'marquge01', name: 'Marquez, German', team: 'COL', ip: 126.1 },
    { id: 'martich02', name: 'Martin, Chris', team: 'TEX', ip: 42.1 },
    { id: 'martico02', name: 'Martin, Corbin', team: 'BAL', ip: 18 },
    { id: 'martida03', name: 'Martin, Davis', team: 'CHW', ip: 142.2 },
    { id: 'martiju01', name: 'Martinez, Justin', team: 'ARI', ip: 15.1 },
    { id: 'martini01', name: 'Martinez, Nick', team: 'CIN', ip: 165.2 },
    { id: 'martise01', name: 'Martinez, Seth', team: 'MIA', ip: 6.2 },
    { id: 'mastrmi01', name: 'Mastrobuoni, Miles', team: 'SEA', ip: 1 },
    { id: 'mateojo01', name: 'Mateo, Jorge', team: 'BAL', ip: 1 },
    { id: 'matonph01', name: 'Maton, Phil', team: 'TOT', ip: 61.1 },
    { id: 'matonph01', name: 'Maton, Phil', team: 'STL', ip: 38.1 },
    { id: 'matonph01', name: 'Maton, Phil', team: 'TEX', ip: 23 },
    { id: 'matsuyu01', name: 'Matsui, Yuki', team: 'SDP', ip: 63.1 },
    { id: 'matthze01', name: 'Matthews, Zebby', team: 'MIN', ip: 79.1 },
    { id: 'mattsis01', name: 'Mattson, Isaac', team: 'PIT', ip: 47.2 },
    { id: 'matzst01', name: 'Matz, Steven', team: 'TOT', ip: 76.2 },
    { id: 'matzst01', name: 'Matz, Steven', team: 'STL', ip: 55 },
    { id: 'matzst01', name: 'Matz, Steven', team: 'BOS', ip: 21.2 },
    { id: 'matzety01', name: 'Matzek, Tyler', team: 'NYY', ip: 6.1 },
    { id: 'maxweza01', name: 'Maxwell, Zach', team: 'CIN', ip: 10 },
    { id: 'maydu01', name: 'May, Dustin', team: 'TOT', ip: 132.1 },
    { id: 'maydu01', name: 'May, Dustin', team: 'LAD', ip: 104 },
    { id: 'maydu01', name: 'May, Dustin', team: 'BOS', ip: 28.1 },
    { id: 'mayzati01', name: 'Mayza, Tim', team: 'TOT', ip: 16.2 },
    { id: 'mayzati01', name: 'Mayza, Tim', team: 'PIT', ip: 9.1 },
    { id: 'mayzati01', name: 'Mayza, Tim', team: 'PHI', ip: 7.1 },
    { id: 'mazurad01', name: 'Mazur, Adam', team: 'MIA', ip: 30 },
    { id: 'mccauda01', name: 'McCaughan, Darren', team: 'MIN', ip: 5.1 },
    { id: 'mccorch01', name: 'McCormick, Chas', team: 'HOU', ip: 3 },
    { id: 'mcdanga01', name: 'McDaniels, Garrett', team: 'LAA', ip: 10.2 },
    { id: 'mcderch01', name: 'McDermott, Chayce', team: 'BAL', ip: 8.2 },
    { id: 'mcdontr01', name: 'McDonald, Trevor', team: 'SFG', ip: 15 },
    { id: 'mcfartj01', name: 'McFarland, TJ', team: 'ATH', ip: 15.2 },
    { id: 'mcgeeea01', name: 'McGee, Easton', team: 'MIL', ip: 14.2 },
    { id: 'mcgousc01', name: 'McGough, Scott', team: 'TOT', ip: 16 },
    { id: 'mcgousc01', name: 'McGough, Scott', team: 'ARI', ip: 7 },
    { id: 'mcgousc01', name: 'McGough, Scott', team: 'ATH', ip: 9 },
    { id: 'mcgremi01', name: 'McGreevy, Michael', team: 'STL', ip: 95.2 },
    { id: 'mcguire01', name: 'McGuire, Reese', team: 'CHC', ip: 1 },
    { id: 'mckentr01', name: 'McKenzie, Triston', team: 'CLE', ip: 5.2 },
    { id: 'mckinza01', name: 'McKinstry, Zach', team: 'DET', ip: 0.1 },
    { id: 'mcleano01', name: 'McLean, Nolan', team: 'NYM', ip: 48 },
    { id: 'mearsni01', name: 'Mears, Nick', team: 'MIL', ip: 56.2 },
    { id: 'medervi01', name: 'Mederos, Victor', team: 'LAA', ip: 17 },
    { id: 'megiltr01', name: 'Megill, Trevor', team: 'MIL', ip: 47 },
    { id: 'megilty01', name: 'Megill, Tylor', team: 'NYM', ip: 68.1 },
    { id: 'mejiaju01', name: 'Mejia, Juan', team: 'COL', ip: 61.1 },
    { id: 'meltotr01', name: 'Melton, Troy', team: 'DET', ip: 45.2 },
    { id: 'menacr01', name: 'Mena, Cristian', team: 'ARI', ip: 6.2 },
    { id: 'mercami01', name: 'Mercado, Michael', team: 'PHI', ip: 3 },
    { id: 'merryju01', name: 'Merryweather, Julian', team: 'CHC', ip: 18.2 },
    { id: 'messipa01', name: 'Messick, Parker', team: 'CLE', ip: 39.2 },
    { id: 'meylu01', name: 'Mey, Luis', team: 'CIN', ip: 21 },
    { id: 'meyerma01', name: 'Meyer, Max', team: 'MIA', ip: 64.2 },
    { id: 'mikolmi01', name: 'Mikolas, Miles', team: 'STL', ip: 156.1 },
    { id: 'mileywa01', name: 'Miley, Wade', team: 'CIN', ip: 12 },
    { id: 'millebo06', name: 'Miller, Bobby', team: 'LAD', ip: 5 },
    { id: 'millebr04', name: 'Miller, Bryce', team: 'SEA', ip: 90.1 },
    { id: 'milleer01', name: 'Miller, Erik', team: 'SFG', ip: 30 },
    { id: 'millema03', name: 'Miller, Mason', team: 'TOT', ip: 61.2 },
    { id: 'millema03', name: 'Miller, Mason', team: 'ATH', ip: 38.1 },
    { id: 'millema03', name: 'Miller, Mason', team: 'SDP', ip: 23.1 },
    { id: 'millesh01', name: 'Miller, Shelby', team: 'TOT', ip: 46 },
    { id: 'millesh01', name: 'Miller, Shelby', team: 'ARI', ip: 36.1 },
    { id: 'millesh01', name: 'Miller, Shelby', team: 'MIL', ip: 9.2 },
    { id: 'milneho01', name: 'Milner, Hoby', team: 'TEX', ip: 70.1 },
    { id: 'minteaj01', name: 'Minter, AJ', team: 'NYM', ip: 11 },
    { id: 'misiean01', name: 'Misiewicz, Anthony', team: 'MIN', ip: 4.2 },
    { id: 'misioja01', name: 'Misiorowski, Jacob', team: 'MIL', ip: 66 },
    { id: 'mizeca01', name: 'Mize, Casey', team: 'DET', ip: 149 },
    { id: 'mlodzca01', name: 'Mlodzinski, Carmen', team: 'PIT', ip: 99 },
    { id: 'molinan01', name: 'Molina, Anthony', team: 'COL', ip: 34.2 },
    { id: 'mollsa01', name: 'Moll, Sam', team: 'CIN', ip: 18.1 },
    { id: 'montafr02', name: 'Montas, Frankie', team: 'NYM', ip: 38.2 },
    { id: 'monteke01', name: 'Montero, Keider', team: 'DET', ip: 90.2 },
    { id: 'montera01', name: 'Montero, Rafael', team: 'TOT', ip: 60.1 },
    { id: 'montera01', name: 'Montero, Rafael', team: 'TOT', ip: 26 },
    { id: 'montera01', name: 'Montero, Rafael', team: 'HOU', ip: 4 },
    { id: 'montera01', name: 'Montero, Rafael', team: 'ATL', ip: 34.1 },
    { id: 'montera01', name: 'Montero, Rafael', team: 'DET', ip: 22 },
    { id: 'montepa01', name: 'Monteverde, Patrick', team: 'MIA', ip: 3.2 },
    { id: 'montgma01', name: 'Montgomery, Mason', team: 'TBR', ip: 46 },
    { id: 'morallu01', name: 'Morales, Luis', team: 'ATH', ip: 48.2 },
    { id: 'moranjo01', name: 'Moran, Jovani', team: 'BOS', ip: 4 },
    { id: 'morejad01', name: 'Morejon, Adrian', team: 'SDP', ip: 73.2 },
    { id: 'moretda01', name: 'Moreta, Dauri', team: 'PIT', ip: 16.2 },
    { id: 'morgada01', name: 'Morgan, David', team: 'SDP', ip: 47.1 },
    { id: 'morgael01', name: 'Morgan, Eli', team: 'CHC', ip: 7.1 },
    { id: 'morilju02', name: 'Morillo, Juan', team: 'ARI', ip: 34.1 },
    { id: 'mortoch02', name: 'Morton, Charlie', team: 'TOT', ip: 142 },
    { id: 'mortoch02', name: 'Morton, Charlie', team: 'TOT', ip: 140.2 },
    { id: 'mortoch02', name: 'Morton, Charlie', team: 'ATL', ip: 1.1 },
    { id: 'mortoch02', name: 'Morton, Charlie', team: 'BAL', ip: 101.1 },
    { id: 'mortoch02', name: 'Morton, Charlie', team: 'DET', ip: 39.1 },
    { id: 'munozan01', name: 'Munoz, Andres', team: 'SEA', ip: 62.1 },
    { id: 'munozro01', name: 'Munoz, Roddery', team: 'STL', ip: 11 },
    { id: 'munozro02', name: 'Munoz, Rolddy', team: 'ATL', ip: 3.2 },
    { id: 'murdono01', name: 'Murdock, Noah', team: 'ATH', ip: 17 },
    { id: 'murfepe01', name: 'Murfee, Penn', team: 'CHW', ip: 12.2 },
    { id: 'murphch01', name: 'Murphy, Chris', team: 'BOS', ip: 34.2 },
    { id: 'murraja01', name: 'Murray, Jayden', team: 'HOU', ip: 11.2 },
    { id: 'myersto01', name: 'Myers, Tobias', team: 'MIL', ip: 50.2 },
    { id: 'woodssi01', name: 'Woods Richardson, Simeon', team: 'MIN', ip: 111.1 },
    { id: 'ferrejo01', name: 'Ferrer, Jose A', team: 'WSN', ip: 76.1 },
    { id: 'lynchda02', name: 'Lynch IV, Daniel', team: 'KCR', ip: 67.2 },
    { id: 'delosen01', name: 'De Los Santos, Enyel', team: 'TOT', ip: 66 },
    { id: 'delosen01', name: 'De Los Santos, Enyel', team: 'ATL', ip: 43.2 },
    { id: 'delosen01', name: 'De Los Santos, Enyel', team: 'HOU', ip: 22.1 },
    { id: 'mcculla02', name: 'McCullers Jr, Lance', team: 'HOU', ip: 55.1 },
    { id: 'leitema02', name: 'Leiter Jr, Mark', team: 'NYY', ip: 48.1 },
    { id: 'delosye01', name: 'De los Santos, Yerry', team: 'NYY', ip: 35.2 },
    { id: 'vanbebr01', name: 'Van Belle, Brian', team: 'TBR', ip: 8.1 },
    { id: 'deleojo03', name: 'De Leon, Jose', team: 'BOS', ip: 6.2 },
    { id: 'lasorjo01', name: 'La Sorsa, Joe', team: 'CIN', ip: 6.2 },
    { id: 'edwarca01', name: 'Edwards Jr, Carl', team: 'TOT', ip: 6 },
    { id: 'edwarca01', name: 'Edwards Jr, Carl', team: 'LAA', ip: 3 },
    { id: 'edwarca01', name: 'Edwards Jr, Carl', team: 'TEX', ip: 3 },
    { id: 'montech01', name: 'Montes De Oca, Christian', team: 'ARI', ip: 2.2 },
    { id: 'degeubr01', name: 'de Geus, Brett', team: 'PHI', ip: 2 },
    { id: 'nanceto01', name: 'Nance, Tommy', team: 'TOR', ip: 31.2 },
    { id: 'nelsoky01', name: 'Nelson, Kyle', team: 'ARI', ip: 2 },
    { id: 'nelsory01', name: 'Nelson, Ryne', team: 'ARI', ip: 154 },
    { id: 'nerishe01', name: 'Neris, Hector', team: 'TOT', ip: 26.2 },
    { id: 'nerishe01', name: 'Neris, Hector', team: 'TOT', ip: 25.2 },
    { id: 'nerishe01', name: 'Neris, Hector', team: 'ATL', ip: 1 },
    { id: 'nerishe01', name: 'Neris, Hector', team: 'LAA', ip: 14 },
    { id: 'nerishe01', name: 'Neris, Hector', team: 'HOU', ip: 11.2 },
    { id: 'newcose01', name: 'Newcomb, Sean', team: 'TOT', ip: 92.1 },
    { id: 'newcose01', name: 'Newcomb, Sean', team: 'BOS', ip: 41 },
    { id: 'newcose01', name: 'Newcomb, Sean', team: 'ATH', ip: 51.1 },
    { id: 'newmake01', name: 'Newman, Kevin', team: 'LAA', ip: 4 },
    { id: 'nicolky01', name: 'Nicolas, Kyle', team: 'PIT', ip: 38 },
    { id: 'nidoto01', name: 'Nido, Tomas', team: 'DET', ip: 1.2 },
    { id: 'nikhado01', name: 'Nikhazy, Doug', team: 'CLE', ip: 4 },
    { id: 'nolaaa01', name: 'Nola, Aaron', team: 'PHI', ip: 94.1 },
    { id: 'nolaau01', name: 'Nola, Austin', team: 'COL', ip: 1 },
    { id: 'nunezde01', name: 'Nunez, Dedniel', team: 'NYM', ip: 9.2 },
    { id: 'nunezed03', name: 'Nunez, Eduarniel', team: 'TOT', ip: 12.2 },
    { id: 'nunezed03', name: 'Nunez, Eduarniel', team: 'SDP', ip: 4.2 },
    { id: 'nunezed03', name: 'Nunez, Eduarniel', team: 'ATH', ip: 8 },
    { id: 'oberba01', name: 'Ober, Bailey', team: 'MIN', ip: 146.1 },
    { id: 'obrieri01', name: 'O\'Brien, Riley', team: 'STL', ip: 48 },
    { id: 'ogasash01', name: 'Ogasawara, Shinnosuke', team: 'WSN', ip: 38.2 },
    { id: 'ohlpi01', name: 'Ohl, Pierson', team: 'MIN', ip: 30 },
    { id: 'ohtansh01', name: 'Ohtani, Shohei', team: 'LAD', ip: 47 },
    { id: 'okertst01', name: 'Okert, Steven', team: 'HOU', ip: 71.2 },
    { id: 'olsonre01', name: 'Olson, Reese', team: 'DET', ip: 68.2 },
    { id: 'ortka01', name: 'Ort, Kaleb', team: 'HOU', ip: 46 },
    { id: 'ortizlu03', name: 'Ortiz, Luis', team: 'CLE', ip: 88.2 },
    { id: 'orzeer01', name: 'Orze, Eric', team: 'TBR', ip: 41.2 },
    { id: 'otanemi01', name: 'Otanez, Michel', team: 'ATH', ip: 5.1 },
    { id: 'ottavad01', name: 'Ottavino, Adam', team: 'NYY', ip: 1.2 },
    { id: 'oviedjo01', name: 'Oviedo, Johan', team: 'PIT', ip: 40.1 },
    { id: 'owensty01', name: 'Owens, Tyler', team: 'DET', ip: 3 },
    { id: 'paddach01', name: 'Paddack, Chris', team: 'TOT', ip: 158 },
    { id: 'paddach01', name: 'Paddack, Chris', team: 'MIN', ip: 111 },
    { id: 'paddach01', name: 'Paddack, Chris', team: 'DET', ip: 47 },
    { id: 'paganem01', name: 'Pagan, Emilio', team: 'CIN', ip: 68.2 },
    { id: 'palenda01', name: 'Palencia, Daniel', team: 'CHC', ip: 52.2 },
    { id: 'palisja01', name: 'Palisch, Jake', team: 'CHW', ip: 1 },
    { id: 'pallaan01', name: 'Pallante, Andre', team: 'STL', ip: 162.2 },
    { id: 'palmqca01', name: 'Palmquist, Carson', team: 'COL', ip: 34.1 },
    { id: 'parkemi01', name: 'Parker, Mitchell', team: 'WSN', ip: 164.2 },
    { id: 'patrich01', name: 'Patrick, Chad', team: 'MIL', ip: 119.2 },
    { id: 'payamjo01', name: 'Payamps, Joel', team: 'TOT', ip: 26.1 },
    { id: 'payamjo01', name: 'Payamps, Joel', team: 'MIL', ip: 23.2 },
    { id: 'payamjo01', name: 'Payamps, Joel', team: 'ATL', ip: 2.2 },
    { id: 'pearsna01', name: 'Pearson, Nate', team: 'CHC', ip: 14.2 },
    { id: 'pegueel01', name: 'Peguero, Elvis', team: 'TOT', ip: 9.1 },
    { id: 'pegueel01', name: 'Peguero, Elvis', team: 'MIL', ip: 7.1 },
    { id: 'pegueel01', name: 'Peguero, Elvis', team: 'CHW', ip: 2 },
    { id: 'peguejo01', name: 'Peguero, Joel', team: 'SFG', ip: 22.1 },
    { id: 'pepiory01', name: 'Pepiot, Ryan', team: 'TBR', ip: 167.2 },
    { id: 'peralfr01', name: 'Peralta, Freddy', team: 'MIL', ip: 176.2 },
    { id: 'perallu01', name: 'Peralta, Luis', team: 'COL', ip: 19 },
    { id: 'peralsa01', name: 'Peralta, Sammy', team: 'LAA', ip: 10.2 },
    { id: 'peralwa01', name: 'Peralta, Wandy', team: 'SDP', ip: 71.2 },
    { id: 'perazos02', name: 'Peraza, Oswald', team: 'LAA', ip: 2.1 },
    { id: 'perdoan01', name: 'Perdomo, Angel', team: 'ATH', ip: 3.1 },
    { id: 'peredjh01', name: 'Pereda, Jhonny', team: 'ATH', ip: 3 },
    { id: 'perezci01', name: 'Perez, Cionel', team: 'BAL', ip: 21.2 },
    { id: 'perezeu02', name: 'Perez, Eury', team: 'MIA', ip: 95.1 },
    { id: 'perezma02', name: 'Perez, Martin', team: 'CHW', ip: 56 },
    { id: 'perkija01', name: 'Perkins, Jack', team: 'ATH', ip: 38.2 },
    { id: 'petermi01', name: 'Petersen, Michael', team: 'TOT', ip: 18 },
    { id: 'petermi01', name: 'Petersen, Michael', team: 'ATL', ip: 6.2 },
    { id: 'petermi01', name: 'Petersen, Michael', team: 'MIA', ip: 11.1 },
    { id: 'peterda01', name: 'Peterson, David', team: 'NYM', ip: 168.2 },
    { id: 'pettych02', name: 'Petty, Chase', team: 'CIN', ip: 6 },
    { id: 'pfaadbr01', name: 'Pfaadt, Brandon', team: 'ARI', ip: 176.2 },
    { id: 'phillco01', name: 'Phillips, Connor', team: 'CIN', ip: 25 },
    { id: 'phillev01', name: 'Phillips, Evan', team: 'LAD', ip: 5.2 },
    { id: 'phillty01', name: 'Phillips, Tyler', team: 'MIA', ip: 77.2 },
    { id: 'pilkiko01', name: 'Pilkington, Konnor', team: 'WSN', ip: 28.1 },
    { id: 'pinaro01', name: 'Pina, Robinson', team: 'TOT', ip: 2.1 },
    { id: 'pinaro01', name: 'Pina, Robinson', team: 'MIA', ip: 1 },
    { id: 'pinaro01', name: 'Pina, Robinson', team: 'TOR', ip: 1.1 },
    { id: 'pintajo01', name: 'Pintaro, Jonathan', team: 'NYM', ip: 0.2 },
    { id: 'pivetni01', name: 'Pivetta, Nick', team: 'SDP', ip: 181.2 },
    { id: 'pocheco01', name: 'Poche, Colin', team: 'TOT', ip: 9.1 },
    { id: 'pocheco01', name: 'Poche, Colin', team: 'WSN', ip: 8.2 },
    { id: 'pocheco01', name: 'Poche, Colin', team: 'NYM', ip: 0.2 },
    { id: 'pomerdr01', name: 'Pomeranz, Drew', team: 'CHC', ip: 49.2 },
    { id: 'popza01', name: 'Pop, Zach', team: 'TOT', ip: 6.2 },
    { id: 'popza01', name: 'Pop, Zach', team: 'SEA', ip: 5.1 },
    { id: 'popza01', name: 'Pop, Zach', team: 'NYM', ip: 1.1 },
    { id: 'popeau01', name: 'Pope, Austin', team: 'ARI', ip: 2 },
    { id: 'portelo01', name: 'Porter, Logan', team: 'SFG', ip: 1 },
    { id: 'poteeco01', name: 'Poteet, Cody', team: 'BAL', ip: 2.2 },
    { id: 'poulipj01', name: 'Poulin, PJ', team: 'WSN', ip: 24.2 },
    { id: 'povicca01', name: 'Povich, Cade', team: 'BAL', ip: 112.1 },
    { id: 'pressry01', name: 'Pressly, Ryan', team: 'CHC', ip: 41.1 },
    { id: 'priesqu01', name: 'Priester, Quinn', team: 'MIL', ip: 157.1 },
    { id: 'pukaj01', name: 'Puk, AJ', team: 'ARI', ip: 8 },
    { id: 'quantca01', name: 'Quantrill, Cal', team: 'TOT', ip: 117.2 },
    { id: 'quantca01', name: 'Quantrill, Cal', team: 'MIA', ip: 109.2 },
    { id: 'quantca01', name: 'Quantrill, Cal', team: 'ATL', ip: 8 },
    { id: 'quijajo01', name: 'Quijada, Jose', team: 'LAA', ip: 1.1 },
    { id: 'quintjo01', name: 'Quintana, Jose', team: 'MIL', ip: 131.2 },
    { id: 'raganco01', name: 'Ragans, Cole', team: 'KCR', ip: 61.2 },
    { id: 'ragsdca01', name: 'Ragsdale, Carson', team: 'BAL', ip: 5 },
    { id: 'raineta01', name: 'Rainey, Tanner', team: 'TOT', ip: 9.2 },
    { id: 'raineta01', name: 'Rainey, Tanner', team: 'PIT', ip: 7.2 },
    { id: 'raineta01', name: 'Rainey, Tanner', team: 'DET', ip: 2 },
    { id: 'raleybr01', name: 'Raley, Brooks', team: 'NYM', ip: 25.2 },
    { id: 'ramirer02', name: 'Ramirez, Erasmo', team: 'MIN', ip: 11 },
    { id: 'ramiryo01', name: 'Ramirez, Yohan', team: 'PIT', ip: 33.1 },
    { id: 'rangeal01', name: 'Rangel, Alan', team: 'PHI', ip: 11 },
    { id: 'raqueni01', name: 'Raquet, Nick', team: 'STL', ip: 2 },
    { id: 'rashita01', name: 'Rashi, Taylor', team: 'ARI', ip: 16.1 },
    { id: 'rasmudr01', name: 'Rasmussen, Drew', team: 'TBR', ip: 150 },
    { id: 'rayro02', name: 'Ray, Robbie', team: 'SFG', ip: 182.1 },
    { id: 'reaco01', name: 'Rea, Colin', team: 'CHC', ip: 159.1 },
    { id: 'reyespa01', name: 'Reyes, Pablo', team: 'NYY', ip: 1 },
    { id: 'reynose01', name: 'Reynolds, Sean', team: 'SDP', ip: 27 },
    { id: 'ribalor01', name: 'Ribalta, Orlando', team: 'WSN', ip: 24.1 },
    { id: 'richatr01', name: 'Richards, Trevor', team: 'TOT', ip: 5.2 },
    { id: 'richatr01', name: 'Richards, Trevor', team: 'KCR', ip: 3 },
    { id: 'richatr01', name: 'Richards, Trevor', team: 'ARI', ip: 2.2 },
    { id: 'richaly01', name: 'Richardson, Lyon', team: 'CIN', ip: 37.2 },
    { id: 'rivasle01', name: 'Rivas, Leo', team: 'SEA', ip: 1 },
    { id: 'riverem01', name: 'Rivera, Emmanuel', team: 'BAL', ip: 1 },
    { id: 'roach02', name: 'Roa, Christian', team: 'MIA', ip: 3 },
    { id: 'roberda11', name: 'Robert, Daniel', team: 'PHI', ip: 13 },
    { id: 'roberet01', name: 'Roberts, Ethan', team: 'CHC', ip: 9 },
    { id: 'roberda08', name: 'Robertson, David', team: 'PHI', ip: 17.2 },
    { id: 'rockjo01', name: 'Rock, Joe', team: 'TBR', ip: 7.2 },
    { id: 'rockeku01', name: 'Rocker, Kumar', team: 'TEX', ip: 64.1 },
    { id: 'rodonca01', name: 'Rodon, Carlos', team: 'NYY', ip: 195.1 },
    { id: 'rodribr01', name: 'Rodriguez, Bradgley', team: 'SDP', ip: 7.2 },
    { id: 'rodrica02', name: 'Rodriguez, Carlos', team: 'MIL', ip: 9.2 },
    { id: 'rodried05', name: 'Rodriguez, Eduardo', team: 'ARI', ip: 154.1 },
    { id: 'rodriel02', name: 'Rodriguez, Elvin', team: 'TOT', ip: 19.2 },
    { id: 'rodriel02', name: 'Rodriguez, Elvin', team: 'MIL', ip: 18.2 },
    { id: 'rodriel02', name: 'Rodriguez, Elvin', team: 'BAL', ip: 1 },
    { id: 'rodrima01', name: 'Rodriguez, Manuel', team: 'TBR', ip: 30.1 },
    { id: 'rodrira02', name: 'Rodriguez, Randy', team: 'SFG', ip: 50.2 },
    { id: 'rodriya01', name: 'Rodriguez, Yariel', team: 'TOR', ip: 73 },
    { id: 'rogerja03', name: 'Rogers, Jake', team: 'DET', ip: 3.2 },
    { id: 'rogerta01', name: 'Rogers, Taylor', team: 'TOT', ip: 50.2 },
    { id: 'rogerta01', name: 'Rogers, Taylor', team: 'CIN', ip: 33 },
    { id: 'rogerta01', name: 'Rogers, Taylor', team: 'CHC', ip: 17.2 },
    { id: 'rogertr01', name: 'Rogers, Trevor', team: 'BAL', ip: 109.2 },
    { id: 'rogerty01', name: 'Rogers, Tyler', team: 'TOT', ip: 77.1 },
    { id: 'rogerty01', name: 'Rogers, Tyler', team: 'SFG', ip: 50 },
    { id: 'rogerty01', name: 'Rogers, Tyler', team: 'NYM', ip: 27.1 },
    { id: 'rojasmi02', name: 'Rojas, Miguel', team: 'LAD', ip: 5 },
    { id: 'rolisry01', name: 'Rolison, Ryan', team: 'COL', ip: 42.1 },
    { id: 'romanjo03', name: 'Romano, Jordan', team: 'PHI', ip: 42.2 },
    { id: 'romerjo01', name: 'Romero, JoJo', team: 'STL', ip: 61 },
    { id: 'roonejo01', name: 'Rooney, John', team: 'HOU', ip: 1.1 },
    { id: 'rosaram01', name: 'Rosario, Amed', team: 'WSN', ip: 1 },
    { id: 'rossjo01', name: 'Ross, Joe', team: 'PHI', ip: 51 },
    { id: 'rouppla01', name: 'Roupp, Landen', team: 'SFG', ip: 106.2 },
    { id: 'roycrch01', name: 'Roycroft, Chris', team: 'STL', ip: 20.2 },
    { id: 'ruizjo01', name: 'Ruiz, Jose', team: 'TOT', ip: 16.1 },
    { id: 'ruizjo01', name: 'Ruiz, Jose', team: 'PHI', ip: 14.1 },
    { id: 'ruizjo01', name: 'Ruiz, Jose', team: 'ATL', ip: 2 },
    { id: 'rutleja01', name: 'Rutledge, Jackson', team: 'WSN', ip: 73.1 },
    { id: 'ryanjo04', name: 'Ryan, Joe', team: 'MIN', ip: 171 },
    { id: 'saalfan01', name: 'Saalfrank, Andrew', team: 'ARI', ip: 29 },
    { id: 'sabroer01', name: 'Sabrowski, Erik', team: 'CLE', ip: 29.1 },
    { id: 'salazce01', name: 'Salazar, Cesar', team: 'HOU', ip: 1 },
    { id: 'salazed01', name: 'Salazar, Eduardo', team: 'WSN', ip: 29 },
    { id: 'salech01', name: 'Sale, Chris', team: 'ATL', ip: 125.2 },
    { id: 'sanchal04', name: 'Sanchez, Ali', team: 'TOR', ip: 1 },
    { id: 'sanchcr01', name: 'Sanchez, Cristopher', team: 'PHI', ip: 202 },
    { id: 'sanchga02', name: 'Sanchez, Gary', team: 'BAL', ip: 1 },
    { id: 'sandeca01', name: 'Sanders, Cam', team: 'PIT', ip: 6.2 },
    { id: 'sandlni01', name: 'Sandlin, Nick', team: 'TOR', ip: 16.1 },
    { id: 'sandrja01', name: 'Sandridge, Jayvien', team: 'NYY', ip: 0.2 },
    { id: 'sandsco01', name: 'Sands, Cole', team: 'MIN', ip: 72 },
    { id: 'sanmare01', name: 'Sanmartin, Reiver', team: 'CIN', ip: 1.2 },
    { id: 'sanojja01', name: 'Sanoja, Javier', team: 'MIA', ip: 9.1 },
    { id: 'santade01', name: 'Santana, Dennis', team: 'PIT', ip: 70.1 },
    { id: 'santito01', name: 'Santillan, Tony', team: 'CIN', ip: 73.2 },
    { id: 'santogr01', name: 'Santos, Gregory', team: 'SEA', ip: 7 },
    { id: 'sasakro01', name: 'Sasaki, Roki', team: 'LAD', ip: 36.1 },
    { id: 'sauceta01', name: 'Saucedo, Tayler', team: 'SEA', ip: 13.1 },
    { id: 'sauerma01', name: 'Sauer, Matt', team: 'LAD', ip: 29.2 },
    { id: 'scherma01', name: 'Scherzer, Max', team: 'TOR', ip: 85 },
    { id: 'schlica01', name: 'Schlittler, Cam', team: 'NYY', ip: 73 },
    { id: 'schmicl01', name: 'Schmidt, Clarke', team: 'NYY', ip: 78.2 },
    { id: 'scholje01', name: 'Scholtens, Jesse', team: 'TBR', ip: 8.1 },
    { id: 'schrejo01', name: 'Schreiber, John', team: 'KCR', ip: 64 },
    { id: 'schulpa01', name: 'Schultz, Paxton', team: 'TOR', ip: 24.2 },
    { id: 'schwesp01', name: 'Schwellenbach, Spencer', team: 'ATL', ip: 110.2 },
    { id: 'scottta01', name: 'Scott, Tanner', team: 'LAD', ip: 57 },
    { id: 'scottta02', name: 'Scott, Tayler', team: 'TOT', ip: 27.1 },
    { id: 'scottta02', name: 'Scott, Tayler', team: 'HOU', ip: 18.1 },
    { id: 'scottta02', name: 'Scott, Tayler', team: 'ARI', ip: 9 },
    { id: 'seaboco01', name: 'Seabold, Connor', team: 'TOT', ip: 10.1 },
    { id: 'seaboco01', name: 'Seabold, Connor', team: 'TBR', ip: 6.2 },
    { id: 'seaboco01', name: 'Seabold, Connor', team: 'ATL', ip: 3.2 },
    { id: 'searsjp01', name: 'Sears, JP', team: 'TOT', ip: 135.2 },
    { id: 'searsjp01', name: 'Sears, JP', team: 'ATH', ip: 111 },
    { id: 'searsjp01', name: 'Sears, JP', team: 'SDP', ip: 24.2 },
    { id: 'seiglan01', name: 'Seigler, Anthony', team: 'MIL', ip: 1 },
    { id: 'selbyco01', name: 'Selby, Colin', team: 'BAL', ip: 14 },
    { id: 'sengako01', name: 'Senga, Kodai', team: 'NYM', ip: 113.1 },
    { id: 'senzaan01', name: 'Senzatela, Antonio', team: 'COL', ip: 130 },
    { id: 'severlu01', name: 'Severino, Luis', team: 'ATH', ip: 162.2 },
    { id: 'sewalpa01', name: 'Sewald, Paul', team: 'TOT', ip: 19.2 },
    { id: 'sewalpa01', name: 'Sewald, Paul', team: 'CLE', ip: 15.1 },
    { id: 'sewalpa01', name: 'Sewald, Paul', team: 'DET', ip: 4.1 },
    { id: 'seymoca01', name: 'Seymour, Carson', team: 'SFG', ip: 36 },
    { id: 'seymoia01', name: 'Seymour, Ian', team: 'TBR', ip: 57 },
    { id: 'sheehem01', name: 'Sheehan, Emmet', team: 'LAD', ip: 73.1 },
    { id: 'shugach01', name: 'Shugart, Chase', team: 'PIT', ip: 45 },
    { id: 'shustja01', name: 'Shuster, Jared', team: 'CHW', ip: 15.2 },
    { id: 'silsech01', name: 'Silseth, Chase', team: 'LAA', ip: 11 },
    { id: 'simpsjo02', name: 'Simpson, Josh', team: 'MIA', ip: 30.2 },
    { id: 'simslu01', name: 'Sims, Lucas', team: 'WSN', ip: 12.1 },
    { id: 'singebr01', name: 'Singer, Brady', team: 'CIN', ip: 169.2 },
    { id: 'siskev01', name: 'Sisk, Evan', team: 'TOT', ip: 17.2 },
    { id: 'siskev01', name: 'Sisk, Evan', team: 'KCR', ip: 5.1 },
    { id: 'siskev01', name: 'Sisk, Evan', team: 'PIT', ip: 12.1 },
    { id: 'skenepa01', name: 'Skenes, Paul', team: 'PIT', ip: 187.2 },
    { id: 'skubata01', name: 'Skubal, Tarik', team: 'DET', ip: 195.1 },
    { id: 'slateju01', name: 'Slaten, Justin', team: 'BOS', ip: 34 },
    { id: 'slateau01', name: 'Slater, Austin', team: 'NYY', ip: 0.2 },
    { id: 'smithca06', name: 'Smith, Cade', team: 'CLE', ip: 73.2 },
    { id: 'smithdy01', name: 'Smith, Dylan', team: 'DET', ip: 13 },
    { id: 'smithsh02', name: 'Smith, Shane', team: 'CHW', ip: 146.1 },
    { id: 'smithaj01', name: 'Smith-Shawver, AJ', team: 'ATL', ip: 44.1 },
    { id: 'snellbl01', name: 'Snell, Blake', team: 'LAD', ip: 61.1 },
    { id: 'snideco01', name: 'Snider, Collin', team: 'SEA', ip: 26.1 },
    { id: 'sommedr01', name: 'Sommers, Drew', team: 'DET', ip: 3 },
    { id: 'soriage01', name: 'Soriano, George', team: 'MIA', ip: 36.2 },
    { id: 'soriajo02', name: 'Soriano, Jose', team: 'LAA', ip: 169 },
    { id: 'sorokmi01', name: 'Soroka, Michael', team: 'TOT', ip: 89.2 },
    { id: 'sorokmi01', name: 'Soroka, Michael', team: 'WSN', ip: 81.1 },
    { id: 'sorokmi01', name: 'Soroka, Michael', team: 'CHC', ip: 8.1 },
    { id: 'sotogr01', name: 'Soto, Gregory', team: 'TOT', ip: 60.1 },
    { id: 'sotogr01', name: 'Soto, Gregory', team: 'BAL', ip: 36.1 },
    { id: 'sotogr01', name: 'Soto, Gregory', team: 'NYM', ip: 24 },
    { id: 'sousabe01', name: 'Sousa, Bennett', team: 'HOU', ip: 50.2 },
    { id: 'speiega01', name: 'Speier, Gabe', team: 'SEA', ip: 62 },
    { id: 'spencmi01', name: 'Spence, Mitch', team: 'ATH', ip: 84.2 },
    { id: 'spierca01', name: 'Spiers, Carson', team: 'CIN', ip: 13.1 },
    { id: 'sprinje01', name: 'Springs, Jeffrey', team: 'ATH', ip: 171 },
    { id: 'sproabr01', name: 'Sproat, Brandon', team: 'NYM', ip: 20.2 },
    { id: 'stallja01', name: 'Stallings, Jacob', team: 'COL', ip: 2 },
    { id: 'stanery01', name: 'Stanek, Ryne', team: 'NYM', ip: 56 },
    { id: 'steelju01', name: 'Steele, Justin', team: 'CHC', ip: 22.2 },
    { id: 'stefami01', name: 'Stefanic, Michael', team: 'TOR', ip: 1 },
    { id: 'stephro01', name: 'Stephenson, Robert', team: 'LAA', ip: 10 },
    { id: 'sternju01', name: 'Sterner, Justin', team: 'ATH', ip: 65 },
    { id: 'stewabr01', name: 'Stewart, Brock', team: 'TOT', ip: 37.2 },
    { id: 'stewabr01', name: 'Stewart, Brock', team: 'MIN', ip: 34 },
    { id: 'stewabr01', name: 'Stewart, Brock', team: 'LAD', ip: 3.2 },
    { id: 'stockro01', name: 'Stock, Robert', team: 'BOS', ip: 2.2 },
    { id: 'strahma01', name: 'Strahm, Matt', team: 'PHI', ip: 62.1 },
    { id: 'stratch01', name: 'Stratton, Chris', team: 'TOT', ip: 21 },
    { id: 'stratch01', name: 'Stratton, Chris', team: 'KCR', ip: 17 },
    { id: 'stratch01', name: 'Stratton, Chris', team: 'LAD', ip: 4 },
    { id: 'strathu01', name: 'Stratton, Hunter', team: 'TOT', ip: 19 },
    { id: 'strathu01', name: 'Stratton, Hunter', team: 'PIT', ip: 2.2 },
    { id: 'strathu01', name: 'Stratton, Hunter', team: 'ATL', ip: 16.1 },
    { id: 'strichu01', name: 'Strickland, Hunter', team: 'LAA', ip: 22 },
    { id: 'stridsp01', name: 'Strider, Spencer', team: 'ATL', ip: 125.1 },
    { id: 'stromma01', name: 'Stroman, Marcus', team: 'NYY', ip: 39 },
    { id: 'strowka01', name: 'Strowd, Kade', team: 'BAL', ip: 26.1 },
    { id: 'suareal01', name: 'Suarez, Albert', team: 'BAL', ip: 11.2 },
    { id: 'suarejo01', name: 'Suarez, Jose', team: 'ATL', ip: 19.1 },
    { id: 'suarera01', name: 'Suarez, Ranger', team: 'PHI', ip: 157.1 },
    { id: 'suarero01', name: 'Suarez, Robert', team: 'SDP', ip: 69.2 },
    { id: 'suerowa01', name: 'Suero, Wander', team: 'ATL', ip: 6.1 },
    { id: 'suganto01', name: 'Sugano, Tomoyuki', team: 'BAL', ip: 157 },
    { id: 'sulseco01', name: 'Sulser, Cole', team: 'TBR', ip: 22.2 },
    { id: 'suterbr01', name: 'Suter, Brent', team: 'CIN', ip: 67.2 },
    { id: 'svansma01', name: 'Svanson, Matt', team: 'STL', ip: 60.1 },
    { id: 'swanser01', name: 'Swanson, Erik', team: 'TOR', ip: 5.1 },
    { id: 'taillja01', name: 'Taillon, Jameson', team: 'CHC', ip: 129.2 },
    { id: 'tarnofr01', name: 'Tarnok, Freddy', team: 'MIA', ip: 7.1 },
    { id: 'tatedi01', name: 'Tate, Dillon', team: 'TOR', ip: 6.1 },
    { id: 'taylogr02', name: 'Taylor, Grant', team: 'CHW', ip: 36.2 },
    { id: 'taylotr01', name: 'Taylor, Troy', team: 'SEA', ip: 6.2 },
    { id: 'tellero01', name: 'Tellez, Rowdy', team: 'TEX', ip: 2 },
    { id: 'tengka01', name: 'Teng, Kai-Wei', team: 'SFG', ip: 29.2 },
    { id: 'thielca01', name: 'Thielbar, Caleb', team: 'CHC', ip: 58 },
    { id: 'thomaco02', name: 'Thomas, Connor', team: 'MIL', ip: 5.1 },
    { id: 'thompma02', name: 'Thompson, Mason', team: 'WSN', ip: 10.2 },
    { id: 'thompry02', name: 'Thompson, Ryan', team: 'ARI', ip: 41.1 },
    { id: 'thompza01', name: 'Thompson, Zach', team: 'ATL', ip: 3.2 },
    { id: 'thorntr01', name: 'Thornton, Trent', team: 'SEA', ip: 42.1 },
    { id: 'tidwebl01', name: 'Tidwell, Blade', team: 'NYM', ip: 15 },
    { id: 'tinocje01', name: 'Tinoco, Jesus', team: 'MIA', ip: 19.1 },
    { id: 'tollepa01', name: 'Tolle, Payton', team: 'BOS', ip: 16.1 },
    { id: 'tongjo01', name: 'Tong, Jonah', team: 'NYM', ip: 18.2 },
    { id: 'tonkimi01', name: 'Tonkin, Michael', team: 'MIN', ip: 24 },
    { id: 'topaju01', name: 'Topa, Justin', team: 'MIN', ip: 60 },
    { id: 'toroab01', name: 'Toro, Abraham', team: 'BOS', ip: 1 },
    { id: 'torrelu01', name: 'Torrens, Luis', team: 'NYM', ip: 0.2 },
    { id: 'toussto01', name: 'Toussaint, Touki', team: 'LAA', ip: 2 },
    { id: 'treinbl01', name: 'Treinen, Blake', team: 'LAD', ip: 26.2 },
    { id: 'trejoal01', name: 'Trejo, Alan', team: 'COL', ip: 1 },
    { id: 'trevijo01', name: 'Trevino, Jose', team: 'CIN', ip: 2.1 },
    { id: 'triolja01', name: 'Triolo, Jared', team: 'PIT', ip: 1 },
    { id: 'trivilo01', name: 'Trivino, Lou', team: 'TOT', ip: 47.2 },
    { id: 'trivilo01', name: 'Trivino, Lou', team: 'SFG', ip: 12.1 },
    { id: 'trivilo01', name: 'Trivino, Lou', team: 'LAD', ip: 26.1 },
    { id: 'trivilo01', name: 'Trivino, Lou', team: 'PHI', ip: 9 },
    { id: 'turnbsp01', name: 'Turnbull, Spencer', team: 'TOR', ip: 6.1 },
    { id: 'ucetaed01', name: 'Uceta, Edwin', team: 'TBR', ip: 76 },
    { id: 'urenajo01', name: 'Urena, Jose', team: 'TOT', ip: 55 },
    { id: 'urenajo01', name: 'Urena, Jose', team: 'TOT', ip: 49 },
    { id: 'urenajo01', name: 'Urena, Jose', team: 'TOT', ip: 6 },
    { id: 'urenajo01', name: 'Urena, Jose', team: 'NYM', ip: 3 },
    { id: 'urenajo01', name: 'Urena, Jose', team: 'TOR', ip: 12.1 },
    { id: 'urenajo01', name: 'Urena, Jose', team: 'LAD', ip: 3 },
    { id: 'urenajo01', name: 'Urena, Jose', team: 'MIN', ip: 17.2 },
    { id: 'urenajo01', name: 'Urena, Jose', team: 'LAA', ip: 19 },
    { id: 'uribeab01', name: 'Uribe, Abner', team: 'MIL', ip: 75.1 },
    { id: 'urquijo01', name: 'Urquidy, Jose', team: 'DET', ip: 2.1 },
    { id: 'valdefr01', name: 'Valdez, Framber', team: 'HOU', ip: 192 },
    { id: 'vanwelo01', name: 'VanWey, Logan', team: 'HOU', ip: 10.2 },
    { id: 'vargaca01', name: 'Vargas, Carlos', team: 'SEA', ip: 77 },
    { id: 'varlalo01', name: 'Varland, Louis', team: 'TOT', ip: 72.2 },
    { id: 'varlalo01', name: 'Varland, Louis', team: 'MIN', ip: 49 },
    { id: 'varlalo01', name: 'Varland, Louis', team: 'TOR', ip: 23.2 },
    { id: 'vasilmi01', name: 'Vasil, Mike', team: 'CHW', ip: 101 },
    { id: 'vasqura02', name: 'Vasquez, Randy', team: 'SDP', ip: 133.2 },
    { id: 'vazqulu01', name: 'Vazquez, Luis', team: 'BAL', ip: 4.1 },
    { id: 'venezan01', name: 'Veneziano, Anthony', team: 'TOT', ip: 25 },
    { id: 'venezan01', name: 'Veneziano, Anthony', team: 'MIA', ip: 21 },
    { id: 'venezan01', name: 'Veneziano, Anthony', team: 'STL', ip: 4 },
    { id: 'verlaju01', name: 'Verlander, Justin', team: 'SFG', ip: 152 },
    { id: 'vesiaal01', name: 'Vesia, Alex', team: 'LAD', ip: 59.2 },
    { id: 'vestwi01', name: 'Vest, Will', team: 'DET', ip: 68.2 },
    { id: 'vodnivi01', name: 'Vodnik, Victor', team: 'COL', ip: 50.2 },
    { id: 'wachami01', name: 'Wacha, Michael', team: 'KCR', ip: 172.2 },
    { id: 'waddebr01', name: 'Waddell, Brandon', team: 'NYM', ip: 31.1 },
    { id: 'wadety01', name: 'Wade, Tyler', team: 'SDP', ip: 1 },
    { id: 'waldrhu01', name: 'Waldrep, Hurston', team: 'ATL', ip: 56.1 },
    { id: 'waldrma01', name: 'Waldron, Matt', team: 'SDP', ip: 4.2 },
    { id: 'walkejo03', name: 'Walker, Josh', team: 'TOR', ip: 5 },
    { id: 'walkery01', name: 'Walker, Ryan', team: 'SFG', ip: 61.1 },
    { id: 'walketa01', name: 'Walker, Taijuan', team: 'PHI', ip: 123.2 },
    { id: 'waltebr01', name: 'Walter, Brandon', team: 'HOU', ip: 53.2 },
    { id: 'waltean01', name: 'Walters, Andrew', team: 'CLE', ip: 1.1 },
    { id: 'warreau01', name: 'Warren, Austin', team: 'NYM', ip: 9.1 },
    { id: 'warrewi01', name: 'Warren, Will', team: 'NYY', ip: 162.1 },
    { id: 'weathry01', name: 'Weathers, Ryan', team: 'MIA', ip: 38.1 },
    { id: 'weavelu01', name: 'Weaver, Luke', team: 'NYY', ip: 64.2 },
    { id: 'webbja01', name: 'Webb, Jacob', team: 'TEX', ip: 66 },
    { id: 'webblo01', name: 'Webb, Logan', team: 'SFG', ip: 207 },
    { id: 'weemsjo01', name: 'Weems, Jordan', team: 'HOU', ip: 4.1 },
    { id: 'weissgr01', name: 'Weissert, Greg', team: 'BOS', ip: 67 },
    { id: 'wellsty01', name: 'Wells, Tyler', team: 'BAL', ip: 21.2 },
    { id: 'wentzjo01', name: 'Wentz, Joey', team: 'TOT', ip: 98 },
    { id: 'wentzjo01', name: 'Wentz, Joey', team: 'TOT', ip: 90 },
    { id: 'wentzjo01', name: 'Wentz, Joey', team: 'PIT', ip: 26 },
    { id: 'wentzjo01', name: 'Wentz, Joey', team: 'MIN', ip: 8 },
    { id: 'wentzjo01', name: 'Wentz, Joey', team: 'ATL', ip: 64 },
    { id: 'wesneha01', name: 'Wesneski, Hayden', team: 'HOU', ip: 32 },
    { id: 'wheelza01', name: 'Wheeler, Zack', team: 'PHI', ip: 149.2 },
    { id: 'whiseca01', name: 'Whisenhunt, Carson', team: 'SFG', ip: 23.1 },
    { id: 'whiteow01', name: 'White, Owen', team: 'CHW', ip: 7 },
    { id: 'whitlfo01', name: 'Whitley, Forrest', team: 'TOT', ip: 12 },
    { id: 'whitlfo01', name: 'Whitley, Forrest', team: 'HOU', ip: 7.1 },
    { id: 'whitlfo01', name: 'Whitley, Forrest', team: 'TBR', ip: 4.2 },
    { id: 'whitlga01', name: 'Whitlock, Garrett', team: 'BOS', ip: 72 },
    { id: 'wicksjo01', name: 'Wicks, Jordan', team: 'CHC', ip: 14.1 },
    { id: 'wilcoco01', name: 'Wilcox, Cole', team: 'TBR', ip: 1 },
    { id: 'wilesna01', name: 'Wiles, Nathan', team: 'ATL', ip: 1 },
    { id: 'willide03', name: 'Williams, Devin', team: 'NYY', ip: 62 },
    { id: 'williga01', name: 'Williams, Gavin', team: 'CLE', ip: 167.2 },
    { id: 'willilu01', name: 'Williams, Luke', team: 'ATL', ip: 6 },
    { id: 'willitr01', name: 'Williams, Trevor', team: 'WSN', ip: 82.2 },
    { id: 'wilsobr02', name: 'Wilson, Bryse', team: 'CHW', ip: 47.1 },
    { id: 'wilsoju10', name: 'Wilson, Justin', team: 'BOS', ip: 48.1 },
    { id: 'wilsost02', name: 'Wilson, Steven', team: 'CHW', ip: 55.1 },
    { id: 'wilsowe01', name: 'Wilson, Weston', team: 'PHI', ip: 3 },
    { id: 'wilsowi03', name: 'Wilson, Will', team: 'CLE', ip: 2 },
    { id: 'winanal01', name: 'Winans, Allan', team: 'NYY', ip: 9.1 },
    { id: 'winckjo01', name: 'Winckowski, Josh', team: 'BOS', ip: 11.2 },
    { id: 'winnco01', name: 'Winn, Cole', team: 'TEX', ip: 41.2 },
    { id: 'winnke01', name: 'Winn, Keaton', team: 'SFG', ip: 10 },
    { id: 'wolfrgr01', name: 'Wolfram, Grant', team: 'BAL', ip: 26.2 },
    { id: 'woobr01', name: 'Woo, Bryan', team: 'SEA', ip: 186.2 },
    { id: 'woodfja01', name: 'Woodford, Jake', team: 'ARI', ip: 36.1 },
    { id: 'woodrbr01', name: 'Woodruff, Brandon', team: 'MIL', ip: 64.2 },
    { id: 'wroblju01', name: 'Wrobleski, Justin', team: 'LAD', ip: 66.2 },
    { id: 'wynnera01', name: 'Wynne, Randy', team: 'CIN', ip: 3 },
    { id: 'yamamyo01', name: 'Yamamoto, Yoshinobu', team: 'LAD', ip: 173.2 },
    { id: 'yarbrry01', name: 'Yarbrough, Ryan', team: 'NYY', ip: 64 },
    { id: 'yastrmi01', name: 'Yastrzemski, Mike', team: 'SFG', ip: 1 },
    { id: 'yateski01', name: 'Yates, Kirby', team: 'LAD', ip: 41.1 },
    { id: 'yesavtr01', name: 'Yesavage, Trey', team: 'TOR', ip: 14 },
    { id: 'yohocr01', name: 'Yoho, Craig', team: 'MIL', ip: 8.2 },
    { id: 'youngbr01', name: 'Young, Brandon', team: 'BAL', ip: 57.2 },
    { id: 'youngda02', name: 'Young, Danny', team: 'NYM', ip: 8.1 },
    { id: 'youngja02', name: 'Young, Jared', team: 'NYM', ip: 0.1 },
    { id: 'zastrro01', name: 'Zastryzny, Rob', team: 'MIL', ip: 22 },
    { id: 'zeferry01', name: 'Zeferjahn, Ryan', team: 'LAA', ip: 57 },
    { id: 'zerpaan01', name: 'Zerpa, Angel', team: 'KCR', ip: 64.2 },
    { id: 'zimmebr02', name: 'Zimmermann, Bruce', team: 'MIL', ip: 6 },
    { id: 'zuberty01', name: 'Zuber, Tyler', team: 'TOT', ip: 12 },
    { id: 'zuberty01', name: 'Zuber, Tyler', team: 'NYM', ip: 2 },
    { id: 'zuberty01', name: 'Zuber, Tyler', team: 'MIA', ip: 10 },
    { id: 'zulueyo01', name: 'Zulueta, Yosver', team: 'CIN', ip: 7.1 },
];

export function convertToCsv() {
    const pitchersOnIndividualTeams: PitchersOnIndividualTeams[] = [];

    allPitchers.forEach(indTeam => {
        if (indTeam.team !== 'TOT' && multiTeamPitchers[indTeam.id]) {
            const nameParts = multiTeamPitchers[indTeam.id].name.split(', ');
            pitchersOnIndividualTeams.push({
                year: 2025,
                name: nameParts[0] + ',' + nameParts[1][0],
                throws: multiTeamPitchers[indTeam.id].throws,
                team: indTeam.team,
                ip: indTeam.ip.toString().replace('.1', '.33').replace('.2', '.67'),
            });
        }
    });

    return pitchersOnIndividualTeams;
}
