type MultiTeamPitchers = {
    name: string;
    team: string;
    throws: string;
    ip: number;
};

type AllPitchers = {
    id: string;
    name: string;
    team: string;
    ip: number;
};

type PitchersOnIndividualTeams = {
    year: number;
    name: string;
    throws: string;
    team: string;
    ip: string;
};

const multiTeamPitchers: Record<string, MultiTeamPitchers> = {
    // paste here the formatted column from the 'Carded' sheet of the 'Pitcher_Stats_20xx.xlsx' file... only the pitchers whose team is 'TOT'
    adamja01: { name: 'Adam, Jason', team: 'TOT', throws: 'R', ip: 73.2 },
    armstsh01: { name: 'Armstrong, Shawn', team: 'TOT', throws: 'R', ip: 66.2 },
    avilape01: { name: 'Avila, Pedro', team: 'TOT', throws: 'R', ip: 82.2 },
    banksta01: { name: 'Banks, Tanner', team: 'TOT', throws: 'L', ip: 72.1 },
    baumami01: { name: 'Baumann, Mike', team: 'TOT', throws: 'R', ip: 58.1 },
    beeksja02: { name: 'Beeks, Jalen', team: 'TOT', throws: 'L', ip: 70 },
    blackpa01: { name: 'Blackburn, Paul', team: 'TOT', throws: 'R', ip: 75.1 },
    brazohu01: { name: 'Brazoban, Huascar', team: 'TOT', throws: 'R', ip: 51.2 },
    brebbjo01: { name: 'Brebbia, John', team: 'TOT', throws: 'R', ip: 55.1 },
    burkebr01: { name: 'Burke, Brock', team: 'TOT', throws: 'L', ip: 34 },
    chafian01: { name: 'Chafin, Andrew', team: 'TOT', throws: 'L', ip: 56.1 },
    chargjt01: { name: 'Chargois, JT', team: 'TOT', throws: 'R', ip: 36.1 },
    civalaa01: { name: 'Civale, Aaron', team: 'TOT', throws: 'R', ip: 161 },
    contrro01: { name: 'Contreras, Roansy', team: 'TOT', throws: 'R', ip: 68.1 },
    delosen01: { name: 'De Los Santos, Enyel', team: 'TOT', throws: 'R', ip: 64 },
    dominse01: { name: 'Dominguez, Seranthony', team: 'TOT', throws: 'R', ip: 58.2 },
    eflinza01: { name: 'Eflin, Zach', team: 'TOT', throws: 'R', ip: 165.1 },
    erceglu01: { name: 'Erceg, Lucas', team: 'TOT', throws: 'R', ip: 61.2 },
    estevca01: { name: 'Estevez, Carlos', team: 'TOT', throws: 'R', ip: 55 },
    feddeer01: { name: 'Fedde, Erick', team: 'TOT', throws: 'R', ip: 177.1 },
    ferguca01: { name: 'Ferguson, Caleb', team: 'TOT', throws: 'L', ip: 54.1 },
    flaheja01: { name: 'Flaherty, Jack', team: 'TOT', throws: 'R', ip: 162 },
    florody01: { name: 'Floro, Dylan', team: 'TOT', throws: 'R', ip: 68.2 },
    garcilu03: { name: 'Garcia, Luis', team: 'TOT', throws: 'R', ip: 59 },
    garciyi01: { name: 'Garcia, Yimi', team: 'TOT', throws: 'R', ip: 39 },
    harvehu01: { name: 'Harvey, Hunter', team: 'TOT', throws: 'R', ip: 50.2 },
    hillti01: { name: 'Hill, Tim', team: 'TOT', throws: 'L', ip: 67 },
    hoeinbr01: { name: 'Hoeing, Bryan', team: 'TOT', throws: 'R', ip: 53.2 },
    irvinco01: { name: 'Irvin, Cole', team: 'TOT', throws: 'L', ip: 111 },
    jackslu01: { name: 'Jackson, Luke', team: 'TOT', throws: 'R', ip: 53 },
    junisja01: { name: 'Junis, Jakob', team: 'TOT', throws: 'R', ip: 67 },
    kikucyu01: { name: 'Kikuchi, Yusei', team: 'TOT', throws: 'L', ip: 175.2 },
    kopecmi01: { name: 'Kopech, Michael', team: 'TOT', throws: 'R', ip: 67.2 },
    leitema02: { name: 'Leiter Jr, Mark', team: 'TOT', throws: 'R', ip: 58 },
    lopezjo02: { name: 'Lopez, Jorge', team: 'TOT', throws: 'R', ip: 53 },
    lorenmi01: { name: 'Lorenzen, Michael', team: 'TOT', throws: 'R', ip: 130.1 },
    lovelri01: { name: 'Lovelady, Richard', team: 'TOT', throws: 'L', ip: 34.1 },
    matonph01: { name: 'Maton, Phil', team: 'TOT', throws: 'R', ip: 64 },
    mayzati01: { name: 'Mayza, Tim', team: 'TOT', throws: 'L', ip: 42.2 },
    mearsni01: { name: 'Mears, Nick', team: 'TOT', throws: 'R', ip: 57.2 },
    millety01: { name: 'Miller, Tyson', team: 'TOT', throws: 'R', ip: 62 },
    montafr02: { name: 'Montas, Frankie', team: 'TOT', throws: 'R', ip: 150.2 },
    nerishe01: { name: 'Neris, Hector', team: 'TOT', throws: 'R', ip: 59.1 },
    paxtoja01: { name: 'Paxton, James', team: 'TOT', throws: 'L', ip: 100.1 },
    pearsna01: { name: 'Pearson, Nate', team: 'TOT', throws: 'R', ip: 66.1 },
    perezma02: { name: 'Perez, Martin', team: 'TOT', throws: 'L', ip: 135 },
    pukaj01: { name: 'Puk, AJ', team: 'TOT', throws: 'L', ip: 71.1 },
    ramiryo01: { name: 'Ramirez, Yohan', team: 'TOT', throws: 'R', ip: 45 },
    richatr01: { name: 'Richards, Trevor', team: 'TOT', throws: 'R', ip: 65.1 },
    rogertr01: { name: 'Rogers, Trevor', team: 'TOT', throws: 'L', ip: 124.1 },
    santade01: { name: 'Santana, Dennis', team: 'TOT', throws: 'R', ip: 71.2 },
    scottta01: { name: 'Scott, Tanner', team: 'TOT', throws: 'L', ip: 72 },
    simslu01: { name: 'Sims, Lucas', team: 'TOT', throws: 'R', ip: 49.1 },
    smithbu03: { name: 'Smith, Burch', team: 'TOT', throws: 'R', ip: 56.1 },
    sotogr01: { name: 'Soto, Gregory', team: 'TOT', throws: 'L', ip: 53 },
    stanery01: { name: 'Stanek, Ryne', team: 'TOT', throws: 'R', ip: 55.1 },
    tatedi01: { name: 'Tate, Dillon', team: 'TOT', throws: 'R', ip: 36.2 },
    tinocje01: { name: 'Tinoco, Jesus', team: 'TOT', throws: 'R', ip: 40.2 },
    tonkimi01: { name: 'Tonkin, Michael', team: 'TOT', throws: 'R', ip: 79.1 },
    wentzjo01: { name: 'Wentz, Joey', team: 'TOT', throws: 'L', ip: 67.1 },
    yarbrry01: { name: 'Yarbrough, Ryan', team: 'TOT', throws: 'L', ip: 98.2 },

};

const allPitchers: AllPitchers[] = [
    // paste here the formatted column from the 'Original_with_Ind_Teams' sheet of the 'Pitcher_Stats_20xx.xlsx' file... including all pitchers
    { id: 'gilbelo01', name: 'Logan Gilbert', team: 'SEA', ip: 208.2 },
    { id: 'lugose01', name: 'Seth Lugo', team: 'KCR', ip: 206.2 },
    { id: 'webblo01', name: 'Logan Webb', team: 'SFG', ip: 204.2 },
    { id: 'wheelza01', name: 'Zack Wheeler', team: 'PHI', ip: 200 },
    { id: 'nolaaa01', name: 'Aaron Nola', team: 'PHI', ip: 199.1 },
    { id: 'burneco01', name: 'Corbin Burnes', team: 'BAL', ip: 194.1 },
    { id: 'berrijo01', name: 'José Berríos', team: 'TOR', ip: 192.1 },
    { id: 'skubata01', name: 'Tarik Skubal*', team: 'DET', ip: 192 },
    { id: 'kirbyge01', name: 'George Kirby', team: 'SEA', ip: 191 },
    { id: 'ceasedy01', name: 'Dylan Cease', team: 'SDP', ip: 189.1 },
    { id: 'irvinja01', name: 'Jake Irvin', team: 'WSN', ip: 187.2 },
    { id: 'raganco01', name: 'Cole Ragans*', team: 'KCR', ip: 186.1 },
    { id: 'lopezpa01', name: 'Pablo López', team: 'MIN', ip: 185.1 },
    { id: 'crawfku01', name: 'Kutter Crawford', team: 'BOS', ip: 183.2 },
    { id: 'severlu01', name: 'Luis Severino', team: 'NYM', ip: 182 },
    { id: 'manaese01', name: 'Sean Manaea*', team: 'NYM', ip: 181.2 },
    { id: 'pfaadbr01', name: 'Brandon Pfaadt', team: 'ARI', ip: 181.2 },
    { id: 'sanchcr01', name: 'Cristopher Sánchez*', team: 'PHI', ip: 181.2 },
    { id: 'gausmke01', name: 'Kevin Gausman', team: 'TOR', ip: 181 },
    { id: 'searsjp01', name: 'JP Sears*', team: 'OAK', ip: 180.2 },
    { id: 'millebr04', name: 'Bryce Miller', team: 'SEA', ip: 180.1 },
    { id: 'singebr01', name: 'Brady Singer', team: 'KCR', ip: 179.2 },
    { id: 'anderty01', name: 'Tyler Anderson*', team: 'LAA', ip: 179.1 },
    { id: 'houckta01', name: 'Tanner Houck', team: 'BOS', ip: 178.2 },
    { id: 'oberba01', name: 'Bailey Ober', team: 'MIN', ip: 178.2 },
    { id: 'kellemi03', name: 'Mitch Keller', team: 'PIT', ip: 178 },
    { id: 'salech01', name: 'Chris Sale*', team: 'ATL', ip: 177.2 },
    { id: 'feddeer01', name: 'Erick Fedde', team: 'TOT', ip: 177.1 },
    { id: 'feddeer01', name: 'Erick Fedde', team: 'CHW', ip: 121.2 },
    { id: 'feddeer01', name: 'Erick Fedde', team: 'STL', ip: 55.2 },
    { id: 'valdefr01', name: 'Framber Valdez*', team: 'HOU', ip: 176.1 },
    { id: 'kikucyu01', name: 'Yusei Kikuchi*', team: 'TOT', ip: 175.2 },
    { id: 'kikucyu01', name: 'Yusei Kikuchi*', team: 'TOR', ip: 115.2 },
    { id: 'kikucyu01', name: 'Yusei Kikuchi*', team: 'HOU', ip: 60 },
    { id: 'castilu02', name: 'Luis Castillo', team: 'SEA', ip: 175.1 },
    { id: 'rodonca01', name: 'Carlos Rodón*', team: 'NYY', ip: 175 },
    { id: 'corbipa01', name: 'Patrick Corbin*', team: 'WSN', ip: 174.2 },
    { id: 'cortene01', name: 'Nestor Cortes*', team: 'NYY', ip: 174.1 },
    { id: 'friedma01', name: 'Max Fried*', team: 'ATL', ip: 174.1 },
    { id: 'bibeeta01', name: 'Tanner Bibee', team: 'CLE', ip: 173.2 },
    { id: 'kingmi01', name: 'Michael King', team: 'SDP', ip: 173.2 },
    { id: 'peralfr01', name: 'Freddy Peralta', team: 'MIL', ip: 173.2 },
    { id: 'imanash01', name: 'Shota Imanaga*', team: 'CHC', ip: 173.1 },
    { id: 'cannigr01', name: 'Griffin Canning', team: 'LAA', ip: 171.2 },
    { id: 'mikolmi01', name: 'Miles Mikolas', team: 'STL', ip: 171.2 },
    { id: 'bassich01', name: 'Chris Bassitt', team: 'TOR', ip: 171 },
    { id: 'eovalna01', name: 'Nathan Eovaldi', team: 'TEX', ip: 170.2 },
    { id: 'quintjo01', name: 'Jose Quintana*', team: 'NYM', ip: 170.1 },
    { id: 'brownhu01', name: 'Hunter Brown', team: 'HOU', ip: 170 },
    { id: 'gibsoky01', name: 'Kyle Gibson', team: 'STL', ip: 169.2 },
    { id: 'reaco01', name: 'Colin Rea', team: 'MIL', ip: 167.2 },
    { id: 'blancro01', name: 'Ronel Blanco', team: 'HOU', ip: 167.1 },
    { id: 'wachami01', name: 'Michael Wacha', team: 'KCR', ip: 166.2 },
    { id: 'gorema01', name: 'MacKenzie Gore*', team: 'WSN', ip: 166.1 },
    { id: 'grayso01', name: 'Sonny Gray', team: 'STL', ip: 166.1 },
    { id: 'mortoch02', name: 'Charlie Morton', team: 'ATL', ip: 165.1 },
    { id: 'taillja01', name: 'Jameson Taillon', team: 'CHC', ip: 165.1 },
    { id: 'eflinza01', name: 'Zach Eflin', team: 'TOT', ip: 165.1 },
    { id: 'eflinza01', name: 'Zach Eflin', team: 'TBR', ip: 110 },
    { id: 'eflinza01', name: 'Zach Eflin', team: 'BAL', ip: 55.1 },
    { id: 'gombeau01', name: 'Austin Gomber*', team: 'COL', ip: 165 },
    { id: 'bellobr01', name: 'Brayan Bello', team: 'BOS', ip: 162.1 },
    { id: 'feltnry01', name: 'Ryan Feltner', team: 'COL', ip: 162.1 },
    { id: 'flaheja01', name: 'Jack Flaherty', team: 'TOT', ip: 162 },
    { id: 'flaheja01', name: 'Jack Flaherty', team: 'DET', ip: 106.2 },
    { id: 'flaheja01', name: 'Jack Flaherty', team: 'LAD', ip: 55.1 },
    { id: 'civalaa01', name: 'Aaron Civale', team: 'TOT', ip: 161 },
    { id: 'civalaa01', name: 'Aaron Civale', team: 'TBR', ip: 87 },
    { id: 'civalaa01', name: 'Aaron Civale', team: 'MIL', ip: 74 },
    { id: 'flexech01', name: 'Chris Flexen', team: 'CHW', ip: 160 },
    { id: 'heanean01', name: 'Andrew Heaney*', team: 'TEX', ip: 160 },
    { id: 'litteza01', name: 'Zack Littell', team: 'TBR', ip: 156.1 },
    { id: 'stromma01', name: 'Marcus Stroman', team: 'NYY', ip: 154.2 },
    { id: 'gillu01', name: 'Luis Gil', team: 'NYY', ip: 151.2 },
    { id: 'spencmi01', name: 'Mitch Spence', team: 'OAK', ip: 151.1 },
    { id: 'livelbe01', name: 'Ben Lively', team: 'CLE', ip: 151 },
    { id: 'parkemi01', name: 'Mitchell Parker*', team: 'WSN', ip: 151 },
    { id: 'nelsory01', name: 'Ryne Nelson', team: 'ARI', ip: 150.2 },
    { id: 'suarera01', name: 'Ranger Suárez*', team: 'PHI', ip: 150.2 },
    { id: 'montafr02', name: 'Frankie Montas', team: 'TOT', ip: 150.2 },
    { id: 'montafr02', name: 'Frankie Montas', team: 'CIN', ip: 93.1 },
    { id: 'montafr02', name: 'Frankie Montas', team: 'MIL', ip: 57.1 },
    { id: 'greenhu01', name: 'Hunter Greene', team: 'CIN', ip: 150.1 },
    { id: 'quantca01', name: 'Cal Quantrill', team: 'COL', ip: 148.1 },
    { id: 'galleza01', name: 'Zac Gallen', team: 'ARI', ip: 148 },
    { id: 'assadja01', name: 'Javier Assad', team: 'CHC', ip: 147 },
    { id: 'waldrma01', name: 'Matt Waldron', team: 'SDP', ip: 146.2 },
    { id: 'crochga01', name: 'Garrett Crochet*', team: 'CHW', ip: 146 },
    { id: 'pivetni01', name: 'Nick Pivetta', team: 'BOS', ip: 145.2 },
    { id: 'arrigsp01', name: 'Spencer Arrighetti', team: 'HOU', ip: 145 },
    { id: 'falteba01', name: 'Bailey Falter*', team: 'PIT', ip: 142.1 },
    { id: 'martini01', name: 'Nick Martinez', team: 'CIN', ip: 142.1 },
    { id: 'stonega01', name: 'Gavin Stone', team: 'LAD', ip: 140.1 },
    { id: 'abbotan01', name: 'Andrew Abbott*', team: 'CIN', ip: 138 },
    { id: 'bradlta01', name: 'Taj Bradley', team: 'TBR', ip: 138 },
    { id: 'myersto01', name: 'Tobias Myers', team: 'MIL', ip: 138 },
    { id: 'lopezre01', name: 'Reynaldo López', team: 'ATL', ip: 135.2 },
    { id: 'ortizlu03', name: 'Luis Ortiz', team: 'PIT', ip: 135.2 },
    { id: 'ryanjo04', name: 'Joe Ryan', team: 'MIN', ip: 135 },
    { id: 'perezma02', name: 'Martín Pérez*', team: 'TOT', ip: 135 },
    { id: 'perezma02', name: 'Martín Pérez*', team: 'PIT', ip: 83 },
    { id: 'perezma02', name: 'Martín Pérez*', team: 'SDP', ip: 52 },
    { id: 'steelju01', name: 'Justin Steele*', team: 'CHC', ip: 134.2 },
    { id: 'glasnty01', name: 'Tyler Glasnow', team: 'LAD', ip: 134 },
    { id: 'suareal01', name: 'Albert Suárez', team: 'BAL', ip: 133.2 },
    { id: 'woodssi01', name: 'Simeon Woods Richardson', team: 'MIN', ip: 133.2 },
    { id: 'skenepa01', name: 'Paul Skenes', team: 'PIT', ip: 133 },
    { id: 'hendrky01', name: 'Kyle Hendricks', team: 'CHC', ip: 130.2 },
    { id: 'lorenmi01', name: 'Michael Lorenzen', team: 'TOT', ip: 130.1 },
    { id: 'lorenmi01', name: 'Michael Lorenzen', team: 'TEX', ip: 101.2 },
    { id: 'lorenmi01', name: 'Michael Lorenzen', team: 'KCR', ip: 28.2 },
    { id: 'pepiory01', name: 'Ryan Pepiot', team: 'TBR', ip: 130 },
    { id: 'kremede01', name: 'Dean Kremer', team: 'BAL', ip: 129.2 },
    { id: 'marshal01', name: 'Alec Marsh', team: 'KCR', ip: 129 },
    { id: 'estesjo01', name: 'Joey Estes', team: 'OAK', ip: 127.2 },
    { id: 'cannojo02', name: 'Jonathan Cannon', team: 'CHW', ip: 124.1 },
    { id: 'harriky01', name: 'Kyle Harrison*', team: 'SFG', ip: 124.1 },
    { id: 'rogertr01', name: 'Trevor Rogers*', team: 'TOT', ip: 124.1 },
    { id: 'rogertr01', name: 'Trevor Rogers*', team: 'MIA', ip: 105.1 },
    { id: 'rogertr01', name: 'Trevor Rogers*', team: 'BAL', ip: 19 },
    { id: 'schwesp01', name: 'Spencer Schwellenbach', team: 'ATL', ip: 123.2 },
    { id: 'jonesja09', name: 'Jared Jones', team: 'PIT', ip: 121.2 },
    { id: 'pallaan01', name: 'Andre Pallante', team: 'STL', ip: 121.1 },
    { id: 'woobr01', name: 'Bryan Woo', team: 'SEA', ip: 121.1 },
    { id: 'peterda01', name: 'David Peterson*', team: 'NYM', ip: 121 },
    { id: 'lynnla01', name: 'Lance Lynn', team: 'STL', ip: 117.1 },
    { id: 'montgjo01', name: 'Jordan Montgomery*', team: 'ARI', ip: 117 },
    { id: 'rodrigr01', name: 'Grayson Rodriguez', team: 'BAL', ip: 116.2 },
    { id: 'lodolni01', name: 'Nick Lodolo*', team: 'CIN', ip: 115.1 },
    { id: 'freelky01', name: 'Kyle Freeland*', team: 'COL', ip: 113.1 },
    { id: 'soriajo02', name: 'José Soriano', team: 'LAA', ip: 113 },
    { id: 'maedake01', name: 'Kenta Maeda', team: 'DET', ip: 112.1 },
    { id: 'olsonre01', name: 'Reese Olson', team: 'DET', ip: 112.1 },
    { id: 'irvinco01', name: 'Cole Irvin*', team: 'TOT', ip: 111 },
    { id: 'irvinco01', name: 'Cole Irvin*', team: 'BAL', ip: 107.1 },
    { id: 'irvinco01', name: 'Cole Irvin*', team: 'MIN', ip: 3.2 },
    { id: 'hicksjo03', name: 'Jordan Hicks', team: 'SFG', ip: 109.2 },
    { id: 'urenajo01', name: 'José Ureña', team: 'TEX', ip: 109 },
    { id: 'alexaty01', name: 'Tyler Alexander*', team: 'TBR', ip: 107.2 },
    { id: 'wilsobr02', name: 'Bryse Wilson', team: 'MIL', ip: 104.2 },
    { id: 'snellbl01', name: 'Blake Snell*', team: 'SFG', ip: 104 },
    { id: 'carraca01', name: 'Carlos Carrasco', team: 'CLE', ip: 103.2 },
    { id: 'francbo01', name: 'Bowden Francis', team: 'TOR', ip: 103.2 },
    { id: 'grayjo02', name: 'Jon Gray', team: 'TEX', ip: 102.2 },
    { id: 'mizeca01', name: 'Casey Mize', team: 'DET', ip: 102.1 },
    { id: 'paxtoja01', name: 'James Paxton*', team: 'TOT', ip: 100.1 },
    { id: 'paxtoja01', name: 'James Paxton*', team: 'LAD', ip: 89.1 },
    { id: 'paxtoja01', name: 'James Paxton*', team: 'BOS', ip: 11 },
    { id: 'musgrjo01', name: 'Joe Musgrove', team: 'SDP', ip: 99.2 },
    { id: 'criswco01', name: 'Cooper Criswell', team: 'BOS', ip: 99.1 },
    { id: 'yarbrry01', name: 'Ryan Yarbrough*', team: 'TOT', ip: 98.2 },
    { id: 'yarbrry01', name: 'Ryan Yarbrough*', team: 'LAD', ip: 67.1 },
    { id: 'yarbrry01', name: 'Ryan Yarbrough*', team: 'TOR', ip: 31.1 },
    { id: 'monteke01', name: 'Keider Montero', team: 'DET', ip: 98.1 },
    { id: 'vasqura02', name: 'Randy Vásquez', team: 'SDP', ip: 98 },
    { id: 'allenlo02', name: 'Logan Allen*', team: 'CLE', ip: 97.1 },
    { id: 'cabreed02', name: 'Edward Cabrera', team: 'MIA', ip: 96.1 },
    { id: 'colege01', name: 'Gerrit Cole', team: 'NYY', ip: 95 },
    { id: 'dunnida01', name: 'Dane Dunning', team: 'TEX', ip: 95 },
    { id: 'holtoty01', name: 'Tyler Holton*', team: 'DET', ip: 94.1 },
    { id: 'spierca01', name: 'Carson Spiers', team: 'CIN', ip: 90.2 },
    { id: 'verlaju01', name: 'Justin Verlander', team: 'HOU', ip: 90.1 },
    { id: 'lawde01', name: 'Derek Law', team: 'WSN', ip: 90 },
    { id: 'yamamyo01', name: 'Yoshinobu Yamamoto', team: 'LAD', ip: 90 },
    { id: 'hudsoda02', name: 'Dakota Hudson', team: 'COL', ip: 89 },
    { id: 'herzdj01', name: 'DJ Herz*', team: 'WSN', ip: 88.2 },
    { id: 'paddach01', name: 'Chris Paddack', team: 'MIN', ip: 88.1 },
    { id: 'detmere01', name: 'Reid Detmers*', team: 'LAA', ip: 87.1 },
    { id: 'fulmeca01', name: 'Carson Fulmer', team: 'LAA', ip: 86.2 },
    { id: 'rodriya01', name: 'Yariel Rodríguez', team: 'TOR', ip: 86.2 },
    { id: 'weathry01', name: 'Ryan Weathers*', team: 'MIA', ip: 86.2 },
    { id: 'liberma01', name: 'Matthew Liberatore*', team: 'STL', ip: 86 },
    { id: 'schmicl01', name: 'Clarke Schmidt', team: 'NYY', ip: 85.1 },
    { id: 'stripro01', name: 'Ross Stripling', team: 'OAK', ip: 85.1 },
    { id: 'weavelu01', name: 'Luke Weaver', team: 'NYY', ip: 84 },
    { id: 'walketa01', name: 'Taijuan Walker', team: 'PHI', ip: 83.2 },
    { id: 'munozro01', name: 'Roddery Muñoz', team: 'MIA', ip: 82.2 },
    { id: 'avilape01', name: 'Pedro Avila', team: 'TOT', ip: 82.2 },
    { id: 'avilape01', name: 'Pedro Avila', team: 'SDP', ip: 8 },
    { id: 'avilape01', name: 'Pedro Avila', team: 'CLE', ip: 74.2 },
    { id: 'darviyu01', name: 'Yu Darvish', team: 'SDP', ip: 81.2 },
    { id: 'hjellse01', name: 'Sean Hjelle', team: 'SFG', ip: 80.2 },
    { id: 'walkery01', name: 'Ryan Walker', team: 'SFG', ip: 80 },
    { id: 'povicca01', name: 'Cade Povich*', team: 'BAL', ip: 79.2 },
    { id: 'sandopa02', name: 'Patrick Sandoval*', team: 'LAA', ip: 79.2 },
    { id: 'sorokmi01', name: 'Michael Soroka', team: 'CHW', ip: 79.2 },
    { id: 'bazsh01', name: 'Shane Baz', team: 'TBR', ip: 79.1 },
    { id: 'tonkimi01', name: 'Michael Tonkin', team: 'TOT', ip: 79.1 },
    { id: 'tonkimi01', name: 'Michael Tonkin', team: 'TOT', ip: 72.1 },
    { id: 'tonkimi01', name: 'Michael Tonkin', team: 'NYM', ip: 7 },
    { id: 'tonkimi01', name: 'Michael Tonkin', team: 'MIN', ip: 16.1 },
    { id: 'tonkimi01', name: 'Michael Tonkin', team: 'NYY', ip: 56 },
    { id: 'akinke01', name: 'Keegan Akin*', team: 'BAL', ip: 78.2 },
    { id: 'abreubr01', name: 'Bryan Abreu', team: 'HOU', ip: 78.1 },
    { id: 'megilty01', name: 'Tylor Megill', team: 'NYM', ip: 78 },
    { id: 'ashcrgr01', name: 'Graham Ashcraft', team: 'CIN', ip: 77.1 },
    { id: 'ceccosl01', name: 'Slade Cecconi', team: 'ARI', ip: 77 },
    { id: 'bradfco01', name: 'Cody Bradford*', team: 'TEX', ip: 76.1 },
    { id: 'williga01', name: 'Gavin Williams', team: 'CLE', ip: 76 },
    { id: 'winckjo01', name: 'Josh Winckowski', team: 'BOS', ip: 76 },
    { id: 'mckentr01', name: 'Triston McKenzie', team: 'CLE', ip: 75.2 },
    { id: 'buehlwa01', name: 'Walker Buehler', team: 'LAD', ip: 75.1 },
    { id: 'smithca06', name: 'Cade Smith', team: 'CLE', ip: 75.1 },
    { id: 'blackpa01', name: 'Paul Blackburn', team: 'TOT', ip: 75.1 },
    { id: 'blackpa01', name: 'Paul Blackburn', team: 'OAK', ip: 51 },
    { id: 'blackpa01', name: 'Paul Blackburn', team: 'NYM', ip: 24.1 },
    { id: 'gaddihu01', name: 'Hunter Gaddis', team: 'CLE', ip: 74.2 },
    { id: 'claseem01', name: 'Emmanuel Clase', team: 'CLE', ip: 74.1 },
    { id: 'buttojo01', name: 'José Buttó', team: 'NYM', ip: 74 },
    { id: 'rossjo01', name: 'Joe Ross', team: 'MIL', ip: 74 },
    { id: 'kellyme01', name: 'Merrill Kelly', team: 'ARI', ip: 73.2 },
    { id: 'vodnivi01', name: 'Victor Vodnik', team: 'COL', ip: 73.2 },
    { id: 'adamja01', name: 'Jason Adam', team: 'TOT', ip: 73.2 },
    { id: 'adamja01', name: 'Jason Adam', team: 'TBR', ip: 47 },
    { id: 'adamja01', name: 'Jason Adam', team: 'SDP', ip: 26.2 },
    { id: 'shustja01', name: 'Jared Shuster*', team: 'CHW', ip: 73.1 },
    { id: 'strichu01', name: 'Hunter Strickland', team: 'LAA', ip: 73.1 },
    { id: 'martiju01', name: 'Justin Martínez', team: 'ARI', ip: 72.2 },
    { id: 'harriho03', name: 'Hogan Harris*', team: 'OAK', ip: 72.1 },
    { id: 'thorntr01', name: 'Trent Thornton', team: 'SEA', ip: 72.1 },
    { id: 'banksta01', name: 'Tanner Banks*', team: 'TOT', ip: 72.1 },
    { id: 'banksta01', name: 'Tanner Banks*', team: 'CHW', ip: 48 },
    { id: 'banksta01', name: 'Tanner Banks*', team: 'PHI', ip: 24.1 },
    { id: 'birdsha01', name: 'Hayden Birdsong', team: 'SFG', ip: 72 },
    { id: 'roberda08', name: 'David Robertson', team: 'TEX', ip: 72 },
    { id: 'scottta01', name: 'Tanner Scott*', team: 'TOT', ip: 72 },
    { id: 'scottta01', name: 'Tanner Scott*', team: 'MIA', ip: 45.2 },
    { id: 'scottta01', name: 'Tanner Scott*', team: 'SDP', ip: 26.1 },
    { id: 'santade01', name: 'Dennis Santana', team: 'TOT', ip: 71.2 },
    { id: 'santade01', name: 'Dennis Santana', team: 'NYY', ip: 27.1 },
    { id: 'santade01', name: 'Dennis Santana', team: 'PIT', ip: 44.1 },
    { id: 'blachty01', name: 'Ty Blach*', team: 'COL', ip: 71.1 },
    { id: 'sandsco01', name: 'Cole Sands', team: 'MIN', ip: 71.1 },
    { id: 'pukaj01', name: 'A.J. Puk*', team: 'TOT', ip: 71.1 },
    { id: 'pukaj01', name: 'A.J. Puk*', team: 'MIA', ip: 44 },
    { id: 'pukaj01', name: 'A.J. Puk*', team: 'ARI', ip: 27.1 },
    { id: 'farmebu01', name: 'Buck Farmer', team: 'CIN', ip: 71 },
    { id: 'haderjo01', name: 'Josh Hader*', team: 'HOU', ip: 71 },
    { id: 'jaxgr01', name: 'Griffin Jax', team: 'MIN', ip: 71 },
    { id: 'kellyke02', name: 'Kevin Kelly', team: 'TBR', ip: 70.2 },
    { id: 'kittran01', name: 'Andrew Kittredge', team: 'STL', ip: 70.2 },
    { id: 'cronide01', name: 'Declan Cronin', team: 'MIA', ip: 70.1 },
    { id: 'rogerty01', name: 'Tyler Rogers', team: 'SFG', ip: 70.1 },
    { id: 'vestwi01', name: 'Will Vest', team: 'DET', ip: 70.1 },
    { id: 'ginkeke01', name: 'Kevin Ginkel', team: 'ARI', ip: 70 },
    { id: 'beeksja02', name: 'Jalen Beeks*', team: 'TOT', ip: 70 },
    { id: 'beeksja02', name: 'Jalen Beeks*', team: 'COL', ip: 49.1 },
    { id: 'beeksja02', name: 'Jalen Beeks*', team: 'PIT', ip: 20.2 },
    { id: 'housead01', name: 'Adrian Houser', team: 'NYM', ip: 69.1 },
    { id: 'iglesra01', name: 'Raisel Iglesias', team: 'ATL', ip: 69.1 },
    { id: 'knackla01', name: 'Landon Knack', team: 'LAD', ip: 69 },
    { id: 'bellova01', name: 'Valente Bellozo', team: 'MIA', ip: 68.2 },
    { id: 'jimenjo02', name: 'Joe Jiménez', team: 'ATL', ip: 68.2 },
    { id: 'scottta02', name: 'Tayler Scott', team: 'HOU', ip: 68.2 },
    { id: 'florody01', name: 'Dylan Floro', team: 'TOT', ip: 68.2 },
    { id: 'florody01', name: 'Dylan Floro', team: 'WSN', ip: 52.1 },
    { id: 'florody01', name: 'Dylan Floro', team: 'ARI', ip: 16.1 },
    { id: 'holmegr01', name: 'Grant Holmes', team: 'ATL', ip: 68.1 },
    { id: 'contrro01', name: 'Roansy Contreras', team: 'TOT', ip: 68.1 },
    { id: 'contrro01', name: 'Roansy Contreras', team: 'PIT', ip: 16.1 },
    { id: 'contrro01', name: 'Roansy Contreras', team: 'LAA', ip: 52 },
    { id: 'briesbe01', name: 'Beau Brieske', team: 'DET', ip: 67.2 },
    { id: 'wesneha01', name: 'Hayden Wesneski', team: 'CHC', ip: 67.2 },
    { id: 'kopecmi01', name: 'Michael Kopech', team: 'TOT', ip: 67.2 },
    { id: 'kopecmi01', name: 'Michael Kopech', team: 'CHW', ip: 43.2 },
    { id: 'kopecmi01', name: 'Michael Kopech', team: 'LAD', ip: 24 },
    { id: 'milleer01', name: 'Erik Miller*', team: 'SFG', ip: 67.1 },
    { id: 'wentzjo01', name: 'Joey Wentz*', team: 'TOT', ip: 67.1 },
    { id: 'wentzjo01', name: 'Joey Wentz*', team: 'DET', ip: 55.1 },
    { id: 'wentzjo01', name: 'Joey Wentz*', team: 'PIT', ip: 12 },
    { id: 'hillti01', name: 'Tim Hill*', team: 'TOT', ip: 67 },
    { id: 'hillti01', name: 'Tim Hill*', team: 'CHW', ip: 23 },
    { id: 'hillti01', name: 'Tim Hill*', team: 'NYY', ip: 44 },
    { id: 'junisja01', name: 'Jakob Junis', team: 'TOT', ip: 67 },
    { id: 'junisja01', name: 'Jakob Junis', team: 'MIL', ip: 26 },
    { id: 'junisja01', name: 'Jakob Junis', team: 'CIN', ip: 41 },
    { id: 'cruzfe01', name: 'Fernando Cruz', team: 'CIN', ip: 66.2 },
    { id: 'fernary01', name: 'Ryan Fernandez', team: 'STL', ip: 66.2 },
    { id: 'leclejo01', name: 'José Leclerc', team: 'TEX', ip: 66.2 },
    { id: 'luzarje01', name: 'Jesús Luzardo*', team: 'MIA', ip: 66.2 },
    { id: 'willitr01', name: 'Trevor Williams', team: 'WSN', ip: 66.2 },
    { id: 'armstsh01', name: 'Shawn Armstrong', team: 'TOT', ip: 66.2 },
    { id: 'armstsh01', name: 'Shawn Armstrong', team: 'TOT', ip: 20 },
    { id: 'armstsh01', name: 'Shawn Armstrong', team: 'TBR', ip: 46.2 },
    { id: 'armstsh01', name: 'Shawn Armstrong', team: 'STL', ip: 12.2 },
    { id: 'armstsh01', name: 'Shawn Armstrong', team: 'CHC', ip: 7.1 },
    { id: 'helslry01', name: 'Ryan Helsley', team: 'STL', ip: 66.1 },
    { id: 'hoffmje02', name: 'Jeff Hoffman', team: 'PHI', ip: 66.1 },
    { id: 'thompry02', name: 'Ryan Thompson', team: 'ARI', ip: 66.1 },
    { id: 'vesiaal01', name: 'Alex Vesia*', team: 'LAD', ip: 66.1 },
    { id: 'pearsna01', name: 'Nate Pearson', team: 'TOT', ip: 66.1 },
    { id: 'pearsna01', name: 'Nate Pearson', team: 'TOR', ip: 40 },
    { id: 'pearsna01', name: 'Nate Pearson', team: 'CHC', ip: 26.1 },
    { id: 'barneja01', name: 'Jacob Barnes', team: 'WSN', ip: 66 },
    { id: 'herriti01', name: 'Tim Herrin*', team: 'CLE', ip: 65.2 },
    { id: 'suterbr01', name: 'Brent Suter*', team: 'CIN', ip: 65.2 },
    { id: 'kochaja01', name: 'Jack Kochanowicz', team: 'LAA', ip: 65.1 },
    { id: 'richatr01', name: 'Trevor Richards', team: 'TOT', ip: 65.1 },
    { id: 'richatr01', name: 'Trevor Richards', team: 'TOR', ip: 52.1 },
    { id: 'richatr01', name: 'Trevor Richards', team: 'MIN', ip: 13 },
    { id: 'millema03', name: 'Mason Miller', team: 'OAK', ip: 65 },
    { id: 'suarero01', name: 'Robert Suarez', team: 'SDP', ip: 65 },
    { id: 'milneho01', name: 'Hoby Milner*', team: 'MIL', ip: 64.2 },
    { id: 'festada01', name: 'David Festa', team: 'MIN', ip: 64.1 },
    { id: 'kinlety01', name: 'Tyler Kinley', team: 'COL', ip: 64 },
    { id: 'delosen01', name: 'Enyel De Los Santos', team: 'TOT', ip: 64 },
    { id: 'delosen01', name: 'Enyel De Los Santos', team: 'TOT', ip: 23.2 },
    { id: 'delosen01', name: 'Enyel De Los Santos', team: 'SDP', ip: 40.1 },
    { id: 'delosen01', name: 'Enyel De Los Santos', team: 'NYY', ip: 6.1 },
    { id: 'delosen01', name: 'Enyel De Los Santos', team: 'CHW', ip: 17.1 },
    { id: 'matonph01', name: 'Phil Maton', team: 'TOT', ip: 64 },
    { id: 'matonph01', name: 'Phil Maton', team: 'TBR', ip: 35.1 },
    { id: 'matonph01', name: 'Phil Maton', team: 'NYM', ip: 28.2 },
    { id: 'finneky01', name: 'Kyle Finnegan', team: 'WSN', ip: 63.2 },
    { id: 'morejad01', name: 'Adrián Morejón*', team: 'SDP', ip: 63.2 },
    { id: 'bidoos01', name: 'Osvaldo Bido', team: 'OAK', ip: 63.1 },
    { id: 'chaveje01', name: 'Jesse Chavez', team: 'ATL', ip: 63.1 },
    { id: 'weissgr01', name: 'Greg Weissert', team: 'BOS', ip: 63.1 },
    { id: 'holmecl01', name: 'Clay Holmes', team: 'NYY', ip: 63 },
    { id: 'hudsoda01', name: 'Daniel Hudson', team: 'LAD', ip: 63 },
    { id: 'kerkeor01', name: 'Orion Kerkering', team: 'PHI', ip: 63 },
    { id: 'cabrege01', name: 'Génesis Cabrera*', team: 'TOR', ip: 62.2 },
    { id: 'matsuyu01', name: 'Yuki Matsui*', team: 'SDP', ip: 62.2 },
    { id: 'strahma01', name: 'Matt Strahm*', team: 'PHI', ip: 62.2 },
    { id: 'hudsobr01', name: 'Bryan Hudson*', team: 'MIL', ip: 62.1 },
    { id: 'koenija01', name: 'Jared Koenig*', team: 'MIL', ip: 62 },
    { id: 'millety01', name: 'Tyson Miller', team: 'TOT', ip: 62 },
    { id: 'millety01', name: 'Tyson Miller', team: 'SEA', ip: 11.2 },
    { id: 'millety01', name: 'Tyson Miller', team: 'CHC', ip: 50.1 },
    { id: 'alvarjo03', name: 'José Alvarado*', team: 'PHI', ip: 61.2 },
    { id: 'chapmar01', name: 'Aroldis Chapman*', team: 'PIT', ip: 61.2 },
    { id: 'yateski01', name: 'Kirby Yates', team: 'TEX', ip: 61.2 },
    { id: 'erceglu01', name: 'Lucas Erceg', team: 'TOT', ip: 61.2 },
    { id: 'erceglu01', name: 'Lucas Erceg', team: 'OAK', ip: 36.2 },
    { id: 'erceglu01', name: 'Lucas Erceg', team: 'KCR', ip: 25 },
    { id: 'lambepe01', name: 'Peter Lambert', team: 'COL', ip: 61.1 },
    { id: 'estraje01', name: 'Jeremiah Estrada', team: 'SDP', ip: 61 },
    { id: 'vothau01', name: 'Austin Voth', team: 'SEA', ip: 61 },
    { id: 'hancoem01', name: 'Emerson Hancock', team: 'SEA', ip: 60.2 },
    { id: 'canoye01', name: 'Yennier Cano', team: 'BAL', ip: 60 },
    { id: 'cleavga01', name: 'Garrett Cleavinger*', team: 'TBR', ip: 60 },
    { id: 'foleyja01', name: 'Jason Foley', team: 'DET', ip: 60 },
    { id: 'kingjo01', name: 'John King*', team: 'STL', ip: 60 },
    { id: 'rogerta01', name: 'Taylor Rogers*', team: 'SFG', ip: 60 },
    { id: 'garciro04', name: 'Robert Garcia*', team: 'WSN', ip: 59.2 },
    { id: 'lawreju01', name: 'Justin Lawrence', team: 'COL', ip: 59.2 },
    { id: 'leedy01', name: 'Dylan Lee*', team: 'ATL', ip: 59.2 },
    { id: 'mantijo01', name: 'Joe Mantiply*', team: 'ARI', ip: 59.2 },
    { id: 'molinan01', name: 'Anthony Molina', team: 'COL', ip: 59.2 },
    { id: 'jarvibr01', name: 'Bryce Jarvis', team: 'ARI', ip: 59.1 },
    { id: 'munozan01', name: 'Andrés Muñoz', team: 'SEA', ip: 59.1 },
    { id: 'nerishe01', name: 'Héctor Neris', team: 'TOT', ip: 59.1 },
    { id: 'nerishe01', name: 'Héctor Neris', team: 'CHC', ip: 44 },
    { id: 'nerishe01', name: 'Héctor Neris', team: 'HOU', ip: 15.1 },
    { id: 'dovalca01', name: 'Camilo Doval', team: 'SFG', ip: 59 },
    { id: 'payamjo01', name: 'Joel Payamps', team: 'MIL', ip: 59 },
    { id: 'romerjo01', name: 'JoJo Romero*', team: 'STL', ip: 59 },
    { id: 'garcilu03', name: 'Luis García', team: 'TOT', ip: 59 },
    { id: 'garcilu03', name: 'Luis García', team: 'LAA', ip: 43.2 },
    { id: 'garcilu03', name: 'Luis García', team: 'BOS', ip: 15.1 },
    { id: 'smylydr01', name: 'Drew Smyly*', team: 'CHC', ip: 58.2 },
    { id: 'dominse01', name: 'Seranthony Domínguez', team: 'TOT', ip: 58.2 },
    { id: 'dominse01', name: 'Seranthony Domínguez', team: 'PHI', ip: 36 },
    { id: 'dominse01', name: 'Seranthony Domínguez', team: 'BAL', ip: 22.2 },
    { id: 'alcaljo01', name: 'Jorge Alcalá', team: 'MIN', ip: 58.1 },
    { id: 'stratch01', name: 'Chris Stratton', team: 'KCR', ip: 58.1 },
    { id: 'anderch01', name: 'Chase Anderson', team: 'TOT', ip: 58.1 },
    { id: 'anderch01', name: 'Chase Anderson', team: 'BOS', ip: 52 },
    { id: 'anderch01', name: 'Chase Anderson', team: 'TEX', ip: 6.1 },
    { id: 'baumami01', name: 'Mike Baumann', team: 'TOT', ip: 58.1 },
    { id: 'baumami01', name: 'Mike Baumann', team: 'TOT', ip: 44 },
    { id: 'baumami01', name: 'Mike Baumann', team: 'TOT', ip: 14.1 },
    { id: 'baumami01', name: 'Mike Baumann', team: 'BAL', ip: 18.1 },
    { id: 'baumami01', name: 'Mike Baumann', team: 'SEA', ip: 16.1 },
    { id: 'baumami01', name: 'Mike Baumann', team: 'SFG', ip: 0.2 },
    { id: 'baumami01', name: 'Mike Baumann', team: 'LAA', ip: 9.1 },
    { id: 'baumami01', name: 'Mike Baumann', team: 'MIA', ip: 13.2 },
    { id: 'leitema02', name: 'Mark Leiter Jr.', team: 'TOT', ip: 58 },
    { id: 'leitema02', name: 'Mark Leiter Jr.', team: 'CHC', ip: 36.1 },
    { id: 'leitema02', name: 'Mark Leiter Jr.', team: 'NYY', ip: 21.2 },
    { id: 'bednada01', name: 'David Bednar', team: 'PIT', ip: 57.2 },
    { id: 'sandlni01', name: 'Nick Sandlin', team: 'CLE', ip: 57.2 },
    { id: 'mearsni01', name: 'Nick Mears', team: 'TOT', ip: 57.2 },
    { id: 'mearsni01', name: 'Nick Mears', team: 'COL', ip: 45.1 },
    { id: 'mearsni01', name: 'Nick Mears', team: 'MIL', ip: 12.1 },
    { id: 'faedoal01', name: 'Alex Faedo', team: 'DET', ip: 57.1 },
    { id: 'garrere01', name: 'Reed Garrett', team: 'NYM', ip: 57.1 },
    { id: 'meyerma01', name: 'Max Meyer', team: 'MIA', ip: 57 },
    { id: 'kellyza01', name: 'Zack Kelly', team: 'BOS', ip: 56.2 },
    { id: 'mcartja01', name: 'James McArthur', team: 'KCR', ip: 56.2 },
    { id: 'mcfartj01', name: 'T.J. McFarland*', team: 'OAK', ip: 56.2 },
    { id: 'pressry01', name: 'Ryan Pressly', team: 'HOU', ip: 56.2 },
    { id: 'webbja01', name: 'Jacob Webb', team: 'BAL', ip: 56.2 },
    { id: 'diazal03', name: 'Alexis Díaz', team: 'CIN', ip: 56.1 },
    { id: 'johnspi01', name: 'Pierce Johnson', team: 'ATL', ip: 56.1 },
    { id: 'chafian01', name: 'Andrew Chafin*', team: 'TOT', ip: 56.1 },
    { id: 'chafian01', name: 'Andrew Chafin*', team: 'DET', ip: 37 },
    { id: 'chafian01', name: 'Andrew Chafin*', team: 'TEX', ip: 19.1 },
    { id: 'smithbu03', name: 'Burch Smith', team: 'TOT', ip: 56.1 },
    { id: 'smithbu03', name: 'Burch Smith', team: 'MIA', ip: 29.2 },
    { id: 'smithbu03', name: 'Burch Smith', team: 'BAL', ip: 26.2 },
    { id: 'millebo06', name: 'Bobby Miller', team: 'LAD', ip: 56 },
    { id: 'ottavad01', name: 'Adam Ottavino', team: 'NYM', ip: 56 },
    { id: 'millesh01', name: 'Shelby Miller', team: 'DET', ip: 55.2 },
    { id: 'brownbe02', name: 'Ben Brown', team: 'CHC', ip: 55.1 },
    { id: 'bummeaa01', name: 'Aaron Bummer*', team: 'ATL', ip: 55.1 },
    { id: 'slateju01', name: 'Justin Slaten', team: 'BOS', ip: 55.1 },
    { id: 'winnke01', name: 'Keaton Winn', team: 'SFG', ip: 55.1 },
    { id: 'brebbjo01', name: 'John Brebbia', team: 'TOT', ip: 55.1 },
    { id: 'brebbjo01', name: 'John Brebbia', team: 'CHW', ip: 48.2 },
    { id: 'brebbjo01', name: 'John Brebbia', team: 'ATL', ip: 6.2 },
    { id: 'stanery01', name: 'Ryne Stanek', team: 'TOT', ip: 55.1 },
    { id: 'stanery01', name: 'Ryne Stanek', team: 'SEA', ip: 39 },
    { id: 'stanery01', name: 'Ryne Stanek', team: 'NYM', ip: 16.1 },
    { id: 'barlosc01', name: 'Scott Barlow', team: 'CLE', ip: 55 },
    { id: 'estevca01', name: 'Carlos Estévez', team: 'TOT', ip: 55 },
    { id: 'estevca01', name: 'Carlos Estévez', team: 'LAA', ip: 34 },
    { id: 'estevca01', name: 'Carlos Estévez', team: 'PHI', ip: 21 },
    { id: 'janseke01', name: 'Kenley Jansen', team: 'BOS', ip: 54.2 },
    { id: 'nicolky01', name: 'Kyle Nicolas', team: 'PIT', ip: 54.2 },
    { id: 'phillev01', name: 'Evan Phillips', team: 'LAD', ip: 54.2 },
    { id: 'duranjh01', name: 'Jhoan Durán', team: 'MIN', ip: 54.1 },
    { id: 'turnbsp01', name: 'Spencer Turnbull', team: 'PHI', ip: 54.1 },
    { id: 'ferguca01', name: 'Caleb Ferguson*', team: 'TOT', ip: 54.1 },
    { id: 'ferguca01', name: 'Caleb Ferguson*', team: 'NYY', ip: 33.1 },
    { id: 'ferguca01', name: 'Caleb Ferguson*', team: 'HOU', ip: 21 },
    { id: 'diazed04', name: 'Edwin Díaz', team: 'NYM', ip: 53.2 },
    { id: 'fauchca01', name: 'Calvin Faucher', team: 'MIA', ip: 53.2 },
    { id: 'perezci01', name: 'Cionel Pérez*', team: 'BAL', ip: 53.2 },
    { id: 'zerpaan01', name: 'Ángel Zerpa*', team: 'KCR', ip: 53.2 },
    { id: 'hoeinbr01', name: 'Bryan Hoeing', team: 'TOT', ip: 53.2 },
    { id: 'hoeinbr01', name: 'Bryan Hoeing', team: 'MIA', ip: 30 },
    { id: 'hoeinbr01', name: 'Bryan Hoeing', team: 'SDP', ip: 23.2 },
    { id: 'anderju01', name: 'Justin Anderson', team: 'CHW', ip: 53.1 },
    { id: 'greench03', name: 'Chad Green', team: 'TOR', ip: 53.1 },
    { id: 'kuhlch01', name: 'Chad Kuhl', team: 'CHW', ip: 53.1 },
    { id: 'bendean01', name: 'Anthony Bender', team: 'MIA', ip: 53 },
    { id: 'jackslu01', name: 'Luke Jackson', team: 'TOT', ip: 53 },
    { id: 'jackslu01', name: 'Luke Jackson', team: 'SFG', ip: 35 },
    { id: 'jackslu01', name: 'Luke Jackson', team: 'ATL', ip: 18 },
    { id: 'lopezjo02', name: 'Jorge López', team: 'TOT', ip: 53 },
    { id: 'lopezjo02', name: 'Jorge López', team: 'NYM', ip: 26.1 },
    { id: 'lopezjo02', name: 'Jorge López', team: 'CHC', ip: 26.2 },
    { id: 'sotogr01', name: 'Gregory Soto*', team: 'TOT', ip: 53 },
    { id: 'sotogr01', name: 'Gregory Soto*', team: 'PHI', ip: 35.1 },
    { id: 'sotogr01', name: 'Gregory Soto*', team: 'BAL', ip: 17.2 },
    { id: 'martise01', name: 'Seth Martinez', team: 'HOU', ip: 52.2 },
    { id: 'kimbrcr01', name: 'Craig Kimbrel', team: 'BAL', ip: 52.1 },
    { id: 'rodrira02', name: 'Randy Rodríguez', team: 'SFG', ip: 52.1 },
    { id: 'suarejo01', name: 'José Suarez*', team: 'LAA', ip: 52.1 },
    { id: 'schrejo01', name: 'John Schreiber', team: 'KCR', ip: 51.2 },
    { id: 'brazohu01', name: 'Huascar Brazobán', team: 'TOT', ip: 51.2 },
    { id: 'brazohu01', name: 'Huascar Brazobán', team: 'MIA', ip: 30.2 },
    { id: 'brazohu01', name: 'Huascar Brazobán', team: 'NYM', ip: 21 },
    { id: 'ferguty01', name: 'Tyler Ferguson', team: 'OAK', ip: 51.1 },
    { id: 'holdeco01', name: 'Colin Holderman', team: 'PIT', ip: 51.1 },
    { id: 'pegueel01', name: 'Elvis Peguero', team: 'MIL', ip: 51.1 },
    { id: 'bernabr01', name: 'Brennan Bernardino*', team: 'BOS', ip: 51 },
    { id: 'grovemi01', name: 'Michael Grove', team: 'LAD', ip: 51 },
    { id: 'raineta01', name: 'Tanner Rainey', team: 'WSN', ip: 51 },
    { id: 'ruizjo01', name: 'José Ruiz', team: 'PHI', ip: 51 },
    { id: 'mlodzca01', name: 'Carmen Mlodzinski', team: 'PIT', ip: 50.2 },
    { id: 'harvehu01', name: 'Hunter Harvey', team: 'TOT', ip: 50.2 },
    { id: 'harvehu01', name: 'Hunter Harvey', team: 'WSN', ip: 45 },
    { id: 'harvehu01', name: 'Hunter Harvey', team: 'KCR', ip: 5.2 },
    { id: 'rouppla01', name: 'Landen Roupp', team: 'SFG', ip: 50.1 },
    { id: 'martida03', name: 'Davis Martin', team: 'CHW', ip: 50 },
    { id: 'rodried05', name: 'Eduardo Rodríguez*', team: 'ARI', ip: 50 },
    { id: 'bandaan01', name: 'Anthony Banda*', team: 'LAD', ip: 49.2 },
    { id: 'elderbr01', name: 'Bryce Elder', team: 'ATL', ip: 49.2 },
    { id: 'nardian01', name: 'Andrew Nardi*', team: 'MIA', ip: 49.2 },
    { id: 'varlalo01', name: 'Louie Varland', team: 'MIN', ip: 49.2 },
    { id: 'priesqu01', name: 'Quinn Priester', team: 'TOT', ip: 49.2 },
    { id: 'priesqu01', name: 'Quinn Priester', team: 'PIT', ip: 44.2 },
    { id: 'priesqu01', name: 'Quinn Priester', team: 'BOS', ip: 5 },
    { id: 'mulleky01', name: 'Kyle Muller*', team: 'OAK', ip: 49.1 },
    { id: 'simslu01', name: 'Lucas Sims', team: 'TOT', ip: 49.1 },
    { id: 'simslu01', name: 'Lucas Sims', team: 'CIN', ip: 35.1 },
    { id: 'simslu01', name: 'Lucas Sims', team: 'BOS', ip: 14 },
    { id: 'bivensp01', name: 'Spencer Bivens', team: 'SFG', ip: 48.2 },
    { id: 'leahyky01', name: 'Kyle Leahy', team: 'STL', ip: 48.2 },
    { id: 'moorema02', name: 'Matt Moore*', team: 'LAA', ip: 48.1 },
    { id: 'popza01', name: 'Zach Pop', team: 'TOR', ip: 48.1 },
    { id: 'boylejo01', name: 'Joe Boyle', team: 'OAK', ip: 47.2 },
    { id: 'scottch01', name: 'Christian Scott', team: 'NYM', ip: 47.1 },
    { id: 'thielca01', name: 'Caleb Thielbar*', team: 'MIN', ip: 47.1 },
    { id: 'kolekst01', name: 'Stephen Kolek', team: 'SDP', ip: 46.2 },
    { id: 'treinbl01', name: 'Blake Treinen', team: 'LAD', ip: 46.2 },
    { id: 'wilsoju10', name: 'Justin Wilson*', team: 'CIN', ip: 46.2 },
    { id: 'megiltr01', name: 'Trevor Megill', team: 'MIL', ip: 46.1 },
    { id: 'wicksjo01', name: 'Jordan Wicks*', team: 'CHC', ip: 46 },
    { id: 'littlbr02', name: 'Brendon Little*', team: 'TOR', ip: 45.2 },
    { id: 'dubinsh01', name: 'Shawn Dubin', team: 'HOU', ip: 45.1 },
    { id: 'fairbpe01', name: 'Pete Fairbanks', team: 'TBR', ip: 45.1 },
    { id: 'hurtebr01', name: 'Brant Hurter*', team: 'DET', ip: 45.1 },
    { id: 'ramiryo01', name: 'Yohan Ramírez', team: 'TOT', ip: 45 },
    { id: 'ramiryo01', name: 'Yohan Ramírez', team: 'TOT', ip: 37.2 },
    { id: 'ramiryo01', name: 'Yohan Ramírez', team: 'TOT', ip: 7.1 },
    { id: 'ramiryo01', name: 'Yohan Ramírez', team: 'NYM', ip: 8.1 },
    { id: 'ramiryo01', name: 'Yohan Ramírez', team: 'BAL', ip: 6 },
    { id: 'ramiryo01', name: 'Yohan Ramírez', team: 'LAD', ip: 29.1 },
    { id: 'ramiryo01', name: 'Yohan Ramírez', team: 'BOS', ip: 1.1 },
    { id: 'martich02', name: 'Chris Martin', team: 'BOS', ip: 44.1 },
    { id: 'matzst01', name: 'Steven Matz*', team: 'STL', ip: 44.1 },
    { id: 'thorpdr01', name: 'Drew Thorpe', team: 'CHW', ip: 44.1 },
    { id: 'britojh01', name: 'Jhony Brito', team: 'SDP', ip: 43.2 },
    { id: 'latzja01', name: 'Jacob Latz*', team: 'TEX', ip: 43.2 },
    { id: 'lynchda02', name: 'Daniel Lynch IV*', team: 'KCR', ip: 43.1 },
    { id: 'scherma01', name: 'Max Scherzer', team: 'TEX', ip: 43.1 },
    { id: 'hernajo02', name: 'Jonathan Hernández', team: 'TOT', ip: 43.1 },
    { id: 'hernajo02', name: 'Jonathan Hernández', team: 'TEX', ip: 41 },
    { id: 'hernajo02', name: 'Jonathan Hernández', team: 'SEA', ip: 2.1 },
    { id: 'halldl01', name: 'DL Hall*', team: 'MIL', ip: 43 },
    { id: 'hodgepo01', name: 'Porter Hodge', team: 'CHC', ip: 43 },
    { id: 'booseca01', name: 'Cam Booser*', team: 'BOS', ip: 42.2 },
    { id: 'kahnlto01', name: 'Tommy Kahnle', team: 'NYY', ip: 42.2 },
    { id: 'longsa01', name: 'Sam Long*', team: 'KCR', ip: 42.2 },
    { id: 'mayzati01', name: 'Tim Mayza*', team: 'TOT', ip: 42.2 },
    { id: 'mayzati01', name: 'Tim Mayza*', team: 'TOR', ip: 24.2 },
    { id: 'mayzati01', name: 'Tim Mayza*', team: 'NYY', ip: 18 },
    { id: 'curryxz01', name: 'Xzavion Curry', team: 'TOT', ip: 42.2 },
    { id: 'curryxz01', name: 'Xzavion Curry', team: 'CLE', ip: 24.2 },
    { id: 'curryxz01', name: 'Xzavion Curry', team: 'MIA', ip: 18 },
    { id: 'ollerad01', name: 'Adam Oller', team: 'MIA', ip: 42.1 },
    { id: 'morgael01', name: 'Eli Morgan', team: 'CLE', ip: 42 },
    { id: 'mccauda01', name: 'Darren McCaughan', team: 'TOT', ip: 42 },
    { id: 'mccauda01', name: 'Darren McCaughan', team: 'MIA', ip: 36 },
    { id: 'mccauda01', name: 'Darren McCaughan', team: 'CLE', ip: 6 },
    { id: 'snideco01', name: 'Collin Snider', team: 'SEA', ip: 41.2 },
    { id: 'ucetaed01', name: 'Edwin Uceta', team: 'TBR', ip: 41.2 },
    { id: 'weemsjo01', name: 'Jordan Weems', team: 'WSN', ip: 41.2 },
    { id: 'adamsau02', name: 'Austin Adams', team: 'OAK', ip: 41.1 },
    { id: 'smithwi04', name: 'Will Smith*', team: 'KCR', ip: 41.1 },
    { id: 'kellebr01', name: 'Brad Keller', team: 'TOT', ip: 41.1 },
    { id: 'kellebr01', name: 'Brad Keller', team: 'CHW', ip: 16.2 },
    { id: 'kellebr01', name: 'Brad Keller', team: 'BOS', ip: 24.2 },
    { id: 'tinocje01', name: 'Jesús Tinoco', team: 'TOT', ip: 40.2 },
    { id: 'tinocje01', name: 'Jesús Tinoco', team: 'TOT', ip: 30.2 },
    { id: 'tinocje01', name: 'Jesús Tinoco', team: 'TEX', ip: 10 },
    { id: 'tinocje01', name: 'Jesús Tinoco', team: 'CHC', ip: 4 },
    { id: 'tinocje01', name: 'Jesús Tinoco', team: 'MIA', ip: 26.2 },
    { id: 'birdja01', name: 'Jake Bird', team: 'COL', ip: 40 },
    { id: 'medinlu02', name: 'Luis Medina', team: 'OAK', ip: 40 },
    { id: 'boydma01', name: 'Matthew Boyd*', team: 'CLE', ip: 39.2 },
    { id: 'sewalpa01', name: 'Paul Sewald', team: 'ARI', ip: 39.2 },
    { id: 'bradiky01', name: 'Kyle Bradish', team: 'BAL', ip: 39.1 },
    { id: 'swanser01', name: 'Erik Swanson', team: 'TOR', ip: 39.1 },
    { id: 'woodal02', name: 'Alex Wood*', team: 'OAK', ip: 39.1 },
    { id: 'garciyi01', name: 'Yimi García', team: 'TOT', ip: 39 },
    { id: 'garciyi01', name: 'Yimi García', team: 'TOR', ip: 30 },
    { id: 'garciyi01', name: 'Yimi García', team: 'SEA', ip: 9 },
    { id: 'alexasc02', name: 'Scott Alexander*', team: 'OAK', ip: 38.2 },
    { id: 'cantijo01', name: 'Joey Cantillo*', team: 'CLE', ip: 38.2 },
    { id: 'sauceta01', name: 'Tayler Saucedo*', team: 'SEA', ip: 38.2 },
    { id: 'henryto01', name: 'Tommy Henry*', team: 'ARI', ip: 38.1 },
    { id: 'montera01', name: 'Rafael Montero', team: 'HOU', ip: 38.1 },
    { id: 'peralwa01', name: 'Wandy Peralta*', team: 'SDP', ip: 38.1 },
    { id: 'cousija01', name: 'Jake Cousins', team: 'NYY', ip: 38 },
    { id: 'paganem01', name: 'Emilio Pagán', team: 'CIN', ip: 38 },
    { id: 'vieirth01', name: 'Thyago Vieira', team: 'TOT', ip: 38 },
    { id: 'vieirth01', name: 'Thyago Vieira', team: 'TOT', ip: 38 },
    { id: 'vieirth01', name: 'Thyago Vieira', team: 'MIL', ip: 22.1 },
    { id: 'vieirth01', name: 'Thyago Vieira', team: 'BAL', ip: 0 },
    { id: 'vieirth01', name: 'Thyago Vieira', team: 'ARI', ip: 15.2 },
    { id: 'hamilia01', name: 'Ian Hamilton', team: 'NYY', ip: 37.2 },
    { id: 'matthze01', name: 'Zebby Matthews', team: 'MIN', ip: 37.2 },
    { id: 'mollsa01', name: 'Sam Moll*', team: 'CIN', ip: 37.2 },
    { id: 'rodrima01', name: 'Manuel Rodríguez', team: 'TBR', ip: 37.2 },
    { id: 'strathu01', name: 'Hunter Stratton', team: 'PIT', ip: 37.2 },
    { id: 'youngda02', name: 'Danny Young*', team: 'NYM', ip: 37.2 },
    { id: 'honeybr01', name: 'Brent Honeywell Jr.', team: 'TOT', ip: 37.2 },
    { id: 'honeybr01', name: 'Brent Honeywell Jr.', team: 'PIT', ip: 3.1 },
    { id: 'honeybr01', name: 'Brent Honeywell Jr.', team: 'LAD', ip: 34.1 },
    { id: 'pocheco01', name: 'Colin Poche*', team: 'TBR', ip: 37.1 },
    { id: 'garrebr01', name: 'Braxton Garrett*', team: 'MIA', ip: 37 },
    { id: 'phillty01', name: 'Tyler Phillips', team: 'PHI', ip: 36.2 },
    { id: 'tatedi01', name: 'Dillon Tate', team: 'TOT', ip: 36.2 },
    { id: 'tatedi01', name: 'Dillon Tate', team: 'BAL', ip: 33.1 },
    { id: 'tatedi01', name: 'Dillon Tate', team: 'TOR', ip: 3.1 },
    { id: 'blackma01', name: 'Mason Black', team: 'SFG', ip: 36.1 },
    { id: 'wroblju01', name: 'Justin Wrobleski*', team: 'LAD', ip: 36.1 },
    { id: 'chargjt01', name: 'JT Chargois', team: 'TOT', ip: 36.1 },
    { id: 'chargjt01', name: 'JT Chargois', team: 'MIA', ip: 16.2 },
    { id: 'chargjt01', name: 'JT Chargois', team: 'SEA', ip: 19.2 },
    { id: 'anderni01', name: 'Nick Anderson', team: 'KCR', ip: 35.2 },
    { id: 'leiteja01', name: 'Jack Leiter', team: 'TEX', ip: 35.2 },
    { id: 'nastrni01', name: 'Nick Nastrini', team: 'CHW', ip: 35.2 },
    { id: 'sanchsi01', name: 'Sixto Sánchez', team: 'MIA', ip: 35.2 },
    { id: 'okertst01', name: 'Steven Okert*', team: 'MIN', ip: 35.1 },
    { id: 'nunezde01', name: 'Dedniel Núñez', team: 'NYM', ip: 35 },
    { id: 'woodfja01', name: 'Jake Woodford', team: 'TOT', ip: 35 },
    { id: 'woodfja01', name: 'Jake Woodford', team: 'CHW', ip: 8.1 },
    { id: 'woodfja01', name: 'Jake Woodford', team: 'PIT', ip: 26.2 },
    { id: 'fundeko01', name: 'Kody Funderburk*', team: 'MIN', ip: 34.2 },
    { id: 'javiecr01', name: 'Cristian Javier', team: 'HOU', ip: 34.2 },
    { id: 'joycebe01', name: 'Ben Joyce', team: 'LAA', ip: 34.2 },
    { id: 'wilsost02', name: 'Steven Wilson', team: 'CHW', ip: 34.2 },
    { id: 'gordota01', name: 'Tanner Gordon', team: 'COL', ip: 34.1 },
    { id: 'minteaj01', name: 'A.J. Minter*', team: 'ATL', ip: 34.1 },
    { id: 'roycrch01', name: 'Chris Roycroft', team: 'STL', ip: 34.1 },
    { id: 'lovelri01', name: 'Richard Lovelady*', team: 'TOT', ip: 34.1 },
    { id: 'lovelri01', name: 'Richard Lovelady*', team: 'CHC', ip: 5.2 },
    { id: 'lovelri01', name: 'Richard Lovelady*', team: 'TBR', ip: 28.2 },
    { id: 'ginnjt01', name: 'J.T. Ginn', team: 'OAK', ip: 34 },
    { id: 'otanemi01', name: 'Michel Otañez', team: 'OAK', ip: 34 },
    { id: 'burkebr01', name: 'Brock Burke*', team: 'TOT', ip: 34 },
    { id: 'burkebr01', name: 'Brock Burke*', team: 'TEX', ip: 13.2 },
    { id: 'burkebr01', name: 'Brock Burke*', team: 'LAA', ip: 20.1 },
    { id: 'gonzama02', name: 'Marco Gonzales*', team: 'PIT', ip: 33.2 },
    { id: 'mazurad01', name: 'Adam Mazur', team: 'SDP', ip: 33.2 },
    { id: 'sprinje01', name: 'Jeffrey Springs*', team: 'TBR', ip: 33 },
    { id: 'burrry01', name: 'Ryan Burr', team: 'TOR', ip: 32.2 },
    { id: 'mcgousc01', name: 'Scott McGough', team: 'ARI', ip: 32.2 },
    { id: 'diekmja01', name: 'Jake Diekman*', team: 'NYM', ip: 32 },
    { id: 'ferrejo01', name: 'Jose A. Ferrer*', team: 'WSN', ip: 32 },
    { id: 'kellyjo05', name: 'Joe Kelly', team: 'LAD', ip: 32 },
    { id: 'aguiaju01', name: 'Julian Aguiar', team: 'CIN', ip: 31.2 },
    { id: 'chivian01', name: 'Angel Chivilli', team: 'COL', ip: 31.2 },
    { id: 'tylerky01', name: 'Kyle Tyler', team: 'MIA', ip: 31.2 },
    { id: 'flemijo01', name: 'Josh Fleming*', team: 'PIT', ip: 31.1 },
    { id: 'kellymi03', name: 'Michael Kelly', team: 'OAK', ip: 31.1 },
    { id: 'leasujo01', name: 'Jordan Leasure', team: 'CHW', ip: 31.1 },
    { id: 'lowderh01', name: 'Rhett Lowder', team: 'CIN', ip: 30.2 },
    { id: 'rayro02', name: 'Robbie Ray*', team: 'SFG', ip: 30.2 },
    { id: 'blalobr01', name: 'Bradley Blalock', team: 'TOT', ip: 30.2 },
    { id: 'blalobr01', name: 'Bradley Blalock', team: 'MIL', ip: 1 },
    { id: 'blalobr01', name: 'Bradley Blalock', team: 'COL', ip: 29.2 },
    { id: 'bowmama01', name: 'Matt Bowman', team: 'TOT', ip: 30.2 },
    { id: 'bowmama01', name: 'Matt Bowman', team: 'TOT', ip: 24 },
    { id: 'bowmama01', name: 'Matt Bowman', team: 'MIN', ip: 7.2 },
    { id: 'bowmama01', name: 'Matt Bowman', team: 'ARI', ip: 6.2 },
    { id: 'bowmama01', name: 'Matt Bowman', team: 'SEA', ip: 0.2 },
    { id: 'bowmama01', name: 'Matt Bowman', team: 'BAL', ip: 15.2 },
    { id: 'bubickr01', name: 'Kris Bubic*', team: 'KCR', ip: 30.1 },
    { id: 'danieda01', name: 'Davis Daniel', team: 'LAA', ip: 30.1 },
    { id: 'thompke02', name: 'Keegan Thompson', team: 'CHC', ip: 30.1 },
    { id: 'chiriyo01', name: 'Yonny Chirinos', team: 'MIA', ip: 30 },
    { id: 'hernaca04', name: 'Carlos Hernández', team: 'KCR', ip: 30 },
    { id: 'kershcl01', name: 'Clayton Kershaw*', team: 'LAD', ip: 30 },
    { id: 'santito01', name: 'Tony Santillan', team: 'CIN', ip: 30 },
    { id: 'couloda01', name: 'Danny Coulombe*', team: 'BAL', ip: 29.2 },
    { id: 'bielabr01', name: 'Brandon Bielak', team: 'TOT', ip: 29.2 },
    { id: 'bielabr01', name: 'Brandon Bielak', team: 'HOU', ip: 17.1 },
    { id: 'bielabr01', name: 'Brandon Bielak', team: 'OAK', ip: 12.1 },
    { id: 'hanifbr01', name: 'Brenan Hanifee', team: 'DET', ip: 29.1 },
    { id: 'soriage01', name: 'George Soriano', team: 'MIA', ip: 29.1 },
    { id: 'salazed01', name: 'Eduardo Salazar', team: 'TOT', ip: 29.1 },
    { id: 'salazed01', name: 'Eduardo Salazar', team: 'LAD', ip: 2 },
    { id: 'salazed01', name: 'Eduardo Salazar', team: 'WSN', ip: 27.1 },
    { id: 'howarsp01', name: 'Spencer Howard', team: 'TOT', ip: 29 },
    { id: 'howarsp01', name: 'Spencer Howard', team: 'SFG', ip: 24 },
    { id: 'howarsp01', name: 'Spencer Howard', team: 'CLE', ip: 5 },
    { id: 'rasmudr01', name: 'Drew Rasmussen', team: 'TBR', ip: 28.2 },
    { id: 'ashbyaa01', name: 'Aaron Ashby*', team: 'MIL', ip: 28.1 },
    { id: 'diazyi01', name: 'Yilber Díaz', team: 'ARI', ip: 28.1 },
    { id: 'allenlo01', name: 'Logan Allen*', team: 'ARI', ip: 28 },
    { id: 'brasiry01', name: 'Ryan Brasier', team: 'LAD', ip: 28 },
    { id: 'gassero01', name: 'Robert Gasser*', team: 'MIL', ip: 28 },
    { id: 'bazared01', name: 'Eduard Bazardo', team: 'SEA', ip: 27.2 },
    { id: 'mannima02', name: 'Matt Manning', team: 'DET', ip: 27.2 },
    { id: 'sammobr01', name: 'Bryan Sammons*', team: 'DET', ip: 27.1 },
    { id: 'allarko01', name: 'Kolby Allard*', team: 'PHI', ip: 27 },
    { id: 'andergr01', name: 'Grant Anderson', team: 'TEX', ip: 26.2 },
    { id: 'brookaa01', name: 'Aaron Brooks', team: 'OAK', ip: 26.2 },
    { id: 'devench02', name: 'Chris Devenski', team: 'TBR', ip: 26.2 },
    { id: 'roberet01', name: 'Ethan Roberts', team: 'CHC', ip: 26.2 },
    { id: 'garabge01', name: 'Gerson Garabito', team: 'TEX', ip: 26.1 },
    { id: 'jacksja01', name: 'Jay Jackson', team: 'MIN', ip: 26.1 },
    { id: 'kingbr02', name: 'Bryan King*', team: 'HOU', ip: 26.1 },
    { id: 'varlagu01', name: 'Gus Varland', team: 'TOT', ip: 26.1 },
    { id: 'varlagu01', name: 'Gus Varland', team: 'LAD', ip: 6 },
    { id: 'varlagu01', name: 'Gus Varland', team: 'CHW', ip: 20.1 },
    { id: 'littllu01', name: 'Luke Little*', team: 'CHC', ip: 26 },
    { id: 'marteyu01', name: 'Yunior Marté', team: 'PHI', ip: 26 },
    { id: 'jimenda01', name: 'Dany Jiménez', team: 'OAK', ip: 25.2 },
    { id: 'crousha01', name: 'Hans Crouse', team: 'LAA', ip: 25.1 },
    { id: 'francjp01', name: 'J.P. France', team: 'HOU', ip: 25.1 },
    { id: 'ortka01', name: 'Kaleb Ort', team: 'HOU', ip: 24.2 },
    { id: 'cimbead01', name: 'Adam Cimber', team: 'LAA', ip: 24.1 },
    { id: 'manoaal01', name: 'Alek Manoah', team: 'TOR', ip: 24.1 },
    { id: 'poteeco01', name: 'Cody Poteet', team: 'NYY', ip: 24.1 },
    { id: 'staumjo01', name: 'Josh Staumont', team: 'MIN', ip: 24.1 },
    { id: 'ellarfr01', name: 'Fraser Ellard*', team: 'CHW', ip: 24 },
    { id: 'rosenke01', name: 'Kenny Rosenberg*', team: 'LAA', ip: 24 },
    { id: 'hentgsa01', name: 'Sam Hentges*', team: 'CLE', ip: 23.2 },
    { id: 'speiega01', name: 'Gabe Speier*', team: 'SEA', ip: 23.2 },
    { id: 'festama01', name: 'Matt Festa', team: 'TOT', ip: 23.2 },
    { id: 'festama01', name: 'Matt Festa', team: 'NYM', ip: 1 },
    { id: 'festama01', name: 'Matt Festa', team: 'TEX', ip: 22.2 },
    { id: 'whitemi03', name: 'Mitch White', team: 'TOT', ip: 23.2 },
    { id: 'whitemi03', name: 'Mitch White', team: 'TOT', ip: 13.2 },
    { id: 'whitemi03', name: 'Mitch White', team: 'TOR', ip: 10 },
    { id: 'whitemi03', name: 'Mitch White', team: 'SFG', ip: 5.1 },
    { id: 'whitemi03', name: 'Mitch White', team: 'MIL', ip: 8.1 },
    { id: 'bakerbr01', name: 'Bryan Baker', team: 'BAL', ip: 23.1 },
    { id: 'gonzavi02', name: 'Victor González*', team: 'NYY', ip: 23.1 },
    { id: 'marinro01', name: 'Ron Marinaccio', team: 'NYY', ip: 23.1 },
    { id: 'maddety01', name: 'Ty Madden', team: 'DET', ip: 23 },
    { id: 'mcgremi01', name: 'Michael McGreevy', team: 'STL', ip: 23 },
    { id: 'toussto01', name: 'Touki Toussaint', team: 'CHW', ip: 23 },
    { id: 'warrewi01', name: 'Will Warren', team: 'NYY', ip: 22.2 },
    { id: 'bassobr01', name: 'Brady Basso*', team: 'OAK', ip: 22.1 },
    { id: 'kerrra01', name: 'Ray Kerr*', team: 'ATL', ip: 22.1 },
    { id: 'nanceto01', name: 'Tommy Nance', team: 'TOR', ip: 22 },
    { id: 'englema01', name: 'Mason Englert', team: 'DET', ip: 21.2 },
    { id: 'reidfse01', name: 'Sean Reid-Foley', team: 'NYM', ip: 21.2 },
    { id: 'willide03', name: 'Devin Williams', team: 'MIL', ip: 21.2 },
    { id: 'pareden01', name: 'Enoli Paredes', team: 'TOT', ip: 21.2 },
    { id: 'pareden01', name: 'Enoli Paredes', team: 'MIL', ip: 20.2 },
    { id: 'pareden01', name: 'Enoli Paredes', team: 'CHC', ip: 1 },
    { id: 'rodriye01', name: 'Yerry Rodríguez', team: 'TOT', ip: 21.2 },
    { id: 'rodriye01', name: 'Yerry Rodríguez', team: 'TEX', ip: 17 },
    { id: 'rodriye01', name: 'Yerry Rodríguez', team: 'TOR', ip: 4.2 },
    { id: 'guentse01', name: 'Sean Guenther*', team: 'DET', ip: 21 },
    { id: 'breweco01', name: 'Colten Brewer', team: 'CHC', ip: 20.2 },
    { id: 'fittsri01', name: 'Richard Fitts', team: 'BOS', ip: 20.2 },
    { id: 'gallegi01', name: 'Giovanny Gallegos', team: 'STL', ip: 20.2 },
    { id: 'germado01', name: 'Domingo Germán', team: 'PIT', ip: 20.2 },
    { id: 'meansjo01', name: 'John Means*', team: 'BAL', ip: 20.2 },
    { id: 'ramirem01', name: 'Emmanuel Ramírez', team: 'MIA', ip: 20.2 },
    { id: 'ramirer02', name: 'Erasmo Ramírez', team: 'TBR', ip: 20.2 },
    { id: 'ryanry01', name: 'Ryder Ryan', team: 'PIT', ip: 20.2 },
    { id: 'blewesc01', name: 'Scott Blewett', team: 'MIN', ip: 20.1 },
    { id: 'davisno01', name: 'Noah Davis', team: 'COL', ip: 20.1 },
    { id: 'ryanri01', name: 'River Ryan', team: 'LAD', ip: 20.1 },
    { id: 'criswje01', name: 'Jeff Criswell', team: 'COL', ip: 19.2 },
    { id: 'petermi01', name: 'Michael Petersen', team: 'TOT', ip: 19.2 },
    { id: 'petermi01', name: 'Michael Petersen', team: 'LAD', ip: 14 },
    { id: 'petermi01', name: 'Michael Petersen', team: 'MIA', ip: 5.2 },
    { id: 'henriro01', name: 'Ronny Henriquez', team: 'MIN', ip: 19.1 },
    { id: 'martejo01', name: 'José Marte', team: 'LAA', ip: 19.1 },
    { id: 'quijajo01', name: 'José Quijada*', team: 'LAA', ip: 19.1 },
    { id: 'taylotr01', name: 'Troy Taylor', team: 'SEA', ip: 19.1 },
    { id: 'berropr01', name: 'Prelander Berroa', team: 'CHW', ip: 19 },
    { id: 'burkese01', name: 'Sean Burke', team: 'CHW', ip: 19 },
    { id: 'leonedo01', name: 'Dominic Leone', team: 'CHW', ip: 19 },
    { id: 'maldoan01', name: 'Anthony Maldonado', team: 'MIA', ip: 19 },
    { id: 'boltoco01', name: 'Cody Bolton', team: 'SEA', ip: 18.2 },
    { id: 'langeal01', name: 'Alex Lange', team: 'DET', ip: 18.2 },
    { id: 'walstbl01', name: 'Blake Walston*', team: 'ARI', ip: 18.1 },
    { id: 'whitlga01', name: 'Garrett Whitlock', team: 'BOS', ip: 18.1 },
    { id: 'hernada03', name: 'Daysbel Hernández', team: 'ATL', ip: 18 },
    { id: 'hornba01', name: 'Bailey Horn*', team: 'BOS', ip: 18 },
    { id: 'penniwa01', name: 'Walter Pennington*', team: 'TOT', ip: 18 },
    { id: 'penniwa01', name: 'Walter Pennington*', team: 'KCR', ip: 0.2 },
    { id: 'penniwa01', name: 'Walter Pennington*', team: 'TEX', ip: 17.1 },
    { id: 'bushky01', name: 'Ky Bush*', team: 'CHW', ip: 17.2 },
    { id: 'emanuke01', name: 'Kent Emanuel*', team: 'MIA', ip: 17.2 },
    { id: 'hughebr01', name: 'Brandon Hughes*', team: 'ARI', ip: 17.2 },
    { id: 'lasorjo01', name: 'Joe La Sorsa*', team: 'WSN', ip: 17.2 },
    { id: 'smithdr01', name: 'Drew Smith', team: 'NYM', ip: 17.2 },
    { id: 'zuniggu01', name: 'Guillo Zuñiga', team: 'LAA', ip: 17.2 },
    { id: 'alzolad01', name: 'Adbert Alzolay', team: 'CHC', ip: 17.1 },
    { id: 'winnco01', name: 'Cole Winn', team: 'TEX', ip: 17.1 },
    { id: 'biggehu01', name: 'Hunter Bigge', team: 'TOT', ip: 17.1 },
    { id: 'biggehu01', name: 'Hunter Bigge', team: 'CHC', ip: 3.1 },
    { id: 'biggehu01', name: 'Hunter Bigge', team: 'TBR', ip: 14 },
    { id: 'thompza02', name: 'Zack Thompson*', team: 'STL', ip: 17 },
    { id: 'zeferry01', name: 'Ryan Zeferjahn', team: 'LAA', ip: 17 },
    { id: 'keuchda01', name: 'Dallas Keuchel*', team: 'MIL', ip: 16.2 },
    { id: 'cobbal01', name: 'Alex Cobb', team: 'CLE', ip: 16.1 },
    { id: 'sauerma01', name: 'Matt Sauer', team: 'KCR', ip: 16.1 },
    { id: 'sborzjo01', name: 'Josh Sborz', team: 'TEX', ip: 16.1 },
    { id: 'zulueyo01', name: 'Yosver Zulueta', team: 'CIN', ip: 16.1 },
    { id: 'cuasjo01', name: 'José Cuas', team: 'TOT', ip: 16.1 },
    { id: 'cuasjo01', name: 'José Cuas', team: 'CHC', ip: 13.1 },
    { id: 'cuasjo01', name: 'José Cuas', team: 'TOR', ip: 3 },
    { id: 'andersh01', name: 'Shaun Anderson', team: 'TOT', ip: 16.1 },
    { id: 'andersh01', name: 'Shaun Anderson', team: 'TEX', ip: 3.1 },
    { id: 'andersh01', name: 'Shaun Anderson', team: 'MIA', ip: 13 },
    { id: 'sulseco01', name: 'Cole Sulser', team: 'TOT', ip: 16.1 },
    { id: 'sulseco01', name: 'Cole Sulser', team: 'NYM', ip: 4.2 },
    { id: 'sulseco01', name: 'Cole Sulser', team: 'TBR', ip: 11.2 },
    { id: 'becktr01', name: 'Tristan Beck', team: 'SFG', ip: 16 },
    { id: 'clevimi01', name: 'Mike Clevinger', team: 'CHW', ip: 16 },
    { id: 'almonye01', name: 'Yency Almonte', team: 'CHC', ip: 15.2 },
    { id: 'cisnejo01', name: 'José Cisnero', team: 'LAA', ip: 15.2 },
    { id: 'holmagr01', name: 'Grant Holman', team: 'OAK', ip: 15.2 },
    { id: 'stewabr01', name: 'Brock Stewart', team: 'MIN', ip: 15.2 },
    { id: 'youngal01', name: 'Alex Young*', team: 'TOT', ip: 15.2 },
    { id: 'youngal01', name: 'Alex Young*', team: 'CIN', ip: 2 },
    { id: 'youngal01', name: 'Alex Young*', team: 'NYM', ip: 13.2 },
    { id: 'hernael01', name: 'Elieser Hernández', team: 'TOT', ip: 15.2 },
    { id: 'hernael01', name: 'Elieser Hernández', team: 'LAD', ip: 9.2 },
    { id: 'hernael01', name: 'Elieser Hernández', team: 'MIL', ip: 6 },
    { id: 'wellsty01', name: 'Tyler Wells', team: 'BAL', ip: 15.1 },
    { id: 'merryju01', name: 'Julian Merryweather', team: 'CHC', ip: 15 },
    { id: 'peralsa01', name: 'Sammy Peralta*', team: 'CHW', ip: 15 },
    { id: 'cosgrto01', name: 'Tom Cosgrove*', team: 'SDP', ip: 14.2 },
    { id: 'jacobal01', name: 'Alek Jacob', team: 'SDP', ip: 14.2 },
    { id: 'palenda01', name: 'Daniel Palencia', team: 'CHC', ip: 14.2 },
    { id: 'jeffeda01', name: 'Daulton Jefferies', team: 'TOT', ip: 14.2 },
    { id: 'jeffeda01', name: 'Daulton Jefferies', team: 'SFG', ip: 4.2 },
    { id: 'jeffeda01', name: 'Daulton Jefferies', team: 'PIT', ip: 10 },
    { id: 'uribeab01', name: 'Abner Uribe', team: 'MIL', ip: 14.1 },
    { id: 'willibr02', name: 'Brandon Williamson*', team: 'CIN', ip: 14.1 },
    { id: 'beedety01', name: 'Tyler Beede', team: 'CLE', ip: 14 },
    { id: 'garcide01', name: 'Deivi García', team: 'CHW', ip: 14 },
    { id: 'castrmi01', name: 'Miguel Castro', team: 'ARI', ip: 13.2 },
    { id: 'lazarma01', name: 'Max Lazar', team: 'PHI', ip: 13.2 },
    { id: 'rodrijo06', name: 'Joely Rodríguez*', team: 'BOS', ip: 13.2 },
    { id: 'romanjo03', name: 'Jordan Romano', team: 'TOR', ip: 13.2 },
    { id: 'vinesda01', name: 'Darius Vines', team: 'ATL', ip: 13.2 },
    { id: 'barnema01', name: 'Matt Barnes', team: 'WSN', ip: 13.1 },
    { id: 'ramirni01', name: 'Nick Ramirez*', team: 'LAD', ip: 13.1 },
    { id: 'roberni01', name: 'Nick Robertson', team: 'TOT', ip: 13.1 },
    { id: 'roberni01', name: 'Nick Robertson', team: 'STL', ip: 12.1 },
    { id: 'roberni01', name: 'Nick Robertson', team: 'TOR', ip: 1 },
    { id: 'venezan01', name: 'Anthony Veneziano*', team: 'TOT', ip: 13.1 },
    { id: 'venezan01', name: 'Anthony Veneziano*', team: 'KCR', ip: 2 },
    { id: 'venezan01', name: 'Anthony Veneziano*', team: 'MIA', ip: 11.1 },
    { id: 'aldegsa01', name: 'Sam Aldegheri*', team: 'LAA', ip: 13 },
    { id: 'mercami01', name: 'Michael Mercado', team: 'PHI', ip: 13 },
    { id: 'millery01', name: 'Ryan Miller', team: 'LAA', ip: 13 },
    { id: 'mahlety01', name: 'Tyler Mahle', team: 'TEX', ip: 12.2 },
    { id: 'sabroer01', name: 'Erik Sabrowski*', team: 'CLE', ip: 12.2 },
    { id: 'halvose01', name: 'Seth Halvorsen', team: 'COL', ip: 12.1 },
    { id: 'hergeji01', name: 'Jimmy Herget', team: 'ATL', ip: 12.1 },
    { id: 'perallu01', name: 'Luis Peralta*', team: 'COL', ip: 12.1 },
    { id: 'rodrica02', name: 'Carlos Rodríguez', team: 'MIL', ip: 12.1 },
    { id: 'senzaan01', name: 'Antonio Senzatela', team: 'COL', ip: 12.1 },
    { id: 'vespini01', name: 'Nick Vespi*', team: 'BAL', ip: 12.1 },
    { id: 'walkejo03', name: 'Josh Walker*', team: 'NYM', ip: 12.1 },
    { id: 'biebesh01', name: 'Shane Bieber', team: 'CLE', ip: 12 },
    { id: 'hellebe01', name: 'Ben Heller', team: 'PIT', ip: 12 },
    { id: 'mcmiljo01', name: 'John McMillon', team: 'MIA', ip: 12 },
    { id: 'plesaza01', name: 'Zach Plesac', team: 'LAA', ip: 12 },
    { id: 'nittovi01', name: 'Vinny Nittoli', team: 'TOT', ip: 12 },
    { id: 'nittovi01', name: 'Vinny Nittoli', team: 'OAK', ip: 8 },
    { id: 'nittovi01', name: 'Vinny Nittoli', team: 'BAL', ip: 4 },
    { id: 'avilani01', name: 'Nick Avila', team: 'SFG', ip: 11.2 },
    { id: 'blossja01', name: 'Jake Bloss', team: 'HOU', ip: 11.2 },
    { id: 'rockeku01', name: 'Kumar Rocker', team: 'TEX', ip: 11.2 },
    { id: 'strzepe01', name: 'Peter Strzelecki', team: 'CLE', ip: 11.2 },
    { id: 'lucasea01', name: 'Easton Lucas*', team: 'TOT', ip: 11.2 },
    { id: 'lucasea01', name: 'Easton Lucas*', team: 'OAK', ip: 3.2 },
    { id: 'lucasea01', name: 'Easton Lucas*', team: 'DET', ip: 3.1 },
    { id: 'lucasea01', name: 'Easton Lucas*', team: 'TOR', ip: 4.2 },
    { id: 'cuetojo01', name: 'Johnny Cueto', team: 'LAA', ip: 11.1 },
    { id: 'gillalo01', name: 'Logan Gillaspie', team: 'SDP', ip: 11.1 },
    { id: 'gomezyo01', name: 'Yoendrys Gómez', team: 'NYY', ip: 11.1 },
    { id: 'hergeke01', name: 'Kevin Herget', team: 'MIL', ip: 11.1 },
    { id: 'degeubr01', name: 'Brett de Geus', team: 'TOT', ip: 11.1 },
    { id: 'degeubr01', name: 'Brett de Geus', team: 'TOT', ip: 5.2 },
    { id: 'degeubr01', name: 'Brett de Geus', team: 'SEA', ip: 3.1 },
    { id: 'degeubr01', name: 'Brett de Geus', team: 'MIA', ip: 5.2 },
    { id: 'degeubr01', name: 'Brett de Geus', team: 'TOR', ip: 2.1 },
    { id: 'borucry01', name: 'Ryan Borucki*', team: 'PIT', ip: 11 },
    { id: 'feyerjo01', name: 'J.P. Feyereisen', team: 'LAD', ip: 11 },
    { id: 'mushipa01', name: 'Parker Mushinski*', team: 'HOU', ip: 11 },
    { id: 'reynose01', name: 'Sean Reynolds', team: 'SDP', ip: 11 },
    { id: 'rogerjo01', name: 'Josh Rogers*', team: 'COL', ip: 11 },
    { id: 'tengka01', name: 'Kai-Wei Teng', team: 'SFG', ip: 11 },
    { id: 'adonjo01', name: 'Joan Adon', team: 'WSN', ip: 10.2 },
    { id: 'degroja01', name: 'Jacob deGrom', team: 'TEX', ip: 10.2 },
    { id: 'hillja01', name: 'Jaden Hill', team: 'COL', ip: 10.2 },
    { id: 'kiliaca01', name: 'Caleb Kilian', team: 'CHC', ip: 10.2 },
    { id: 'nelsoky01', name: 'Kyle Nelson*', team: 'ARI', ip: 10.2 },
    { id: 'pintori01', name: 'Ricardo Pinto', team: 'PHI', ip: 10.2 },
    { id: 'warreau01', name: 'Austin Warren', team: 'SFG', ip: 10.2 },
    { id: 'castehu01', name: 'Humberto Castellanos', team: 'ARI', ip: 10.1 },
    { id: 'danaca01', name: 'Caden Dana', team: 'LAA', ip: 10.1 },
    { id: 'lopezja04', name: 'Jacob Lopez*', team: 'TBR', ip: 10.1 },
    { id: 'lucchjo01', name: 'Joey Lucchesi*', team: 'NYM', ip: 10.1 },
    { id: 'sneadki01', name: 'Kirby Snead*', team: 'SEA', ip: 10.1 },
    { id: 'castidi01', name: 'Diego Castillo', team: 'MIN', ip: 10 },
    { id: 'guerrlu01', name: 'Luis Guerrero', team: 'BOS', ip: 10 },
    { id: 'matzety01', name: 'Tyler Matzek*', team: 'ATL', ip: 10 },
    { id: 'newcose01', name: 'Sean Newcomb*', team: 'OAK', ip: 10 },
    { id: 'wagueja01', name: 'Jacob Waguespack', team: 'TBR', ip: 10 },
    { id: 'kuhnejo01', name: 'Joel Kuhnel', team: 'TOT', ip: 10 },
    { id: 'kuhnejo01', name: 'Joel Kuhnel', team: 'HOU', ip: 2 },
    { id: 'kuhnejo01', name: 'Joel Kuhnel', team: 'TBR', ip: 8 },
    { id: 'burdini01', name: 'Nick Burdi', team: 'NYY', ip: 9.2 },
    { id: 'diazjh01', name: 'Jhonathan Díaz*', team: 'SEA', ip: 9.2 },
    { id: 'dobnara01', name: 'Randy Dobnak', team: 'MIN', ip: 9.2 },
    { id: 'montgma01', name: 'Mason Montgomery*', team: 'TBR', ip: 9.2 },
    { id: 'olougja01', name: 'Jack O\'Loughlin*', team: 'OAK', ip: 9.2 },
    { id: 'friaslu01', name: 'Luis Frías', team: 'TOT', ip: 9.2 },
    { id: 'friaslu01', name: 'Luis Frías', team: 'ARI', ip: 6.1 },
    { id: 'friaslu01', name: 'Luis Frías', team: 'TOR', ip: 3.1 },
    { id: 'bachala01', name: 'Lake Bachar', team: 'MIA', ip: 9.1 },
    { id: 'legumca01', name: 'Casey Legumina', team: 'CIN', ip: 9.1 },
    { id: 'duffety01', name: 'Tyler Duffey', team: 'KCR', ip: 9 },
    { id: 'hartlge01', name: 'Geoff Hartlieb', team: 'COL', ip: 9 },
    { id: 'stridsp01', name: 'Spencer Strider', team: 'ATL', ip: 9 },
    { id: 'windejo01', name: 'Josh Winder', team: 'MIN', ip: 9 },
    { id: 'parsowe01', name: 'Wes Parsons', team: 'TOT', ip: 9 },
    { id: 'parsowe01', name: 'Wes Parsons', team: 'TOR', ip: 5 },
    { id: 'parsowe01', name: 'Wes Parsons', team: 'CLE', ip: 4 },
    { id: 'carasma01', name: 'Matt Carasiti', team: 'COL', ip: 8.2 },
    { id: 'espinpa01', name: 'Paolo Espino', team: 'TOR', ip: 8.2 },
    { id: 'shugach01', name: 'Chase Shugart', team: 'BOS', ip: 8.2 },
    { id: 'waltean01', name: 'Andrew Walters', team: 'CLE', ip: 8.2 },
    { id: 'bickfph01', name: 'Phil Bickford', team: 'NYY', ip: 8.1 },
    { id: 'caspabe01', name: 'Ben Casparius', team: 'LAD', ip: 8.1 },
    { id: 'gilbety01', name: 'Tyler Gilbert*', team: 'PHI', ip: 8.1 },
    { id: 'grayjo03', name: 'Josiah Gray', team: 'WSN', ip: 8.1 },
    { id: 'rutleja01', name: 'Jackson Rutledge', team: 'WSN', ip: 8.1 },
    { id: 'wingetr01', name: 'Trey Wingenter', team: 'TOT', ip: 8.1 },
    { id: 'wingetr01', name: 'Trey Wingenter', team: 'BOS', ip: 2.1 },
    { id: 'wingetr01', name: 'Trey Wingenter', team: 'CHC', ip: 6 },
    { id: 'gillico01', name: 'Connor Gillispie', team: 'CLE', ip: 8 },
    { id: 'hernani01', name: 'Nick Hernandez', team: 'HOU', ip: 8 },
    { id: 'junkja01', name: 'Janson Junk', team: 'TOT', ip: 8 },
    { id: 'junkja01', name: 'Janson Junk', team: 'MIL', ip: 8 },
    { id: 'junkja01', name: 'Janson Junk', team: 'OAK', ip: 0 },
    { id: 'obrieri01', name: 'Riley O\'Brien', team: 'STL', ip: 8 },
    { id: 'silsech01', name: 'Chase Silseth', team: 'LAA', ip: 8 },
    { id: 'gracego01', name: 'Gordon Graceffo', team: 'STL', ip: 7.2 },
    { id: 'winanal01', name: 'Allan Winans', team: 'ATL', ip: 7.2 },
    { id: 'zastrro01', name: 'Rob Zastryzny*', team: 'MIL', ip: 7.2 },
    { id: 'jayty01', name: 'Tyler Jay*', team: 'TOT', ip: 7.2 },
    { id: 'jayty01', name: 'Tyler Jay*', team: 'NYM', ip: 4.2 },
    { id: 'jayty01', name: 'Tyler Jay*', team: 'MIL', ip: 3 },
    { id: 'gratebr01', name: 'Brusdar Graterol', team: 'LAD', ip: 7.1 },
    { id: 'santogr01', name: 'Gregory Santos', team: 'SEA', ip: 7.1 },
    { id: 'kleinwi01', name: 'Will Klein', team: 'TOT', ip: 7.1 },
    { id: 'kleinwi01', name: 'Will Klein', team: 'KCR', ip: 5.2 },
    { id: 'kleinwi01', name: 'Will Klein', team: 'OAK', ip: 1.2 },
    { id: 'crismna01', name: 'Nabil Crismatt', team: 'LAD', ip: 7 },
    { id: 'davisau01', name: 'Austin Davis*', team: 'SDP', ip: 7 },
    { id: 'kitchau01', name: 'Austin Kitchen*', team: 'MIA', ip: 7 },
    { id: 'maciejo01', name: 'Josh Maciejewski*', team: 'NYY', ip: 7 },
    { id: 'mileywa01', name: 'Wade Miley*', team: 'MIL', ip: 7 },
    { id: 'raleybr01', name: 'Brooks Raley*', team: 'NYM', ip: 7 },
    { id: 'waldrhu01', name: 'Hurston Waldrep', team: 'ATL', ip: 7 },
    { id: 'selbyco01', name: 'Colin Selby', team: 'TOT', ip: 7 },
    { id: 'selbyco01', name: 'Colin Selby', team: 'KCR', ip: 3 },
    { id: 'selbyco01', name: 'Colin Selby', team: 'BAL', ip: 4 },
    { id: 'bermujo01', name: 'Jonathan Bermúdez*', team: 'MIA', ip: 6.2 },
    { id: 'campbis01', name: 'Isaiah Campbell', team: 'BOS', ip: 6.2 },
    { id: 'eiserbr01', name: 'Brandon Eisert*', team: 'TOR', ip: 6.2 },
    { id: 'fostema01', name: 'Matt Foster', team: 'CHW', ip: 6.2 },
    { id: 'hartwgr01', name: 'Grant Hartwig', team: 'NYM', ip: 6.2 },
    { id: 'hurtky01', name: 'Kyle Hurt', team: 'LAD', ip: 6.2 },
    { id: 'leibrbr01', name: 'Brandon Leibrandt*', team: 'CIN', ip: 6.1 },
    { id: 'andrima01', name: 'Matt Andriese', team: 'MIA', ip: 6 },
    { id: 'bukaujb01', name: 'JB Bukauskas', team: 'MIL', ip: 6 },
    { id: 'contrlu01', name: 'Luis Contreras', team: 'HOU', ip: 6 },
    { id: 'iriarja01', name: 'Jairo Iriarte', team: 'CHW', ip: 6 },
    { id: 'neelyja01', name: 'Jack Neely', team: 'CHC', ip: 6 },
    { id: 'bruihju01', name: 'Justin Bruihl*', team: 'PIT', ip: 5.2 },
    { id: 'brzykza01', name: 'Zach Brzykcy', team: 'WSN', ip: 5.2 },
    { id: 'cruzst01', name: 'Steven Cruz', team: 'KCR', ip: 5.2 },
    { id: 'roberda11', name: 'Daniel Robert', team: 'TEX', ip: 5.2 },
    { id: 'garream01', name: 'Amir Garrett*', team: 'LAA', ip: 5.1 },
    { id: 'heasljo01', name: 'Jonathan Heasley', team: 'BAL', ip: 5.1 },
    { id: 'hernajo03', name: 'Jose Hernandez*', team: 'PIT', ip: 5.1 },
    { id: 'kellyca01', name: 'Casey Kelly', team: 'CIN', ip: 5.1 },
    { id: 'mattsis01', name: 'Isaac Mattson', team: 'PIT', ip: 5.1 },
    { id: 'medervi01', name: 'Víctor Mederos', team: 'LAA', ip: 5.1 },
    { id: 'nelsoni01', name: 'Nick Nelson', team: 'PHI', ip: 5.1 },
    { id: 'sengako01', name: 'Kodai Senga', team: 'NYM', ip: 5.1 },
    { id: 'lylesjo01', name: 'Jordan Lyles', team: 'KCR', ip: 5 },
    { id: 'davidtu01', name: 'Tucker Davidson*', team: 'BAL', ip: 4.2 },
    { id: 'adcocty01', name: 'Ty Adcock', team: 'NYM', ip: 4.1 },
    { id: 'gosean01', name: 'Anthony Gose*', team: 'CLE', ip: 4.1 },
    { id: 'hernaen02', name: 'Kiké Hernández', team: 'LAD', ip: 4.1 },
    { id: 'lametdi01', name: 'Dinelson Lamet', team: 'LAD', ip: 4.1 },
    { id: 'pruitau01', name: 'Austin Pruitt', team: 'TEX', ip: 4.1 },
    { id: 'smithaj01', name: 'AJ Smith-Shawver', team: 'ATL', ip: 4.1 },
    { id: 'villael02', name: 'Eli Villalobos', team: 'MIA', ip: 4.1 },
    { id: 'bauerja01', name: 'Jake Bauers*', team: 'MIL', ip: 4 },
    { id: 'boushca01', name: 'Caleb Boushley', team: 'MIN', ip: 4 },
    { id: 'busenal01', name: 'Alan Busenitz', team: 'CIN', ip: 4 },
    { id: 'duartda01', name: 'Daniel Duarte', team: 'MIN', ip: 4 },
    { id: 'farmeky01', name: 'Kyle Farmer', team: 'MIN', ip: 4 },
    { id: 'gutievl01', name: 'Vladimir Gutierrez', team: 'MIA', ip: 4 },
    { id: 'jobeja01', name: 'Jackson Jobe', team: 'DET', ip: 4 },
    { id: 'loaisjo01', name: 'Jonathan Loáisiga', team: 'NYY', ip: 4 },
    { id: 'marquge01', name: 'Germán Márquez', team: 'COL', ip: 4 },
    { id: 'mcderch01', name: 'Chayce McDermott', team: 'BAL', ip: 4 },
    { id: 'penroza01', name: 'Zach Penrod*', team: 'BOS', ip: 4 },
    { id: 'reyesge01', name: 'Gerardo Reyes', team: 'OAK', ip: 4 },
    { id: 'riverem01', name: 'Emmanuel Rivera', team: 'MIA', ip: 4 },
    { id: 'shawbr01', name: 'Bryan Shaw', team: 'CHW', ip: 4 },
    { id: 'sternju01', name: 'Justin Sterner', team: 'TBR', ip: 4 },
    { id: 'stubbga01', name: 'Garrett Stubbs', team: 'PHI', ip: 4 },
    { id: 'uwasana01', name: 'Naoyuki Uwasawa', team: 'BOS', ip: 4 },
    { id: 'willilu01', name: 'Luke Williams', team: 'ATL', ip: 4 },
    { id: 'vanasri01', name: 'Ricky Vanasco', team: 'TOT', ip: 4 },
    { id: 'vanasri01', name: 'Ricky Vanasco', team: 'LAD', ip: 2 },
    { id: 'vanasri01', name: 'Ricky Vanasco', team: 'DET', ip: 2 },
    { id: 'altavda01', name: 'Dan Altavilla', team: 'KCR', ip: 3.2 },
    { id: 'beetecl01', name: 'Clayton Beeter', team: 'NYY', ip: 3.2 },
    { id: 'hillri01', name: 'Rich Hill*', team: 'BOS', ip: 3.2 },
    { id: 'mailelu01', name: 'Luke Maile', team: 'CIN', ip: 3.2 },
    { id: 'buchada01', name: 'David Buchanan', team: 'CIN', ip: 3.1 },
    { id: 'burromi01', name: 'Mike Burrows', team: 'PIT', ip: 3.1 },
    { id: 'effrosc01', name: 'Scott Effross', team: 'NYY', ip: 3.1 },
    { id: 'henried01', name: 'Edgardo Henriquez', team: 'LAD', ip: 3.1 },
    { id: 'pintri01', name: 'Riley Pint', team: 'COL', ip: 3.1 },
    { id: 'ribalor01', name: 'Orlando Ribalta', team: 'WSN', ip: 3.1 },
    { id: 'stephja01', name: 'Jackson Stephens', team: 'ATL', ip: 3.1 },
    { id: 'whitlfo01', name: 'Forrest Whitley', team: 'HOU', ip: 3.1 },
    { id: 'zuberty01', name: 'Tyler Zuber', team: 'TBR', ip: 3.1 },
    { id: 'fitzgty01', name: 'Tyler Fitzgerald', team: 'SFG', ip: 3 },
    { id: 'headrbr01', name: 'Brent Headrick*', team: 'MIN', ip: 3 },
    { id: 'kniznan01', name: 'Andrew Knizner', team: 'TEX', ip: 3 },
    { id: 'mcdontr01', name: 'Trevor McDonald', team: 'SFG', ip: 3 },
    { id: 'menacr01', name: 'Cristian Mena', team: 'ARI', ip: 3 },
    { id: 'smithdo02', name: 'Dominic Smith*', team: 'BOS', ip: 3 },
    { id: 'whiteow01', name: 'Owen White', team: 'TEX', ip: 3 },
    { id: 'brogdco01', name: 'Connor Brogdon', team: 'TOT', ip: 3 },
    { id: 'brogdco01', name: 'Connor Brogdon', team: 'PHI', ip: 2 },
    { id: 'brogdco01', name: 'Connor Brogdon', team: 'LAD', ip: 1 },
    { id: 'guilllu01', name: 'Luis Guillorme', team: 'TOT', ip: 3 },
    { id: 'guilllu01', name: 'Luis Guillorme', team: 'ATL', ip: 1 },
    { id: 'guilllu01', name: 'Luis Guillorme', team: 'LAA', ip: 2 },
    { id: 'jacqujo01', name: 'Joe Jacques*', team: 'TOT', ip: 3 },
    { id: 'jacqujo01', name: 'Joe Jacques*', team: 'BOS', ip: 1.2 },
    { id: 'jacqujo01', name: 'Joe Jacques*', team: 'ARI', ip: 1.1 },
    { id: 'bowlajo01', name: 'Jonathan Bowlan', team: 'KCR', ip: 2.2 },
    { id: 'teherju01', name: 'Julio Teheran', team: 'NYM', ip: 2.2 },
    { id: 'tellero01', name: 'Rowdy Tellez*', team: 'PIT', ip: 2.2 },
    { id: 'curtijo02', name: 'John Curtiss', team: 'COL', ip: 2.1 },
    { id: 'dunshpa01', name: 'Parker Dunshee', team: 'ATL', ip: 2.1 },
    { id: 'johnsse01', name: 'Seth Johnson', team: 'PHI', ip: 2.1 },
    { id: 'loutory01', name: 'Ryan Loutos', team: 'STL', ip: 2.1 },
    { id: 'topaju01', name: 'Justin Topa', team: 'MIN', ip: 2.1 },
    { id: 'antonte01', name: 'Tejay Antone', team: 'CIN', ip: 2 },
    { id: 'dodddy01', name: 'Dylan Dodd*', team: 'ATL', ip: 2 },
    { id: 'ederja01', name: 'Jake Eder*', team: 'CHW', ip: 2 },
    { id: 'gibauia01', name: 'Ian Gibaut', team: 'CIN', ip: 2 },
    { id: 'hedgeau01', name: 'Austin Hedges', team: 'CLE', ip: 2 },
    { id: 'henslda01', name: 'David Hensley', team: 'MIA', ip: 2 },
    { id: 'kineris01', name: 'Isiah Kiner-Falefa', team: 'TOR', ip: 2 },
    { id: 'kristza01', name: 'Zac Kristofak', team: 'LAA', ip: 2 },
    { id: 'logueza01', name: 'Zach Logue*', team: 'LAD', ip: 2 },
    { id: 'mckinza01', name: 'Zach McKinstry', team: 'DET', ip: 2 },
    { id: 'milleow01', name: 'Owen Miller', team: 'MIL', ip: 2 },
    { id: 'rivasle01', name: 'Leo Rivas', team: 'SEA', ip: 2 },
    { id: 'rojasjo01', name: 'Josh Rojas', team: 'SEA', ip: 2 },
    { id: 'rortvbe01', name: 'Ben Rortvedt', team: 'TBR', ip: 2 },
    { id: 'speasal01', name: 'Alex Speas', team: 'HOU', ip: 2 },
    { id: 'trevijo01', name: 'Jose Trevino', team: 'NYY', ip: 2 },
    { id: 'vargail01', name: 'Ildemaro Vargas', team: 'WSN', ip: 2 },
    { id: 'brujavi01', name: 'Vidal Bruján', team: 'MIA', ip: 1.2 },
    { id: 'feiglbr01', name: 'Brady Feigl*', team: 'PIT', ip: 1.2 },
    { id: 'orzeer01', name: 'Eric Orze', team: 'NYM', ip: 1.2 },
    { id: 'castrwi01', name: 'Willi Castro', team: 'MIN', ip: 1.1 },
    { id: 'crawfbr01', name: 'Brandon Crawford', team: 'STL', ip: 1.1 },
    { id: 'holloga01', name: 'Gavin Hollowell', team: 'CHC', ip: 1.1 },
    { id: 'wallnma01', name: 'Matt Wallner', team: 'MIN', ip: 1.1 },
    { id: 'wantzan01', name: 'Andrew Wantz', team: 'LAA', ip: 1.1 },
    { id: 'alvared01', name: 'Eddy Alvarez', team: 'NYM', ip: 1 },
    { id: 'barnhtu01', name: 'Tucker Barnhart', team: 'ARI', ip: 1 },
    { id: 'boteda01', name: 'David Bote', team: 'CHC', ip: 1 },
    { id: 'burgora01', name: 'Raymond Burgos*', team: 'SFG', ip: 1 },
    { id: 'churcma01', name: 'Marc Church', team: 'TEX', ip: 1 },
    { id: 'clemeko01', name: 'Kody Clemens', team: 'PHI', ip: 1 },
    { id: 'clemeer01', name: 'Ernie Clement', team: 'TOR', ip: 1 },
    { id: 'colemdy01', name: 'Dylan Coleman', team: 'HOU', ip: 1 },
    { id: 'diazmi02', name: 'Miguel Díaz', team: 'HOU', ip: 1 },
    { id: 'gilbrlu01', name: 'Lucas Gilbreath*', team: 'COL', ip: 1 },
    { id: 'hampsga01', name: 'Garrett Hampson', team: 'KCR', ip: 1 },
    { id: 'heinety01', name: 'Tyler Heineman', team: 'TOR', ip: 1 },
    { id: 'hicksaa01', name: 'Aaron Hicks', team: 'LAA', ip: 1 },
    { id: 'kessigr01', name: 'Grae Kessinger', team: 'HOU', ip: 1 },
    { id: 'kloffad01', name: 'Adam Kloffenstein', team: 'STL', ip: 1 },
    { id: 'krookma01', name: 'Matt Krook*', team: 'BAL', ip: 1 },
    { id: 'loftini01', name: 'Nick Loftin', team: 'KCR', ip: 1 },
    { id: 'mccanja02', name: 'James McCann', team: 'BAL', ip: 1 },
    { id: 'meekeja01', name: 'James Meeker', team: 'MIL', ip: 1 },
    { id: 'mendida01', name: 'Danny Mendick', team: 'CHW', ip: 1 },
    { id: 'misiean01', name: 'Anthony Misiewicz*', team: 'NYY', ip: 1 },
    { id: 'prattni01', name: 'Nick Pratto*', team: 'KCR', ip: 1 },
    { id: 'reyespa01', name: 'Pablo Reyes', team: 'BOS', ip: 1 },
    { id: 'rojasmi02', name: 'Miguel Rojas', team: 'LAD', ip: 1 },
    { id: 'saalfan01', name: 'Andrew Saalfrank*', team: 'ARI', ip: 1 },
    { id: 'shrevch01', name: 'Chasen Shreve*', team: 'COL', ip: 1 },
    { id: 'smithpa04', name: 'Pavin Smith*', team: 'ARI', ip: 1 },
    { id: 'stefami01', name: 'Michael Stefanic', team: 'LAA', ip: 1 },
    { id: 'tuckeco01', name: 'Cole Tucker', team: 'LAA', ip: 1 },
    { id: 'waltodo01', name: 'Donovan Walton', team: 'SFG', ip: 1 },
    { id: 'william01', name: 'Amos Willingham', team: 'WSN', ip: 1 },
    { id: 'wilsowe01', name: 'Weston Wilson', team: 'PHI', ip: 1 },
    { id: 'yastrmi01', name: 'Mike Yastrzemski*', team: 'SFG', ip: 1 },
    { id: 'kraveev01', name: 'Evan Kravetz*', team: 'CIN', ip: 0.2 },
    { id: 'mervima01', name: 'Matt Mervis', team: 'CHC', ip: 0.2 },
    { id: 'ortizlu02', name: 'Luis Ortiz', team: 'PHI', ip: 0.2 },
    { id: 'richaly01', name: 'Lyon Richardson', team: 'CIN', ip: 0.2 },
    { id: 'andrecl02', name: 'Clayton Andrews*', team: 'NYY', ip: 0.1 },
    { id: 'cabreos01', name: 'Oswaldo Cabrera', team: 'NYY', ip: 0.1 },
    { id: 'henlebl01', name: 'Blair Henley', team: 'HOU', ip: 0.1 },
    { id: 'justiev01', name: 'Evan Justice*', team: 'COL', ip: 0.1 },
    { id: 'kochma01', name: 'Matt Koch', team: 'COL', ip: 0.1 },
    { id: 'peredjh01', name: 'Jhonny Pereda', team: 'MIA', ip: 0.1 },
    { id: 'sanomi01', name: 'Miguel Sanó', team: 'LAA', ip: 0.1 },
    { id: 'torrelu01', name: 'Luis Torrens', team: 'NYM', ip: 0.1 },
    { id: 'wisdopa01', name: 'Patrick Wisdom', team: 'CHC', ip: 0.1 },
    { id: 'edwarca01', name: 'Carl Edwards Jr.', team: 'SDP', ip: 0 },
    { id: 'suerowa01', name: 'Wander Suero', team: 'HOU', ip: 0 },
];

export function convertToCsv() {
    const pitchersOnIndividualTeams: PitchersOnIndividualTeams[] = [];

    allPitchers.forEach(indTeam => {
        if (indTeam.team !== 'TOT' && multiTeamPitchers[indTeam.id]) {
            const nameParts = multiTeamPitchers[indTeam.id].name.split(', ');
            pitchersOnIndividualTeams.push({
                year: 2024,
                name: nameParts[0] + ',' + nameParts[1][0],
                throws: multiTeamPitchers[indTeam.id].throws,
                team: indTeam.team,
                ip: indTeam.ip.toString().replace('.1', '.33').replace('.2', '.67'),
            });
        }
    });

    return pitchersOnIndividualTeams;
}
