const multiTeamHitters = {
    baderha01: { name: 'Bader, Harrison', team: 'TOT', bats: 'R', ab: 319 },
    belljo02: { name: 'Bell, Josh', team: 'TOT', bats: 'S', ab: 547 },
    burgeja01: { name: 'Burger, Jake', team: 'TOT', bats: 'R', ab: 492 },
    candeje01: { name: 'Candelario, Jeimer', team: 'TOT', bats: 'S', ab: 505 },
    canhama01: { name: 'Canha, Mark', team: 'TOT', bats: 'R', ab: 435 },
    canzodo01: { name: 'Canzone, Dominic', team: 'TOT', bats: 'L', ab: 173 },
    castrro01: { name: 'Castro, Rodolfo', team: 'TOT', bats: 'S', ab: 227 },
    choiji01: { name: 'Choi, Ji Man', team: 'TOT', bats: 'L', ab: 104 },
    coopega03: { name: 'Cooper, Garrett', team: 'TOT', bats: 'R', ab: 422 },
    croncj01: { name: 'Cron, CJ', team: 'TOT', bats: 'R', ab: 258 },
    dejonpa01: { name: 'DeJong, Paul', team: 'TOT', bats: 'R', ab: 372 },
    donaljo02: { name: 'Donaldson, Josh', team: 'TOT', bats: 'R', ab: 165 },
    escobed01: { name: 'Escobar, Eduardo', team: 'TOT', bats: 'S', ab: 288 },
    grichra01: { name: 'Grichuk, Randal', team: 'TOT', bats: 'R', ab: 434 },
    haaseer01: { name: 'Haase, Eric', team: 'TOT', bats: 'R', ab: 274 },
    hedgeau01: { name: 'Hedges, Austin', team: 'TOT', bats: 'R', ab: 185 },
    hernaen02: { name: 'Hernandez, Enrique', team: 'TOT', bats: 'R', ab: 465 },
    hicksaa01: { name: 'Hicks, Aaron', team: 'TOT', bats: 'S', ab: 269 },
    kellyca02: { name: 'Kelly, Carson', team: 'TOT', bats: 'R', ab: 136 },
    laurera01: { name: 'Laureano, Ramon', team: 'TOT', bats: 'R', ab: 361 },
    lopezni01: { name: 'Lopez, Nicky', team: 'TOT', bats: 'L', ab: 225 },
    moustmi01: { name: 'Moustakas, Mike', team: 'TOT', bats: 'L', ab: 352 },
    peterja01: { name: 'Peterson, Jace', team: 'TOT', bats: 'L', ab: 374 },
    phamth01: { name: 'Pham, Tommy', team: 'TOT', bats: 'R', ab: 426 },
    polloaj01: { name: 'Pollock, AJ', team: 'TOT', bats: 'R', ab: 133 },
    profaju01: { name: 'Profar, Jurickson', team: 'TOT', bats: 'S', ab: 459 },
    renfrhu01: { name: 'Renfroe, Hunter', team: 'TOT', bats: 'R', ab: 498 },
    rivasal01: { name: 'Rivas, Alfonso', team: 'TOT', bats: 'L', ab: 109 },
    rojasjo01: { name: 'Rojas, Josh', team: 'TOT', bats: 'L', ab: 314 },
    rosaram01: { name: 'Rosario, Amed', team: 'TOT', bats: 'R', ab: 510 },
    sanchga02: { name: 'Sanchez, Gary', team: 'TOT', bats: 'R', ab: 240 },
    santaca01: { name: 'Santana, Carlos', team: 'TOT', bats: 'S', ab: 550 },
    tapiara01: { name: 'Tapia, Raimel', team: 'TOT', bats: 'L', ab: 148 },
    thomptr01: { name: 'Thompson, Trayce', team: 'TOT', bats: 'R', ab: 153 },
    uriaslu01: { name: 'Urias, Luis', team: 'TOT', bats: 'R', ab: 144 },
    velazne01: { name: 'Velazquez, Nelson', team: 'TOT', bats: 'R', ab: 162 },
    wongko01: { name: 'Wong, Kolten', team: 'TOT', bats: 'L', ab: 224 },
    wynnsau01: { name: 'Wynns, Austin', team: 'TOT', bats: 'R', ab: 130 },
    zavalse01: { name: 'Zavala, Seby', team: 'TOT', bats: 'R', ab: 175 },
};

module.exports = multiTeamHitters;
