const rmlTeams = {
    Athletics: 1,
    Blaze: 2,
    Boomers: 3,
    Browns: 4,
    Captains: 5,
    'Carolins Mudcats': 6,
    'Colt .45s': 7,
    Dawgs: 8,
    'Dodgers-old': 9,
    Expos: 10,
    Gypsies: 11,
    Highlanders: 12,
    Knights: 13,
    Monarchs: 14,
    Mudhens: 15,
    Pelicans: 16,
    Pilgrims: 17,
    'Red Sox': 18,
    Reds: 19,
    'River Dogs': 20,
    'Midland Rockhounds': 21,
    Twins: 22,
    Yankees: 23,
    Whales: 24,
    'Z-Unowned': 25,
    Express: 26,
    Marlins: 27,
    'Twins-old': 28,
    'Indians-1': 29,
    'Indians-2': 30,
    Grays: 31,
    Bandits: 32,
    Stogies: 33,
    Stars: 34,
    TinCaps: 35,
    Dodgers: 36,
    'Yellow Jackets': 37,
    Pilots: 38,
    RockHounds: 39,
    Hornets: 40,
    Titans: 41,
    'Clown Princes': 42,

};

module.exports = rmlTeams;
